using System.Drawing;
using System.Windows.Forms;
﻿namespace iS800
{
	// Token: 0x02000082 RID: 130
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class Equip_201_mon : global::System.Windows.Forms.Form
	{
		// Token: 0x06001CD5 RID: 7381 RVA: 0x003D34A0 File Offset: 0x003D18A0
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			if (disposing && this.components != null)
			{
				this.components.Dispose();
			}
			base.Dispose(disposing);
		}

		// Token: 0x06001CD6 RID: 7382 RVA: 0x003D34C0 File Offset: 0x003D18C0
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.components = new global::System.ComponentModel.Container();
			this.CheckBox_Alm_transbordo = new global::System.Windows.Forms.CheckBox();
			this.CheckBox_Alm_energia = new global::System.Windows.Forms.CheckBox();
			this.CheckBox_Alm_nivel = new global::System.Windows.Forms.CheckBox();
			this.Grupo_escrita_de_dados = new global::System.Windows.Forms.GroupBox();
			this.Tela_nivel_destino = new global::System.Windows.Forms.NumericUpDown();
			this.Grupo_simulacao_alarmes = new global::System.Windows.Forms.GroupBox();
			this.CheckBox_Alm_arrombamento = new global::System.Windows.Forms.CheckBox();
			this.Label_nivel_destino = new global::System.Windows.Forms.Label();
			this.Grupo_ctrl_com = new global::System.Windows.Forms.GroupBox();
			this.Tela_endereco_estacao = new global::System.Windows.Forms.NumericUpDown();
			this.Tela_endereco_mestre = new global::System.Windows.Forms.NumericUpDown();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.msg = new global::System.Windows.Forms.TextBox();
			this.Comando_hab_monitoracao = new global::System.Windows.Forms.Button();
			this.Label_end_estacao = new global::System.Windows.Forms.Label();
			this.Grupo_status = new global::System.Windows.Forms.GroupBox();
			this.Grupo_alarmes = new global::System.Windows.Forms.GroupBox();
			this.CheckBox_Alm_alagamento_status = new global::System.Windows.Forms.CheckBox();
			this.CheckBox_Alm_energia_status = new global::System.Windows.Forms.CheckBox();
			this.CheckBox_Alm_arrombamento_status = new global::System.Windows.Forms.CheckBox();
			this.Grupo_bomba3 = new global::System.Windows.Forms.GroupBox();
			this.Label_modo_b3 = new global::System.Windows.Forms.Label();
			this.Modo_b3 = new global::System.Windows.Forms.TextBox();
			this.Cmd_manual_b3 = new global::System.Windows.Forms.Button();
			this.Cmd_desliga_b3 = new global::System.Windows.Forms.Button();
			this.Cmd_liga_b3 = new global::System.Windows.Forms.Button();
			this.Label_status_b3 = new global::System.Windows.Forms.Label();
			this.Cmd_automatico_b3 = new global::System.Windows.Forms.Button();
			this.Status_b3 = new global::System.Windows.Forms.TextBox();
			this.Grupo_bomba2 = new global::System.Windows.Forms.GroupBox();
			this.Label_modo_b2 = new global::System.Windows.Forms.Label();
			this.Modo_b2 = new global::System.Windows.Forms.TextBox();
			this.Cmd_manual_b2 = new global::System.Windows.Forms.Button();
			this.Cmd_desliga_b2 = new global::System.Windows.Forms.Button();
			this.Cmd_liga_b2 = new global::System.Windows.Forms.Button();
			this.Cmd_automatico_b2 = new global::System.Windows.Forms.Button();
			this.Label_status_b2 = new global::System.Windows.Forms.Label();
			this.Status_b2 = new global::System.Windows.Forms.TextBox();
			this.Grupo_bomba1 = new global::System.Windows.Forms.GroupBox();
			this.Cmd_manual_b1 = new global::System.Windows.Forms.Button();
			this.Cmd_desliga_b1 = new global::System.Windows.Forms.Button();
			this.Cmd_automatico_b1 = new global::System.Windows.Forms.Button();
			this.Cmd_liga_b1 = new global::System.Windows.Forms.Button();
			this.Label_modo_b1 = new global::System.Windows.Forms.Label();
			this.Modo_b1 = new global::System.Windows.Forms.TextBox();
			this.Label_status_b1 = new global::System.Windows.Forms.Label();
			this.Status_b1 = new global::System.Windows.Forms.TextBox();
			this.Grupo_setpoints = new global::System.Windows.Forms.GroupBox();
			this.Comando_escreve_setpoint = new global::System.Windows.Forms.Button();
			this.Comando_le_setpoint = new global::System.Windows.Forms.Button();
			this.Grupo_set_B3 = new global::System.Windows.Forms.GroupBox();
			this.Set_valor_Desiga_B3 = new global::System.Windows.Forms.TextBox();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.Label_liga_b3 = new global::System.Windows.Forms.Label();
			this.Set_valor_Liga_B3 = new global::System.Windows.Forms.TextBox();
			this.Grupo_set_B2 = new global::System.Windows.Forms.GroupBox();
			this.Set_valor_Desiga_B2 = new global::System.Windows.Forms.TextBox();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.Label_liga_b2 = new global::System.Windows.Forms.Label();
			this.Set_valor_Liga_B2 = new global::System.Windows.Forms.TextBox();
			this.Grupo_set_B1 = new global::System.Windows.Forms.GroupBox();
			this.Set_valor_Desiga_B1 = new global::System.Windows.Forms.TextBox();
			this.Label_desliga_b1 = new global::System.Windows.Forms.Label();
			this.Label_liga_b1 = new global::System.Windows.Forms.Label();
			this.Set_valor_Liga_B1 = new global::System.Windows.Forms.TextBox();
			this.Timer_monitoracao = new global::System.Windows.Forms.Timer(this.components);
			this.Grupo_estatistica = new global::System.Windows.Forms.GroupBox();
			this.Label_Est_retry = new global::System.Windows.Forms.Label();
			this.Est_retry = new global::System.Windows.Forms.TextBox();
			this.Est_eficiencia = new global::System.Windows.Forms.TextBox();
			this.Button_limpa_estatistica = new global::System.Windows.Forms.Button();
			this.Label_Est_RX = new global::System.Windows.Forms.Label();
			this.Label_Est_Eficiencia = new global::System.Windows.Forms.Label();
			this.Label_Est_TX = new global::System.Windows.Forms.Label();
			this.Est_Rx = new global::System.Windows.Forms.TextBox();
			this.Est_TX = new global::System.Windows.Forms.TextBox();
			this.Grupo_escrita_de_dados.SuspendLayout();
			
			this.Grupo_simulacao_alarmes.SuspendLayout();
			this.Grupo_ctrl_com.SuspendLayout();
			
			
			this.Grupo_status.SuspendLayout();
			this.Grupo_alarmes.SuspendLayout();
			this.Grupo_bomba3.SuspendLayout();
			this.Grupo_bomba2.SuspendLayout();
			this.Grupo_bomba1.SuspendLayout();
			this.Grupo_setpoints.SuspendLayout();
			this.Grupo_set_B3.SuspendLayout();
			this.Grupo_set_B2.SuspendLayout();
			this.Grupo_set_B1.SuspendLayout();
			this.Grupo_estatistica.SuspendLayout();
			this.SuspendLayout();
			this.CheckBox_Alm_transbordo.AutoCheck = false;
			this.CheckBox_Alm_transbordo.AutoSize = true;
			global::System.Windows.Forms.Control checkBox_Alm_transbordo = this.CheckBox_Alm_transbordo;
			checkBox_Alm_transbordo.Location = new global::System.Drawing.Point(51, 60);
			this.CheckBox_Alm_transbordo.Name = "CheckBox_Alm_transbordo";
			global::System.Windows.Forms.Control checkBox_Alm_transbordo2 = this.CheckBox_Alm_transbordo;
			checkBox_Alm_transbordo2.Size = new global::System.Drawing.Size(80, 17);
			this.CheckBox_Alm_transbordo.TabIndex = 2;
			this.CheckBox_Alm_transbordo.TabStop = false;
			this.CheckBox_Alm_transbordo.Text = "Transbordo";
			this.CheckBox_Alm_transbordo.UseVisualStyleBackColor = true;
			this.CheckBox_Alm_energia.AutoCheck = false;
			this.CheckBox_Alm_energia.AutoSize = true;
			global::System.Windows.Forms.Control checkBox_Alm_energia = this.CheckBox_Alm_energia;
checkBox_Alm_energia.Location = new global::System.Drawing.Point(51, 37);
			this.CheckBox_Alm_energia.Name = "CheckBox_Alm_energia";
			global::System.Windows.Forms.Control checkBox_Alm_energia2 = this.CheckBox_Alm_energia;
			Size = new System.Drawing.Size(90, 17);
			checkBox_Alm_energia2.Size = this.Size;
			this.CheckBox_Alm_energia.TabIndex = 1;
			this.CheckBox_Alm_energia.TabStop = false;
			this.CheckBox_Alm_energia.Text = "Falha energia";
			this.CheckBox_Alm_energia.UseVisualStyleBackColor = true;
			this.CheckBox_Alm_nivel.AutoCheck = false;
			this.CheckBox_Alm_nivel.AutoSize = true;
			global::System.Windows.Forms.Control checkBox_Alm_nivel = this.CheckBox_Alm_nivel;
checkBox_Alm_nivel.Location = new global::System.Drawing.Point(51, 83);
			this.CheckBox_Alm_nivel.Name = "CheckBox_Alm_nivel";
			global::System.Windows.Forms.Control checkBox_Alm_nivel2 = this.CheckBox_Alm_nivel;
			Size = new System.Drawing.Size(94, 17);
			checkBox_Alm_nivel2.Size = this.Size;
			this.CheckBox_Alm_nivel.TabIndex = 0;
			this.CheckBox_Alm_nivel.TabStop = false;
			this.CheckBox_Alm_nivel.Text = "Falha de nível";
			this.CheckBox_Alm_nivel.UseVisualStyleBackColor = true;
			this.Grupo_escrita_de_dados.Controls.Add(this.Tela_nivel_destino);
			this.Grupo_escrita_de_dados.Controls.Add(this.Grupo_simulacao_alarmes);
			this.Grupo_escrita_de_dados.Controls.Add(this.Label_nivel_destino);
			global::System.Windows.Forms.Control grupo_escrita_de_dados = this.Grupo_escrita_de_dados;
grupo_escrita_de_dados.Location = new global::System.Drawing.Point(362, 12);
			this.Grupo_escrita_de_dados.Name = "Grupo_escrita_de_dados";
			global::System.Windows.Forms.Control grupo_escrita_de_dados2 = this.Grupo_escrita_de_dados;
			Size = new System.Drawing.Size(371, 198);
			grupo_escrita_de_dados2.Size = this.Size;
			this.Grupo_escrita_de_dados.TabIndex = 1;
			this.Grupo_escrita_de_dados.TabStop = false;
			this.Grupo_escrita_de_dados.Text = "Medidas para simulçação de escrita";
			global::System.Windows.Forms.Control tela_nivel_destino = this.Tela_nivel_destino;
tela_nivel_destino.Location = new global::System.Drawing.Point(185, 32);
			this.Tela_nivel_destino.Name = "Tela_nivel_destino";
			global::System.Windows.Forms.Control tela_nivel_destino2 = this.Tela_nivel_destino;
			Size = new System.Drawing.Size(93, 20);
			tela_nivel_destino2.Size = this.Size;
			this.Tela_nivel_destino.TabIndex = 7;
			this.Tela_nivel_destino.TextAlign = HorizontalAlignment.Right;
			this.Grupo_simulacao_alarmes.Controls.Add(this.CheckBox_Alm_arrombamento);
			this.Grupo_simulacao_alarmes.Controls.Add(this.CheckBox_Alm_nivel);
			this.Grupo_simulacao_alarmes.Controls.Add(this.CheckBox_Alm_energia);
			this.Grupo_simulacao_alarmes.Controls.Add(this.CheckBox_Alm_transbordo);
			global::System.Windows.Forms.Control grupo_simulacao_alarmes = this.Grupo_simulacao_alarmes;
grupo_simulacao_alarmes.Location = new global::System.Drawing.Point(22, 58);
			this.Grupo_simulacao_alarmes.Name = "Grupo_simulacao_alarmes";
			global::System.Windows.Forms.Control grupo_simulacao_alarmes2 = this.Grupo_simulacao_alarmes;
			Size = new System.Drawing.Size(328, 118);
			grupo_simulacao_alarmes2.Size = this.Size;
			this.Grupo_simulacao_alarmes.TabIndex = 4;
			this.Grupo_simulacao_alarmes.TabStop = false;
			this.Grupo_simulacao_alarmes.Text = "Alarmes";
			this.CheckBox_Alm_arrombamento.AutoCheck = false;
			this.CheckBox_Alm_arrombamento.AutoSize = true;
			global::System.Windows.Forms.Control checkBox_Alm_arrombamento = this.CheckBox_Alm_arrombamento;
checkBox_Alm_arrombamento.Location = new global::System.Drawing.Point(194, 37);
			this.CheckBox_Alm_arrombamento.Name = "CheckBox_Alm_arrombamento";
			global::System.Windows.Forms.Control checkBox_Alm_arrombamento2 = this.CheckBox_Alm_arrombamento;
			Size = new System.Drawing.Size(94, 17);
			checkBox_Alm_arrombamento2.Size = this.Size;
			this.CheckBox_Alm_arrombamento.TabIndex = 0;
			this.CheckBox_Alm_arrombamento.TabStop = false;
			this.CheckBox_Alm_arrombamento.Text = "Arrombamento";
			this.CheckBox_Alm_arrombamento.UseVisualStyleBackColor = true;
			this.Label_nivel_destino.AutoSize = true;
			global::System.Windows.Forms.Control label_nivel_destino = this.Label_nivel_destino;
label_nivel_destino.Location = new global::System.Drawing.Point(71, 35);
			this.Label_nivel_destino.Name = "Label_nivel_destino";
			global::System.Windows.Forms.Control label_nivel_destino2 = this.Label_nivel_destino;
			Size = new System.Drawing.Size(92, 13);
			label_nivel_destino2.Size = this.Size;
			this.Label_nivel_destino.TabIndex = 2;
			this.Label_nivel_destino.Text = "Nível Destino(%) :";
			this.Grupo_ctrl_com.Controls.Add(this.Tela_endereco_estacao);
			this.Grupo_ctrl_com.Controls.Add(this.Tela_endereco_mestre);
			this.Grupo_ctrl_com.Controls.Add(this.Label2);
			this.Grupo_ctrl_com.Controls.Add(this.msg);
			this.Grupo_ctrl_com.Controls.Add(this.Comando_hab_monitoracao);
			this.Grupo_ctrl_com.Controls.Add(this.Label_end_estacao);
			global::System.Windows.Forms.Control grupo_ctrl_com = this.Grupo_ctrl_com;
grupo_ctrl_com.Location = new global::System.Drawing.Point(12, 12);
			this.Grupo_ctrl_com.Name = "Grupo_ctrl_com";
			global::System.Windows.Forms.Control grupo_ctrl_com2 = this.Grupo_ctrl_com;
			Size = new System.Drawing.Size(333, 198);
			grupo_ctrl_com2.Size = this.Size;
			this.Grupo_ctrl_com.TabIndex = 0;
			this.Grupo_ctrl_com.TabStop = false;
			this.Grupo_ctrl_com.Text = "Controle de Monitoração";
			global::System.Windows.Forms.Control tela_endereco_estacao = this.Tela_endereco_estacao;
tela_endereco_estacao.Location = new global::System.Drawing.Point(157, 77);
			global::System.Windows.Forms.NumericUpDown tela_endereco_estacao2 = this.Tela_endereco_estacao;
			decimal maximum;
			maximum = new decimal(new int[]
			{
				200,
				0,
				0,
				0
			});
			tela_endereco_estacao2.Maximum = maximum;
			this.Tela_endereco_estacao.Name = "Tela_endereco_estacao";
			global::System.Windows.Forms.Control tela_endereco_estacao3 = this.Tela_endereco_estacao;
			Size = new System.Drawing.Size(93, 20);
			tela_endereco_estacao3.Size = this.Size;
			this.Tela_endereco_estacao.TabIndex = 6;
			this.Tela_endereco_estacao.TextAlign = HorizontalAlignment.Right;
			global::System.Windows.Forms.Control tela_endereco_mestre = this.Tela_endereco_mestre;
tela_endereco_mestre.Location = new global::System.Drawing.Point(157, 38);
			global::System.Windows.Forms.NumericUpDown tela_endereco_mestre2 = this.Tela_endereco_mestre;
			maximum = new decimal(new int[]
			{
				200,
				0,
				0,
				0
			});
			tela_endereco_mestre2.Maximum = maximum;
			this.Tela_endereco_mestre.Name = "Tela_endereco_mestre";
			global::System.Windows.Forms.Control tela_endereco_mestre3 = this.Tela_endereco_mestre;
			Size = new System.Drawing.Size(93, 20);
			tela_endereco_mestre3.Size = this.Size;
			this.Tela_endereco_mestre.TabIndex = 6;
			this.Tela_endereco_mestre.TextAlign = HorizontalAlignment.Right;
			this.Label2.AutoSize = true;
			global::System.Windows.Forms.Control label = this.Label2;
label.Location = new global::System.Drawing.Point(22, 40);
			this.Label2.Name = "Label2";
			global::System.Windows.Forms.Control label2 = this.Label2;
			Size = new System.Drawing.Size(94, 13);
			label2.Size = this.Size;
			this.Label2.TabIndex = 3;
			this.Label2.Text = "Endereço Mestre :";
			this.msg.BackColor = global::System.Drawing.Color.Beige;
			this.msg.ForeColor = global::System.Drawing.SystemColors.WindowText;
			global::System.Windows.Forms.Control msg = this.msg;
msg.Location = new global::System.Drawing.Point(23, 111);
			this.msg.Name = "msg";
			this.msg.ReadOnly = true;
			global::System.Windows.Forms.Control msg2 = this.msg;
			Size = new System.Drawing.Size(290, 20);
			msg2.Size = this.Size;
			this.msg.TabIndex = 1;
			this.msg.TabStop = false;
			this.msg.TextAlign = HorizontalAlignment.Right;
			global::System.Windows.Forms.Control comando_hab_monitoracao = this.Comando_hab_monitoracao;
comando_hab_monitoracao.Location = new global::System.Drawing.Point(146, 148);
			this.Comando_hab_monitoracao.Name = "Comando_hab_monitoracao";
			global::System.Windows.Forms.Control comando_hab_monitoracao2 = this.Comando_hab_monitoracao;
			Size = new System.Drawing.Size(167, 26);
			comando_hab_monitoracao2.Size = this.Size;
			this.Comando_hab_monitoracao.TabIndex = 2;
			this.Comando_hab_monitoracao.Text = "Iniciar";
			this.Comando_hab_monitoracao.UseVisualStyleBackColor = true;
			this.Label_end_estacao.AutoSize = true;
			global::System.Windows.Forms.Control label_end_estacao = this.Label_end_estacao;
label_end_estacao.Location = new global::System.Drawing.Point(22, 79);
			this.Label_end_estacao.Name = "Label_end_estacao";
			global::System.Windows.Forms.Control label_end_estacao2 = this.Label_end_estacao;
			Size = new System.Drawing.Size(101, 13);
			label_end_estacao2.Size = this.Size;
			this.Label_end_estacao.TabIndex = 0;
			this.Label_end_estacao.Text = "Endereço Estação :";
			this.Grupo_status.Controls.Add(this.Grupo_alarmes);
			this.Grupo_status.Controls.Add(this.Grupo_bomba3);
			this.Grupo_status.Controls.Add(this.Grupo_bomba2);
			this.Grupo_status.Controls.Add(this.Grupo_bomba1);
			global::System.Windows.Forms.Control grupo_status = this.Grupo_status;
grupo_status.Location = new global::System.Drawing.Point(15, 216);
			this.Grupo_status.Name = "Grupo_status";
			global::System.Windows.Forms.Control grupo_status2 = this.Grupo_status;
			Size = new System.Drawing.Size(718, 267);
			grupo_status2.Size = this.Size;
			this.Grupo_status.TabIndex = 2;
			this.Grupo_status.TabStop = false;
			this.Grupo_status.Text = "Bombas - Comando e Status";
			this.Grupo_alarmes.Controls.Add(this.CheckBox_Alm_alagamento_status);
			this.Grupo_alarmes.Controls.Add(this.CheckBox_Alm_energia_status);
			this.Grupo_alarmes.Controls.Add(this.CheckBox_Alm_arrombamento_status);
			global::System.Windows.Forms.Control grupo_alarmes = this.Grupo_alarmes;
grupo_alarmes.Location = new global::System.Drawing.Point(19, 190);
			this.Grupo_alarmes.Name = "Grupo_alarmes";
			global::System.Windows.Forms.Control grupo_alarmes2 = this.Grupo_alarmes;
			Size = new System.Drawing.Size(679, 62);
			grupo_alarmes2.Size = this.Size;
			this.Grupo_alarmes.TabIndex = 3;
			this.Grupo_alarmes.TabStop = false;
			this.Grupo_alarmes.Text = "Alarmes";
			this.CheckBox_Alm_alagamento_status.AutoCheck = false;
			global::System.Windows.Forms.Control checkBox_Alm_alagamento_status = this.CheckBox_Alm_alagamento_status;
checkBox_Alm_alagamento_status.Location = new global::System.Drawing.Point(513, 29);
			this.CheckBox_Alm_alagamento_status.Name = "CheckBox_Alm_alagamento_status";
			global::System.Windows.Forms.Control checkBox_Alm_alagamento_status2 = this.CheckBox_Alm_alagamento_status;
			Size = new System.Drawing.Size(82, 17);
			checkBox_Alm_alagamento_status2.Size = this.Size;
			this.CheckBox_Alm_alagamento_status.TabIndex = 2;
			this.CheckBox_Alm_alagamento_status.TabStop = false;
			this.CheckBox_Alm_alagamento_status.Text = "Alagamento";
			this.CheckBox_Alm_alagamento_status.UseVisualStyleBackColor = true;
			this.CheckBox_Alm_energia_status.AutoCheck = false;
			global::System.Windows.Forms.Control checkBox_Alm_energia_status = this.CheckBox_Alm_energia_status;
checkBox_Alm_energia_status.Location = new global::System.Drawing.Point(105, 29);
			this.CheckBox_Alm_energia_status.Name = "CheckBox_Alm_energia_status";
			global::System.Windows.Forms.Control checkBox_Alm_energia_status2 = this.CheckBox_Alm_energia_status;
			Size = new System.Drawing.Size(90, 17);
			checkBox_Alm_energia_status2.Size = this.Size;
			this.CheckBox_Alm_energia_status.TabIndex = 0;
			this.CheckBox_Alm_energia_status.TabStop = false;
			this.CheckBox_Alm_energia_status.Text = "Falha energia";
			this.CheckBox_Alm_energia_status.UseVisualStyleBackColor = true;
			this.CheckBox_Alm_arrombamento_status.AutoCheck = false;
			global::System.Windows.Forms.Control checkBox_Alm_arrombamento_status = this.CheckBox_Alm_arrombamento_status;
checkBox_Alm_arrombamento_status.Location = new global::System.Drawing.Point(307, 29);
			this.CheckBox_Alm_arrombamento_status.Name = "CheckBox_Alm_arrombamento_status";
			global::System.Windows.Forms.Control checkBox_Alm_arrombamento_status2 = this.CheckBox_Alm_arrombamento_status;
			Size = new System.Drawing.Size(94, 17);
			checkBox_Alm_arrombamento_status2.Size = this.Size;
			this.CheckBox_Alm_arrombamento_status.TabIndex = 1;
			this.CheckBox_Alm_arrombamento_status.TabStop = false;
			this.CheckBox_Alm_arrombamento_status.Text = "Arrombamento";
			this.CheckBox_Alm_arrombamento_status.UseVisualStyleBackColor = true;
			this.Grupo_bomba3.Controls.Add(this.Modo_b3);
			this.Grupo_bomba3.Controls.Add(this.Label_modo_b3);
			this.Grupo_bomba3.Controls.Add(this.Cmd_manual_b3);
			this.Grupo_bomba3.Controls.Add(this.Cmd_desliga_b3);
			this.Grupo_bomba3.Controls.Add(this.Cmd_liga_b3);
			this.Grupo_bomba3.Controls.Add(this.Label_status_b3);
			this.Grupo_bomba3.Controls.Add(this.Cmd_automatico_b3);
			this.Grupo_bomba3.Controls.Add(this.Status_b3);
			global::System.Windows.Forms.Control grupo_bomba = this.Grupo_bomba3;
grupo_bomba.Location = new global::System.Drawing.Point(502, 28);
			this.Grupo_bomba3.Name = "Grupo_bomba3";
			global::System.Windows.Forms.Control grupo_bomba2 = this.Grupo_bomba3;
			Size = new System.Drawing.Size(195, 156);
			grupo_bomba2.Size = this.Size;
			this.Grupo_bomba3.TabIndex = 2;
			this.Grupo_bomba3.TabStop = false;
			this.Grupo_bomba3.Text = "Bomba 3";
			this.Label_modo_b3.AutoSize = true;
			global::System.Windows.Forms.Control label_modo_b = this.Label_modo_b3;
label_modo_b.Location = new global::System.Drawing.Point(11, 55);
			this.Label_modo_b3.Name = "Label_modo_b3";
			global::System.Windows.Forms.Control label_modo_b2 = this.Label_modo_b3;
			Size = new System.Drawing.Size(63, 13);
			label_modo_b2.Size = this.Size;
			this.Label_modo_b3.TabIndex = 6;
			this.Label_modo_b3.Text = "Modo Ope :";
			this.Modo_b3.BackColor = global::System.Drawing.Color.Beige;
			global::System.Windows.Forms.Control modo_b = this.Modo_b3;
modo_b.Location = new global::System.Drawing.Point(73, 52);
			this.Modo_b3.Name = "Modo_b3";
			this.Modo_b3.ReadOnly = true;
			global::System.Windows.Forms.Control modo_b2 = this.Modo_b3;
			Size = new System.Drawing.Size(109, 20);
			modo_b2.Size = this.Size;
			this.Modo_b3.TabIndex = 7;
			this.Modo_b3.TabStop = false;
			this.Modo_b3.TextAlign = HorizontalAlignment.Right;
			global::System.Windows.Forms.Control cmd_manual_b = this.Cmd_manual_b3;
cmd_manual_b.Location = new global::System.Drawing.Point(101, 118);
			this.Cmd_manual_b3.Name = "Cmd_manual_b3";
			global::System.Windows.Forms.Control cmd_manual_b2 = this.Cmd_manual_b3;
			Size = new System.Drawing.Size(81, 26);
			cmd_manual_b2.Size = this.Size;
			this.Cmd_manual_b3.TabIndex = 3;
			this.Cmd_manual_b3.Text = "Manual";
			this.Cmd_manual_b3.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control cmd_desliga_b = this.Cmd_desliga_b3;
cmd_desliga_b.Location = new global::System.Drawing.Point(14, 118);
			this.Cmd_desliga_b3.Name = "Cmd_desliga_b3";
			global::System.Windows.Forms.Control cmd_desliga_b2 = this.Cmd_desliga_b3;
			Size = new System.Drawing.Size(81, 26);
			cmd_desliga_b2.Size = this.Size;
			this.Cmd_desliga_b3.TabIndex = 3;
			this.Cmd_desliga_b3.Text = "Desligar";
			this.Cmd_desliga_b3.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control cmd_liga_b = this.Cmd_liga_b3;
cmd_liga_b.Location = new global::System.Drawing.Point(14, 86);
			this.Cmd_liga_b3.Name = "Cmd_liga_b3";
			global::System.Windows.Forms.Control cmd_liga_b2 = this.Cmd_liga_b3;
			Size = new System.Drawing.Size(81, 26);
			cmd_liga_b2.Size = this.Size;
			this.Cmd_liga_b3.TabIndex = 2;
			this.Cmd_liga_b3.Text = "Ligar";
			this.Cmd_liga_b3.UseVisualStyleBackColor = true;
			this.Label_status_b3.AutoSize = true;
			global::System.Windows.Forms.Control label_status_b = this.Label_status_b3;
label_status_b.Location = new global::System.Drawing.Point(11, 27);
			this.Label_status_b3.Name = "Label_status_b3";
			global::System.Windows.Forms.Control label_status_b2 = this.Label_status_b3;
			Size = new System.Drawing.Size(43, 13);
			label_status_b2.Size = this.Size;
			this.Label_status_b3.TabIndex = 0;
			this.Label_status_b3.Text = "Status :";
			global::System.Windows.Forms.Control cmd_automatico_b = this.Cmd_automatico_b3;
cmd_automatico_b.Location = new global::System.Drawing.Point(101, 86);
			this.Cmd_automatico_b3.Name = "Cmd_automatico_b3";
			global::System.Windows.Forms.Control cmd_automatico_b2 = this.Cmd_automatico_b3;
			Size = new System.Drawing.Size(81, 26);
			cmd_automatico_b2.Size = this.Size;
			this.Cmd_automatico_b3.TabIndex = 2;
			this.Cmd_automatico_b3.Text = "Automático";
			this.Cmd_automatico_b3.UseVisualStyleBackColor = true;
			this.Status_b3.BackColor = global::System.Drawing.Color.Beige;
			global::System.Windows.Forms.Control status_b = this.Status_b3;
status_b.Location = new global::System.Drawing.Point(73, 24);
			this.Status_b3.Name = "Status_b3";
			this.Status_b3.ReadOnly = true;
			global::System.Windows.Forms.Control status_b2 = this.Status_b3;
			Size = new System.Drawing.Size(109, 20);
			status_b2.Size = this.Size;
			this.Status_b3.TabIndex = 1;
			this.Status_b3.TabStop = false;
			this.Status_b3.TextAlign = HorizontalAlignment.Right;
			this.Grupo_bomba2.Controls.Add(this.Modo_b2);
			this.Grupo_bomba2.Controls.Add(this.Label_modo_b2);
			this.Grupo_bomba2.Controls.Add(this.Cmd_manual_b2);
			this.Grupo_bomba2.Controls.Add(this.Cmd_desliga_b2);
			this.Grupo_bomba2.Controls.Add(this.Cmd_liga_b2);
			this.Grupo_bomba2.Controls.Add(this.Cmd_automatico_b2);
			this.Grupo_bomba2.Controls.Add(this.Label_status_b2);
			this.Grupo_bomba2.Controls.Add(this.Status_b2);
			global::System.Windows.Forms.Control grupo_bomba3 = this.Grupo_bomba2;
grupo_bomba3.Location = new global::System.Drawing.Point(260, 28);
			this.Grupo_bomba2.Name = "Grupo_bomba2";
			global::System.Windows.Forms.Control grupo_bomba4 = this.Grupo_bomba2;
			Size = new System.Drawing.Size(195, 156);
			grupo_bomba4.Size = this.Size;
			this.Grupo_bomba2.TabIndex = 1;
			this.Grupo_bomba2.TabStop = false;
			this.Grupo_bomba2.Text = "Bomba 2";
			this.Label_modo_b2.AutoSize = true;
			global::System.Windows.Forms.Control label_modo_b3 = this.Label_modo_b2;
label_modo_b3.Location = new global::System.Drawing.Point(11, 55);
			this.Label_modo_b2.Name = "Label_modo_b2";
			global::System.Windows.Forms.Control label_modo_b4 = this.Label_modo_b2;
			Size = new System.Drawing.Size(63, 13);
			label_modo_b4.Size = this.Size;
			this.Label_modo_b2.TabIndex = 4;
			this.Label_modo_b2.Text = "Modo Ope :";
			this.Modo_b2.BackColor = global::System.Drawing.Color.Beige;
			global::System.Windows.Forms.Control modo_b3 = this.Modo_b2;
modo_b3.Location = new global::System.Drawing.Point(73, 52);
			this.Modo_b2.Name = "Modo_b2";
			this.Modo_b2.ReadOnly = true;
			global::System.Windows.Forms.Control modo_b4 = this.Modo_b2;
			Size = new System.Drawing.Size(109, 20);
			modo_b4.Size = this.Size;
			this.Modo_b2.TabIndex = 5;
			this.Modo_b2.TabStop = false;
			this.Modo_b2.TextAlign = HorizontalAlignment.Right;
			global::System.Windows.Forms.Control cmd_manual_b3 = this.Cmd_manual_b2;
cmd_manual_b3.Location = new global::System.Drawing.Point(101, 118);
			this.Cmd_manual_b2.Name = "Cmd_manual_b2";
			global::System.Windows.Forms.Control cmd_manual_b4 = this.Cmd_manual_b2;
			Size = new System.Drawing.Size(81, 26);
			cmd_manual_b4.Size = this.Size;
			this.Cmd_manual_b2.TabIndex = 3;
			this.Cmd_manual_b2.Text = "Manual";
			this.Cmd_manual_b2.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control cmd_desliga_b3 = this.Cmd_desliga_b2;
cmd_desliga_b3.Location = new global::System.Drawing.Point(14, 118);
			this.Cmd_desliga_b2.Name = "Cmd_desliga_b2";
			global::System.Windows.Forms.Control cmd_desliga_b4 = this.Cmd_desliga_b2;
			Size = new System.Drawing.Size(81, 26);
			cmd_desliga_b4.Size = this.Size;
			this.Cmd_desliga_b2.TabIndex = 3;
			this.Cmd_desliga_b2.Text = "Desligar";
			this.Cmd_desliga_b2.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control cmd_liga_b3 = this.Cmd_liga_b2;
cmd_liga_b3.Location = new global::System.Drawing.Point(14, 86);
			this.Cmd_liga_b2.Name = "Cmd_liga_b2";
			global::System.Windows.Forms.Control cmd_liga_b4 = this.Cmd_liga_b2;
			Size = new System.Drawing.Size(81, 26);
			cmd_liga_b4.Size = this.Size;
			this.Cmd_liga_b2.TabIndex = 2;
			this.Cmd_liga_b2.Text = "Ligar";
			this.Cmd_liga_b2.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control cmd_automatico_b3 = this.Cmd_automatico_b2;
cmd_automatico_b3.Location = new global::System.Drawing.Point(101, 86);
			this.Cmd_automatico_b2.Name = "Cmd_automatico_b2";
			global::System.Windows.Forms.Control cmd_automatico_b4 = this.Cmd_automatico_b2;
			Size = new System.Drawing.Size(81, 26);
			cmd_automatico_b4.Size = this.Size;
			this.Cmd_automatico_b2.TabIndex = 2;
			this.Cmd_automatico_b2.Text = "Automático";
			this.Cmd_automatico_b2.UseVisualStyleBackColor = true;
			this.Label_status_b2.AutoSize = true;
			global::System.Windows.Forms.Control label_status_b3 = this.Label_status_b2;
label_status_b3.Location = new global::System.Drawing.Point(11, 27);
			this.Label_status_b2.Name = "Label_status_b2";
			global::System.Windows.Forms.Control label_status_b4 = this.Label_status_b2;
			Size = new System.Drawing.Size(43, 13);
			label_status_b4.Size = this.Size;
			this.Label_status_b2.TabIndex = 0;
			this.Label_status_b2.Text = "Status :";
			this.Status_b2.BackColor = global::System.Drawing.Color.Beige;
			global::System.Windows.Forms.Control status_b3 = this.Status_b2;
status_b3.Location = new global::System.Drawing.Point(73, 24);
			this.Status_b2.Name = "Status_b2";
			this.Status_b2.ReadOnly = true;
			global::System.Windows.Forms.Control status_b4 = this.Status_b2;
			Size = new System.Drawing.Size(109, 20);
			status_b4.Size = this.Size;
			this.Status_b2.TabIndex = 1;
			this.Status_b2.TabStop = false;
			this.Status_b2.TextAlign = HorizontalAlignment.Right;
			this.Grupo_bomba1.Controls.Add(this.Modo_b1);
			this.Grupo_bomba1.Controls.Add(this.Cmd_manual_b1);
			this.Grupo_bomba1.Controls.Add(this.Cmd_desliga_b1);
			this.Grupo_bomba1.Controls.Add(this.Cmd_automatico_b1);
			this.Grupo_bomba1.Controls.Add(this.Cmd_liga_b1);
			this.Grupo_bomba1.Controls.Add(this.Label_modo_b1);
			this.Grupo_bomba1.Controls.Add(this.Label_status_b1);
			this.Grupo_bomba1.Controls.Add(this.Status_b1);
			global::System.Windows.Forms.Control grupo_bomba5 = this.Grupo_bomba1;
grupo_bomba5.Location = new global::System.Drawing.Point(18, 28);
			this.Grupo_bomba1.Name = "Grupo_bomba1";
			global::System.Windows.Forms.Control grupo_bomba6 = this.Grupo_bomba1;
			Size = new System.Drawing.Size(195, 156);
			grupo_bomba6.Size = this.Size;
			this.Grupo_bomba1.TabIndex = 0;
			this.Grupo_bomba1.TabStop = false;
			this.Grupo_bomba1.Text = "Bomba 1";
			global::System.Windows.Forms.Control cmd_manual_b5 = this.Cmd_manual_b1;
cmd_manual_b5.Location = new global::System.Drawing.Point(101, 118);
			this.Cmd_manual_b1.Name = "Cmd_manual_b1";
			global::System.Windows.Forms.Control cmd_manual_b6 = this.Cmd_manual_b1;
			Size = new System.Drawing.Size(81, 26);
			cmd_manual_b6.Size = this.Size;
			this.Cmd_manual_b1.TabIndex = 3;
			this.Cmd_manual_b1.Text = "Manual";
			this.Cmd_manual_b1.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control cmd_desliga_b5 = this.Cmd_desliga_b1;
cmd_desliga_b5.Location = new global::System.Drawing.Point(14, 118);
			this.Cmd_desliga_b1.Name = "Cmd_desliga_b1";
			global::System.Windows.Forms.Control cmd_desliga_b6 = this.Cmd_desliga_b1;
			Size = new System.Drawing.Size(81, 26);
			cmd_desliga_b6.Size = this.Size;
			this.Cmd_desliga_b1.TabIndex = 3;
			this.Cmd_desliga_b1.Text = "Desligar";
			this.Cmd_desliga_b1.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control cmd_automatico_b5 = this.Cmd_automatico_b1;
cmd_automatico_b5.Location = new global::System.Drawing.Point(101, 86);
			this.Cmd_automatico_b1.Name = "Cmd_automatico_b1";
			global::System.Windows.Forms.Control cmd_automatico_b6 = this.Cmd_automatico_b1;
			Size = new System.Drawing.Size(81, 26);
			cmd_automatico_b6.Size = this.Size;
			this.Cmd_automatico_b1.TabIndex = 2;
			this.Cmd_automatico_b1.Text = "Automático";
			this.Cmd_automatico_b1.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control cmd_liga_b5 = this.Cmd_liga_b1;
cmd_liga_b5.Location = new global::System.Drawing.Point(14, 86);
			this.Cmd_liga_b1.Name = "Cmd_liga_b1";
			global::System.Windows.Forms.Control cmd_liga_b6 = this.Cmd_liga_b1;
			Size = new System.Drawing.Size(81, 26);
			cmd_liga_b6.Size = this.Size;
			this.Cmd_liga_b1.TabIndex = 2;
			this.Cmd_liga_b1.Text = "Ligar";
			this.Cmd_liga_b1.UseVisualStyleBackColor = true;
			this.Label_modo_b1.AutoSize = true;
			global::System.Windows.Forms.Control label_modo_b5 = this.Label_modo_b1;
label_modo_b5.Location = new global::System.Drawing.Point(11, 55);
			this.Label_modo_b1.Name = "Label_modo_b1";
			global::System.Windows.Forms.Control label_modo_b6 = this.Label_modo_b1;
			Size = new System.Drawing.Size(63, 13);
			label_modo_b6.Size = this.Size;
			this.Label_modo_b1.TabIndex = 0;
			this.Label_modo_b1.Text = "Modo Ope :";
			this.Modo_b1.BackColor = global::System.Drawing.Color.Beige;
			global::System.Windows.Forms.Control modo_b5 = this.Modo_b1;
modo_b5.Location = new global::System.Drawing.Point(73, 52);
			this.Modo_b1.Name = "Modo_b1";
			this.Modo_b1.ReadOnly = true;
			global::System.Windows.Forms.Control modo_b6 = this.Modo_b1;
			Size = new System.Drawing.Size(109, 20);
			modo_b6.Size = this.Size;
			this.Modo_b1.TabIndex = 1;
			this.Modo_b1.TabStop = false;
			this.Modo_b1.TextAlign = HorizontalAlignment.Right;
			this.Label_status_b1.AutoSize = true;
			global::System.Windows.Forms.Control label_status_b5 = this.Label_status_b1;
label_status_b5.Location = new global::System.Drawing.Point(11, 27);
			this.Label_status_b1.Name = "Label_status_b1";
			global::System.Windows.Forms.Control label_status_b6 = this.Label_status_b1;
			Size = new System.Drawing.Size(43, 13);
			label_status_b6.Size = this.Size;
			this.Label_status_b1.TabIndex = 0;
			this.Label_status_b1.Text = "Status :";
			this.Status_b1.BackColor = global::System.Drawing.Color.Beige;
			global::System.Windows.Forms.Control status_b5 = this.Status_b1;
status_b5.Location = new global::System.Drawing.Point(73, 24);
			this.Status_b1.Name = "Status_b1";
			this.Status_b1.ReadOnly = true;
			global::System.Windows.Forms.Control status_b6 = this.Status_b1;
			Size = new System.Drawing.Size(109, 20);
			status_b6.Size = this.Size;
			this.Status_b1.TabIndex = 1;
			this.Status_b1.TabStop = false;
			this.Status_b1.TextAlign = HorizontalAlignment.Right;
			this.Grupo_setpoints.Controls.Add(this.Comando_escreve_setpoint);
			this.Grupo_setpoints.Controls.Add(this.Comando_le_setpoint);
			this.Grupo_setpoints.Controls.Add(this.Grupo_set_B3);
			this.Grupo_setpoints.Controls.Add(this.Grupo_set_B2);
			this.Grupo_setpoints.Controls.Add(this.Grupo_set_B1);
			global::System.Windows.Forms.Control grupo_setpoints = this.Grupo_setpoints;
grupo_setpoints.Location = new global::System.Drawing.Point(15, 501);
			this.Grupo_setpoints.Name = "Grupo_setpoints";
			global::System.Windows.Forms.Control grupo_setpoints2 = this.Grupo_setpoints;
			Size = new System.Drawing.Size(520, 181);
			grupo_setpoints2.Size = this.Size;
			this.Grupo_setpoints.TabIndex = 3;
			this.Grupo_setpoints.TabStop = false;
			this.Grupo_setpoints.Text = "Setpoints";
			global::System.Windows.Forms.Control comando_escreve_setpoint = this.Comando_escreve_setpoint;
comando_escreve_setpoint.Location = new global::System.Drawing.Point(376, 140);
			this.Comando_escreve_setpoint.Name = "Comando_escreve_setpoint";
			global::System.Windows.Forms.Control comando_escreve_setpoint2 = this.Comando_escreve_setpoint;
			Size = new System.Drawing.Size(124, 26);
			comando_escreve_setpoint2.Size = this.Size;
			this.Comando_escreve_setpoint.TabIndex = 4;
			this.Comando_escreve_setpoint.Text = "Escrever";
			this.Comando_escreve_setpoint.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control comando_le_setpoint = this.Comando_le_setpoint;
comando_le_setpoint.Location = new global::System.Drawing.Point(21, 140);
			this.Comando_le_setpoint.Name = "Comando_le_setpoint";
			global::System.Windows.Forms.Control comando_le_setpoint2 = this.Comando_le_setpoint;
			Size = new System.Drawing.Size(124, 26);
			comando_le_setpoint2.Size = this.Size;
			this.Comando_le_setpoint.TabIndex = 3;
			this.Comando_le_setpoint.Text = "Ler";
			this.Comando_le_setpoint.UseVisualStyleBackColor = true;
			this.Grupo_set_B3.Controls.Add(this.Set_valor_Desiga_B3);
			this.Grupo_set_B3.Controls.Add(this.Label3);
			this.Grupo_set_B3.Controls.Add(this.Label_liga_b3);
			this.Grupo_set_B3.Controls.Add(this.Set_valor_Liga_B3);
			global::System.Windows.Forms.Control grupo_set_B = this.Grupo_set_B3;
grupo_set_B.Location = new global::System.Drawing.Point(350, 29);
			this.Grupo_set_B3.Name = "Grupo_set_B3";
			global::System.Windows.Forms.Control grupo_set_B2 = this.Grupo_set_B3;
			Size = new System.Drawing.Size(150, 96);
			grupo_set_B2.Size = this.Size;
			this.Grupo_set_B3.TabIndex = 2;
			this.Grupo_set_B3.TabStop = false;
			this.Grupo_set_B3.Text = "Bomba 3 - Níveis";
			this.Set_valor_Desiga_B3.BackColor = global::System.Drawing.SystemColors.ButtonHighlight;
			global::System.Windows.Forms.Control set_valor_Desiga_B = this.Set_valor_Desiga_B3;
set_valor_Desiga_B.Location = new global::System.Drawing.Point(80, 28);
			this.Set_valor_Desiga_B3.Name = "Set_valor_Desiga_B3";
			global::System.Windows.Forms.Control set_valor_Desiga_B2 = this.Set_valor_Desiga_B3;
			Size = new System.Drawing.Size(53, 20);
			set_valor_Desiga_B2.Size = this.Size;
			this.Set_valor_Desiga_B3.TabIndex = 3;
			this.Set_valor_Desiga_B3.Tag = "c";
			this.Set_valor_Desiga_B3.TextAlign = HorizontalAlignment.Center;
			this.Label3.AutoSize = true;
			global::System.Windows.Forms.Control label3 = this.Label3;
label3.Location = new global::System.Drawing.Point(19, 32);
			this.Label3.Name = "Label3";
			global::System.Windows.Forms.Control label4 = this.Label3;
			Size = new System.Drawing.Size(65, 13);
			label4.Size = this.Size;
			this.Label3.TabIndex = 2;
			this.Label3.Text = "Desliga (%) :";
			this.Label_liga_b3.AutoSize = true;
			global::System.Windows.Forms.Control label_liga_b = this.Label_liga_b3;
label_liga_b.Location = new global::System.Drawing.Point(19, 58);
			this.Label_liga_b3.Name = "Label_liga_b3";
			global::System.Windows.Forms.Control label_liga_b2 = this.Label_liga_b3;
			Size = new System.Drawing.Size(50, 13);
			label_liga_b2.Size = this.Size;
			this.Label_liga_b3.TabIndex = 0;
			this.Label_liga_b3.Text = "Liga (%) :";
			this.Set_valor_Liga_B3.BackColor = global::System.Drawing.SystemColors.ButtonHighlight;
			global::System.Windows.Forms.Control set_valor_Liga_B = this.Set_valor_Liga_B3;
set_valor_Liga_B.Location = new global::System.Drawing.Point(80, 55);
			this.Set_valor_Liga_B3.Name = "Set_valor_Liga_B3";
			global::System.Windows.Forms.Control set_valor_Liga_B2 = this.Set_valor_Liga_B3;
			Size = new System.Drawing.Size(53, 20);
			set_valor_Liga_B2.Size = this.Size;
			this.Set_valor_Liga_B3.TabIndex = 1;
			this.Set_valor_Liga_B3.Tag = "c";
			this.Set_valor_Liga_B3.TextAlign = HorizontalAlignment.Center;
			this.Grupo_set_B2.Controls.Add(this.Set_valor_Desiga_B2);
			this.Grupo_set_B2.Controls.Add(this.Label1);
			this.Grupo_set_B2.Controls.Add(this.Label_liga_b2);
			this.Grupo_set_B2.Controls.Add(this.Set_valor_Liga_B2);
			global::System.Windows.Forms.Control grupo_set_B3 = this.Grupo_set_B2;
grupo_set_B3.Location = new global::System.Drawing.Point(183, 28);
			this.Grupo_set_B2.Name = "Grupo_set_B2";
			global::System.Windows.Forms.Control grupo_set_B4 = this.Grupo_set_B2;
			Size = new System.Drawing.Size(150, 96);
			grupo_set_B4.Size = this.Size;
			this.Grupo_set_B2.TabIndex = 1;
			this.Grupo_set_B2.TabStop = false;
			this.Grupo_set_B2.Text = "Bomba 2 - Níveis";
			this.Set_valor_Desiga_B2.BackColor = global::System.Drawing.SystemColors.ButtonHighlight;
			global::System.Windows.Forms.Control set_valor_Desiga_B3 = this.Set_valor_Desiga_B2;
set_valor_Desiga_B3.Location = new global::System.Drawing.Point(79, 28);
			this.Set_valor_Desiga_B2.Name = "Set_valor_Desiga_B2";
			global::System.Windows.Forms.Control set_valor_Desiga_B4 = this.Set_valor_Desiga_B2;
			Size = new System.Drawing.Size(53, 20);
			set_valor_Desiga_B4.Size = this.Size;
			this.Set_valor_Desiga_B2.TabIndex = 3;
			this.Set_valor_Desiga_B2.TextAlign = HorizontalAlignment.Center;
			this.Label1.AutoSize = true;
			global::System.Windows.Forms.Control label5 = this.Label1;
label5.Location = new global::System.Drawing.Point(14, 32);
			this.Label1.Name = "Label1";
			global::System.Windows.Forms.Control label6 = this.Label1;
			Size = new System.Drawing.Size(65, 13);
			label6.Size = this.Size;
			this.Label1.TabIndex = 2;
			this.Label1.Text = "Desliga (%) :";
			this.Label_liga_b2.AutoSize = true;
			global::System.Windows.Forms.Control label_liga_b3 = this.Label_liga_b2;
label_liga_b3.Location = new global::System.Drawing.Point(14, 59);
			this.Label_liga_b2.Name = "Label_liga_b2";
			global::System.Windows.Forms.Control label_liga_b4 = this.Label_liga_b2;
			Size = new System.Drawing.Size(50, 13);
			label_liga_b4.Size = this.Size;
			this.Label_liga_b2.TabIndex = 0;
			this.Label_liga_b2.Text = "Liga (%) :";
			this.Set_valor_Liga_B2.BackColor = global::System.Drawing.SystemColors.ButtonHighlight;
			global::System.Windows.Forms.Control set_valor_Liga_B3 = this.Set_valor_Liga_B2;
set_valor_Liga_B3.Location = new global::System.Drawing.Point(79, 56);
			this.Set_valor_Liga_B2.Name = "Set_valor_Liga_B2";
			global::System.Windows.Forms.Control set_valor_Liga_B4 = this.Set_valor_Liga_B2;
			Size = new System.Drawing.Size(53, 20);
			set_valor_Liga_B4.Size = this.Size;
			this.Set_valor_Liga_B2.TabIndex = 1;
			this.Set_valor_Liga_B2.TextAlign = HorizontalAlignment.Center;
			this.Grupo_set_B1.Controls.Add(this.Set_valor_Desiga_B1);
			this.Grupo_set_B1.Controls.Add(this.Label_desliga_b1);
			this.Grupo_set_B1.Controls.Add(this.Label_liga_b1);
			this.Grupo_set_B1.Controls.Add(this.Set_valor_Liga_B1);
			global::System.Windows.Forms.Control grupo_set_B5 = this.Grupo_set_B1;
grupo_set_B5.Location = new global::System.Drawing.Point(19, 29);
			this.Grupo_set_B1.Name = "Grupo_set_B1";
			global::System.Windows.Forms.Control grupo_set_B6 = this.Grupo_set_B1;
			Size = new System.Drawing.Size(150, 96);
			grupo_set_B6.Size = this.Size;
			this.Grupo_set_B1.TabIndex = 0;
			this.Grupo_set_B1.TabStop = false;
			this.Grupo_set_B1.Text = "Bomba 1 - Níveis";
			this.Set_valor_Desiga_B1.BackColor = global::System.Drawing.SystemColors.ButtonHighlight;
			global::System.Windows.Forms.Control set_valor_Desiga_B5 = this.Set_valor_Desiga_B1;
set_valor_Desiga_B5.Location = new global::System.Drawing.Point(69, 28);
			this.Set_valor_Desiga_B1.Name = "Set_valor_Desiga_B1";
			global::System.Windows.Forms.Control set_valor_Desiga_B6 = this.Set_valor_Desiga_B1;
			Size = new System.Drawing.Size(53, 20);
			set_valor_Desiga_B6.Size = this.Size;
			this.Set_valor_Desiga_B1.TabIndex = 3;
			this.Set_valor_Desiga_B1.TextAlign = HorizontalAlignment.Center;
			this.Label_desliga_b1.AutoSize = true;
			global::System.Windows.Forms.Control label_desliga_b = this.Label_desliga_b1;
label_desliga_b.Location = new global::System.Drawing.Point(10, 32);
			this.Label_desliga_b1.Name = "Label_desliga_b1";
			global::System.Windows.Forms.Control label_desliga_b2 = this.Label_desliga_b1;
			Size = new System.Drawing.Size(65, 13);
			label_desliga_b2.Size = this.Size;
			this.Label_desliga_b1.TabIndex = 2;
			this.Label_desliga_b1.Text = "Desliga (%) :";
			this.Label_liga_b1.AutoSize = true;
			global::System.Windows.Forms.Control label_liga_b5 = this.Label_liga_b1;
label_liga_b5.Location = new global::System.Drawing.Point(10, 58);
			this.Label_liga_b1.Name = "Label_liga_b1";
			global::System.Windows.Forms.Control label_liga_b6 = this.Label_liga_b1;
			Size = new System.Drawing.Size(50, 13);
			label_liga_b6.Size = this.Size;
			this.Label_liga_b1.TabIndex = 0;
			this.Label_liga_b1.Text = "Liga (%) :";
			this.Set_valor_Liga_B1.BackColor = global::System.Drawing.SystemColors.ButtonHighlight;
			global::System.Windows.Forms.Control set_valor_Liga_B5 = this.Set_valor_Liga_B1;
set_valor_Liga_B5.Location = new global::System.Drawing.Point(69, 55);
			this.Set_valor_Liga_B1.Name = "Set_valor_Liga_B1";
			global::System.Windows.Forms.Control set_valor_Liga_B6 = this.Set_valor_Liga_B1;
			Size = new System.Drawing.Size(53, 20);
			set_valor_Liga_B6.Size = this.Size;
			this.Set_valor_Liga_B1.TabIndex = 1;
			this.Set_valor_Liga_B1.TextAlign = HorizontalAlignment.Center;
			this.Timer_monitoracao.Interval = 2000;
			this.Grupo_estatistica.Controls.Add(this.Label_Est_retry);
			this.Grupo_estatistica.Controls.Add(this.Est_retry);
			this.Grupo_estatistica.Controls.Add(this.Est_eficiencia);
			this.Grupo_estatistica.Controls.Add(this.Button_limpa_estatistica);
			this.Grupo_estatistica.Controls.Add(this.Label_Est_RX);
			this.Grupo_estatistica.Controls.Add(this.Label_Est_Eficiencia);
			this.Grupo_estatistica.Controls.Add(this.Label_Est_TX);
			this.Grupo_estatistica.Controls.Add(this.Est_Rx);
			this.Grupo_estatistica.Controls.Add(this.Est_TX);
			global::System.Windows.Forms.Control grupo_estatistica = this.Grupo_estatistica;
grupo_estatistica.Location = new global::System.Drawing.Point(563, 502);
			this.Grupo_estatistica.Name = "Grupo_estatistica";
			global::System.Windows.Forms.Control grupo_estatistica2 = this.Grupo_estatistica;
			Size = new System.Drawing.Size(170, 180);
			grupo_estatistica2.Size = this.Size;
			this.Grupo_estatistica.TabIndex = 4;
			this.Grupo_estatistica.TabStop = false;
			this.Grupo_estatistica.Tag = "v";
			this.Grupo_estatistica.Text = "Estatística";
			this.Label_Est_retry.AutoSize = true;
			global::System.Windows.Forms.Control label_Est_retry = this.Label_Est_retry;
label_Est_retry.Location = new global::System.Drawing.Point(28, 76);
			this.Label_Est_retry.Name = "Label_Est_retry";
			global::System.Windows.Forms.Control label_Est_retry2 = this.Label_Est_retry;
			Size = new System.Drawing.Size(63, 13);
			label_Est_retry2.Size = this.Size;
			this.Label_Est_retry.TabIndex = 10;
			this.Label_Est_retry.Text = "Tentativas :";
			this.Est_retry.BackColor = global::System.Drawing.Color.Beige;
			global::System.Windows.Forms.Control est_retry = this.Est_retry;
est_retry.Location = new global::System.Drawing.Point(107, 73);
			this.Est_retry.Name = "Est_retry";
			this.Est_retry.ReadOnly = true;
			global::System.Windows.Forms.Control est_retry2 = this.Est_retry;
			Size = new System.Drawing.Size(53, 20);
			est_retry2.Size = this.Size;
			this.Est_retry.TabIndex = 9;
			this.Est_retry.Tag = "c";
			this.Est_retry.TextAlign = HorizontalAlignment.Center;
			this.Est_eficiencia.BackColor = global::System.Drawing.Color.Beige;
			global::System.Windows.Forms.Control est_eficiencia = this.Est_eficiencia;
est_eficiencia.Location = new global::System.Drawing.Point(107, 99);
			this.Est_eficiencia.Name = "Est_eficiencia";
			this.Est_eficiencia.ReadOnly = true;
			global::System.Windows.Forms.Control est_eficiencia2 = this.Est_eficiencia;
			Size = new System.Drawing.Size(53, 20);
			est_eficiencia2.Size = this.Size;
			this.Est_eficiencia.TabIndex = 5;
			this.Est_eficiencia.Tag = "c";
			this.Est_eficiencia.TextAlign = HorizontalAlignment.Center;
			global::System.Windows.Forms.Control button_limpa_estatistica = this.Button_limpa_estatistica;
button_limpa_estatistica.Location = new global::System.Drawing.Point(29, 140);
			this.Button_limpa_estatistica.Name = "Button_limpa_estatistica";
			global::System.Windows.Forms.Control button_limpa_estatistica2 = this.Button_limpa_estatistica;
			Size = new System.Drawing.Size(112, 26);
			button_limpa_estatistica2.Size = this.Size;
			this.Button_limpa_estatistica.TabIndex = 8;
			this.Button_limpa_estatistica.Text = "Reiniciar";
			this.Button_limpa_estatistica.UseVisualStyleBackColor = true;
			this.Label_Est_RX.AutoSize = true;
			global::System.Windows.Forms.Control label_Est_RX = this.Label_Est_RX;
label_Est_RX.Location = new global::System.Drawing.Point(28, 50);
			this.Label_Est_RX.Name = "Label_Est_RX";
			global::System.Windows.Forms.Control label_Est_RX2 = this.Label_Est_RX;
			Size = new System.Drawing.Size(28, 13);
			label_Est_RX2.Size = this.Size;
			this.Label_Est_RX.TabIndex = 7;
			this.Label_Est_RX.Text = "RX :";
			this.Label_Est_Eficiencia.AutoSize = true;
			global::System.Windows.Forms.Control label_Est_Eficiencia = this.Label_Est_Eficiencia;
label_Est_Eficiencia.Location = new global::System.Drawing.Point(26, 102);
			this.Label_Est_Eficiencia.Name = "Label_Est_Eficiencia";
			global::System.Windows.Forms.Control label_Est_Eficiencia2 = this.Label_Est_Eficiencia;
			Size = new System.Drawing.Size(73, 13);
			label_Est_Eficiencia2.Size = this.Size;
			this.Label_Est_Eficiencia.TabIndex = 7;
			this.Label_Est_Eficiencia.Text = "Eficiência(%) :";
			this.Label_Est_TX.AutoSize = true;
			global::System.Windows.Forms.Control label_Est_TX = this.Label_Est_TX;
label_Est_TX.Location = new global::System.Drawing.Point(28, 24);
			this.Label_Est_TX.Name = "Label_Est_TX";
			global::System.Windows.Forms.Control label_Est_TX2 = this.Label_Est_TX;
			Size = new System.Drawing.Size(27, 13);
			label_Est_TX2.Size = this.Size;
			this.Label_Est_TX.TabIndex = 6;
			this.Label_Est_TX.Text = "TX :";
			this.Est_Rx.BackColor = global::System.Drawing.Color.Beige;
			global::System.Windows.Forms.Control est_Rx = this.Est_Rx;
est_Rx.Location = new global::System.Drawing.Point(107, 47);
			this.Est_Rx.Name = "Est_Rx";
			this.Est_Rx.ReadOnly = true;
			global::System.Windows.Forms.Control est_Rx2 = this.Est_Rx;
			Size = new System.Drawing.Size(53, 20);
			est_Rx2.Size = this.Size;
			this.Est_Rx.TabIndex = 5;
			this.Est_Rx.Tag = "c";
			this.Est_Rx.TextAlign = HorizontalAlignment.Center;
			this.Est_TX.BackColor = global::System.Drawing.Color.Beige;
			global::System.Windows.Forms.Control est_TX = this.Est_TX;
est_TX.Location = new global::System.Drawing.Point(107, 21);
			this.Est_TX.Name = "Est_TX";
			this.Est_TX.ReadOnly = true;
			global::System.Windows.Forms.Control est_TX2 = this.Est_TX;
			Size = new System.Drawing.Size(53, 20);
			est_TX2.Size = this.Size;
			this.Est_TX.TabIndex = 4;
			this.Est_TX.Tag = "c";
			this.Est_TX.TextAlign = HorizontalAlignment.Center;
			global::System.Drawing.SizeF autoScaleDimensions;
			autoScaleDimensions = new global::System.Drawing.SizeF(6f, 13f);
			this.AutoScaleDimensions = autoScaleDimensions;
			this.AutoScaleMode = AutoScaleMode.Font;
			Size = new System.Drawing.Size(745, 707);
			this.ClientSize = Size;
			this.Controls.Add(this.Grupo_estatistica);
			this.Controls.Add(this.Grupo_setpoints);
			this.Controls.Add(this.Grupo_status);
			this.Controls.Add(this.Grupo_escrita_de_dados);
			this.Controls.Add(this.Grupo_ctrl_com);
			this.FormBorderStyle = FormBorderStyle.None;
this.Location = new global::System.Drawing.Point(160, 2);
			this.Name = "Equip_201_mon";
			this.StartPosition = global::System.Windows.Forms.FormStartPosition.Manual;
			this.Text = "Equip_201_mon";
			this.Grupo_escrita_de_dados.ResumeLayout(false);
			this.Grupo_escrita_de_dados.PerformLayout();
			
			this.Grupo_simulacao_alarmes.ResumeLayout(false);
			this.Grupo_simulacao_alarmes.PerformLayout();
			this.Grupo_ctrl_com.ResumeLayout(false);
			this.Grupo_ctrl_com.PerformLayout();
			
			
			this.Grupo_status.ResumeLayout(false);
			this.Grupo_alarmes.ResumeLayout(false);
			this.Grupo_bomba3.ResumeLayout(false);
			this.Grupo_bomba3.PerformLayout();
			this.Grupo_bomba2.ResumeLayout(false);
			this.Grupo_bomba2.PerformLayout();
			this.Grupo_bomba1.ResumeLayout(false);
			this.Grupo_bomba1.PerformLayout();
			this.Grupo_setpoints.ResumeLayout(false);
			this.Grupo_set_B3.ResumeLayout(false);
			this.Grupo_set_B3.PerformLayout();
			this.Grupo_set_B2.ResumeLayout(false);
			this.Grupo_set_B2.PerformLayout();
			this.Grupo_set_B1.ResumeLayout(false);
			this.Grupo_set_B1.PerformLayout();
			this.Grupo_estatistica.ResumeLayout(false);
			this.Grupo_estatistica.PerformLayout();
			this.ResumeLayout(false);
		}

		// Token: 0x04001587 RID: 5511
		private global::System.ComponentModel.IContainer components;
	}
}
