namespace iS800
{
	// Token: 0x02000085 RID: 133
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class Equip_202_mon : global::System.Windows.Forms.Form
	{
		// Token: 0x06002073 RID: 8307 RVA: 0x003EDF78 File Offset: 0x003EC378
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				if (disposing && this.components != null)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x06002074 RID: 8308 RVA: 0x003EDFB8 File Offset: 0x003EC3B8
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.components = new global::System.ComponentModel.Container();
			this.Grupo_ctrl_com = new global::System.Windows.Forms.GroupBox();
			this.msg_modo_operacao = new global::System.Windows.Forms.TextBox();
			this.Tela_endereco_estacao = new global::System.Windows.Forms.NumericUpDown();
			this.Tela_endereco_mestre = new global::System.Windows.Forms.NumericUpDown();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.msg = new global::System.Windows.Forms.TextBox();
			this.Comando_hab_monitoracao = new global::System.Windows.Forms.Button();
			this.Label_end_estacao = new global::System.Windows.Forms.Label();
			this.Timer_monitoracao = new global::System.Windows.Forms.Timer(this.components);
			this.Grupo_setpoints = new global::System.Windows.Forms.GroupBox();
			this.Valor_Niveldesliga = new global::System.Windows.Forms.TextBox();
			this.Label_NivelDesliga = new global::System.Windows.Forms.Label();
			this.Valor_NivelLiga = new global::System.Windows.Forms.TextBox();
			this.Label_NivelLiga = new global::System.Windows.Forms.Label();
			this.Valor_PressaoSuc = new global::System.Windows.Forms.TextBox();
			this.Label_PressaoSuc = new global::System.Windows.Forms.Label();
			this.Valor_PressaoRec = new global::System.Windows.Forms.TextBox();
			this.Label_PressaoRec = new global::System.Windows.Forms.Label();
			this.Valor_TempoMaisUmaBomba = new global::System.Windows.Forms.TextBox();
			this.Label_TempoMaisUmaBomba = new global::System.Windows.Forms.Label();
			this.Valor_NivelB4 = new global::System.Windows.Forms.TextBox();
			this.Label_NivelB4 = new global::System.Windows.Forms.Label();
			this.Valor_NivelB3 = new global::System.Windows.Forms.TextBox();
			this.Label_NivelB3 = new global::System.Windows.Forms.Label();
			this.Valor_NivelB2 = new global::System.Windows.Forms.TextBox();
			this.Label_NivelB2 = new global::System.Windows.Forms.Label();
			this.Valor_NivelB1 = new global::System.Windows.Forms.TextBox();
			this.Label_NivelB1 = new global::System.Windows.Forms.Label();
			this.Valor_NivelDesejado = new global::System.Windows.Forms.TextBox();
			this.Label_NivelDesejado = new global::System.Windows.Forms.Label();
			this.Comando_escreve_setpoint = new global::System.Windows.Forms.Button();
			this.Comando_le_setpoint = new global::System.Windows.Forms.Button();
			this.Grupo_estatistica = new global::System.Windows.Forms.GroupBox();
			this.Label_Est_retry = new global::System.Windows.Forms.Label();
			this.Est_retry = new global::System.Windows.Forms.TextBox();
			this.Est_eficiencia = new global::System.Windows.Forms.TextBox();
			this.Button_limpa_estatistica = new global::System.Windows.Forms.Button();
			this.Label_Est_RX = new global::System.Windows.Forms.Label();
			this.Label_Est_Eficiencia = new global::System.Windows.Forms.Label();
			this.Label_Est_TX = new global::System.Windows.Forms.Label();
			this.Est_Rx = new global::System.Windows.Forms.TextBox();
			this.Est_TX = new global::System.Windows.Forms.TextBox();
			this.Grupo_status = new global::System.Windows.Forms.GroupBox();
			this.Grupo_bomba4 = new global::System.Windows.Forms.GroupBox();
			this.Cmd_falha_b4 = new global::System.Windows.Forms.Button();
			this.Modo_b4 = new global::System.Windows.Forms.TextBox();
			this.Label_modo_b4 = new global::System.Windows.Forms.Label();
			this.Cmd_manual_b4 = new global::System.Windows.Forms.Button();
			this.Cmd_desliga_b4 = new global::System.Windows.Forms.Button();
			this.Cmd_liga_b4 = new global::System.Windows.Forms.Button();
			this.Label_status_b4 = new global::System.Windows.Forms.Label();
			this.Cmd_automatico_b4 = new global::System.Windows.Forms.Button();
			this.Status_b4 = new global::System.Windows.Forms.TextBox();
			this.Grupo_bomba3 = new global::System.Windows.Forms.GroupBox();
			this.Cmd_falha_b3 = new global::System.Windows.Forms.Button();
			this.Modo_b3 = new global::System.Windows.Forms.TextBox();
			this.Label_modo_b3 = new global::System.Windows.Forms.Label();
			this.Cmd_manual_b3 = new global::System.Windows.Forms.Button();
			this.Cmd_desliga_b3 = new global::System.Windows.Forms.Button();
			this.Cmd_liga_b3 = new global::System.Windows.Forms.Button();
			this.Label_status_b3 = new global::System.Windows.Forms.Label();
			this.Cmd_automatico_b3 = new global::System.Windows.Forms.Button();
			this.Status_b3 = new global::System.Windows.Forms.TextBox();
			this.Grupo_bomba2 = new global::System.Windows.Forms.GroupBox();
			this.Cmd_falha_b2 = new global::System.Windows.Forms.Button();
			this.Modo_b2 = new global::System.Windows.Forms.TextBox();
			this.Label_modo_b2 = new global::System.Windows.Forms.Label();
			this.Cmd_manual_b2 = new global::System.Windows.Forms.Button();
			this.Cmd_desliga_b2 = new global::System.Windows.Forms.Button();
			this.Cmd_liga_b2 = new global::System.Windows.Forms.Button();
			this.Cmd_automatico_b2 = new global::System.Windows.Forms.Button();
			this.Label_status_b2 = new global::System.Windows.Forms.Label();
			this.Status_b2 = new global::System.Windows.Forms.TextBox();
			this.Grupo_bomba1 = new global::System.Windows.Forms.GroupBox();
			this.Cmd_falha_b1 = new global::System.Windows.Forms.Button();
			this.Modo_b1 = new global::System.Windows.Forms.TextBox();
			this.Cmd_manual_b1 = new global::System.Windows.Forms.Button();
			this.Cmd_desliga_b1 = new global::System.Windows.Forms.Button();
			this.Cmd_automatico_b1 = new global::System.Windows.Forms.Button();
			this.Cmd_liga_b1 = new global::System.Windows.Forms.Button();
			this.Label_modo_b1 = new global::System.Windows.Forms.Label();
			this.Label_status_b1 = new global::System.Windows.Forms.Label();
			this.Status_b1 = new global::System.Windows.Forms.TextBox();
			this.Grupo_escrita_de_dados = new global::System.Windows.Forms.GroupBox();
			this.Tela_nivel_origem = new global::System.Windows.Forms.NumericUpDown();
			this.Label_nivel_origem = new global::System.Windows.Forms.Label();
			this.Tela_nivel_destino = new global::System.Windows.Forms.NumericUpDown();
			this.Label_nivel_destino = new global::System.Windows.Forms.Label();
			this.Grupo_alarmes = new global::System.Windows.Forms.GroupBox();
			this.CheckBox_Alm_ff_status = new global::System.Windows.Forms.CheckBox();
			this.CheckBox_Alm_bat_bx_status = new global::System.Windows.Forms.CheckBox();
			this.CheckBox_Alm_alagamento_status = new global::System.Windows.Forms.CheckBox();
			this.CheckBox_Alm_ope_bat_status = new global::System.Windows.Forms.CheckBox();
			this.CheckBox_Alm_arrombamento_status = new global::System.Windows.Forms.CheckBox();
			this.Label_EA1 = new global::System.Windows.Forms.Label();
			this.Valor_EA1 = new global::System.Windows.Forms.TextBox();
			this.Label_EA2 = new global::System.Windows.Forms.Label();
			this.Valor_EA2 = new global::System.Windows.Forms.TextBox();
			this.Label_EA3 = new global::System.Windows.Forms.Label();
			this.Valor_EA3 = new global::System.Windows.Forms.TextBox();
			this.Label_EA4 = new global::System.Windows.Forms.Label();
			this.Valor_EA4 = new global::System.Windows.Forms.TextBox();
			this.Label_EA5 = new global::System.Windows.Forms.Label();
			this.Valor_EA5 = new global::System.Windows.Forms.TextBox();
			this.Label_EA6 = new global::System.Windows.Forms.Label();
			this.Valor_EA6 = new global::System.Windows.Forms.TextBox();
			this.Label_EA7 = new global::System.Windows.Forms.Label();
			this.Valor_EA7 = new global::System.Windows.Forms.TextBox();
			this.Label_EA8 = new global::System.Windows.Forms.Label();
			this.Valor_EA8 = new global::System.Windows.Forms.TextBox();
			this.Grupo_medidas = new global::System.Windows.Forms.GroupBox();
			this.Valor_EA16 = new global::System.Windows.Forms.TextBox();
			this.Label_EA16 = new global::System.Windows.Forms.Label();
			this.Valor_EA15 = new global::System.Windows.Forms.TextBox();
			this.Label_EA15 = new global::System.Windows.Forms.Label();
			this.Valor_EA14 = new global::System.Windows.Forms.TextBox();
			this.Label_EA14 = new global::System.Windows.Forms.Label();
			this.Valor_EA13 = new global::System.Windows.Forms.TextBox();
			this.Label_EA13 = new global::System.Windows.Forms.Label();
			this.Valor_EA12 = new global::System.Windows.Forms.TextBox();
			this.Label_EA12 = new global::System.Windows.Forms.Label();
			this.Valor_EA11 = new global::System.Windows.Forms.TextBox();
			this.Label_EA11 = new global::System.Windows.Forms.Label();
			this.Valor_EA10 = new global::System.Windows.Forms.TextBox();
			this.Label_EA10 = new global::System.Windows.Forms.Label();
			this.Valor_EA9 = new global::System.Windows.Forms.TextBox();
			this.Label_EA9 = new global::System.Windows.Forms.Label();
			this.Grupo_ctrl_com.SuspendLayout();
			this.Tela_endereco_estacao.BeginInit();
			this.Tela_endereco_mestre.BeginInit();
			this.Grupo_setpoints.SuspendLayout();
			this.Grupo_estatistica.SuspendLayout();
			this.Grupo_status.SuspendLayout();
			this.Grupo_bomba4.SuspendLayout();
			this.Grupo_bomba3.SuspendLayout();
			this.Grupo_bomba2.SuspendLayout();
			this.Grupo_bomba1.SuspendLayout();
			this.Grupo_escrita_de_dados.SuspendLayout();
			this.Tela_nivel_origem.BeginInit();
			this.Tela_nivel_destino.BeginInit();
			this.Grupo_alarmes.SuspendLayout();
			this.Grupo_medidas.SuspendLayout();
			this.SuspendLayout();
			this.Grupo_ctrl_com.Controls.Add(this.msg_modo_operacao);
			this.Grupo_ctrl_com.Controls.Add(this.Tela_endereco_estacao);
			this.Grupo_ctrl_com.Controls.Add(this.Tela_endereco_mestre);
			this.Grupo_ctrl_com.Controls.Add(this.Label2);
			this.Grupo_ctrl_com.Controls.Add(this.msg);
			this.Grupo_ctrl_com.Controls.Add(this.Comando_hab_monitoracao);
			this.Grupo_ctrl_com.Controls.Add(this.Label_end_estacao);
			global::System.Windows.Forms.Control grupo_ctrl_com = this.Grupo_ctrl_com;
			global::System.Drawing.Point location;
			location = new global::System.Drawing.Point(26, 27);
			grupo_ctrl_com.Location = location;
			this.Grupo_ctrl_com.Name = "Grupo_ctrl_com";
			global::System.Windows.Forms.Control grupo_ctrl_com2 = this.Grupo_ctrl_com;
			global::System.Drawing.Size size;
			size = new global::System.Drawing.Size(333, 176);
			grupo_ctrl_com2.Size = size;
			this.Grupo_ctrl_com.TabIndex = (HorizontalAlignment)1;
			this.Grupo_ctrl_com.TabStop = false;
			this.Grupo_ctrl_com.Text = "Controle de Monitoração";
			this.msg_modo_operacao.BackColor = global::System.Drawing.Color.Beige;
			this.msg_modo_operacao.ForeColor = global::System.Drawing.SystemColors.WindowText;
			global::System.Windows.Forms.Control msg_modo_operacao = this.msg_modo_operacao;
			location = new global::System.Drawing.Point(23, 137);
			msg_modo_operacao.Location = location;
			this.msg_modo_operacao.Multiline = true;
			this.msg_modo_operacao.Name = "msg_modo_operacao";
			this.msg_modo_operacao.ReadOnly = true;
			global::System.Windows.Forms.Control msg_modo_operacao2 = this.msg_modo_operacao;
			size = new global::System.Drawing.Size(202, 19);
			msg_modo_operacao2.Size = size;
			this.msg_modo_operacao.TabIndex = (HorizontalAlignment)7;
			this.msg_modo_operacao.TabStop = false;
			this.msg_modo_operacao.TextAlign = (HorizontalAlignment)2;
			global::System.Windows.Forms.Control tela_endereco_estacao = this.Tela_endereco_estacao;
			location = new global::System.Drawing.Point(157, 55);
			tela_endereco_estacao.Location = location;
			global::System.Windows.Forms.NumericUpDown tela_endereco_estacao2 = this.Tela_endereco_estacao;
			decimal maximum;
			maximum = new decimal(new int[]
			{
				200,
				0,
				0,
				0
			});
			tela_endereco_estacao2.Maximum = maximum;
			this.Tela_endereco_estacao.Name = "Tela_endereco_estacao";
			global::System.Windows.Forms.Control tela_endereco_estacao3 = this.Tela_endereco_estacao;
			size = new global::System.Drawing.Size(93, 20);
			tela_endereco_estacao3.Size = size;
			this.Tela_endereco_estacao.TabIndex = (HorizontalAlignment)6;
			this.Tela_endereco_estacao.TextAlign = (HorizontalAlignment)2;
			global::System.Windows.Forms.Control tela_endereco_mestre = this.Tela_endereco_mestre;
			location = new global::System.Drawing.Point(157, 27);
			tela_endereco_mestre.Location = location;
			global::System.Windows.Forms.NumericUpDown tela_endereco_mestre2 = this.Tela_endereco_mestre;
			maximum = new decimal(new int[]
			{
				200,
				0,
				0,
				0
			});
			tela_endereco_mestre2.Maximum = maximum;
			this.Tela_endereco_mestre.Name = "Tela_endereco_mestre";
			global::System.Windows.Forms.Control tela_endereco_mestre3 = this.Tela_endereco_mestre;
			size = new global::System.Drawing.Size(93, 20);
			tela_endereco_mestre3.Size = size;
			this.Tela_endereco_mestre.TabIndex = (HorizontalAlignment)6;
			this.Tela_endereco_mestre.TextAlign = (HorizontalAlignment)2;
			this.Label2.AutoSize = true;
			global::System.Windows.Forms.Control label = this.Label2;
			location = new global::System.Drawing.Point(22, 29);
			label.Location = location;
			this.Label2.Name = "Label2";
			global::System.Windows.Forms.Control label2 = this.Label2;
			size = new global::System.Drawing.Size(94, 13);
			label2.Size = size;
			this.Label2.TabIndex = (HorizontalAlignment)3;
			this.Label2.Text = "Endereço Mestre :";
			this.msg.BackColor = global::System.Drawing.Color.Beige;
			this.msg.ForeColor = global::System.Drawing.SystemColors.WindowText;
			global::System.Windows.Forms.Control msg = this.msg;
			location = new global::System.Drawing.Point(23, 87);
			msg.Location = location;
			this.msg.Multiline = true;
			this.msg.Name = "msg";
			this.msg.ReadOnly = true;
			global::System.Windows.Forms.Control msg2 = this.msg;
			size = new global::System.Drawing.Size(290, 30);
			msg2.Size = size;
			this.msg.TabIndex = (HorizontalAlignment)1;
			this.msg.TabStop = false;
			this.msg.TextAlign = (HorizontalAlignment)2;
			global::System.Windows.Forms.Control comando_hab_monitoracao = this.Comando_hab_monitoracao;
			location = new global::System.Drawing.Point(231, 133);
			comando_hab_monitoracao.Location = location;
			this.Comando_hab_monitoracao.Name = "Comando_hab_monitoracao";
			global::System.Windows.Forms.Control comando_hab_monitoracao2 = this.Comando_hab_monitoracao;
			size = new global::System.Drawing.Size(82, 26);
			comando_hab_monitoracao2.Size = size;
			this.Comando_hab_monitoracao.TabIndex = (HorizontalAlignment)2;
			this.Comando_hab_monitoracao.Text = "Iniciar";
			this.Comando_hab_monitoracao.UseVisualStyleBackColor = true;
			this.Label_end_estacao.AutoSize = true;
			global::System.Windows.Forms.Control label_end_estacao = this.Label_end_estacao;
			location = new global::System.Drawing.Point(22, 57);
			label_end_estacao.Location = location;
			this.Label_end_estacao.Name = "Label_end_estacao";
			global::System.Windows.Forms.Control label_end_estacao2 = this.Label_end_estacao;
			size = new global::System.Drawing.Size(101, 13);
			label_end_estacao2.Size = size;
			this.Label_end_estacao.TabIndex = (HorizontalAlignment)0;
			this.Label_end_estacao.Text = "Endereço Estação :";
			this.Timer_monitoracao.Interval = (HorizontalAlignment)1000;
			this.Grupo_setpoints.Controls.Add(this.Valor_Niveldesliga);
			this.Grupo_setpoints.Controls.Add(this.Label_NivelDesliga);
			this.Grupo_setpoints.Controls.Add(this.Valor_NivelLiga);
			this.Grupo_setpoints.Controls.Add(this.Label_NivelLiga);
			this.Grupo_setpoints.Controls.Add(this.Valor_PressaoSuc);
			this.Grupo_setpoints.Controls.Add(this.Label_PressaoSuc);
			this.Grupo_setpoints.Controls.Add(this.Valor_PressaoRec);
			this.Grupo_setpoints.Controls.Add(this.Label_PressaoRec);
			this.Grupo_setpoints.Controls.Add(this.Valor_TempoMaisUmaBomba);
			this.Grupo_setpoints.Controls.Add(this.Label_TempoMaisUmaBomba);
			this.Grupo_setpoints.Controls.Add(this.Valor_NivelB4);
			this.Grupo_setpoints.Controls.Add(this.Label_NivelB4);
			this.Grupo_setpoints.Controls.Add(this.Valor_NivelB3);
			this.Grupo_setpoints.Controls.Add(this.Label_NivelB3);
			this.Grupo_setpoints.Controls.Add(this.Valor_NivelB2);
			this.Grupo_setpoints.Controls.Add(this.Label_NivelB2);
			this.Grupo_setpoints.Controls.Add(this.Valor_NivelB1);
			this.Grupo_setpoints.Controls.Add(this.Label_NivelB1);
			this.Grupo_setpoints.Controls.Add(this.Valor_NivelDesejado);
			this.Grupo_setpoints.Controls.Add(this.Label_NivelDesejado);
			this.Grupo_setpoints.Controls.Add(this.Comando_escreve_setpoint);
			this.Grupo_setpoints.Controls.Add(this.Comando_le_setpoint);
			this.Grupo_setpoints.Enabled = false;
			global::System.Windows.Forms.Control grupo_setpoints = this.Grupo_setpoints;
			location = new global::System.Drawing.Point(26, 498);
			grupo_setpoints.Location = location;
			this.Grupo_setpoints.Name = "Grupo_setpoints";
			global::System.Windows.Forms.Control grupo_setpoints2 = this.Grupo_setpoints;
			size = new global::System.Drawing.Size(383, 207);
			grupo_setpoints2.Size = size;
			this.Grupo_setpoints.TabIndex = (HorizontalAlignment)4;
			this.Grupo_setpoints.TabStop = false;
			this.Grupo_setpoints.Text = "Setpoints";
			this.Valor_Niveldesliga.BackColor = global::System.Drawing.SystemColors.ButtonHighlight;
			global::System.Windows.Forms.Control valor_Niveldesliga = this.Valor_Niveldesliga;
			location = new global::System.Drawing.Point(325, 79);
			valor_Niveldesliga.Location = location;
			this.Valor_Niveldesliga.Name = "Valor_Niveldesliga";
			global::System.Windows.Forms.Control valor_Niveldesliga2 = this.Valor_Niveldesliga;
			size = new global::System.Drawing.Size(45, 20);
			valor_Niveldesliga2.Size = size;
			this.Valor_Niveldesliga.TabIndex = (HorizontalAlignment)24;
			this.Valor_Niveldesliga.TextAlign = (HorizontalAlignment)1;
			this.Label_NivelDesliga.AutoSize = true;
			global::System.Windows.Forms.Control label_NivelDesliga = this.Label_NivelDesliga;
			location = new global::System.Drawing.Point(170, 82);
			label_NivelDesliga.Location = location;
			this.Label_NivelDesliga.Name = "Label_NivelDesliga";
			global::System.Windows.Forms.Control label_NivelDesliga2 = this.Label_NivelDesliga;
			size = new global::System.Drawing.Size(152, 13);
			label_NivelDesliga2.Size = size;
			this.Label_NivelDesliga.TabIndex = (HorizontalAlignment)23;
			this.Label_NivelDesliga.Text = "Proteção - Nível Bloqueio (%) :";
			this.Valor_NivelLiga.BackColor = global::System.Drawing.SystemColors.ButtonHighlight;
			global::System.Windows.Forms.Control valor_NivelLiga = this.Valor_NivelLiga;
			location = new global::System.Drawing.Point(325, 107);
			valor_NivelLiga.Location = location;
			this.Valor_NivelLiga.Name = "Valor_NivelLiga";
			global::System.Windows.Forms.Control valor_NivelLiga2 = this.Valor_NivelLiga;
			size = new global::System.Drawing.Size(45, 20);
			valor_NivelLiga2.Size = size;
			this.Valor_NivelLiga.TabIndex = (HorizontalAlignment)22;
			this.Valor_NivelLiga.TextAlign = (HorizontalAlignment)1;
			this.Label_NivelLiga.AutoSize = true;
			global::System.Windows.Forms.Control label_NivelLiga = this.Label_NivelLiga;
			location = new global::System.Drawing.Point(170, 110);
			label_NivelLiga.Location = location;
			this.Label_NivelLiga.Name = "Label_NivelLiga";
			global::System.Windows.Forms.Control label_NivelLiga2 = this.Label_NivelLiga;
			size = new global::System.Drawing.Size(158, 13);
			label_NivelLiga2.Size = size;
			this.Label_NivelLiga.TabIndex = (HorizontalAlignment)21;
			this.Label_NivelLiga.Text = "Proteção - Nível Liberação (%) :";
			this.Valor_PressaoSuc.BackColor = global::System.Drawing.SystemColors.ButtonHighlight;
			global::System.Windows.Forms.Control valor_PressaoSuc = this.Valor_PressaoSuc;
			location = new global::System.Drawing.Point(326, 51);
			valor_PressaoSuc.Location = location;
			this.Valor_PressaoSuc.Name = "Valor_PressaoSuc";
			global::System.Windows.Forms.Control valor_PressaoSuc2 = this.Valor_PressaoSuc;
			size = new global::System.Drawing.Size(45, 20);
			valor_PressaoSuc2.Size = size;
			this.Valor_PressaoSuc.TabIndex = (HorizontalAlignment)20;
			this.Valor_PressaoSuc.TextAlign = (HorizontalAlignment)1;
			this.Label_PressaoSuc.AutoSize = true;
			global::System.Windows.Forms.Control label_PressaoSuc = this.Label_PressaoSuc;
			location = new global::System.Drawing.Point(170, 54);
			label_PressaoSuc.Location = location;
			this.Label_PressaoSuc.Name = "Label_PressaoSuc";
			global::System.Windows.Forms.Control label_PressaoSuc2 = this.Label_PressaoSuc;
			size = new global::System.Drawing.Size(108, 13);
			label_PressaoSuc2.Size = size;
			this.Label_PressaoSuc.TabIndex = (HorizontalAlignment)19;
			this.Label_PressaoSuc.Text = "Pressao Sucção (%) :";
			this.Valor_PressaoRec.BackColor = global::System.Drawing.SystemColors.ButtonHighlight;
			global::System.Windows.Forms.Control valor_PressaoRec = this.Valor_PressaoRec;
			location = new global::System.Drawing.Point(326, 23);
			valor_PressaoRec.Location = location;
			this.Valor_PressaoRec.Name = "Valor_PressaoRec";
			global::System.Windows.Forms.Control valor_PressaoRec2 = this.Valor_PressaoRec;
			size = new global::System.Drawing.Size(45, 20);
			valor_PressaoRec2.Size = size;
			this.Valor_PressaoRec.TabIndex = (HorizontalAlignment)18;
			this.Valor_PressaoRec.TextAlign = (HorizontalAlignment)1;
			this.Label_PressaoRec.AutoSize = true;
			global::System.Windows.Forms.Control label_PressaoRec = this.Label_PressaoRec;
			location = new global::System.Drawing.Point(170, 26);
			label_PressaoRec.Location = location;
			this.Label_PressaoRec.Name = "Label_PressaoRec";
			global::System.Windows.Forms.Control label_PressaoRec2 = this.Label_PressaoRec;
			size = new global::System.Drawing.Size(117, 13);
			label_PressaoRec2.Size = size;
			this.Label_PressaoRec.TabIndex = (HorizontalAlignment)17;
			this.Label_PressaoRec.Text = "Pressao Recalque (%) :";
			this.Valor_TempoMaisUmaBomba.BackColor = global::System.Drawing.SystemColors.ButtonHighlight;
			global::System.Windows.Forms.Control valor_TempoMaisUmaBomba = this.Valor_TempoMaisUmaBomba;
			location = new global::System.Drawing.Point(115, 163);
			valor_TempoMaisUmaBomba.Location = location;
			this.Valor_TempoMaisUmaBomba.Name = "Valor_TempoMaisUmaBomba";
			global::System.Windows.Forms.Control valor_TempoMaisUmaBomba2 = this.Valor_TempoMaisUmaBomba;
			size = new global::System.Drawing.Size(45, 20);
			valor_TempoMaisUmaBomba2.Size = size;
			this.Valor_TempoMaisUmaBomba.TabIndex = (HorizontalAlignment)16;
			this.Valor_TempoMaisUmaBomba.TextAlign = (HorizontalAlignment)1;
			this.Label_TempoMaisUmaBomba.AutoSize = true;
			global::System.Windows.Forms.Control label_TempoMaisUmaBomba = this.Label_TempoMaisUmaBomba;
			location = new global::System.Drawing.Point(10, 166);
			label_TempoMaisUmaBomba.Location = location;
			this.Label_TempoMaisUmaBomba.Name = "Label_TempoMaisUmaBomba";
			global::System.Windows.Forms.Control label_TempoMaisUmaBomba2 = this.Label_TempoMaisUmaBomba;
			size = new global::System.Drawing.Size(99, 13);
			label_TempoMaisUmaBomba2.Size = size;
			this.Label_TempoMaisUmaBomba.TabIndex = (HorizontalAlignment)15;
			this.Label_TempoMaisUmaBomba.Text = "Tempo + 1 B (min) :";
			this.Valor_NivelB4.BackColor = global::System.Drawing.SystemColors.ButtonHighlight;
			global::System.Windows.Forms.Control valor_NivelB = this.Valor_NivelB4;
			location = new global::System.Drawing.Point(115, 135);
			valor_NivelB.Location = location;
			this.Valor_NivelB4.Name = "Valor_NivelB4";
			global::System.Windows.Forms.Control valor_NivelB2 = this.Valor_NivelB4;
			size = new global::System.Drawing.Size(45, 20);
			valor_NivelB2.Size = size;
			this.Valor_NivelB4.TabIndex = (HorizontalAlignment)14;
			this.Valor_NivelB4.TextAlign = (HorizontalAlignment)1;
			this.Label_NivelB4.AutoSize = true;
			global::System.Windows.Forms.Control label_NivelB = this.Label_NivelB4;
			location = new global::System.Drawing.Point(10, 138);
			label_NivelB.Location = location;
			this.Label_NivelB4.Name = "Label_NivelB4";
			global::System.Windows.Forms.Control label_NivelB2 = this.Label_NivelB4;
			size = new global::System.Drawing.Size(72, 13);
			label_NivelB2.Size = size;
			this.Label_NivelB4.TabIndex = (HorizontalAlignment)13;
			this.Label_NivelB4.Text = "Nível B4 (%) :";
			this.Valor_NivelB3.BackColor = global::System.Drawing.SystemColors.ButtonHighlight;
			global::System.Windows.Forms.Control valor_NivelB3 = this.Valor_NivelB3;
			location = new global::System.Drawing.Point(115, 107);
			valor_NivelB3.Location = location;
			this.Valor_NivelB3.Name = "Valor_NivelB3";
			global::System.Windows.Forms.Control valor_NivelB4 = this.Valor_NivelB3;
			size = new global::System.Drawing.Size(45, 20);
			valor_NivelB4.Size = size;
			this.Valor_NivelB3.TabIndex = (HorizontalAlignment)12;
			this.Valor_NivelB3.TextAlign = (HorizontalAlignment)1;
			this.Label_NivelB3.AutoSize = true;
			global::System.Windows.Forms.Control label_NivelB3 = this.Label_NivelB3;
			location = new global::System.Drawing.Point(10, 110);
			label_NivelB3.Location = location;
			this.Label_NivelB3.Name = "Label_NivelB3";
			global::System.Windows.Forms.Control label_NivelB4 = this.Label_NivelB3;
			size = new global::System.Drawing.Size(72, 13);
			label_NivelB4.Size = size;
			this.Label_NivelB3.TabIndex = (HorizontalAlignment)11;
			this.Label_NivelB3.Text = "Nível B3 (%) :";
			this.Valor_NivelB2.BackColor = global::System.Drawing.SystemColors.ButtonHighlight;
			global::System.Windows.Forms.Control valor_NivelB5 = this.Valor_NivelB2;
			location = new global::System.Drawing.Point(115, 79);
			valor_NivelB5.Location = location;
			this.Valor_NivelB2.Name = "Valor_NivelB2";
			global::System.Windows.Forms.Control valor_NivelB6 = this.Valor_NivelB2;
			size = new global::System.Drawing.Size(45, 20);
			valor_NivelB6.Size = size;
			this.Valor_NivelB2.TabIndex = (HorizontalAlignment)10;
			this.Valor_NivelB2.TextAlign = (HorizontalAlignment)1;
			this.Label_NivelB2.AutoSize = true;
			global::System.Windows.Forms.Control label_NivelB5 = this.Label_NivelB2;
			location = new global::System.Drawing.Point(10, 82);
			label_NivelB5.Location = location;
			this.Label_NivelB2.Name = "Label_NivelB2";
			global::System.Windows.Forms.Control label_NivelB6 = this.Label_NivelB2;
			size = new global::System.Drawing.Size(72, 13);
			label_NivelB6.Size = size;
			this.Label_NivelB2.TabIndex = (HorizontalAlignment)9;
			this.Label_NivelB2.Text = "Nível B2 (%) :";
			this.Valor_NivelB1.BackColor = global::System.Drawing.SystemColors.ButtonHighlight;
			global::System.Windows.Forms.Control valor_NivelB7 = this.Valor_NivelB1;
			location = new global::System.Drawing.Point(115, 51);
			valor_NivelB7.Location = location;
			this.Valor_NivelB1.Name = "Valor_NivelB1";
			global::System.Windows.Forms.Control valor_NivelB8 = this.Valor_NivelB1;
			size = new global::System.Drawing.Size(45, 20);
			valor_NivelB8.Size = size;
			this.Valor_NivelB1.TabIndex = (HorizontalAlignment)8;
			this.Valor_NivelB1.TextAlign = (HorizontalAlignment)1;
			this.Label_NivelB1.AutoSize = true;
			global::System.Windows.Forms.Control label_NivelB7 = this.Label_NivelB1;
			location = new global::System.Drawing.Point(10, 54);
			label_NivelB7.Location = location;
			this.Label_NivelB1.Name = "Label_NivelB1";
			global::System.Windows.Forms.Control label_NivelB8 = this.Label_NivelB1;
			size = new global::System.Drawing.Size(72, 13);
			label_NivelB8.Size = size;
			this.Label_NivelB1.TabIndex = (HorizontalAlignment)7;
			this.Label_NivelB1.Text = "Nível B1 (%) :";
			this.Valor_NivelDesejado.BackColor = global::System.Drawing.SystemColors.ButtonHighlight;
			global::System.Windows.Forms.Control valor_NivelDesejado = this.Valor_NivelDesejado;
			location = new global::System.Drawing.Point(115, 23);
			valor_NivelDesejado.Location = location;
			this.Valor_NivelDesejado.Name = "Valor_NivelDesejado";
			global::System.Windows.Forms.Control valor_NivelDesejado2 = this.Valor_NivelDesejado;
			size = new global::System.Drawing.Size(45, 20);
			valor_NivelDesejado2.Size = size;
			this.Valor_NivelDesejado.TabIndex = (HorizontalAlignment)6;
			this.Valor_NivelDesejado.TextAlign = (HorizontalAlignment)1;
			this.Label_NivelDesejado.AutoSize = true;
			global::System.Windows.Forms.Control label_NivelDesejado = this.Label_NivelDesejado;
			location = new global::System.Drawing.Point(10, 26);
			label_NivelDesejado.Location = location;
			this.Label_NivelDesejado.Name = "Label_NivelDesejado";
			global::System.Windows.Forms.Control label_NivelDesejado2 = this.Label_NivelDesejado;
			size = new global::System.Drawing.Size(104, 13);
			label_NivelDesejado2.Size = size;
			this.Label_NivelDesejado.TabIndex = (HorizontalAlignment)5;
			this.Label_NivelDesejado.Text = "Nível Desejado (%) :";
			global::System.Windows.Forms.Control comando_escreve_setpoint = this.Comando_escreve_setpoint;
			location = new global::System.Drawing.Point(297, 151);
			comando_escreve_setpoint.Location = location;
			this.Comando_escreve_setpoint.Name = "Comando_escreve_setpoint";
			global::System.Windows.Forms.Control comando_escreve_setpoint2 = this.Comando_escreve_setpoint;
			size = new global::System.Drawing.Size(69, 26);
			comando_escreve_setpoint2.Size = size;
			this.Comando_escreve_setpoint.TabIndex = (HorizontalAlignment)4;
			this.Comando_escreve_setpoint.Text = "Escrever";
			this.Comando_escreve_setpoint.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control comando_le_setpoint = this.Comando_le_setpoint;
			location = new global::System.Drawing.Point(179, 151);
			comando_le_setpoint.Location = location;
			this.Comando_le_setpoint.Name = "Comando_le_setpoint";
			global::System.Windows.Forms.Control comando_le_setpoint2 = this.Comando_le_setpoint;
			size = new global::System.Drawing.Size(105, 26);
			comando_le_setpoint2.Size = size;
			this.Comando_le_setpoint.TabIndex = (HorizontalAlignment)3;
			this.Comando_le_setpoint.Text = "Ler";
			this.Comando_le_setpoint.UseVisualStyleBackColor = true;
			this.Grupo_estatistica.Controls.Add(this.Label_Est_retry);
			this.Grupo_estatistica.Controls.Add(this.Est_retry);
			this.Grupo_estatistica.Controls.Add(this.Est_eficiencia);
			this.Grupo_estatistica.Controls.Add(this.Button_limpa_estatistica);
			this.Grupo_estatistica.Controls.Add(this.Label_Est_RX);
			this.Grupo_estatistica.Controls.Add(this.Label_Est_Eficiencia);
			this.Grupo_estatistica.Controls.Add(this.Label_Est_TX);
			this.Grupo_estatistica.Controls.Add(this.Est_Rx);
			this.Grupo_estatistica.Controls.Add(this.Est_TX);
			global::System.Windows.Forms.Control grupo_estatistica = this.Grupo_estatistica;
			location = new global::System.Drawing.Point(511, 91);
			grupo_estatistica.Location = location;
			this.Grupo_estatistica.Name = "Grupo_estatistica";
			global::System.Windows.Forms.Control grupo_estatistica2 = this.Grupo_estatistica;
			size = new global::System.Drawing.Size(188, 112);
			grupo_estatistica2.Size = size;
			this.Grupo_estatistica.TabIndex = (HorizontalAlignment)5;
			this.Grupo_estatistica.TabStop = false;
			this.Grupo_estatistica.Tag = "v";
			this.Grupo_estatistica.Text = "Estatística";
			this.Label_Est_retry.AutoSize = true;
			global::System.Windows.Forms.Control label_Est_retry = this.Label_Est_retry;
			location = new global::System.Drawing.Point(5, 51);
			label_Est_retry.Location = location;
			this.Label_Est_retry.Name = "Label_Est_retry";
			global::System.Windows.Forms.Control label_Est_retry2 = this.Label_Est_retry;
			size = new global::System.Drawing.Size(24, 13);
			label_Est_retry2.Size = size;
			this.Label_Est_retry.TabIndex = (HorizontalAlignment)10;
			this.Label_Est_retry.Text = "Rp:";
			this.Est_retry.BackColor = global::System.Drawing.Color.Beige;
			global::System.Windows.Forms.Control est_retry = this.Est_retry;
			location = new global::System.Drawing.Point(39, 48);
			est_retry.Location = location;
			this.Est_retry.Name = "Est_retry";
			this.Est_retry.ReadOnly = true;
			global::System.Windows.Forms.Control est_retry2 = this.Est_retry;
			size = new global::System.Drawing.Size(38, 20);
			est_retry2.Size = size;
			this.Est_retry.TabIndex = (HorizontalAlignment)9;
			this.Est_retry.Tag = "c";
			this.Est_retry.TextAlign = (HorizontalAlignment)1;
			this.Est_eficiencia.BackColor = global::System.Drawing.Color.Beige;
			global::System.Windows.Forms.Control est_eficiencia = this.Est_eficiencia;
			location = new global::System.Drawing.Point(125, 47);
			est_eficiencia.Location = location;
			this.Est_eficiencia.Name = "Est_eficiencia";
			this.Est_eficiencia.ReadOnly = true;
			global::System.Windows.Forms.Control est_eficiencia2 = this.Est_eficiencia;
			size = new global::System.Drawing.Size(38, 20);
			est_eficiencia2.Size = size;
			this.Est_eficiencia.TabIndex = (HorizontalAlignment)5;
			this.Est_eficiencia.Tag = "c";
			this.Est_eficiencia.TextAlign = (HorizontalAlignment)1;
			global::System.Windows.Forms.Control button_limpa_estatistica = this.Button_limpa_estatistica;
			location = new global::System.Drawing.Point(19, 76);
			button_limpa_estatistica.Location = location;
			this.Button_limpa_estatistica.Name = "Button_limpa_estatistica";
			global::System.Windows.Forms.Control button_limpa_estatistica2 = this.Button_limpa_estatistica;
			size = new global::System.Drawing.Size(144, 25);
			button_limpa_estatistica2.Size = size;
			this.Button_limpa_estatistica.TabIndex = (HorizontalAlignment)8;
			this.Button_limpa_estatistica.Text = "Reiniciar";
			this.Button_limpa_estatistica.UseVisualStyleBackColor = true;
			this.Label_Est_RX.AutoSize = true;
			global::System.Windows.Forms.Control label_Est_RX = this.Label_Est_RX;
			location = new global::System.Drawing.Point(89, 25);
			label_Est_RX.Location = location;
			this.Label_Est_RX.Name = "Label_Est_RX";
			global::System.Windows.Forms.Control label_Est_RX2 = this.Label_Est_RX;
			size = new global::System.Drawing.Size(28, 13);
			label_Est_RX2.Size = size;
			this.Label_Est_RX.TabIndex = (HorizontalAlignment)7;
			this.Label_Est_RX.Text = "RX :";
			this.Label_Est_Eficiencia.AutoSize = true;
			global::System.Windows.Forms.Control label_Est_Eficiencia = this.Label_Est_Eficiencia;
			location = new global::System.Drawing.Point(89, 51);
			label_Est_Eficiencia.Location = location;
			this.Label_Est_Eficiencia.Name = "Label_Est_Eficiencia";
			global::System.Windows.Forms.Control label_Est_Eficiencia2 = this.Label_Est_Eficiencia;
			size = new global::System.Drawing.Size(42, 13);
			label_Est_Eficiencia2.Size = size;
			this.Label_Est_Eficiencia.TabIndex = (HorizontalAlignment)7;
			this.Label_Est_Eficiencia.Text = "OK(%) :";
			this.Label_Est_TX.AutoSize = true;
			global::System.Windows.Forms.Control label_Est_TX = this.Label_Est_TX;
			location = new global::System.Drawing.Point(5, 25);
			label_Est_TX.Location = location;
			this.Label_Est_TX.Name = "Label_Est_TX";
			global::System.Windows.Forms.Control label_Est_TX2 = this.Label_Est_TX;
			size = new global::System.Drawing.Size(27, 13);
			label_Est_TX2.Size = size;
			this.Label_Est_TX.TabIndex = (HorizontalAlignment)6;
			this.Label_Est_TX.Text = "TX :";
			this.Est_Rx.BackColor = global::System.Drawing.Color.Beige;
			global::System.Windows.Forms.Control est_Rx = this.Est_Rx;
			location = new global::System.Drawing.Point(125, 22);
			est_Rx.Location = location;
			this.Est_Rx.Name = "Est_Rx";
			this.Est_Rx.ReadOnly = true;
			global::System.Windows.Forms.Control est_Rx2 = this.Est_Rx;
			size = new global::System.Drawing.Size(38, 20);
			est_Rx2.Size = size;
			this.Est_Rx.TabIndex = (HorizontalAlignment)5;
			this.Est_Rx.Tag = "c";
			this.Est_Rx.TextAlign = (HorizontalAlignment)1;
			this.Est_TX.BackColor = global::System.Drawing.Color.Beige;
			global::System.Windows.Forms.Control est_TX = this.Est_TX;
			location = new global::System.Drawing.Point(39, 22);
			est_TX.Location = location;
			this.Est_TX.Name = "Est_TX";
			this.Est_TX.ReadOnly = true;
			global::System.Windows.Forms.Control est_TX2 = this.Est_TX;
			size = new global::System.Drawing.Size(38, 20);
			est_TX2.Size = size;
			this.Est_TX.TabIndex = (HorizontalAlignment)4;
			this.Est_TX.Tag = "c";
			this.Est_TX.TextAlign = (HorizontalAlignment)1;
			this.Grupo_status.Controls.Add(this.Grupo_bomba4);
			this.Grupo_status.Controls.Add(this.Grupo_bomba3);
			this.Grupo_status.Controls.Add(this.Grupo_bomba2);
			this.Grupo_status.Controls.Add(this.Grupo_bomba1);
			global::System.Windows.Forms.Control grupo_status = this.Grupo_status;
			location = new global::System.Drawing.Point(26, 212);
			grupo_status.Location = location;
			this.Grupo_status.Name = "Grupo_status";
			global::System.Windows.Forms.Control grupo_status2 = this.Grupo_status;
			size = new global::System.Drawing.Size(673, 280);
			grupo_status2.Size = size;
			this.Grupo_status.TabIndex = (HorizontalAlignment)6;
			this.Grupo_status.TabStop = false;
			this.Grupo_status.Text = "Bombas - Comando e Status";
			this.Grupo_bomba4.Controls.Add(this.Cmd_falha_b4);
			this.Grupo_bomba4.Controls.Add(this.Modo_b4);
			this.Grupo_bomba4.Controls.Add(this.Label_modo_b4);
			this.Grupo_bomba4.Controls.Add(this.Cmd_manual_b4);
			this.Grupo_bomba4.Controls.Add(this.Cmd_desliga_b4);
			this.Grupo_bomba4.Controls.Add(this.Cmd_liga_b4);
			this.Grupo_bomba4.Controls.Add(this.Label_status_b4);
			this.Grupo_bomba4.Controls.Add(this.Cmd_automatico_b4);
			this.Grupo_bomba4.Controls.Add(this.Status_b4);
			this.Grupo_bomba4.Enabled = false;
			global::System.Windows.Forms.Control grupo_bomba = this.Grupo_bomba4;
			location = new global::System.Drawing.Point(339, 147);
			grupo_bomba.Location = location;
			this.Grupo_bomba4.Name = "Grupo_bomba4";
			global::System.Windows.Forms.Control grupo_bomba2 = this.Grupo_bomba4;
			size = new global::System.Drawing.Size(315, 113);
			grupo_bomba2.Size = size;
			this.Grupo_bomba4.TabIndex = (HorizontalAlignment)8;
			this.Grupo_bomba4.TabStop = false;
			this.Grupo_bomba4.Text = "Bomba 4";
			this.Cmd_falha_b4.BackColor = global::System.Drawing.Color.FromArgb(255, 255, 128);
			global::System.Windows.Forms.Control cmd_falha_b = this.Cmd_falha_b4;
			location = new global::System.Drawing.Point(238, 80);
			cmd_falha_b.Location = location;
			this.Cmd_falha_b4.Name = "Cmd_falha_b4";
			global::System.Windows.Forms.Control cmd_falha_b2 = this.Cmd_falha_b4;
			size = new global::System.Drawing.Size(71, 26);
			cmd_falha_b2.Size = size;
			this.Cmd_falha_b4.TabIndex = (HorizontalAlignment)6;
			this.Cmd_falha_b4.Text = "Falha";
			this.Cmd_falha_b4.UseVisualStyleBackColor = false;
			this.Modo_b4.BackColor = global::System.Drawing.Color.Beige;
			global::System.Windows.Forms.Control modo_b = this.Modo_b4;
			location = new global::System.Drawing.Point(73, 56);
			modo_b.Location = location;
			this.Modo_b4.Name = "Modo_b4";
			this.Modo_b4.ReadOnly = true;
			global::System.Windows.Forms.Control modo_b2 = this.Modo_b4;
			size = new global::System.Drawing.Size(82, 20);
			modo_b2.Size = size;
			this.Modo_b4.TabIndex = (HorizontalAlignment)7;
			this.Modo_b4.TabStop = false;
			this.Modo_b4.TextAlign = (HorizontalAlignment)2;
			this.Label_modo_b4.AutoSize = true;
			global::System.Windows.Forms.Control label_modo_b = this.Label_modo_b4;
			location = new global::System.Drawing.Point(11, 59);
			label_modo_b.Location = location;
			this.Label_modo_b4.Name = "Label_modo_b4";
			global::System.Windows.Forms.Control label_modo_b2 = this.Label_modo_b4;
			size = new global::System.Drawing.Size(63, 13);
			label_modo_b2.Size = size;
			this.Label_modo_b4.TabIndex = (HorizontalAlignment)6;
			this.Label_modo_b4.Text = "Modo Ope :";
			global::System.Windows.Forms.Control cmd_manual_b = this.Cmd_manual_b4;
			location = new global::System.Drawing.Point(161, 50);
			cmd_manual_b.Location = location;
			this.Cmd_manual_b4.Name = "Cmd_manual_b4";
			global::System.Windows.Forms.Control cmd_manual_b2 = this.Cmd_manual_b4;
			size = new global::System.Drawing.Size(71, 26);
			cmd_manual_b2.Size = size;
			this.Cmd_manual_b4.TabIndex = (HorizontalAlignment)3;
			this.Cmd_manual_b4.Text = "Manual";
			this.Cmd_manual_b4.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control cmd_desliga_b = this.Cmd_desliga_b4;
			location = new global::System.Drawing.Point(238, 50);
			cmd_desliga_b.Location = location;
			this.Cmd_desliga_b4.Name = "Cmd_desliga_b4";
			global::System.Windows.Forms.Control cmd_desliga_b2 = this.Cmd_desliga_b4;
			size = new global::System.Drawing.Size(71, 26);
			cmd_desliga_b2.Size = size;
			this.Cmd_desliga_b4.TabIndex = (HorizontalAlignment)3;
			this.Cmd_desliga_b4.Text = "Desligar";
			this.Cmd_desliga_b4.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control cmd_liga_b = this.Cmd_liga_b4;
			location = new global::System.Drawing.Point(238, 20);
			cmd_liga_b.Location = location;
			this.Cmd_liga_b4.Name = "Cmd_liga_b4";
			global::System.Windows.Forms.Control cmd_liga_b2 = this.Cmd_liga_b4;
			size = new global::System.Drawing.Size(71, 26);
			cmd_liga_b2.Size = size;
			this.Cmd_liga_b4.TabIndex = (HorizontalAlignment)2;
			this.Cmd_liga_b4.Text = "Ligar";
			this.Cmd_liga_b4.UseVisualStyleBackColor = true;
			this.Label_status_b4.AutoSize = true;
			global::System.Windows.Forms.Control label_status_b = this.Label_status_b4;
			location = new global::System.Drawing.Point(11, 27);
			label_status_b.Location = location;
			this.Label_status_b4.Name = "Label_status_b4";
			global::System.Windows.Forms.Control label_status_b2 = this.Label_status_b4;
			size = new global::System.Drawing.Size(43, 13);
			label_status_b2.Size = size;
			this.Label_status_b4.TabIndex = (HorizontalAlignment)0;
			this.Label_status_b4.Text = "Status :";
			global::System.Windows.Forms.Control cmd_automatico_b = this.Cmd_automatico_b4;
			location = new global::System.Drawing.Point(161, 20);
			cmd_automatico_b.Location = location;
			this.Cmd_automatico_b4.Name = "Cmd_automatico_b4";
			global::System.Windows.Forms.Control cmd_automatico_b2 = this.Cmd_automatico_b4;
			size = new global::System.Drawing.Size(71, 26);
			cmd_automatico_b2.Size = size;
			this.Cmd_automatico_b4.TabIndex = (HorizontalAlignment)2;
			this.Cmd_automatico_b4.Text = "Automático";
			this.Cmd_automatico_b4.UseVisualStyleBackColor = true;
			this.Status_b4.BackColor = global::System.Drawing.Color.Beige;
			global::System.Windows.Forms.Control status_b = this.Status_b4;
			location = new global::System.Drawing.Point(73, 24);
			status_b.Location = location;
			this.Status_b4.Name = "Status_b4";
			this.Status_b4.ReadOnly = true;
			global::System.Windows.Forms.Control status_b2 = this.Status_b4;
			size = new global::System.Drawing.Size(82, 20);
			status_b2.Size = size;
			this.Status_b4.TabIndex = (HorizontalAlignment)1;
			this.Status_b4.TabStop = false;
			this.Status_b4.TextAlign = (HorizontalAlignment)2;
			this.Grupo_bomba3.Controls.Add(this.Cmd_falha_b3);
			this.Grupo_bomba3.Controls.Add(this.Modo_b3);
			this.Grupo_bomba3.Controls.Add(this.Label_modo_b3);
			this.Grupo_bomba3.Controls.Add(this.Cmd_manual_b3);
			this.Grupo_bomba3.Controls.Add(this.Cmd_desliga_b3);
			this.Grupo_bomba3.Controls.Add(this.Cmd_liga_b3);
			this.Grupo_bomba3.Controls.Add(this.Label_status_b3);
			this.Grupo_bomba3.Controls.Add(this.Cmd_automatico_b3);
			this.Grupo_bomba3.Controls.Add(this.Status_b3);
			this.Grupo_bomba3.Enabled = false;
			global::System.Windows.Forms.Control grupo_bomba3 = this.Grupo_bomba3;
			location = new global::System.Drawing.Point(18, 147);
			grupo_bomba3.Location = location;
			this.Grupo_bomba3.Name = "Grupo_bomba3";
			global::System.Windows.Forms.Control grupo_bomba4 = this.Grupo_bomba3;
			size = new global::System.Drawing.Size(315, 113);
			grupo_bomba4.Size = size;
			this.Grupo_bomba3.TabIndex = (HorizontalAlignment)2;
			this.Grupo_bomba3.TabStop = false;
			this.Grupo_bomba3.Text = "Bomba 3";
			this.Cmd_falha_b3.BackColor = global::System.Drawing.Color.FromArgb(255, 255, 128);
			global::System.Windows.Forms.Control cmd_falha_b3 = this.Cmd_falha_b3;
			location = new global::System.Drawing.Point(238, 80);
			cmd_falha_b3.Location = location;
			this.Cmd_falha_b3.Name = "Cmd_falha_b3";
			global::System.Windows.Forms.Control cmd_falha_b4 = this.Cmd_falha_b3;
			size = new global::System.Drawing.Size(71, 26);
			cmd_falha_b4.Size = size;
			this.Cmd_falha_b3.TabIndex = (HorizontalAlignment)9;
			this.Cmd_falha_b3.Text = "Falha";
			this.Cmd_falha_b3.UseVisualStyleBackColor = false;
			this.Modo_b3.BackColor = global::System.Drawing.Color.Beige;
			global::System.Windows.Forms.Control modo_b3 = this.Modo_b3;
			location = new global::System.Drawing.Point(73, 56);
			modo_b3.Location = location;
			this.Modo_b3.Name = "Modo_b3";
			this.Modo_b3.ReadOnly = true;
			global::System.Windows.Forms.Control modo_b4 = this.Modo_b3;
			size = new global::System.Drawing.Size(82, 20);
			modo_b4.Size = size;
			this.Modo_b3.TabIndex = (HorizontalAlignment)7;
			this.Modo_b3.TabStop = false;
			this.Modo_b3.TextAlign = (HorizontalAlignment)2;
			this.Label_modo_b3.AutoSize = true;
			global::System.Windows.Forms.Control label_modo_b3 = this.Label_modo_b3;
			location = new global::System.Drawing.Point(11, 59);
			label_modo_b3.Location = location;
			this.Label_modo_b3.Name = "Label_modo_b3";
			global::System.Windows.Forms.Control label_modo_b4 = this.Label_modo_b3;
			size = new global::System.Drawing.Size(63, 13);
			label_modo_b4.Size = size;
			this.Label_modo_b3.TabIndex = (HorizontalAlignment)6;
			this.Label_modo_b3.Text = "Modo Ope :";
			global::System.Windows.Forms.Control cmd_manual_b3 = this.Cmd_manual_b3;
			location = new global::System.Drawing.Point(161, 50);
			cmd_manual_b3.Location = location;
			this.Cmd_manual_b3.Name = "Cmd_manual_b3";
			global::System.Windows.Forms.Control cmd_manual_b4 = this.Cmd_manual_b3;
			size = new global::System.Drawing.Size(71, 26);
			cmd_manual_b4.Size = size;
			this.Cmd_manual_b3.TabIndex = (HorizontalAlignment)3;
			this.Cmd_manual_b3.Text = "Manual";
			this.Cmd_manual_b3.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control cmd_desliga_b3 = this.Cmd_desliga_b3;
			location = new global::System.Drawing.Point(238, 50);
			cmd_desliga_b3.Location = location;
			this.Cmd_desliga_b3.Name = "Cmd_desliga_b3";
			global::System.Windows.Forms.Control cmd_desliga_b4 = this.Cmd_desliga_b3;
			size = new global::System.Drawing.Size(71, 26);
			cmd_desliga_b4.Size = size;
			this.Cmd_desliga_b3.TabIndex = (HorizontalAlignment)3;
			this.Cmd_desliga_b3.Text = "Desligar";
			this.Cmd_desliga_b3.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control cmd_liga_b3 = this.Cmd_liga_b3;
			location = new global::System.Drawing.Point(238, 20);
			cmd_liga_b3.Location = location;
			this.Cmd_liga_b3.Name = "Cmd_liga_b3";
			global::System.Windows.Forms.Control cmd_liga_b4 = this.Cmd_liga_b3;
			size = new global::System.Drawing.Size(71, 26);
			cmd_liga_b4.Size = size;
			this.Cmd_liga_b3.TabIndex = (HorizontalAlignment)2;
			this.Cmd_liga_b3.Text = "Ligar";
			this.Cmd_liga_b3.UseVisualStyleBackColor = true;
			this.Label_status_b3.AutoSize = true;
			global::System.Windows.Forms.Control label_status_b3 = this.Label_status_b3;
			location = new global::System.Drawing.Point(11, 27);
			label_status_b3.Location = location;
			this.Label_status_b3.Name = "Label_status_b3";
			global::System.Windows.Forms.Control label_status_b4 = this.Label_status_b3;
			size = new global::System.Drawing.Size(43, 13);
			label_status_b4.Size = size;
			this.Label_status_b3.TabIndex = (HorizontalAlignment)0;
			this.Label_status_b3.Text = "Status :";
			global::System.Windows.Forms.Control cmd_automatico_b3 = this.Cmd_automatico_b3;
			location = new global::System.Drawing.Point(161, 20);
			cmd_automatico_b3.Location = location;
			this.Cmd_automatico_b3.Name = "Cmd_automatico_b3";
			global::System.Windows.Forms.Control cmd_automatico_b4 = this.Cmd_automatico_b3;
			size = new global::System.Drawing.Size(71, 26);
			cmd_automatico_b4.Size = size;
			this.Cmd_automatico_b3.TabIndex = (HorizontalAlignment)2;
			this.Cmd_automatico_b3.Text = "Automático";
			this.Cmd_automatico_b3.UseVisualStyleBackColor = true;
			this.Status_b3.BackColor = global::System.Drawing.Color.Beige;
			global::System.Windows.Forms.Control status_b3 = this.Status_b3;
			location = new global::System.Drawing.Point(73, 24);
			status_b3.Location = location;
			this.Status_b3.Name = "Status_b3";
			this.Status_b3.ReadOnly = true;
			global::System.Windows.Forms.Control status_b4 = this.Status_b3;
			size = new global::System.Drawing.Size(82, 20);
			status_b4.Size = size;
			this.Status_b3.TabIndex = (HorizontalAlignment)1;
			this.Status_b3.TabStop = false;
			this.Status_b3.TextAlign = (HorizontalAlignment)2;
			this.Grupo_bomba2.Controls.Add(this.Cmd_falha_b2);
			this.Grupo_bomba2.Controls.Add(this.Modo_b2);
			this.Grupo_bomba2.Controls.Add(this.Label_modo_b2);
			this.Grupo_bomba2.Controls.Add(this.Cmd_manual_b2);
			this.Grupo_bomba2.Controls.Add(this.Cmd_desliga_b2);
			this.Grupo_bomba2.Controls.Add(this.Cmd_liga_b2);
			this.Grupo_bomba2.Controls.Add(this.Cmd_automatico_b2);
			this.Grupo_bomba2.Controls.Add(this.Label_status_b2);
			this.Grupo_bomba2.Controls.Add(this.Status_b2);
			this.Grupo_bomba2.Enabled = false;
			global::System.Windows.Forms.Control grupo_bomba5 = this.Grupo_bomba2;
			location = new global::System.Drawing.Point(339, 28);
			grupo_bomba5.Location = location;
			this.Grupo_bomba2.Name = "Grupo_bomba2";
			global::System.Windows.Forms.Control grupo_bomba6 = this.Grupo_bomba2;
			size = new global::System.Drawing.Size(315, 113);
			grupo_bomba6.Size = size;
			this.Grupo_bomba2.TabIndex = (HorizontalAlignment)1;
			this.Grupo_bomba2.TabStop = false;
			this.Grupo_bomba2.Text = "Bomba 2";
			this.Cmd_falha_b2.BackColor = global::System.Drawing.Color.FromArgb(255, 255, 128);
			global::System.Windows.Forms.Control cmd_falha_b5 = this.Cmd_falha_b2;
			location = new global::System.Drawing.Point(238, 78);
			cmd_falha_b5.Location = location;
			this.Cmd_falha_b2.Name = "Cmd_falha_b2";
			global::System.Windows.Forms.Control cmd_falha_b6 = this.Cmd_falha_b2;
			size = new global::System.Drawing.Size(71, 26);
			cmd_falha_b6.Size = size;
			this.Cmd_falha_b2.TabIndex = (HorizontalAlignment)6;
			this.Cmd_falha_b2.Text = "Falha";
			this.Cmd_falha_b2.UseVisualStyleBackColor = false;
			this.Modo_b2.BackColor = global::System.Drawing.Color.Beige;
			global::System.Windows.Forms.Control modo_b5 = this.Modo_b2;
			location = new global::System.Drawing.Point(73, 56);
			modo_b5.Location = location;
			this.Modo_b2.Name = "Modo_b2";
			this.Modo_b2.ReadOnly = true;
			global::System.Windows.Forms.Control modo_b6 = this.Modo_b2;
			size = new global::System.Drawing.Size(82, 20);
			modo_b6.Size = size;
			this.Modo_b2.TabIndex = (HorizontalAlignment)5;
			this.Modo_b2.TabStop = false;
			this.Modo_b2.TextAlign = (HorizontalAlignment)2;
			this.Label_modo_b2.AutoSize = true;
			global::System.Windows.Forms.Control label_modo_b5 = this.Label_modo_b2;
			location = new global::System.Drawing.Point(11, 59);
			label_modo_b5.Location = location;
			this.Label_modo_b2.Name = "Label_modo_b2";
			global::System.Windows.Forms.Control label_modo_b6 = this.Label_modo_b2;
			size = new global::System.Drawing.Size(63, 13);
			label_modo_b6.Size = size;
			this.Label_modo_b2.TabIndex = (HorizontalAlignment)4;
			this.Label_modo_b2.Text = "Modo Ope :";
			global::System.Windows.Forms.Control cmd_manual_b5 = this.Cmd_manual_b2;
			location = new global::System.Drawing.Point(161, 49);
			cmd_manual_b5.Location = location;
			this.Cmd_manual_b2.Name = "Cmd_manual_b2";
			global::System.Windows.Forms.Control cmd_manual_b6 = this.Cmd_manual_b2;
			size = new global::System.Drawing.Size(71, 26);
			cmd_manual_b6.Size = size;
			this.Cmd_manual_b2.TabIndex = (HorizontalAlignment)3;
			this.Cmd_manual_b2.Text = "Manual";
			this.Cmd_manual_b2.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control cmd_desliga_b5 = this.Cmd_desliga_b2;
			location = new global::System.Drawing.Point(238, 49);
			cmd_desliga_b5.Location = location;
			this.Cmd_desliga_b2.Name = "Cmd_desliga_b2";
			global::System.Windows.Forms.Control cmd_desliga_b6 = this.Cmd_desliga_b2;
			size = new global::System.Drawing.Size(71, 26);
			cmd_desliga_b6.Size = size;
			this.Cmd_desliga_b2.TabIndex = (HorizontalAlignment)3;
			this.Cmd_desliga_b2.Text = "Desligar";
			this.Cmd_desliga_b2.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control cmd_liga_b5 = this.Cmd_liga_b2;
			location = new global::System.Drawing.Point(238, 20);
			cmd_liga_b5.Location = location;
			this.Cmd_liga_b2.Name = "Cmd_liga_b2";
			global::System.Windows.Forms.Control cmd_liga_b6 = this.Cmd_liga_b2;
			size = new global::System.Drawing.Size(71, 26);
			cmd_liga_b6.Size = size;
			this.Cmd_liga_b2.TabIndex = (HorizontalAlignment)2;
			this.Cmd_liga_b2.Text = "Ligar";
			this.Cmd_liga_b2.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control cmd_automatico_b5 = this.Cmd_automatico_b2;
			location = new global::System.Drawing.Point(161, 20);
			cmd_automatico_b5.Location = location;
			this.Cmd_automatico_b2.Name = "Cmd_automatico_b2";
			global::System.Windows.Forms.Control cmd_automatico_b6 = this.Cmd_automatico_b2;
			size = new global::System.Drawing.Size(71, 26);
			cmd_automatico_b6.Size = size;
			this.Cmd_automatico_b2.TabIndex = (HorizontalAlignment)2;
			this.Cmd_automatico_b2.Text = "Automático";
			this.Cmd_automatico_b2.UseVisualStyleBackColor = true;
			this.Label_status_b2.AutoSize = true;
			global::System.Windows.Forms.Control label_status_b5 = this.Label_status_b2;
			location = new global::System.Drawing.Point(11, 27);
			label_status_b5.Location = location;
			this.Label_status_b2.Name = "Label_status_b2";
			global::System.Windows.Forms.Control label_status_b6 = this.Label_status_b2;
			size = new global::System.Drawing.Size(43, 13);
			label_status_b6.Size = size;
			this.Label_status_b2.TabIndex = (HorizontalAlignment)0;
			this.Label_status_b2.Text = "Status :";
			this.Status_b2.BackColor = global::System.Drawing.Color.Beige;
			global::System.Windows.Forms.Control status_b5 = this.Status_b2;
			location = new global::System.Drawing.Point(73, 24);
			status_b5.Location = location;
			this.Status_b2.Name = "Status_b2";
			this.Status_b2.ReadOnly = true;
			global::System.Windows.Forms.Control status_b6 = this.Status_b2;
			size = new global::System.Drawing.Size(82, 20);
			status_b6.Size = size;
			this.Status_b2.TabIndex = (HorizontalAlignment)1;
			this.Status_b2.TabStop = false;
			this.Status_b2.TextAlign = (HorizontalAlignment)2;
			this.Grupo_bomba1.Controls.Add(this.Cmd_falha_b1);
			this.Grupo_bomba1.Controls.Add(this.Modo_b1);
			this.Grupo_bomba1.Controls.Add(this.Cmd_manual_b1);
			this.Grupo_bomba1.Controls.Add(this.Cmd_desliga_b1);
			this.Grupo_bomba1.Controls.Add(this.Cmd_automatico_b1);
			this.Grupo_bomba1.Controls.Add(this.Cmd_liga_b1);
			this.Grupo_bomba1.Controls.Add(this.Label_modo_b1);
			this.Grupo_bomba1.Controls.Add(this.Label_status_b1);
			this.Grupo_bomba1.Controls.Add(this.Status_b1);
			this.Grupo_bomba1.Enabled = false;
			global::System.Windows.Forms.Control grupo_bomba7 = this.Grupo_bomba1;
			location = new global::System.Drawing.Point(18, 28);
			grupo_bomba7.Location = location;
			this.Grupo_bomba1.Name = "Grupo_bomba1";
			global::System.Windows.Forms.Control grupo_bomba8 = this.Grupo_bomba1;
			size = new global::System.Drawing.Size(315, 113);
			grupo_bomba8.Size = size;
			this.Grupo_bomba1.TabIndex = (HorizontalAlignment)0;
			this.Grupo_bomba1.TabStop = false;
			this.Grupo_bomba1.Text = "Bomba 1";
			this.Cmd_falha_b1.BackColor = global::System.Drawing.Color.FromArgb(255, 255, 128);
			global::System.Windows.Forms.Control cmd_falha_b7 = this.Cmd_falha_b1;
			location = new global::System.Drawing.Point(238, 78);
			cmd_falha_b7.Location = location;
			this.Cmd_falha_b1.Name = "Cmd_falha_b1";
			global::System.Windows.Forms.Control cmd_falha_b8 = this.Cmd_falha_b1;
			size = new global::System.Drawing.Size(71, 26);
			cmd_falha_b8.Size = size;
			this.Cmd_falha_b1.TabIndex = (HorizontalAlignment)4;
			this.Cmd_falha_b1.Text = "Falha";
			this.Cmd_falha_b1.UseVisualStyleBackColor = false;
			this.Modo_b1.BackColor = global::System.Drawing.Color.Beige;
			global::System.Windows.Forms.Control modo_b7 = this.Modo_b1;
			location = new global::System.Drawing.Point(73, 54);
			modo_b7.Location = location;
			this.Modo_b1.Name = "Modo_b1";
			this.Modo_b1.ReadOnly = true;
			global::System.Windows.Forms.Control modo_b8 = this.Modo_b1;
			size = new global::System.Drawing.Size(82, 20);
			modo_b8.Size = size;
			this.Modo_b1.TabIndex = (HorizontalAlignment)1;
			this.Modo_b1.TabStop = false;
			this.Modo_b1.TextAlign = (HorizontalAlignment)2;
			global::System.Windows.Forms.Control cmd_manual_b7 = this.Cmd_manual_b1;
			location = new global::System.Drawing.Point(161, 49);
			cmd_manual_b7.Location = location;
			this.Cmd_manual_b1.Name = "Cmd_manual_b1";
			global::System.Windows.Forms.Control cmd_manual_b8 = this.Cmd_manual_b1;
			size = new global::System.Drawing.Size(71, 26);
			cmd_manual_b8.Size = size;
			this.Cmd_manual_b1.TabIndex = (HorizontalAlignment)3;
			this.Cmd_manual_b1.Text = "Manual";
			this.Cmd_manual_b1.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control cmd_desliga_b7 = this.Cmd_desliga_b1;
			location = new global::System.Drawing.Point(238, 49);
			cmd_desliga_b7.Location = location;
			this.Cmd_desliga_b1.Name = "Cmd_desliga_b1";
			global::System.Windows.Forms.Control cmd_desliga_b8 = this.Cmd_desliga_b1;
			size = new global::System.Drawing.Size(71, 26);
			cmd_desliga_b8.Size = size;
			this.Cmd_desliga_b1.TabIndex = (HorizontalAlignment)3;
			this.Cmd_desliga_b1.Text = "Desligar";
			this.Cmd_desliga_b1.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control cmd_automatico_b7 = this.Cmd_automatico_b1;
			location = new global::System.Drawing.Point(161, 20);
			cmd_automatico_b7.Location = location;
			this.Cmd_automatico_b1.Name = "Cmd_automatico_b1";
			global::System.Windows.Forms.Control cmd_automatico_b8 = this.Cmd_automatico_b1;
			size = new global::System.Drawing.Size(71, 26);
			cmd_automatico_b8.Size = size;
			this.Cmd_automatico_b1.TabIndex = (HorizontalAlignment)2;
			this.Cmd_automatico_b1.Text = "Automático";
			this.Cmd_automatico_b1.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control cmd_liga_b7 = this.Cmd_liga_b1;
			location = new global::System.Drawing.Point(238, 20);
			cmd_liga_b7.Location = location;
			this.Cmd_liga_b1.Name = "Cmd_liga_b1";
			global::System.Windows.Forms.Control cmd_liga_b8 = this.Cmd_liga_b1;
			size = new global::System.Drawing.Size(71, 26);
			cmd_liga_b8.Size = size;
			this.Cmd_liga_b1.TabIndex = (HorizontalAlignment)2;
			this.Cmd_liga_b1.Text = "Ligar";
			this.Cmd_liga_b1.UseVisualStyleBackColor = true;
			this.Label_modo_b1.AutoSize = true;
			global::System.Windows.Forms.Control label_modo_b7 = this.Label_modo_b1;
			location = new global::System.Drawing.Point(11, 57);
			label_modo_b7.Location = location;
			this.Label_modo_b1.Name = "Label_modo_b1";
			global::System.Windows.Forms.Control label_modo_b8 = this.Label_modo_b1;
			size = new global::System.Drawing.Size(63, 13);
			label_modo_b8.Size = size;
			this.Label_modo_b1.TabIndex = (HorizontalAlignment)0;
			this.Label_modo_b1.Text = "Modo Ope :";
			this.Label_status_b1.AutoSize = true;
			global::System.Windows.Forms.Control label_status_b7 = this.Label_status_b1;
			location = new global::System.Drawing.Point(11, 27);
			label_status_b7.Location = location;
			this.Label_status_b1.Name = "Label_status_b1";
			global::System.Windows.Forms.Control label_status_b8 = this.Label_status_b1;
			size = new global::System.Drawing.Size(43, 13);
			label_status_b8.Size = size;
			this.Label_status_b1.TabIndex = (HorizontalAlignment)0;
			this.Label_status_b1.Text = "Status :";
			this.Status_b1.BackColor = global::System.Drawing.Color.Beige;
			global::System.Windows.Forms.Control status_b7 = this.Status_b1;
			location = new global::System.Drawing.Point(73, 24);
			status_b7.Location = location;
			this.Status_b1.Name = "Status_b1";
			this.Status_b1.ReadOnly = true;
			global::System.Windows.Forms.Control status_b8 = this.Status_b1;
			size = new global::System.Drawing.Size(82, 20);
			status_b8.Size = size;
			this.Status_b1.TabIndex = (HorizontalAlignment)1;
			this.Status_b1.TabStop = false;
			this.Status_b1.TextAlign = (HorizontalAlignment)2;
			this.Grupo_escrita_de_dados.Controls.Add(this.Tela_nivel_origem);
			this.Grupo_escrita_de_dados.Controls.Add(this.Label_nivel_origem);
			this.Grupo_escrita_de_dados.Controls.Add(this.Tela_nivel_destino);
			this.Grupo_escrita_de_dados.Controls.Add(this.Label_nivel_destino);
			global::System.Windows.Forms.Control grupo_escrita_de_dados = this.Grupo_escrita_de_dados;
			location = new global::System.Drawing.Point(387, 27);
			grupo_escrita_de_dados.Location = location;
			this.Grupo_escrita_de_dados.Name = "Grupo_escrita_de_dados";
			global::System.Windows.Forms.Control grupo_escrita_de_dados2 = this.Grupo_escrita_de_dados;
			size = new global::System.Drawing.Size(312, 58);
			grupo_escrita_de_dados2.Size = size;
			this.Grupo_escrita_de_dados.TabIndex = (HorizontalAlignment)7;
			this.Grupo_escrita_de_dados.TabStop = false;
			this.Grupo_escrita_de_dados.Text = "Medidas para simulçação de Nível";
			global::System.Windows.Forms.Control tela_nivel_origem = this.Tela_nivel_origem;
			location = new global::System.Drawing.Point(82, 24);
			tela_nivel_origem.Location = location;
			this.Tela_nivel_origem.Name = "Tela_nivel_origem";
			global::System.Windows.Forms.Control tela_nivel_origem2 = this.Tela_nivel_origem;
			size = new global::System.Drawing.Size(64, 20);
			tela_nivel_origem2.Size = size;
			this.Tela_nivel_origem.TabIndex = (HorizontalAlignment)9;
			this.Tela_nivel_origem.TextAlign = (HorizontalAlignment)2;
			this.Label_nivel_origem.AutoSize = true;
			global::System.Windows.Forms.Control label_nivel_origem = this.Label_nivel_origem;
			location = new global::System.Drawing.Point(15, 26);
			label_nivel_origem.Location = location;
			this.Label_nivel_origem.Name = "Label_nivel_origem";
			global::System.Windows.Forms.Control label_nivel_origem2 = this.Label_nivel_origem;
			size = new global::System.Drawing.Size(60, 13);
			label_nivel_origem2.Size = size;
			this.Label_nivel_origem.TabIndex = (HorizontalAlignment)8;
			this.Label_nivel_origem.Text = "Origem(%) :";
			global::System.Windows.Forms.Control tela_nivel_destino = this.Tela_nivel_destino;
			location = new global::System.Drawing.Point(236, 24);
			tela_nivel_destino.Location = location;
			this.Tela_nivel_destino.Name = "Tela_nivel_destino";
			global::System.Windows.Forms.Control tela_nivel_destino2 = this.Tela_nivel_destino;
			size = new global::System.Drawing.Size(64, 20);
			tela_nivel_destino2.Size = size;
			this.Tela_nivel_destino.TabIndex = (HorizontalAlignment)7;
			this.Tela_nivel_destino.TextAlign = (HorizontalAlignment)2;
			this.Label_nivel_destino.AutoSize = true;
			global::System.Windows.Forms.Control label_nivel_destino = this.Label_nivel_destino;
			location = new global::System.Drawing.Point(169, 26);
			label_nivel_destino.Location = location;
			this.Label_nivel_destino.Name = "Label_nivel_destino";
			global::System.Windows.Forms.Control label_nivel_destino2 = this.Label_nivel_destino;
			size = new global::System.Drawing.Size(63, 13);
			label_nivel_destino2.Size = size;
			this.Label_nivel_destino.TabIndex = (HorizontalAlignment)2;
			this.Label_nivel_destino.Text = "Destino(%) :";
			this.Grupo_alarmes.Controls.Add(this.CheckBox_Alm_ff_status);
			this.Grupo_alarmes.Controls.Add(this.CheckBox_Alm_bat_bx_status);
			this.Grupo_alarmes.Controls.Add(this.CheckBox_Alm_alagamento_status);
			this.Grupo_alarmes.Controls.Add(this.CheckBox_Alm_ope_bat_status);
			this.Grupo_alarmes.Controls.Add(this.CheckBox_Alm_arrombamento_status);
			this.Grupo_alarmes.Enabled = false;
			global::System.Windows.Forms.Control grupo_alarmes = this.Grupo_alarmes;
			location = new global::System.Drawing.Point(387, 91);
			grupo_alarmes.Location = location;
			this.Grupo_alarmes.Name = "Grupo_alarmes";
			global::System.Windows.Forms.Control grupo_alarmes2 = this.Grupo_alarmes;
			size = new global::System.Drawing.Size(118, 112);
			grupo_alarmes2.Size = size;
			this.Grupo_alarmes.TabIndex = (HorizontalAlignment)8;
			this.Grupo_alarmes.TabStop = false;
			this.Grupo_alarmes.Text = "Alarmes";
			this.CheckBox_Alm_ff_status.AutoCheck = false;
			global::System.Windows.Forms.Control checkBox_Alm_ff_status = this.CheckBox_Alm_ff_status;
			location = new global::System.Drawing.Point(16, 70);
			checkBox_Alm_ff_status.Location = location;
			this.CheckBox_Alm_ff_status.Name = "CheckBox_Alm_ff_status";
			global::System.Windows.Forms.Control checkBox_Alm_ff_status2 = this.CheckBox_Alm_ff_status;
			size = new global::System.Drawing.Size(94, 17);
			checkBox_Alm_ff_status2.Size = size;
			this.CheckBox_Alm_ff_status.TabIndex = (HorizontalAlignment)4;
			this.CheckBox_Alm_ff_status.TabStop = false;
			this.CheckBox_Alm_ff_status.Text = "Falta de Fase";
			this.CheckBox_Alm_ff_status.UseVisualStyleBackColor = true;
			this.CheckBox_Alm_bat_bx_status.AutoCheck = false;
			global::System.Windows.Forms.Control checkBox_Alm_bat_bx_status = this.CheckBox_Alm_bat_bx_status;
			location = new global::System.Drawing.Point(16, 35);
			checkBox_Alm_bat_bx_status.Location = location;
			this.CheckBox_Alm_bat_bx_status.Name = "CheckBox_Alm_bat_bx_status";
			global::System.Windows.Forms.Control checkBox_Alm_bat_bx_status2 = this.CheckBox_Alm_bat_bx_status;
			size = new global::System.Drawing.Size(96, 18);
			checkBox_Alm_bat_bx_status2.Size = size;
			this.CheckBox_Alm_bat_bx_status.TabIndex = (HorizontalAlignment)3;
			this.CheckBox_Alm_bat_bx_status.TabStop = false;
			this.CheckBox_Alm_bat_bx_status.Text = "Bateria Baixa";
			this.CheckBox_Alm_bat_bx_status.UseVisualStyleBackColor = true;
			this.CheckBox_Alm_alagamento_status.AutoCheck = false;
			global::System.Windows.Forms.Control checkBox_Alm_alagamento_status = this.CheckBox_Alm_alagamento_status;
			location = new global::System.Drawing.Point(16, 87);
			checkBox_Alm_alagamento_status.Location = location;
			this.CheckBox_Alm_alagamento_status.Name = "CheckBox_Alm_alagamento_status";
			global::System.Windows.Forms.Control checkBox_Alm_alagamento_status2 = this.CheckBox_Alm_alagamento_status;
			size = new global::System.Drawing.Size(82, 17);
			checkBox_Alm_alagamento_status2.Size = size;
			this.CheckBox_Alm_alagamento_status.TabIndex = (HorizontalAlignment)2;
			this.CheckBox_Alm_alagamento_status.TabStop = false;
			this.CheckBox_Alm_alagamento_status.Text = "Alagamento";
			this.CheckBox_Alm_alagamento_status.UseVisualStyleBackColor = true;
			this.CheckBox_Alm_ope_bat_status.AutoCheck = false;
			global::System.Windows.Forms.Control checkBox_Alm_ope_bat_status = this.CheckBox_Alm_ope_bat_status;
			location = new global::System.Drawing.Point(16, 17);
			checkBox_Alm_ope_bat_status.Location = location;
			this.CheckBox_Alm_ope_bat_status.Name = "CheckBox_Alm_ope_bat_status";
			global::System.Windows.Forms.Control checkBox_Alm_ope_bat_status2 = this.CheckBox_Alm_ope_bat_status;
			size = new global::System.Drawing.Size(96, 18);
			checkBox_Alm_ope_bat_status2.Size = size;
			this.CheckBox_Alm_ope_bat_status.TabIndex = (HorizontalAlignment)0;
			this.CheckBox_Alm_ope_bat_status.TabStop = false;
			this.CheckBox_Alm_ope_bat_status.Text = "Operando Bat.";
			this.CheckBox_Alm_ope_bat_status.UseVisualStyleBackColor = true;
			this.CheckBox_Alm_arrombamento_status.AutoCheck = false;
			global::System.Windows.Forms.Control checkBox_Alm_arrombamento_status = this.CheckBox_Alm_arrombamento_status;
			location = new global::System.Drawing.Point(16, 53);
			checkBox_Alm_arrombamento_status.Location = location;
			this.CheckBox_Alm_arrombamento_status.Name = "CheckBox_Alm_arrombamento_status";
			global::System.Windows.Forms.Control checkBox_Alm_arrombamento_status2 = this.CheckBox_Alm_arrombamento_status;
			size = new global::System.Drawing.Size(94, 17);
			checkBox_Alm_arrombamento_status2.Size = size;
			this.CheckBox_Alm_arrombamento_status.TabIndex = (HorizontalAlignment)1;
			this.CheckBox_Alm_arrombamento_status.TabStop = false;
			this.CheckBox_Alm_arrombamento_status.Text = "Arrombamento";
			this.CheckBox_Alm_arrombamento_status.UseVisualStyleBackColor = true;
			this.Label_EA1.AutoSize = true;
			global::System.Windows.Forms.Control label_EA = this.Label_EA1;
			location = new global::System.Drawing.Point(15, 26);
			label_EA.Location = location;
			this.Label_EA1.Name = "Label_EA1";
			global::System.Windows.Forms.Control label_EA2 = this.Label_EA1;
			size = new global::System.Drawing.Size(56, 13);
			label_EA2.Size = size;
			this.Label_EA1.TabIndex = (HorizontalAlignment)7;
			this.Label_EA1.Text = "EA01 (%) :";
			this.Valor_EA1.BackColor = global::System.Drawing.Color.Beige;
			global::System.Windows.Forms.Control valor_EA = this.Valor_EA1;
			location = new global::System.Drawing.Point(77, 23);
			valor_EA.Location = location;
			this.Valor_EA1.Name = "Valor_EA1";
			this.Valor_EA1.ReadOnly = true;
			global::System.Windows.Forms.Control valor_EA2 = this.Valor_EA1;
			size = new global::System.Drawing.Size(53, 20);
			valor_EA2.Size = size;
			this.Valor_EA1.TabIndex = (HorizontalAlignment)8;
			this.Valor_EA1.TabStop = false;
			this.Valor_EA1.TextAlign = (HorizontalAlignment)1;
			this.Label_EA2.AutoSize = true;
			global::System.Windows.Forms.Control label_EA3 = this.Label_EA2;
			location = new global::System.Drawing.Point(15, 48);
			label_EA3.Location = location;
			this.Label_EA2.Name = "Label_EA2";
			global::System.Windows.Forms.Control label_EA4 = this.Label_EA2;
			size = new global::System.Drawing.Size(56, 13);
			label_EA4.Size = size;
			this.Label_EA2.TabIndex = (HorizontalAlignment)9;
			this.Label_EA2.Text = "EA02 (%) :";
			this.Valor_EA2.BackColor = global::System.Drawing.Color.Beige;
			global::System.Windows.Forms.Control valor_EA3 = this.Valor_EA2;
			location = new global::System.Drawing.Point(77, 45);
			valor_EA3.Location = location;
			this.Valor_EA2.Name = "Valor_EA2";
			this.Valor_EA2.ReadOnly = true;
			global::System.Windows.Forms.Control valor_EA4 = this.Valor_EA2;
			size = new global::System.Drawing.Size(53, 20);
			valor_EA4.Size = size;
			this.Valor_EA2.TabIndex = (HorizontalAlignment)10;
			this.Valor_EA2.TabStop = false;
			this.Valor_EA2.TextAlign = (HorizontalAlignment)1;
			this.Label_EA3.AutoSize = true;
			global::System.Windows.Forms.Control label_EA5 = this.Label_EA3;
			location = new global::System.Drawing.Point(15, 70);
			label_EA5.Location = location;
			this.Label_EA3.Name = "Label_EA3";
			global::System.Windows.Forms.Control label_EA6 = this.Label_EA3;
			size = new global::System.Drawing.Size(56, 13);
			label_EA6.Size = size;
			this.Label_EA3.TabIndex = (HorizontalAlignment)11;
			this.Label_EA3.Text = "EA03 (%) :";
			this.Valor_EA3.BackColor = global::System.Drawing.Color.Beige;
			global::System.Windows.Forms.Control valor_EA5 = this.Valor_EA3;
			location = new global::System.Drawing.Point(77, 67);
			valor_EA5.Location = location;
			this.Valor_EA3.Name = "Valor_EA3";
			this.Valor_EA3.ReadOnly = true;
			global::System.Windows.Forms.Control valor_EA6 = this.Valor_EA3;
			size = new global::System.Drawing.Size(53, 20);
			valor_EA6.Size = size;
			this.Valor_EA3.TabIndex = (HorizontalAlignment)12;
			this.Valor_EA3.TabStop = false;
			this.Valor_EA3.TextAlign = (HorizontalAlignment)1;
			this.Label_EA4.AutoSize = true;
			global::System.Windows.Forms.Control label_EA7 = this.Label_EA4;
			location = new global::System.Drawing.Point(15, 92);
			label_EA7.Location = location;
			this.Label_EA4.Name = "Label_EA4";
			global::System.Windows.Forms.Control label_EA8 = this.Label_EA4;
			size = new global::System.Drawing.Size(56, 13);
			label_EA8.Size = size;
			this.Label_EA4.TabIndex = (HorizontalAlignment)13;
			this.Label_EA4.Text = "EA04 (%) :";
			this.Valor_EA4.BackColor = global::System.Drawing.Color.Beige;
			global::System.Windows.Forms.Control valor_EA7 = this.Valor_EA4;
			location = new global::System.Drawing.Point(77, 89);
			valor_EA7.Location = location;
			this.Valor_EA4.Name = "Valor_EA4";
			this.Valor_EA4.ReadOnly = true;
			global::System.Windows.Forms.Control valor_EA8 = this.Valor_EA4;
			size = new global::System.Drawing.Size(53, 20);
			valor_EA8.Size = size;
			this.Valor_EA4.TabIndex = (HorizontalAlignment)14;
			this.Valor_EA4.TabStop = false;
			this.Valor_EA4.TextAlign = (HorizontalAlignment)1;
			this.Label_EA5.AutoSize = true;
			global::System.Windows.Forms.Control label_EA9 = this.Label_EA5;
			location = new global::System.Drawing.Point(15, 114);
			label_EA9.Location = location;
			this.Label_EA5.Name = "Label_EA5";
			global::System.Windows.Forms.Control label_EA10 = this.Label_EA5;
			size = new global::System.Drawing.Size(56, 13);
			label_EA10.Size = size;
			this.Label_EA5.TabIndex = (HorizontalAlignment)15;
			this.Label_EA5.Text = "EA05 (%) :";
			this.Valor_EA5.BackColor = global::System.Drawing.Color.Beige;
			global::System.Windows.Forms.Control valor_EA9 = this.Valor_EA5;
			location = new global::System.Drawing.Point(77, 111);
			valor_EA9.Location = location;
			this.Valor_EA5.Name = "Valor_EA5";
			this.Valor_EA5.ReadOnly = true;
			global::System.Windows.Forms.Control valor_EA10 = this.Valor_EA5;
			size = new global::System.Drawing.Size(53, 20);
			valor_EA10.Size = size;
			this.Valor_EA5.TabIndex = (HorizontalAlignment)16;
			this.Valor_EA5.TabStop = false;
			this.Valor_EA5.TextAlign = (HorizontalAlignment)1;
			this.Label_EA6.AutoSize = true;
			global::System.Windows.Forms.Control label_EA11 = this.Label_EA6;
			location = new global::System.Drawing.Point(15, 136);
			label_EA11.Location = location;
			this.Label_EA6.Name = "Label_EA6";
			global::System.Windows.Forms.Control label_EA12 = this.Label_EA6;
			size = new global::System.Drawing.Size(56, 13);
			label_EA12.Size = size;
			this.Label_EA6.TabIndex = (HorizontalAlignment)17;
			this.Label_EA6.Text = "EA06 (%) :";
			this.Valor_EA6.BackColor = global::System.Drawing.Color.Beige;
			global::System.Windows.Forms.Control valor_EA11 = this.Valor_EA6;
			location = new global::System.Drawing.Point(77, 133);
			valor_EA11.Location = location;
			this.Valor_EA6.Name = "Valor_EA6";
			this.Valor_EA6.ReadOnly = true;
			global::System.Windows.Forms.Control valor_EA12 = this.Valor_EA6;
			size = new global::System.Drawing.Size(53, 20);
			valor_EA12.Size = size;
			this.Valor_EA6.TabIndex = (HorizontalAlignment)18;
			this.Valor_EA6.TabStop = false;
			this.Valor_EA6.TextAlign = (HorizontalAlignment)1;
			this.Label_EA7.AutoSize = true;
			global::System.Windows.Forms.Control label_EA13 = this.Label_EA7;
			location = new global::System.Drawing.Point(15, 158);
			label_EA13.Location = location;
			this.Label_EA7.Name = "Label_EA7";
			global::System.Windows.Forms.Control label_EA14 = this.Label_EA7;
			size = new global::System.Drawing.Size(56, 13);
			label_EA14.Size = size;
			this.Label_EA7.TabIndex = (HorizontalAlignment)19;
			this.Label_EA7.Text = "EA07 (%) :";
			this.Valor_EA7.BackColor = global::System.Drawing.Color.Beige;
			global::System.Windows.Forms.Control valor_EA13 = this.Valor_EA7;
			location = new global::System.Drawing.Point(77, 155);
			valor_EA13.Location = location;
			this.Valor_EA7.Name = "Valor_EA7";
			this.Valor_EA7.ReadOnly = true;
			global::System.Windows.Forms.Control valor_EA14 = this.Valor_EA7;
			size = new global::System.Drawing.Size(53, 20);
			valor_EA14.Size = size;
			this.Valor_EA7.TabIndex = (HorizontalAlignment)20;
			this.Valor_EA7.TabStop = false;
			this.Valor_EA7.TextAlign = (HorizontalAlignment)1;
			this.Label_EA8.AutoSize = true;
			global::System.Windows.Forms.Control label_EA15 = this.Label_EA8;
			location = new global::System.Drawing.Point(15, 180);
			label_EA15.Location = location;
			this.Label_EA8.Name = "Label_EA8";
			global::System.Windows.Forms.Control label_EA16 = this.Label_EA8;
			size = new global::System.Drawing.Size(56, 13);
			label_EA16.Size = size;
			this.Label_EA8.TabIndex = (HorizontalAlignment)21;
			this.Label_EA8.Text = "EA08 (%) :";
			this.Valor_EA8.BackColor = global::System.Drawing.Color.Beige;
			global::System.Windows.Forms.Control valor_EA15 = this.Valor_EA8;
			location = new global::System.Drawing.Point(77, 177);
			valor_EA15.Location = location;
			this.Valor_EA8.Name = "Valor_EA8";
			this.Valor_EA8.ReadOnly = true;
			global::System.Windows.Forms.Control valor_EA16 = this.Valor_EA8;
			size = new global::System.Drawing.Size(53, 20);
			valor_EA16.Size = size;
			this.Valor_EA8.TabIndex = (HorizontalAlignment)22;
			this.Valor_EA8.TabStop = false;
			this.Valor_EA8.TextAlign = (HorizontalAlignment)1;
			this.Grupo_medidas.Controls.Add(this.Valor_EA16);
			this.Grupo_medidas.Controls.Add(this.Label_EA16);
			this.Grupo_medidas.Controls.Add(this.Valor_EA15);
			this.Grupo_medidas.Controls.Add(this.Label_EA15);
			this.Grupo_medidas.Controls.Add(this.Valor_EA14);
			this.Grupo_medidas.Controls.Add(this.Label_EA14);
			this.Grupo_medidas.Controls.Add(this.Valor_EA13);
			this.Grupo_medidas.Controls.Add(this.Label_EA13);
			this.Grupo_medidas.Controls.Add(this.Valor_EA12);
			this.Grupo_medidas.Controls.Add(this.Label_EA12);
			this.Grupo_medidas.Controls.Add(this.Valor_EA11);
			this.Grupo_medidas.Controls.Add(this.Label_EA11);
			this.Grupo_medidas.Controls.Add(this.Valor_EA10);
			this.Grupo_medidas.Controls.Add(this.Label_EA10);
			this.Grupo_medidas.Controls.Add(this.Valor_EA9);
			this.Grupo_medidas.Controls.Add(this.Label_EA9);
			this.Grupo_medidas.Controls.Add(this.Valor_EA8);
			this.Grupo_medidas.Controls.Add(this.Label_EA8);
			this.Grupo_medidas.Controls.Add(this.Valor_EA7);
			this.Grupo_medidas.Controls.Add(this.Label_EA7);
			this.Grupo_medidas.Controls.Add(this.Valor_EA6);
			this.Grupo_medidas.Controls.Add(this.Label_EA6);
			this.Grupo_medidas.Controls.Add(this.Valor_EA5);
			this.Grupo_medidas.Controls.Add(this.Label_EA5);
			this.Grupo_medidas.Controls.Add(this.Valor_EA4);
			this.Grupo_medidas.Controls.Add(this.Label_EA4);
			this.Grupo_medidas.Controls.Add(this.Valor_EA3);
			this.Grupo_medidas.Controls.Add(this.Label_EA3);
			this.Grupo_medidas.Controls.Add(this.Valor_EA2);
			this.Grupo_medidas.Controls.Add(this.Label_EA2);
			this.Grupo_medidas.Controls.Add(this.Valor_EA1);
			this.Grupo_medidas.Controls.Add(this.Label_EA1);
			this.Grupo_medidas.Enabled = false;
			global::System.Windows.Forms.Control grupo_medidas = this.Grupo_medidas;
			location = new global::System.Drawing.Point(415, 498);
			grupo_medidas.Location = location;
			this.Grupo_medidas.Name = "Grupo_medidas";
			global::System.Windows.Forms.Control grupo_medidas2 = this.Grupo_medidas;
			size = new global::System.Drawing.Size(284, 207);
			grupo_medidas2.Size = size;
			this.Grupo_medidas.TabIndex = (HorizontalAlignment)9;
			this.Grupo_medidas.TabStop = false;
			this.Grupo_medidas.Text = "Medidas Analógicas";
			this.Valor_EA16.BackColor = global::System.Drawing.Color.Beige;
			global::System.Windows.Forms.Control valor_EA17 = this.Valor_EA16;
			location = new global::System.Drawing.Point(215, 177);
			valor_EA17.Location = location;
			this.Valor_EA16.Name = "Valor_EA16";
			this.Valor_EA16.ReadOnly = true;
			global::System.Windows.Forms.Control valor_EA18 = this.Valor_EA16;
			size = new global::System.Drawing.Size(53, 20);
			valor_EA18.Size = size;
			this.Valor_EA16.TabIndex = (HorizontalAlignment)38;
			this.Valor_EA16.TabStop = false;
			this.Valor_EA16.TextAlign = (HorizontalAlignment)1;
			this.Label_EA16.AutoSize = true;
			global::System.Windows.Forms.Control label_EA17 = this.Label_EA16;
			location = new global::System.Drawing.Point(153, 180);
			label_EA17.Location = location;
			this.Label_EA16.Name = "Label_EA16";
			global::System.Windows.Forms.Control label_EA18 = this.Label_EA16;
			size = new global::System.Drawing.Size(56, 13);
			label_EA18.Size = size;
			this.Label_EA16.TabIndex = (HorizontalAlignment)37;
			this.Label_EA16.Text = "EA16 (%) :";
			this.Valor_EA15.BackColor = global::System.Drawing.Color.Beige;
			global::System.Windows.Forms.Control valor_EA19 = this.Valor_EA15;
			location = new global::System.Drawing.Point(215, 155);
			valor_EA19.Location = location;
			this.Valor_EA15.Name = "Valor_EA15";
			this.Valor_EA15.ReadOnly = true;
			global::System.Windows.Forms.Control valor_EA20 = this.Valor_EA15;
			size = new global::System.Drawing.Size(53, 20);
			valor_EA20.Size = size;
			this.Valor_EA15.TabIndex = (HorizontalAlignment)36;
			this.Valor_EA15.TabStop = false;
			this.Valor_EA15.TextAlign = (HorizontalAlignment)1;
			this.Label_EA15.AutoSize = true;
			global::System.Windows.Forms.Control label_EA19 = this.Label_EA15;
			location = new global::System.Drawing.Point(153, 158);
			label_EA19.Location = location;
			this.Label_EA15.Name = "Label_EA15";
			global::System.Windows.Forms.Control label_EA20 = this.Label_EA15;
			size = new global::System.Drawing.Size(56, 13);
			label_EA20.Size = size;
			this.Label_EA15.TabIndex = (HorizontalAlignment)35;
			this.Label_EA15.Text = "EA15 (%) :";
			this.Valor_EA14.BackColor = global::System.Drawing.Color.Beige;
			global::System.Windows.Forms.Control valor_EA21 = this.Valor_EA14;
			location = new global::System.Drawing.Point(215, 133);
			valor_EA21.Location = location;
			this.Valor_EA14.Name = "Valor_EA14";
			this.Valor_EA14.ReadOnly = true;
			global::System.Windows.Forms.Control valor_EA22 = this.Valor_EA14;
			size = new global::System.Drawing.Size(53, 20);
			valor_EA22.Size = size;
			this.Valor_EA14.TabIndex = (HorizontalAlignment)34;
			this.Valor_EA14.TabStop = false;
			this.Valor_EA14.TextAlign = (HorizontalAlignment)1;
			this.Label_EA14.AutoSize = true;
			global::System.Windows.Forms.Control label_EA21 = this.Label_EA14;
			location = new global::System.Drawing.Point(153, 136);
			label_EA21.Location = location;
			this.Label_EA14.Name = "Label_EA14";
			global::System.Windows.Forms.Control label_EA22 = this.Label_EA14;
			size = new global::System.Drawing.Size(56, 13);
			label_EA22.Size = size;
			this.Label_EA14.TabIndex = (HorizontalAlignment)33;
			this.Label_EA14.Text = "EA14 (%) :";
			this.Valor_EA13.BackColor = global::System.Drawing.Color.Beige;
			global::System.Windows.Forms.Control valor_EA23 = this.Valor_EA13;
			location = new global::System.Drawing.Point(215, 111);
			valor_EA23.Location = location;
			this.Valor_EA13.Name = "Valor_EA13";
			this.Valor_EA13.ReadOnly = true;
			global::System.Windows.Forms.Control valor_EA24 = this.Valor_EA13;
			size = new global::System.Drawing.Size(53, 20);
			valor_EA24.Size = size;
			this.Valor_EA13.TabIndex = (HorizontalAlignment)32;
			this.Valor_EA13.TabStop = false;
			this.Valor_EA13.TextAlign = (HorizontalAlignment)1;
			this.Label_EA13.AutoSize = true;
			global::System.Windows.Forms.Control label_EA23 = this.Label_EA13;
			location = new global::System.Drawing.Point(153, 114);
			label_EA23.Location = location;
			this.Label_EA13.Name = "Label_EA13";
			global::System.Windows.Forms.Control label_EA24 = this.Label_EA13;
			size = new global::System.Drawing.Size(56, 13);
			label_EA24.Size = size;
			this.Label_EA13.TabIndex = (HorizontalAlignment)31;
			this.Label_EA13.Text = "EA13 (%) :";
			this.Valor_EA12.BackColor = global::System.Drawing.Color.Beige;
			global::System.Windows.Forms.Control valor_EA25 = this.Valor_EA12;
			location = new global::System.Drawing.Point(215, 89);
			valor_EA25.Location = location;
			this.Valor_EA12.Name = "Valor_EA12";
			this.Valor_EA12.ReadOnly = true;
			global::System.Windows.Forms.Control valor_EA26 = this.Valor_EA12;
			size = new global::System.Drawing.Size(53, 20);
			valor_EA26.Size = size;
			this.Valor_EA12.TabIndex = (HorizontalAlignment)30;
			this.Valor_EA12.TabStop = false;
			this.Valor_EA12.TextAlign = (HorizontalAlignment)1;
			this.Label_EA12.AutoSize = true;
			global::System.Windows.Forms.Control label_EA25 = this.Label_EA12;
			location = new global::System.Drawing.Point(153, 92);
			label_EA25.Location = location;
			this.Label_EA12.Name = "Label_EA12";
			global::System.Windows.Forms.Control label_EA26 = this.Label_EA12;
			size = new global::System.Drawing.Size(56, 13);
			label_EA26.Size = size;
			this.Label_EA12.TabIndex = (HorizontalAlignment)29;
			this.Label_EA12.Text = "EA12 (%) :";
			this.Valor_EA11.BackColor = global::System.Drawing.Color.Beige;
			global::System.Windows.Forms.Control valor_EA27 = this.Valor_EA11;
			location = new global::System.Drawing.Point(215, 67);
			valor_EA27.Location = location;
			this.Valor_EA11.Name = "Valor_EA11";
			this.Valor_EA11.ReadOnly = true;
			global::System.Windows.Forms.Control valor_EA28 = this.Valor_EA11;
			size = new global::System.Drawing.Size(53, 20);
			valor_EA28.Size = size;
			this.Valor_EA11.TabIndex = (HorizontalAlignment)28;
			this.Valor_EA11.TabStop = false;
			this.Valor_EA11.TextAlign = (HorizontalAlignment)1;
			this.Label_EA11.AutoSize = true;
			global::System.Windows.Forms.Control label_EA27 = this.Label_EA11;
			location = new global::System.Drawing.Point(153, 70);
			label_EA27.Location = location;
			this.Label_EA11.Name = "Label_EA11";
			global::System.Windows.Forms.Control label_EA28 = this.Label_EA11;
			size = new global::System.Drawing.Size(56, 13);
			label_EA28.Size = size;
			this.Label_EA11.TabIndex = (HorizontalAlignment)27;
			this.Label_EA11.Text = "EA11 (%) :";
			this.Valor_EA10.BackColor = global::System.Drawing.Color.Beige;
			global::System.Windows.Forms.Control valor_EA29 = this.Valor_EA10;
			location = new global::System.Drawing.Point(215, 45);
			valor_EA29.Location = location;
			this.Valor_EA10.Name = "Valor_EA10";
			this.Valor_EA10.ReadOnly = true;
			global::System.Windows.Forms.Control valor_EA30 = this.Valor_EA10;
			size = new global::System.Drawing.Size(53, 20);
			valor_EA30.Size = size;
			this.Valor_EA10.TabIndex = (HorizontalAlignment)26;
			this.Valor_EA10.TabStop = false;
			this.Valor_EA10.TextAlign = (HorizontalAlignment)1;
			this.Label_EA10.AutoSize = true;
			global::System.Windows.Forms.Control label_EA29 = this.Label_EA10;
			location = new global::System.Drawing.Point(153, 48);
			label_EA29.Location = location;
			this.Label_EA10.Name = "Label_EA10";
			global::System.Windows.Forms.Control label_EA30 = this.Label_EA10;
			size = new global::System.Drawing.Size(56, 13);
			label_EA30.Size = size;
			this.Label_EA10.TabIndex = (HorizontalAlignment)25;
			this.Label_EA10.Text = "EA10 (%) :";
			this.Valor_EA9.BackColor = global::System.Drawing.Color.Beige;
			global::System.Windows.Forms.Control valor_EA31 = this.Valor_EA9;
			location = new global::System.Drawing.Point(215, 23);
			valor_EA31.Location = location;
			this.Valor_EA9.Name = "Valor_EA9";
			this.Valor_EA9.ReadOnly = true;
			global::System.Windows.Forms.Control valor_EA32 = this.Valor_EA9;
			size = new global::System.Drawing.Size(53, 20);
			valor_EA32.Size = size;
			this.Valor_EA9.TabIndex = (HorizontalAlignment)24;
			this.Valor_EA9.TabStop = false;
			this.Valor_EA9.TextAlign = (HorizontalAlignment)1;
			this.Label_EA9.AutoSize = true;
			global::System.Windows.Forms.Control label_EA31 = this.Label_EA9;
			location = new global::System.Drawing.Point(153, 26);
			label_EA31.Location = location;
			this.Label_EA9.Name = "Label_EA9";
			global::System.Windows.Forms.Control label_EA32 = this.Label_EA9;
			size = new global::System.Drawing.Size(56, 13);
			label_EA32.Size = size;
			this.Label_EA9.TabIndex = (HorizontalAlignment)23;
			this.Label_EA9.Text = "EA09 (%) :";
			global::System.Drawing.SizeF autoScaleDimensions;
			autoScaleDimensions = new global::System.Drawing.SizeF(6f, 13f);
			this.AutoScaleDimensions = autoScaleDimensions;
			this.AutoScaleMode = (HorizontalAlignment)1;
			size = new global::System.Drawing.Size(722, 717);
			this.ClientSize = size;
			this.Controls.Add(this.Grupo_medidas);
			this.Controls.Add(this.Grupo_alarmes);
			this.Controls.Add(this.Grupo_escrita_de_dados);
			this.Controls.Add(this.Grupo_status);
			this.Controls.Add(this.Grupo_estatistica);
			this.Controls.Add(this.Grupo_setpoints);
			this.Controls.Add(this.Grupo_ctrl_com);
			this.FormBorderStyle = (HorizontalAlignment)1;
			location = new global::System.Drawing.Point(160, 2);
			this.Location = location;
			this.Name = "Equip_202_mon";
			this.StartPosition = (HorizontalAlignment)4;
			this.Text = "Equipamento MD 202 - Monitoração";
			this.Grupo_ctrl_com.ResumeLayout(false);
			this.Grupo_ctrl_com.PerformLayout();
			this.Tela_endereco_estacao.EndInit();
			this.Tela_endereco_mestre.EndInit();
			this.Grupo_setpoints.ResumeLayout(false);
			this.Grupo_setpoints.PerformLayout();
			this.Grupo_estatistica.ResumeLayout(false);
			this.Grupo_estatistica.PerformLayout();
			this.Grupo_status.ResumeLayout(false);
			this.Grupo_bomba4.ResumeLayout(false);
			this.Grupo_bomba4.PerformLayout();
			this.Grupo_bomba3.ResumeLayout(false);
			this.Grupo_bomba3.PerformLayout();
			this.Grupo_bomba2.ResumeLayout(false);
			this.Grupo_bomba2.PerformLayout();
			this.Grupo_bomba1.ResumeLayout(false);
			this.Grupo_bomba1.PerformLayout();
			this.Grupo_escrita_de_dados.ResumeLayout(false);
			this.Grupo_escrita_de_dados.PerformLayout();
			this.Tela_nivel_origem.EndInit();
			this.Tela_nivel_destino.EndInit();
			this.Grupo_alarmes.ResumeLayout(false);
			this.Grupo_medidas.ResumeLayout(false);
			this.Grupo_medidas.PerformLayout();
			this.ResumeLayout(false);
		}

		// Token: 0x04001713 RID: 5907
		private global::System.ComponentModel.IContainer components;
	}
}
