using System.Drawing;
using System.Windows.Forms;
﻿namespace iS800
{
	// Token: 0x0200009B RID: 155
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class Equip_VA210_conf : global::System.Windows.Forms.Form
	{
		// Token: 0x06002419 RID: 9241 RVA: 0x00409F8C File Offset: 0x0040838C
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			if (disposing && this.components != null)
			{
				this.components.Dispose();
			}
			base.Dispose(disposing);
		}

		// Token: 0x0600241A RID: 9242 RVA: 0x00409FAC File Offset: 0x004083AC
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.grupo_parametros_gerais = new global::System.Windows.Forms.GroupBox();
			this.ComboBox_tipo_leitura = new global::System.Windows.Forms.ComboBox();
			this.Valor_altura_pressiostato = new global::System.Windows.Forms.TextBox();
			this.Label_tempo_sem_comunicacao = new global::System.Windows.Forms.Label();
			this.Label_altura_nivel_alto = new global::System.Windows.Forms.Label();
			this.Label_altura_nivel_baixo = new global::System.Windows.Forms.Label();
			this.Label_altura_pressiostato = new global::System.Windows.Forms.Label();
			this.Valor_end_mestre = new global::System.Windows.Forms.TextBox();
			this.Valor_tempo_max_sem_comunicacao = new global::System.Windows.Forms.TextBox();
			this.Valor_nivel_alto = new global::System.Windows.Forms.TextBox();
			this.Valor_nivel_baixo = new global::System.Windows.Forms.TextBox();
			this.Label_end_mestre = new global::System.Windows.Forms.Label();
			this.Label_numero_recalques = new global::System.Windows.Forms.Label();
			this.grupo_grupos = new global::System.Windows.Forms.GroupBox();
			this.Label_numero_grupos = new global::System.Windows.Forms.Label();
			this.VScroll_num_grupo = new global::System.Windows.Forms.VScrollBar();
			this.Valor_num_grupo = new global::System.Windows.Forms.TextBox();
			this.Valor_grupo_16 = new global::System.Windows.Forms.TextBox();
			this.Valor_grupo_8 = new global::System.Windows.Forms.TextBox();
			this.Valor_grupo_15 = new global::System.Windows.Forms.TextBox();
			this.Valor_grupo_7 = new global::System.Windows.Forms.TextBox();
			this.Valor_grupo_14 = new global::System.Windows.Forms.TextBox();
			this.Valor_grupo_6 = new global::System.Windows.Forms.TextBox();
			this.Valor_grupo_13 = new global::System.Windows.Forms.TextBox();
			this.Valor_grupo_5 = new global::System.Windows.Forms.TextBox();
			this.Valor_grupo_12 = new global::System.Windows.Forms.TextBox();
			this.Valor_grupo_4 = new global::System.Windows.Forms.TextBox();
			this.Valor_grupo_11 = new global::System.Windows.Forms.TextBox();
			this.Valor_grupo_3 = new global::System.Windows.Forms.TextBox();
			this.Valor_grupo_10 = new global::System.Windows.Forms.TextBox();
			this.Valor_grupo_2 = new global::System.Windows.Forms.TextBox();
			this.Valor_grupo_9 = new global::System.Windows.Forms.TextBox();
			this.Valor_grupo_1 = new global::System.Windows.Forms.TextBox();
			this.Label_grupo_16 = new global::System.Windows.Forms.Label();
			this.Label_grupo_8 = new global::System.Windows.Forms.Label();
			this.Label_grupo_15 = new global::System.Windows.Forms.Label();
			this.Label_grupo_7 = new global::System.Windows.Forms.Label();
			this.Label_grupo_14 = new global::System.Windows.Forms.Label();
			this.Label_grupo_6 = new global::System.Windows.Forms.Label();
			this.Label_grupo_13 = new global::System.Windows.Forms.Label();
			this.Label_grupo_5 = new global::System.Windows.Forms.Label();
			this.Label_grupo_12 = new global::System.Windows.Forms.Label();
			this.Label_grupo_4 = new global::System.Windows.Forms.Label();
			this.Label_grupo_11 = new global::System.Windows.Forms.Label();
			this.Label_grupo_3 = new global::System.Windows.Forms.Label();
			this.Label_grupo_10 = new global::System.Windows.Forms.Label();
			this.Label_grupo_2 = new global::System.Windows.Forms.Label();
			this.Label_grupo_9 = new global::System.Windows.Forms.Label();
			this.Label_grupo_1 = new global::System.Windows.Forms.Label();
			this.grupo_parametros_gerais.SuspendLayout();
			this.grupo_grupos.SuspendLayout();
			this.SuspendLayout();
			this.grupo_parametros_gerais.Controls.Add(this.ComboBox_tipo_leitura);
			this.grupo_parametros_gerais.Controls.Add(this.Valor_altura_pressiostato);
			this.grupo_parametros_gerais.Controls.Add(this.Label_tempo_sem_comunicacao);
			this.grupo_parametros_gerais.Controls.Add(this.Label_altura_nivel_alto);
			this.grupo_parametros_gerais.Controls.Add(this.Label_altura_nivel_baixo);
			this.grupo_parametros_gerais.Controls.Add(this.Label_altura_pressiostato);
			this.grupo_parametros_gerais.Controls.Add(this.Valor_end_mestre);
			this.grupo_parametros_gerais.Controls.Add(this.Valor_tempo_max_sem_comunicacao);
			this.grupo_parametros_gerais.Controls.Add(this.Valor_nivel_alto);
			this.grupo_parametros_gerais.Controls.Add(this.Valor_nivel_baixo);
			this.grupo_parametros_gerais.Controls.Add(this.Label_end_mestre);
			this.grupo_parametros_gerais.Controls.Add(this.Label_numero_recalques);
			global::System.Windows.Forms.Control grupo_parametros_gerais = this.grupo_parametros_gerais;
			grupo_parametros_gerais.Location = new global::System.Drawing.Point(12, 12);
			this.grupo_parametros_gerais.Name = "grupo_parametros_gerais";
			global::System.Windows.Forms.Control grupo_parametros_gerais2 = this.grupo_parametros_gerais;
			grupo_parametros_gerais2.Size = new global::System.Drawing.Size(335, 186);
			this.grupo_parametros_gerais.TabIndex = 1;
			this.grupo_parametros_gerais.TabStop = false;
			this.grupo_parametros_gerais.Text = "Parâmetros gerais";
			this.ComboBox_tipo_leitura.FormattingEnabled = true;
			global::System.Windows.Forms.Control comboBox_tipo_leitura = this.ComboBox_tipo_leitura;
comboBox_tipo_leitura.Location = new global::System.Drawing.Point(239, 51);
			this.ComboBox_tipo_leitura.Name = "ComboBox_tipo_leitura";
			global::System.Windows.Forms.Control comboBox_tipo_leitura2 = this.ComboBox_tipo_leitura;
			Size = new System.Drawing.Size(78, 21);
			comboBox_tipo_leitura2.Size = this.Size;
			this.ComboBox_tipo_leitura.TabIndex = 3;
			global::System.Windows.Forms.Control valor_altura_pressiostato = this.Valor_altura_pressiostato;
valor_altura_pressiostato.Location = new global::System.Drawing.Point(239, 76);
			this.Valor_altura_pressiostato.Name = "Valor_altura_pressiostato";
			global::System.Windows.Forms.Control valor_altura_pressiostato2 = this.Valor_altura_pressiostato;
			Size = new System.Drawing.Size(78, 20);
			valor_altura_pressiostato2.Size = this.Size;
			this.Valor_altura_pressiostato.TabIndex = 4;
			this.Valor_altura_pressiostato.TextAlign = HorizontalAlignment.Center;
			this.Label_tempo_sem_comunicacao.AutoSize = true;
			global::System.Windows.Forms.Control label_tempo_sem_comunicacao = this.Label_tempo_sem_comunicacao;
label_tempo_sem_comunicacao.Location = new global::System.Drawing.Point(24, 155);
			this.Label_tempo_sem_comunicacao.Name = "Label_tempo_sem_comunicacao";
			global::System.Windows.Forms.Control label_tempo_sem_comunicacao2 = this.Label_tempo_sem_comunicacao;
			Size = new System.Drawing.Size(209, 13);
			label_tempo_sem_comunicacao2.Size = this.Size;
			this.Label_tempo_sem_comunicacao.TabIndex = 4;
			this.Label_tempo_sem_comunicacao.Text = "Tempo máx. sem comunicação (1-20 min) :";
			this.Label_altura_nivel_alto.AutoSize = true;
			global::System.Windows.Forms.Control label_altura_nivel_alto = this.Label_altura_nivel_alto;
label_altura_nivel_alto.Location = new global::System.Drawing.Point(24, 130);
			this.Label_altura_nivel_alto.Name = "Label_altura_nivel_alto";
			global::System.Windows.Forms.Control label_altura_nivel_alto2 = this.Label_altura_nivel_alto;
			Size = new System.Drawing.Size(159, 13);
			label_altura_nivel_alto2.Size = this.Size;
			this.Label_altura_nivel_alto.TabIndex = 4;
			this.Label_altura_nivel_alto.Text = "Altura para nível alto ( * 10 cm) :";
			this.Label_altura_nivel_baixo.AutoSize = true;
			global::System.Windows.Forms.Control label_altura_nivel_baixo = this.Label_altura_nivel_baixo;
label_altura_nivel_baixo.Location = new global::System.Drawing.Point(24, 105);
			this.Label_altura_nivel_baixo.Name = "Label_altura_nivel_baixo";
			global::System.Windows.Forms.Control label_altura_nivel_baixo2 = this.Label_altura_nivel_baixo;
			Size = new System.Drawing.Size(167, 13);
			label_altura_nivel_baixo2.Size = this.Size;
			this.Label_altura_nivel_baixo.TabIndex = 4;
			this.Label_altura_nivel_baixo.Text = "Altura para nível baixo ( * 10 cm) :";
			this.Label_altura_pressiostato.AutoSize = true;
			global::System.Windows.Forms.Control label_altura_pressiostato = this.Label_altura_pressiostato;
label_altura_pressiostato.Location = new global::System.Drawing.Point(24, 80);
			this.Label_altura_pressiostato.Name = "Label_altura_pressiostato";
			global::System.Windows.Forms.Control label_altura_pressiostato2 = this.Label_altura_pressiostato;
			Size = new System.Drawing.Size(147, 13);
			label_altura_pressiostato2.Size = this.Size;
			this.Label_altura_pressiostato.TabIndex = 4;
			this.Label_altura_pressiostato.Text = "Altura pressiostato ( * 10 cm) :";
			global::System.Windows.Forms.Control valor_end_mestre = this.Valor_end_mestre;
valor_end_mestre.Location = new global::System.Drawing.Point(239, 26);
			this.Valor_end_mestre.Name = "Valor_end_mestre";
			global::System.Windows.Forms.Control valor_end_mestre2 = this.Valor_end_mestre;
			Size = new System.Drawing.Size(78, 20);
			valor_end_mestre2.Size = this.Size;
			this.Valor_end_mestre.TabIndex = 2;
			this.Valor_end_mestre.TextAlign = HorizontalAlignment.Center;
			global::System.Windows.Forms.Control valor_tempo_max_sem_comunicacao = this.Valor_tempo_max_sem_comunicacao;
valor_tempo_max_sem_comunicacao.Location = new global::System.Drawing.Point(239, 151);
			this.Valor_tempo_max_sem_comunicacao.Name = "Valor_tempo_max_sem_comunicacao";
			global::System.Windows.Forms.Control valor_tempo_max_sem_comunicacao2 = this.Valor_tempo_max_sem_comunicacao;
			Size = new System.Drawing.Size(78, 20);
			valor_tempo_max_sem_comunicacao2.Size = this.Size;
			this.Valor_tempo_max_sem_comunicacao.TabIndex = 7;
			this.Valor_tempo_max_sem_comunicacao.TextAlign = HorizontalAlignment.Center;
			global::System.Windows.Forms.Control valor_nivel_alto = this.Valor_nivel_alto;
valor_nivel_alto.Location = new global::System.Drawing.Point(239, 126);
			this.Valor_nivel_alto.Name = "Valor_nivel_alto";
			global::System.Windows.Forms.Control valor_nivel_alto2 = this.Valor_nivel_alto;
			Size = new System.Drawing.Size(78, 20);
			valor_nivel_alto2.Size = this.Size;
			this.Valor_nivel_alto.TabIndex = 6;
			this.Valor_nivel_alto.TextAlign = HorizontalAlignment.Center;
			global::System.Windows.Forms.Control valor_nivel_baixo = this.Valor_nivel_baixo;
valor_nivel_baixo.Location = new global::System.Drawing.Point(239, 101);
			this.Valor_nivel_baixo.Name = "Valor_nivel_baixo";
			global::System.Windows.Forms.Control valor_nivel_baixo2 = this.Valor_nivel_baixo;
			Size = new System.Drawing.Size(78, 20);
			valor_nivel_baixo2.Size = this.Size;
			this.Valor_nivel_baixo.TabIndex = 5;
			this.Valor_nivel_baixo.TextAlign = HorizontalAlignment.Center;
			this.Label_end_mestre.AutoSize = true;
			global::System.Windows.Forms.Control label_end_mestre = this.Label_end_mestre;
label_end_mestre.Location = new global::System.Drawing.Point(24, 30);
			this.Label_end_mestre.Name = "Label_end_mestre";
			global::System.Windows.Forms.Control label_end_mestre2 = this.Label_end_mestre;
			Size = new System.Drawing.Size(108, 13);
			label_end_mestre2.Size = this.Size;
			this.Label_end_mestre.TabIndex = 1;
			this.Label_end_mestre.Text = "Endereço do mestre :";
			this.Label_numero_recalques.AutoSize = true;
			global::System.Windows.Forms.Control label_numero_recalques = this.Label_numero_recalques;
label_numero_recalques.Location = new global::System.Drawing.Point(24, 55);
			this.Label_numero_recalques.Name = "Label_numero_recalques";
			global::System.Windows.Forms.Control label_numero_recalques2 = this.Label_numero_recalques;
			Size = new System.Drawing.Size(65, 13);
			label_numero_recalques2.Size = this.Size;
			this.Label_numero_recalques.TabIndex = 0;
			this.Label_numero_recalques.Text = "Tipo leitura :";
			this.grupo_grupos.Controls.Add(this.Label_numero_grupos);
			this.grupo_grupos.Controls.Add(this.VScroll_num_grupo);
			this.grupo_grupos.Controls.Add(this.Valor_num_grupo);
			this.grupo_grupos.Controls.Add(this.Valor_grupo_16);
			this.grupo_grupos.Controls.Add(this.Valor_grupo_8);
			this.grupo_grupos.Controls.Add(this.Valor_grupo_15);
			this.grupo_grupos.Controls.Add(this.Valor_grupo_7);
			this.grupo_grupos.Controls.Add(this.Valor_grupo_14);
			this.grupo_grupos.Controls.Add(this.Valor_grupo_6);
			this.grupo_grupos.Controls.Add(this.Valor_grupo_13);
			this.grupo_grupos.Controls.Add(this.Valor_grupo_5);
			this.grupo_grupos.Controls.Add(this.Valor_grupo_12);
			this.grupo_grupos.Controls.Add(this.Valor_grupo_4);
			this.grupo_grupos.Controls.Add(this.Valor_grupo_11);
			this.grupo_grupos.Controls.Add(this.Valor_grupo_3);
			this.grupo_grupos.Controls.Add(this.Valor_grupo_10);
			this.grupo_grupos.Controls.Add(this.Valor_grupo_2);
			this.grupo_grupos.Controls.Add(this.Valor_grupo_9);
			this.grupo_grupos.Controls.Add(this.Valor_grupo_1);
			this.grupo_grupos.Controls.Add(this.Label_grupo_16);
			this.grupo_grupos.Controls.Add(this.Label_grupo_8);
			this.grupo_grupos.Controls.Add(this.Label_grupo_15);
			this.grupo_grupos.Controls.Add(this.Label_grupo_7);
			this.grupo_grupos.Controls.Add(this.Label_grupo_14);
			this.grupo_grupos.Controls.Add(this.Label_grupo_6);
			this.grupo_grupos.Controls.Add(this.Label_grupo_13);
			this.grupo_grupos.Controls.Add(this.Label_grupo_5);
			this.grupo_grupos.Controls.Add(this.Label_grupo_12);
			this.grupo_grupos.Controls.Add(this.Label_grupo_4);
			this.grupo_grupos.Controls.Add(this.Label_grupo_11);
			this.grupo_grupos.Controls.Add(this.Label_grupo_3);
			this.grupo_grupos.Controls.Add(this.Label_grupo_10);
			this.grupo_grupos.Controls.Add(this.Label_grupo_2);
			this.grupo_grupos.Controls.Add(this.Label_grupo_9);
			this.grupo_grupos.Controls.Add(this.Label_grupo_1);
			global::System.Windows.Forms.Control grupo_grupos = this.grupo_grupos;
grupo_grupos.Location = new global::System.Drawing.Point(14, 218);
			this.grupo_grupos.Name = "grupo_grupos";
			global::System.Windows.Forms.Control grupo_grupos2 = this.grupo_grupos;
			Size = new System.Drawing.Size(335, 294);
			grupo_grupos2.Size = this.Size;
			this.grupo_grupos.TabIndex = 8;
			this.grupo_grupos.TabStop = false;
			this.grupo_grupos.Text = "Configuração dos Grupos";
			this.Label_numero_grupos.AutoSize = true;
			global::System.Windows.Forms.Control label_numero_grupos = this.Label_numero_grupos;
label_numero_grupos.Location = new global::System.Drawing.Point(24, 35);
			this.Label_numero_grupos.Name = "Label_numero_grupos";
			global::System.Windows.Forms.Control label_numero_grupos2 = this.Label_numero_grupos;
			Size = new System.Drawing.Size(103, 13);
			label_numero_grupos2.Size = this.Size;
			this.Label_numero_grupos.TabIndex = 9;
			this.Label_numero_grupos.Text = "Número de grupos : ";
			this.VScroll_num_grupo.LargeChange = 1;
			global::System.Windows.Forms.Control vscroll_num_grupo = this.VScroll_num_grupo;
vscroll_num_grupo.Location = new global::System.Drawing.Point(232, 32);
			this.VScroll_num_grupo.Name = "VScroll_num_grupo";
			global::System.Windows.Forms.Control vscroll_num_grupo2 = this.VScroll_num_grupo;
			Size = new System.Drawing.Size(26, 21);
			vscroll_num_grupo2.Size = this.Size;
			this.VScroll_num_grupo.TabIndex = 8;
			global::System.Windows.Forms.Control valor_num_grupo = this.Valor_num_grupo;
valor_num_grupo.Location = new global::System.Drawing.Point(165, 32);
			this.Valor_num_grupo.Name = "Valor_num_grupo";
			global::System.Windows.Forms.Control valor_num_grupo2 = this.Valor_num_grupo;
			Size = new System.Drawing.Size(66, 20);
			valor_num_grupo2.Size = this.Size;
			this.Valor_num_grupo.TabIndex = 9;
			this.Valor_num_grupo.TextAlign = HorizontalAlignment.Center;
			this.Valor_grupo_16.AcceptsTab = true;
			global::System.Windows.Forms.Control valor_grupo_ = this.Valor_grupo_16;
valor_grupo_.Location = new global::System.Drawing.Point(234, 259);
			this.Valor_grupo_16.Name = "Valor_grupo_16";
			global::System.Windows.Forms.Control valor_grupo_2 = this.Valor_grupo_16;
			Size = new System.Drawing.Size(73, 20);
			valor_grupo_2.Size = this.Size;
			this.Valor_grupo_16.TabIndex = 22;
			this.Valor_grupo_16.TextAlign = HorizontalAlignment.Center;
			this.Valor_grupo_8.AcceptsReturn = true;
			this.Valor_grupo_8.AcceptsTab = true;
			global::System.Windows.Forms.Control valor_grupo_3 = this.Valor_grupo_8;
valor_grupo_3.Location = new global::System.Drawing.Point(79, 259);
			this.Valor_grupo_8.Name = "Valor_grupo_8";
			global::System.Windows.Forms.Control valor_grupo_4 = this.Valor_grupo_8;
			Size = new System.Drawing.Size(73, 20);
			valor_grupo_4.Size = this.Size;
			this.Valor_grupo_8.TabIndex = 17;
			this.Valor_grupo_8.TextAlign = HorizontalAlignment.Center;
			this.Valor_grupo_15.AcceptsTab = true;
			global::System.Windows.Forms.Control valor_grupo_5 = this.Valor_grupo_15;
valor_grupo_5.Location = new global::System.Drawing.Point(234, 232);
			this.Valor_grupo_15.Name = "Valor_grupo_15";
			global::System.Windows.Forms.Control valor_grupo_6 = this.Valor_grupo_15;
			Size = new System.Drawing.Size(73, 20);
			valor_grupo_6.Size = this.Size;
			this.Valor_grupo_15.TabIndex = 21;
			this.Valor_grupo_15.TextAlign = HorizontalAlignment.Center;
			this.Valor_grupo_7.AcceptsTab = true;
			global::System.Windows.Forms.Control valor_grupo_7 = this.Valor_grupo_7;
valor_grupo_7.Location = new global::System.Drawing.Point(79, 232);
			this.Valor_grupo_7.Name = "Valor_grupo_7";
			global::System.Windows.Forms.Control valor_grupo_8 = this.Valor_grupo_7;
			Size = new System.Drawing.Size(73, 20);
			valor_grupo_8.Size = this.Size;
			this.Valor_grupo_7.TabIndex = 16;
			this.Valor_grupo_7.TextAlign = HorizontalAlignment.Center;
			this.Valor_grupo_14.AcceptsTab = true;
			global::System.Windows.Forms.Control valor_grupo_9 = this.Valor_grupo_14;
valor_grupo_9.Location = new global::System.Drawing.Point(234, 205);
			this.Valor_grupo_14.Name = "Valor_grupo_14";
			global::System.Windows.Forms.Control valor_grupo_10 = this.Valor_grupo_14;
			Size = new System.Drawing.Size(73, 20);
			valor_grupo_10.Size = this.Size;
			this.Valor_grupo_14.TabIndex = 20;
			this.Valor_grupo_14.TextAlign = HorizontalAlignment.Center;
			this.Valor_grupo_6.AcceptsTab = true;
			global::System.Windows.Forms.Control valor_grupo_11 = this.Valor_grupo_6;
valor_grupo_11.Location = new global::System.Drawing.Point(79, 205);
			this.Valor_grupo_6.Name = "Valor_grupo_6";
			global::System.Windows.Forms.Control valor_grupo_12 = this.Valor_grupo_6;
			Size = new System.Drawing.Size(73, 20);
			valor_grupo_12.Size = this.Size;
			this.Valor_grupo_6.TabIndex = 15;
			this.Valor_grupo_6.TextAlign = HorizontalAlignment.Center;
			this.Valor_grupo_13.AcceptsTab = true;
			global::System.Windows.Forms.Control valor_grupo_13 = this.Valor_grupo_13;
valor_grupo_13.Location = new global::System.Drawing.Point(234, 178);
			this.Valor_grupo_13.Name = "Valor_grupo_13";
			global::System.Windows.Forms.Control valor_grupo_14 = this.Valor_grupo_13;
			Size = new System.Drawing.Size(73, 20);
			valor_grupo_14.Size = this.Size;
			this.Valor_grupo_13.TabIndex = 19;
			this.Valor_grupo_13.TextAlign = HorizontalAlignment.Center;
			this.Valor_grupo_5.AcceptsTab = true;
			global::System.Windows.Forms.Control valor_grupo_15 = this.Valor_grupo_5;
valor_grupo_15.Location = new global::System.Drawing.Point(79, 178);
			this.Valor_grupo_5.Name = "Valor_grupo_5";
			global::System.Windows.Forms.Control valor_grupo_16 = this.Valor_grupo_5;
			Size = new System.Drawing.Size(73, 20);
			valor_grupo_16.Size = this.Size;
			this.Valor_grupo_5.TabIndex = 14;
			this.Valor_grupo_5.TextAlign = HorizontalAlignment.Center;
			this.Valor_grupo_12.AcceptsTab = true;
			global::System.Windows.Forms.Control valor_grupo_17 = this.Valor_grupo_12;
valor_grupo_17.Location = new global::System.Drawing.Point(234, 150);
			this.Valor_grupo_12.Name = "Valor_grupo_12";
			global::System.Windows.Forms.Control valor_grupo_18 = this.Valor_grupo_12;
			Size = new System.Drawing.Size(73, 20);
			valor_grupo_18.Size = this.Size;
			this.Valor_grupo_12.TabIndex = 18;
			this.Valor_grupo_12.TextAlign = HorizontalAlignment.Center;
			this.Valor_grupo_4.AcceptsTab = true;
			global::System.Windows.Forms.Control valor_grupo_19 = this.Valor_grupo_4;
valor_grupo_19.Location = new global::System.Drawing.Point(79, 150);
			this.Valor_grupo_4.Name = "Valor_grupo_4";
			global::System.Windows.Forms.Control valor_grupo_20 = this.Valor_grupo_4;
			Size = new System.Drawing.Size(73, 20);
			valor_grupo_20.Size = this.Size;
			this.Valor_grupo_4.TabIndex = 13;
			this.Valor_grupo_4.TextAlign = HorizontalAlignment.Center;
			this.Valor_grupo_11.AcceptsTab = true;
			global::System.Windows.Forms.Control valor_grupo_21 = this.Valor_grupo_11;
valor_grupo_21.Location = new global::System.Drawing.Point(234, 124);
			this.Valor_grupo_11.Name = "Valor_grupo_11";
			global::System.Windows.Forms.Control valor_grupo_22 = this.Valor_grupo_11;
			Size = new System.Drawing.Size(73, 20);
			valor_grupo_22.Size = this.Size;
			this.Valor_grupo_11.TabIndex = 17;
			this.Valor_grupo_11.TextAlign = HorizontalAlignment.Center;
			this.Valor_grupo_3.AcceptsTab = true;
			global::System.Windows.Forms.Control valor_grupo_23 = this.Valor_grupo_3;
valor_grupo_23.Location = new global::System.Drawing.Point(79, 124);
			this.Valor_grupo_3.Name = "Valor_grupo_3";
			global::System.Windows.Forms.Control valor_grupo_24 = this.Valor_grupo_3;
			Size = new System.Drawing.Size(73, 20);
			valor_grupo_24.Size = this.Size;
			this.Valor_grupo_3.TabIndex = 12;
			this.Valor_grupo_3.TextAlign = HorizontalAlignment.Center;
			this.Valor_grupo_10.AcceptsTab = true;
			global::System.Windows.Forms.Control valor_grupo_25 = this.Valor_grupo_10;
valor_grupo_25.Location = new global::System.Drawing.Point(234, 100);
			this.Valor_grupo_10.Name = "Valor_grupo_10";
			global::System.Windows.Forms.Control valor_grupo_26 = this.Valor_grupo_10;
			Size = new System.Drawing.Size(73, 20);
			valor_grupo_26.Size = this.Size;
			this.Valor_grupo_10.TabIndex = 16;
			this.Valor_grupo_10.TextAlign = HorizontalAlignment.Center;
			this.Valor_grupo_2.AcceptsTab = true;
			global::System.Windows.Forms.Control valor_grupo_27 = this.Valor_grupo_2;
valor_grupo_27.Location = new global::System.Drawing.Point(79, 100);
			this.Valor_grupo_2.Name = "Valor_grupo_2";
			global::System.Windows.Forms.Control valor_grupo_28 = this.Valor_grupo_2;
			Size = new System.Drawing.Size(73, 20);
			valor_grupo_28.Size = this.Size;
			this.Valor_grupo_2.TabIndex = 11;
			this.Valor_grupo_2.TextAlign = HorizontalAlignment.Center;
			this.Valor_grupo_9.AcceptsTab = true;
			global::System.Windows.Forms.Control valor_grupo_29 = this.Valor_grupo_9;
valor_grupo_29.Location = new global::System.Drawing.Point(234, 73);
			this.Valor_grupo_9.Name = "Valor_grupo_9";
			global::System.Windows.Forms.Control valor_grupo_30 = this.Valor_grupo_9;
			Size = new System.Drawing.Size(73, 20);
			valor_grupo_30.Size = this.Size;
			this.Valor_grupo_9.TabIndex = 18;
			this.Valor_grupo_9.TextAlign = HorizontalAlignment.Center;
			this.Valor_grupo_1.AcceptsTab = true;
			global::System.Windows.Forms.Control valor_grupo_31 = this.Valor_grupo_1;
valor_grupo_31.Location = new global::System.Drawing.Point(79, 73);
			this.Valor_grupo_1.Name = "Valor_grupo_1";
			global::System.Windows.Forms.Control valor_grupo_32 = this.Valor_grupo_1;
			Size = new System.Drawing.Size(73, 20);
			valor_grupo_32.Size = this.Size;
			this.Valor_grupo_1.TabIndex = 10;
			this.Valor_grupo_1.TextAlign = HorizontalAlignment.Center;
			this.Label_grupo_16.AutoSize = true;
			global::System.Windows.Forms.Control label_grupo_ = this.Label_grupo_16;
label_grupo_.Location = new global::System.Drawing.Point(179, 262);
			this.Label_grupo_16.Name = "Label_grupo_16";
			global::System.Windows.Forms.Control label_grupo_2 = this.Label_grupo_16;
			Size = new System.Drawing.Size(57, 13);
			label_grupo_2.Size = this.Size;
			this.Label_grupo_16.TabIndex = 1;
			this.Label_grupo_16.Text = "Grupo 16 :";
			this.Label_grupo_8.AutoSize = true;
			global::System.Windows.Forms.Control label_grupo_3 = this.Label_grupo_8;
label_grupo_3.Location = new global::System.Drawing.Point(24, 262);
			this.Label_grupo_8.Name = "Label_grupo_8";
			global::System.Windows.Forms.Control label_grupo_4 = this.Label_grupo_8;
			Size = new System.Drawing.Size(57, 13);
			label_grupo_4.Size = this.Size;
			this.Label_grupo_8.TabIndex = 1;
			this.Label_grupo_8.Text = "Grupo 08 :";
			this.Label_grupo_15.AutoSize = true;
			global::System.Windows.Forms.Control label_grupo_5 = this.Label_grupo_15;
label_grupo_5.Location = new global::System.Drawing.Point(179, 235);
			this.Label_grupo_15.Name = "Label_grupo_15";
			global::System.Windows.Forms.Control label_grupo_6 = this.Label_grupo_15;
			Size = new System.Drawing.Size(57, 13);
			label_grupo_6.Size = this.Size;
			this.Label_grupo_15.TabIndex = 1;
			this.Label_grupo_15.Text = "Grupo 15 :";
			this.Label_grupo_7.AutoSize = true;
			global::System.Windows.Forms.Control label_grupo_7 = this.Label_grupo_7;
label_grupo_7.Location = new global::System.Drawing.Point(24, 235);
			this.Label_grupo_7.Name = "Label_grupo_7";
			global::System.Windows.Forms.Control label_grupo_8 = this.Label_grupo_7;
			Size = new System.Drawing.Size(57, 13);
			label_grupo_8.Size = this.Size;
			this.Label_grupo_7.TabIndex = 1;
			this.Label_grupo_7.Text = "Grupo 07 :";
			this.Label_grupo_14.AutoSize = true;
			global::System.Windows.Forms.Control label_grupo_9 = this.Label_grupo_14;
label_grupo_9.Location = new global::System.Drawing.Point(179, 208);
			this.Label_grupo_14.Name = "Label_grupo_14";
			global::System.Windows.Forms.Control label_grupo_10 = this.Label_grupo_14;
			Size = new System.Drawing.Size(57, 13);
			label_grupo_10.Size = this.Size;
			this.Label_grupo_14.TabIndex = 1;
			this.Label_grupo_14.Text = "Grupo 14 :";
			this.Label_grupo_6.AutoSize = true;
			global::System.Windows.Forms.Control label_grupo_11 = this.Label_grupo_6;
label_grupo_11.Location = new global::System.Drawing.Point(24, 208);
			this.Label_grupo_6.Name = "Label_grupo_6";
			global::System.Windows.Forms.Control label_grupo_12 = this.Label_grupo_6;
			Size = new System.Drawing.Size(57, 13);
			label_grupo_12.Size = this.Size;
			this.Label_grupo_6.TabIndex = 1;
			this.Label_grupo_6.Text = "Grupo 06 :";
			this.Label_grupo_13.AutoSize = true;
			global::System.Windows.Forms.Control label_grupo_13 = this.Label_grupo_13;
label_grupo_13.Location = new global::System.Drawing.Point(179, 181);
			this.Label_grupo_13.Name = "Label_grupo_13";
			global::System.Windows.Forms.Control label_grupo_14 = this.Label_grupo_13;
			Size = new System.Drawing.Size(57, 13);
			label_grupo_14.Size = this.Size;
			this.Label_grupo_13.TabIndex = 1;
			this.Label_grupo_13.Text = "Grupo 13 :";
			this.Label_grupo_5.AutoSize = true;
			global::System.Windows.Forms.Control label_grupo_15 = this.Label_grupo_5;
label_grupo_15.Location = new global::System.Drawing.Point(24, 181);
			this.Label_grupo_5.Name = "Label_grupo_5";
			global::System.Windows.Forms.Control label_grupo_16 = this.Label_grupo_5;
			Size = new System.Drawing.Size(57, 13);
			label_grupo_16.Size = this.Size;
			this.Label_grupo_5.TabIndex = 1;
			this.Label_grupo_5.Text = "Grupo 05 :";
			this.Label_grupo_12.AutoSize = true;
			global::System.Windows.Forms.Control label_grupo_17 = this.Label_grupo_12;
label_grupo_17.Location = new global::System.Drawing.Point(179, 153);
			this.Label_grupo_12.Name = "Label_grupo_12";
			global::System.Windows.Forms.Control label_grupo_18 = this.Label_grupo_12;
			Size = new System.Drawing.Size(57, 13);
			label_grupo_18.Size = this.Size;
			this.Label_grupo_12.TabIndex = 1;
			this.Label_grupo_12.Text = "Grupo 12 :";
			this.Label_grupo_4.AutoSize = true;
			global::System.Windows.Forms.Control label_grupo_19 = this.Label_grupo_4;
label_grupo_19.Location = new global::System.Drawing.Point(24, 153);
			this.Label_grupo_4.Name = "Label_grupo_4";
			global::System.Windows.Forms.Control label_grupo_20 = this.Label_grupo_4;
			Size = new System.Drawing.Size(57, 13);
			label_grupo_20.Size = this.Size;
			this.Label_grupo_4.TabIndex = 1;
			this.Label_grupo_4.Text = "Grupo 04 :";
			this.Label_grupo_11.AutoSize = true;
			global::System.Windows.Forms.Control label_grupo_21 = this.Label_grupo_11;
label_grupo_21.Location = new global::System.Drawing.Point(179, 127);
			this.Label_grupo_11.Name = "Label_grupo_11";
			global::System.Windows.Forms.Control label_grupo_22 = this.Label_grupo_11;
			Size = new System.Drawing.Size(57, 13);
			label_grupo_22.Size = this.Size;
			this.Label_grupo_11.TabIndex = 1;
			this.Label_grupo_11.Text = "Grupo 11 :";
			this.Label_grupo_3.AutoSize = true;
			global::System.Windows.Forms.Control label_grupo_23 = this.Label_grupo_3;
label_grupo_23.Location = new global::System.Drawing.Point(24, 127);
			this.Label_grupo_3.Name = "Label_grupo_3";
			global::System.Windows.Forms.Control label_grupo_24 = this.Label_grupo_3;
			Size = new System.Drawing.Size(57, 13);
			label_grupo_24.Size = this.Size;
			this.Label_grupo_3.TabIndex = 1;
			this.Label_grupo_3.Text = "Grupo 03 :";
			this.Label_grupo_10.AutoSize = true;
			global::System.Windows.Forms.Control label_grupo_25 = this.Label_grupo_10;
label_grupo_25.Location = new global::System.Drawing.Point(179, 103);
			this.Label_grupo_10.Name = "Label_grupo_10";
			global::System.Windows.Forms.Control label_grupo_26 = this.Label_grupo_10;
			Size = new System.Drawing.Size(57, 13);
			label_grupo_26.Size = this.Size;
			this.Label_grupo_10.TabIndex = 1;
			this.Label_grupo_10.Text = "Grupo 10 :";
			this.Label_grupo_2.AutoSize = true;
			global::System.Windows.Forms.Control label_grupo_27 = this.Label_grupo_2;
label_grupo_27.Location = new global::System.Drawing.Point(24, 103);
			this.Label_grupo_2.Name = "Label_grupo_2";
			global::System.Windows.Forms.Control label_grupo_28 = this.Label_grupo_2;
			Size = new System.Drawing.Size(57, 13);
			label_grupo_28.Size = this.Size;
			this.Label_grupo_2.TabIndex = 1;
			this.Label_grupo_2.Text = "Grupo 02 :";
			this.Label_grupo_9.AutoSize = true;
			global::System.Windows.Forms.Control label_grupo_29 = this.Label_grupo_9;
label_grupo_29.Location = new global::System.Drawing.Point(179, 76);
			this.Label_grupo_9.Name = "Label_grupo_9";
			global::System.Windows.Forms.Control label_grupo_30 = this.Label_grupo_9;
			Size = new System.Drawing.Size(57, 13);
			label_grupo_30.Size = this.Size;
			this.Label_grupo_9.TabIndex = 1;
			this.Label_grupo_9.Text = "Grupo 09 :";
			this.Label_grupo_1.AutoSize = true;
			global::System.Windows.Forms.Control label_grupo_31 = this.Label_grupo_1;
label_grupo_31.Location = new global::System.Drawing.Point(24, 76);
			this.Label_grupo_1.Name = "Label_grupo_1";
			global::System.Windows.Forms.Control label_grupo_32 = this.Label_grupo_1;
			Size = new System.Drawing.Size(57, 13);
			label_grupo_32.Size = this.Size;
			this.Label_grupo_1.TabIndex = 1;
			this.Label_grupo_1.Text = "Grupo 01 :";
			global::System.Drawing.SizeF autoScaleDimensions;
			autoScaleDimensions = new global::System.Drawing.SizeF(6f, 13f);
			this.AutoScaleDimensions = autoScaleDimensions;
			this.AutoScaleMode = AutoScaleMode.Font;
			Size = new System.Drawing.Size(361, 524);
			this.ClientSize = Size;
			this.Controls.Add(this.grupo_grupos);
			this.Controls.Add(this.grupo_parametros_gerais);
			this.FormBorderStyle = FormBorderStyle.None;
this.Location = new global::System.Drawing.Point(160, 2);
			this.Name = "Equip_VA210_conf";
			this.StartPosition = global::System.Windows.Forms.FormStartPosition.Manual;
			this.Text = "Equipamento VA 210 - Configuração";
			this.grupo_parametros_gerais.ResumeLayout(false);
			this.grupo_parametros_gerais.PerformLayout();
			this.grupo_grupos.ResumeLayout(false);
			this.grupo_grupos.PerformLayout();
			this.ResumeLayout(false);
		}

		// Token: 0x04001A10 RID: 6672
		private global::System.ComponentModel.IContainer components;
	}
}
