using System.Drawing;
using System.Windows.Forms;
﻿namespace iS800
{
	// Token: 0x0200009F RID: 159
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class Equip_VA230_conf : global::System.Windows.Forms.Form
	{
		// Token: 0x060026E7 RID: 9959 RVA: 0x0041FEA0 File Offset: 0x0041E2A0
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			if (disposing && this.components != null)
			{
				this.components.Dispose();
			}
			base.Dispose(disposing);
		}

		// Token: 0x060026E8 RID: 9960 RVA: 0x0041FEC0 File Offset: 0x0041E2C0
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.grupo_parametros_gerais = new global::System.Windows.Forms.GroupBox();
			this.Valor_intervalo_varredura = new global::System.Windows.Forms.TextBox();
			this.Label_intervalo_varredura = new global::System.Windows.Forms.Label();
			this.Valor_end_origem = new global::System.Windows.Forms.TextBox();
			this.Valor_numero_recalques = new global::System.Windows.Forms.TextBox();
			this.Label_end_origem = new global::System.Windows.Forms.Label();
			this.Label_numero_recalques = new global::System.Windows.Forms.Label();
			this.Grupo_ctrl = new global::System.Windows.Forms.GroupBox();
			this.Esc_conf_md_201 = new global::System.Windows.Forms.Button();
			this.Box_Msg = new global::System.Windows.Forms.TextBox();
			this.Ler_conf_md_201 = new global::System.Windows.Forms.Button();
			this.grupo_escalas = new global::System.Windows.Forms.GroupBox();
			this.Label_end_estacao = new global::System.Windows.Forms.Label();
			this.VScroll_end_estacao = new global::System.Windows.Forms.VScrollBar();
			this.Valor_end_estacao = new global::System.Windows.Forms.TextBox();
			this.Valor_escala_canal_15 = new global::System.Windows.Forms.TextBox();
			this.Valor_escala_canal_7 = new global::System.Windows.Forms.TextBox();
			this.Valor_escala_canal_14 = new global::System.Windows.Forms.TextBox();
			this.Valor_escala_canal_6 = new global::System.Windows.Forms.TextBox();
			this.Valor_escala_canal_13 = new global::System.Windows.Forms.TextBox();
			this.Valor_escala_canal_5 = new global::System.Windows.Forms.TextBox();
			this.Valor_escala_canal_12 = new global::System.Windows.Forms.TextBox();
			this.Valor_escala_canal_4 = new global::System.Windows.Forms.TextBox();
			this.Valor_escala_canal_11 = new global::System.Windows.Forms.TextBox();
			this.Valor_escala_canal_3 = new global::System.Windows.Forms.TextBox();
			this.Valor_escala_canal_10 = new global::System.Windows.Forms.TextBox();
			this.Valor_escala_canal_2 = new global::System.Windows.Forms.TextBox();
			this.Valor_escala_canal_9 = new global::System.Windows.Forms.TextBox();
			this.Valor_escala_canal_1 = new global::System.Windows.Forms.TextBox();
			this.Valor_escala_canal_8 = new global::System.Windows.Forms.TextBox();
			this.Valor_escala_canal_0 = new global::System.Windows.Forms.TextBox();
			this.Label_escala_canal_15 = new global::System.Windows.Forms.Label();
			this.Label_escala_canal_7 = new global::System.Windows.Forms.Label();
			this.Label_escala_canal_14 = new global::System.Windows.Forms.Label();
			this.Label_escala_canal_6 = new global::System.Windows.Forms.Label();
			this.Label_escala_canal_13 = new global::System.Windows.Forms.Label();
			this.Label_escala_canal_5 = new global::System.Windows.Forms.Label();
			this.Label_escala_canal_12 = new global::System.Windows.Forms.Label();
			this.Label_escala_canal_4 = new global::System.Windows.Forms.Label();
			this.Label_escala_canal_11 = new global::System.Windows.Forms.Label();
			this.Label_escala_canal_3 = new global::System.Windows.Forms.Label();
			this.Label_escala_canal_10 = new global::System.Windows.Forms.Label();
			this.Label_escala_canal_2 = new global::System.Windows.Forms.Label();
			this.Label_escala_canal_9 = new global::System.Windows.Forms.Label();
			this.Label_escala_canal_1 = new global::System.Windows.Forms.Label();
			this.Label_escala_canal_8 = new global::System.Windows.Forms.Label();
			this.Label_escala_canal_0 = new global::System.Windows.Forms.Label();
			this.grupo_parametros_gerais.SuspendLayout();
			this.Grupo_ctrl.SuspendLayout();
			this.grupo_escalas.SuspendLayout();
			this.SuspendLayout();
			this.grupo_parametros_gerais.Controls.Add(this.Valor_intervalo_varredura);
			this.grupo_parametros_gerais.Controls.Add(this.Label_intervalo_varredura);
			this.grupo_parametros_gerais.Controls.Add(this.Valor_end_origem);
			this.grupo_parametros_gerais.Controls.Add(this.Valor_numero_recalques);
			this.grupo_parametros_gerais.Controls.Add(this.Label_end_origem);
			this.grupo_parametros_gerais.Controls.Add(this.Label_numero_recalques);
			global::System.Windows.Forms.Control grupo_parametros_gerais = this.grupo_parametros_gerais;
			grupo_parametros_gerais.Location = new global::System.Drawing.Point(12, 12);
			this.grupo_parametros_gerais.Name = "grupo_parametros_gerais";
			global::System.Windows.Forms.Control grupo_parametros_gerais2 = this.grupo_parametros_gerais;
			grupo_parametros_gerais2.Size = new global::System.Drawing.Size(335, 125);
			this.grupo_parametros_gerais.TabIndex = 1;
			this.grupo_parametros_gerais.TabStop = false;
			this.grupo_parametros_gerais.Text = "Parâmetros gerais";
			global::System.Windows.Forms.Control valor_intervalo_varredura = this.Valor_intervalo_varredura;
valor_intervalo_varredura.Location = new global::System.Drawing.Point(243, 78);
			this.Valor_intervalo_varredura.Name = "Valor_intervalo_varredura";
			global::System.Windows.Forms.Control valor_intervalo_varredura2 = this.Valor_intervalo_varredura;
			Size = new System.Drawing.Size(74, 20);
			valor_intervalo_varredura2.Size = this.Size;
			this.Valor_intervalo_varredura.TabIndex = 4;
			this.Valor_intervalo_varredura.TextAlign = HorizontalAlignment.Center;
			this.Label_intervalo_varredura.AutoSize = true;
			global::System.Windows.Forms.Control label_intervalo_varredura = this.Label_intervalo_varredura;
label_intervalo_varredura.Location = new global::System.Drawing.Point(24, 82);
			this.Label_intervalo_varredura.Name = "Label_intervalo_varredura";
			global::System.Windows.Forms.Control label_intervalo_varredura2 = this.Label_intervalo_varredura;
			Size = new System.Drawing.Size(128, 13);
			label_intervalo_varredura2.Size = this.Size;
			this.Label_intervalo_varredura.TabIndex = 4;
			this.Label_intervalo_varredura.Text = "Intervalo de varredura (s):";
			global::System.Windows.Forms.Control valor_end_origem = this.Valor_end_origem;
valor_end_origem.Location = new global::System.Drawing.Point(244, 26);
			this.Valor_end_origem.Name = "Valor_end_origem";
			global::System.Windows.Forms.Control valor_end_origem2 = this.Valor_end_origem;
			Size = new System.Drawing.Size(73, 20);
			valor_end_origem2.Size = this.Size;
			this.Valor_end_origem.TabIndex = 2;
			this.Valor_end_origem.TextAlign = HorizontalAlignment.Center;
			global::System.Windows.Forms.Control valor_numero_recalques = this.Valor_numero_recalques;
valor_numero_recalques.Location = new global::System.Drawing.Point(243, 52);
			this.Valor_numero_recalques.Name = "Valor_numero_recalques";
			global::System.Windows.Forms.Control valor_numero_recalques2 = this.Valor_numero_recalques;
			Size = new System.Drawing.Size(74, 20);
			valor_numero_recalques2.Size = this.Size;
			this.Valor_numero_recalques.TabIndex = 3;
			this.Valor_numero_recalques.TextAlign = HorizontalAlignment.Center;
			this.Label_end_origem.AutoSize = true;
			global::System.Windows.Forms.Control label_end_origem = this.Label_end_origem;
label_end_origem.Location = new global::System.Drawing.Point(24, 30);
			this.Label_end_origem.Name = "Label_end_origem";
			global::System.Windows.Forms.Control label_end_origem2 = this.Label_end_origem;
			Size = new System.Drawing.Size(108, 13);
			label_end_origem2.Size = this.Size;
			this.Label_end_origem.TabIndex = 1;
			this.Label_end_origem.Text = "Endereço de origem :";
			this.Label_numero_recalques.AutoSize = true;
			global::System.Windows.Forms.Control label_numero_recalques = this.Label_numero_recalques;
label_numero_recalques.Location = new global::System.Drawing.Point(24, 56);
			this.Label_numero_recalques.Name = "Label_numero_recalques";
			global::System.Windows.Forms.Control label_numero_recalques2 = this.Label_numero_recalques;
			Size = new System.Drawing.Size(162, 13);
			label_numero_recalques2.Size = this.Size;
			this.Label_numero_recalques.TabIndex = 0;
			this.Label_numero_recalques.Text = "Número de estação de recalque:";
			this.Grupo_ctrl.Controls.Add(this.Esc_conf_md_201);
			this.Grupo_ctrl.Controls.Add(this.Box_Msg);
			this.Grupo_ctrl.Controls.Add(this.Ler_conf_md_201);
			global::System.Windows.Forms.Control grupo_ctrl = this.Grupo_ctrl;
grupo_ctrl.Location = new global::System.Drawing.Point(12, 443);
			this.Grupo_ctrl.Name = "Grupo_ctrl";
			global::System.Windows.Forms.Control grupo_ctrl2 = this.Grupo_ctrl;
			Size = new System.Drawing.Size(335, 105);
			grupo_ctrl2.Size = this.Size;
			this.Grupo_ctrl.TabIndex = 23;
			this.Grupo_ctrl.TabStop = false;
			this.Grupo_ctrl.Text = "Comandos e Status";
			global::System.Windows.Forms.Control esc_conf_md_ = this.Esc_conf_md_201;
esc_conf_md_.Location = new global::System.Drawing.Point(194, 61);
			this.Esc_conf_md_201.Name = "Esc_conf_md_201";
			global::System.Windows.Forms.Control esc_conf_md_2 = this.Esc_conf_md_201;
			Size = new System.Drawing.Size(109, 28);
			esc_conf_md_2.Size = this.Size;
			this.Esc_conf_md_201.TabIndex = 25;
			this.Esc_conf_md_201.Text = "Salvar config.";
			this.Esc_conf_md_201.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control box_Msg = this.Box_Msg;
box_Msg.Location = new global::System.Drawing.Point(24, 29);
			this.Box_Msg.Name = "Box_Msg";
			global::System.Windows.Forms.Control box_Msg2 = this.Box_Msg;
			Size = new System.Drawing.Size(293, 20);
			box_Msg2.Size = this.Size;
			this.Box_Msg.TabIndex = 5;
			this.Box_Msg.TabStop = false;
			this.Box_Msg.TextAlign = HorizontalAlignment.Right;
			global::System.Windows.Forms.Control ler_conf_md_ = this.Ler_conf_md_201;
ler_conf_md_.Location = new global::System.Drawing.Point(41, 61);
			this.Ler_conf_md_201.Name = "Ler_conf_md_201";
			global::System.Windows.Forms.Control ler_conf_md_2 = this.Ler_conf_md_201;
			Size = new System.Drawing.Size(109, 28);
			ler_conf_md_2.Size = this.Size;
			this.Ler_conf_md_201.TabIndex = 24;
			this.Ler_conf_md_201.Text = "Ler configuração";
			this.Ler_conf_md_201.UseVisualStyleBackColor = true;
			this.grupo_escalas.Controls.Add(this.Label_end_estacao);
			this.grupo_escalas.Controls.Add(this.VScroll_end_estacao);
			this.grupo_escalas.Controls.Add(this.Valor_end_estacao);
			this.grupo_escalas.Controls.Add(this.Valor_escala_canal_15);
			this.grupo_escalas.Controls.Add(this.Valor_escala_canal_7);
			this.grupo_escalas.Controls.Add(this.Valor_escala_canal_14);
			this.grupo_escalas.Controls.Add(this.Valor_escala_canal_6);
			this.grupo_escalas.Controls.Add(this.Valor_escala_canal_13);
			this.grupo_escalas.Controls.Add(this.Valor_escala_canal_5);
			this.grupo_escalas.Controls.Add(this.Valor_escala_canal_12);
			this.grupo_escalas.Controls.Add(this.Valor_escala_canal_4);
			this.grupo_escalas.Controls.Add(this.Valor_escala_canal_11);
			this.grupo_escalas.Controls.Add(this.Valor_escala_canal_3);
			this.grupo_escalas.Controls.Add(this.Valor_escala_canal_10);
			this.grupo_escalas.Controls.Add(this.Valor_escala_canal_2);
			this.grupo_escalas.Controls.Add(this.Valor_escala_canal_9);
			this.grupo_escalas.Controls.Add(this.Valor_escala_canal_1);
			this.grupo_escalas.Controls.Add(this.Valor_escala_canal_8);
			this.grupo_escalas.Controls.Add(this.Valor_escala_canal_0);
			this.grupo_escalas.Controls.Add(this.Label_escala_canal_15);
			this.grupo_escalas.Controls.Add(this.Label_escala_canal_7);
			this.grupo_escalas.Controls.Add(this.Label_escala_canal_14);
			this.grupo_escalas.Controls.Add(this.Label_escala_canal_6);
			this.grupo_escalas.Controls.Add(this.Label_escala_canal_13);
			this.grupo_escalas.Controls.Add(this.Label_escala_canal_5);
			this.grupo_escalas.Controls.Add(this.Label_escala_canal_12);
			this.grupo_escalas.Controls.Add(this.Label_escala_canal_4);
			this.grupo_escalas.Controls.Add(this.Label_escala_canal_11);
			this.grupo_escalas.Controls.Add(this.Label_escala_canal_3);
			this.grupo_escalas.Controls.Add(this.Label_escala_canal_10);
			this.grupo_escalas.Controls.Add(this.Label_escala_canal_2);
			this.grupo_escalas.Controls.Add(this.Label_escala_canal_9);
			this.grupo_escalas.Controls.Add(this.Label_escala_canal_1);
			this.grupo_escalas.Controls.Add(this.Label_escala_canal_8);
			this.grupo_escalas.Controls.Add(this.Label_escala_canal_0);
			global::System.Windows.Forms.Control grupo_escalas = this.grupo_escalas;
grupo_escalas.Location = new global::System.Drawing.Point(12, 143);
			this.grupo_escalas.Name = "grupo_escalas";
			global::System.Windows.Forms.Control grupo_escalas2 = this.grupo_escalas;
			Size = new System.Drawing.Size(335, 294);
			grupo_escalas2.Size = this.Size;
			this.grupo_escalas.TabIndex = 5;
			this.grupo_escalas.TabStop = false;
			this.grupo_escalas.Text = "Configuração dos Fundos de Escala";
			this.Label_end_estacao.AutoSize = true;
			global::System.Windows.Forms.Control label_end_estacao = this.Label_end_estacao;
label_end_estacao.Location = new global::System.Drawing.Point(24, 35);
			this.Label_end_estacao.Name = "Label_end_estacao";
			global::System.Windows.Forms.Control label_end_estacao2 = this.Label_end_estacao;
			Size = new System.Drawing.Size(135, 13);
			label_end_estacao2.Size = this.Size;
			this.Label_end_estacao.TabIndex = 9;
			this.Label_end_estacao.Text = "End. estação de recalque :";
			this.VScroll_end_estacao.LargeChange = 1;
			global::System.Windows.Forms.Control vscroll_end_estacao = this.VScroll_end_estacao;
vscroll_end_estacao.Location = new global::System.Drawing.Point(232, 32);
			this.VScroll_end_estacao.Name = "VScroll_end_estacao";
			global::System.Windows.Forms.Control vscroll_end_estacao2 = this.VScroll_end_estacao;
			Size = new System.Drawing.Size(26, 21);
			vscroll_end_estacao2.Size = this.Size;
			this.VScroll_end_estacao.TabIndex = 8;
			global::System.Windows.Forms.Control valor_end_estacao = this.Valor_end_estacao;
valor_end_estacao.Location = new global::System.Drawing.Point(165, 32);
			this.Valor_end_estacao.Name = "Valor_end_estacao";
			global::System.Windows.Forms.Control valor_end_estacao2 = this.Valor_end_estacao;
			Size = new System.Drawing.Size(66, 20);
			valor_end_estacao2.Size = this.Size;
			this.Valor_end_estacao.TabIndex = 6;
			this.Valor_end_estacao.TextAlign = HorizontalAlignment.Center;
			this.Valor_escala_canal_15.AcceptsTab = true;
			global::System.Windows.Forms.Control valor_escala_canal_ = this.Valor_escala_canal_15;
valor_escala_canal_.Location = new global::System.Drawing.Point(234, 259);
			this.Valor_escala_canal_15.Name = "Valor_escala_canal_15";
			global::System.Windows.Forms.Control valor_escala_canal_2 = this.Valor_escala_canal_15;
			Size = new System.Drawing.Size(73, 20);
			valor_escala_canal_2.Size = this.Size;
			this.Valor_escala_canal_15.TabIndex = 22;
			this.Valor_escala_canal_15.TextAlign = HorizontalAlignment.Center;
			this.Valor_escala_canal_7.AcceptsTab = true;
			global::System.Windows.Forms.Control valor_escala_canal_3 = this.Valor_escala_canal_7;
valor_escala_canal_3.Location = new global::System.Drawing.Point(79, 259);
			this.Valor_escala_canal_7.Name = "Valor_escala_canal_7";
			global::System.Windows.Forms.Control valor_escala_canal_4 = this.Valor_escala_canal_7;
			Size = new System.Drawing.Size(73, 20);
			valor_escala_canal_4.Size = this.Size;
			this.Valor_escala_canal_7.TabIndex = 14;
			this.Valor_escala_canal_7.TextAlign = HorizontalAlignment.Center;
			this.Valor_escala_canal_14.AcceptsTab = true;
			global::System.Windows.Forms.Control valor_escala_canal_5 = this.Valor_escala_canal_14;
valor_escala_canal_5.Location = new global::System.Drawing.Point(234, 232);
			this.Valor_escala_canal_14.Name = "Valor_escala_canal_14";
			global::System.Windows.Forms.Control valor_escala_canal_6 = this.Valor_escala_canal_14;
			Size = new System.Drawing.Size(73, 20);
			valor_escala_canal_6.Size = this.Size;
			this.Valor_escala_canal_14.TabIndex = 21;
			this.Valor_escala_canal_14.TextAlign = HorizontalAlignment.Center;
			this.Valor_escala_canal_6.AcceptsTab = true;
			global::System.Windows.Forms.Control valor_escala_canal_7 = this.Valor_escala_canal_6;
valor_escala_canal_7.Location = new global::System.Drawing.Point(79, 232);
			this.Valor_escala_canal_6.Name = "Valor_escala_canal_6";
			global::System.Windows.Forms.Control valor_escala_canal_8 = this.Valor_escala_canal_6;
			Size = new System.Drawing.Size(73, 20);
			valor_escala_canal_8.Size = this.Size;
			this.Valor_escala_canal_6.TabIndex = 13;
			this.Valor_escala_canal_6.TextAlign = HorizontalAlignment.Center;
			this.Valor_escala_canal_13.AcceptsTab = true;
			global::System.Windows.Forms.Control valor_escala_canal_9 = this.Valor_escala_canal_13;
valor_escala_canal_9.Location = new global::System.Drawing.Point(234, 205);
			this.Valor_escala_canal_13.Name = "Valor_escala_canal_13";
			global::System.Windows.Forms.Control valor_escala_canal_10 = this.Valor_escala_canal_13;
			Size = new System.Drawing.Size(73, 20);
			valor_escala_canal_10.Size = this.Size;
			this.Valor_escala_canal_13.TabIndex = 20;
			this.Valor_escala_canal_13.TextAlign = HorizontalAlignment.Center;
			this.Valor_escala_canal_5.AcceptsTab = true;
			global::System.Windows.Forms.Control valor_escala_canal_11 = this.Valor_escala_canal_5;
valor_escala_canal_11.Location = new global::System.Drawing.Point(79, 205);
			this.Valor_escala_canal_5.Name = "Valor_escala_canal_5";
			global::System.Windows.Forms.Control valor_escala_canal_12 = this.Valor_escala_canal_5;
			Size = new System.Drawing.Size(73, 20);
			valor_escala_canal_12.Size = this.Size;
			this.Valor_escala_canal_5.TabIndex = 12;
			this.Valor_escala_canal_5.TextAlign = HorizontalAlignment.Center;
			this.Valor_escala_canal_12.AcceptsTab = true;
			global::System.Windows.Forms.Control valor_escala_canal_13 = this.Valor_escala_canal_12;
valor_escala_canal_13.Location = new global::System.Drawing.Point(234, 178);
			this.Valor_escala_canal_12.Name = "Valor_escala_canal_12";
			global::System.Windows.Forms.Control valor_escala_canal_14 = this.Valor_escala_canal_12;
			Size = new System.Drawing.Size(73, 20);
			valor_escala_canal_14.Size = this.Size;
			this.Valor_escala_canal_12.TabIndex = 19;
			this.Valor_escala_canal_12.TextAlign = HorizontalAlignment.Center;
			this.Valor_escala_canal_4.AcceptsTab = true;
			global::System.Windows.Forms.Control valor_escala_canal_15 = this.Valor_escala_canal_4;
valor_escala_canal_15.Location = new global::System.Drawing.Point(79, 178);
			this.Valor_escala_canal_4.Name = "Valor_escala_canal_4";
			global::System.Windows.Forms.Control valor_escala_canal_16 = this.Valor_escala_canal_4;
			Size = new System.Drawing.Size(73, 20);
			valor_escala_canal_16.Size = this.Size;
			this.Valor_escala_canal_4.TabIndex = 11;
			this.Valor_escala_canal_4.TextAlign = HorizontalAlignment.Center;
			this.Valor_escala_canal_11.AcceptsTab = true;
			global::System.Windows.Forms.Control valor_escala_canal_17 = this.Valor_escala_canal_11;
valor_escala_canal_17.Location = new global::System.Drawing.Point(234, 150);
			this.Valor_escala_canal_11.Name = "Valor_escala_canal_11";
			global::System.Windows.Forms.Control valor_escala_canal_18 = this.Valor_escala_canal_11;
			Size = new System.Drawing.Size(73, 20);
			valor_escala_canal_18.Size = this.Size;
			this.Valor_escala_canal_11.TabIndex = 18;
			this.Valor_escala_canal_11.TextAlign = HorizontalAlignment.Center;
			this.Valor_escala_canal_3.AcceptsTab = true;
			global::System.Windows.Forms.Control valor_escala_canal_19 = this.Valor_escala_canal_3;
valor_escala_canal_19.Location = new global::System.Drawing.Point(79, 150);
			this.Valor_escala_canal_3.Name = "Valor_escala_canal_3";
			global::System.Windows.Forms.Control valor_escala_canal_20 = this.Valor_escala_canal_3;
			Size = new System.Drawing.Size(73, 20);
			valor_escala_canal_20.Size = this.Size;
			this.Valor_escala_canal_3.TabIndex = 10;
			this.Valor_escala_canal_3.TextAlign = HorizontalAlignment.Center;
			this.Valor_escala_canal_10.AcceptsTab = true;
			global::System.Windows.Forms.Control valor_escala_canal_21 = this.Valor_escala_canal_10;
valor_escala_canal_21.Location = new global::System.Drawing.Point(234, 124);
			this.Valor_escala_canal_10.Name = "Valor_escala_canal_10";
			global::System.Windows.Forms.Control valor_escala_canal_22 = this.Valor_escala_canal_10;
			Size = new System.Drawing.Size(73, 20);
			valor_escala_canal_22.Size = this.Size;
			this.Valor_escala_canal_10.TabIndex = 17;
			this.Valor_escala_canal_10.TextAlign = HorizontalAlignment.Center;
			this.Valor_escala_canal_2.AcceptsTab = true;
			global::System.Windows.Forms.Control valor_escala_canal_23 = this.Valor_escala_canal_2;
valor_escala_canal_23.Location = new global::System.Drawing.Point(79, 124);
			this.Valor_escala_canal_2.Name = "Valor_escala_canal_2";
			global::System.Windows.Forms.Control valor_escala_canal_24 = this.Valor_escala_canal_2;
			Size = new System.Drawing.Size(73, 20);
			valor_escala_canal_24.Size = this.Size;
			this.Valor_escala_canal_2.TabIndex = 9;
			this.Valor_escala_canal_2.TextAlign = HorizontalAlignment.Center;
			this.Valor_escala_canal_9.AcceptsTab = true;
			global::System.Windows.Forms.Control valor_escala_canal_25 = this.Valor_escala_canal_9;
valor_escala_canal_25.Location = new global::System.Drawing.Point(234, 100);
			this.Valor_escala_canal_9.Name = "Valor_escala_canal_9";
			global::System.Windows.Forms.Control valor_escala_canal_26 = this.Valor_escala_canal_9;
			Size = new System.Drawing.Size(73, 20);
			valor_escala_canal_26.Size = this.Size;
			this.Valor_escala_canal_9.TabIndex = 16;
			this.Valor_escala_canal_9.TextAlign = HorizontalAlignment.Center;
			this.Valor_escala_canal_1.AcceptsTab = true;
			global::System.Windows.Forms.Control valor_escala_canal_27 = this.Valor_escala_canal_1;
valor_escala_canal_27.Location = new global::System.Drawing.Point(79, 100);
			this.Valor_escala_canal_1.Name = "Valor_escala_canal_1";
			global::System.Windows.Forms.Control valor_escala_canal_28 = this.Valor_escala_canal_1;
			Size = new System.Drawing.Size(73, 20);
			valor_escala_canal_28.Size = this.Size;
			this.Valor_escala_canal_1.TabIndex = 8;
			this.Valor_escala_canal_1.TextAlign = HorizontalAlignment.Center;
			this.Valor_escala_canal_8.AcceptsTab = true;
			global::System.Windows.Forms.Control valor_escala_canal_29 = this.Valor_escala_canal_8;
valor_escala_canal_29.Location = new global::System.Drawing.Point(234, 73);
			this.Valor_escala_canal_8.Name = "Valor_escala_canal_8";
			global::System.Windows.Forms.Control valor_escala_canal_30 = this.Valor_escala_canal_8;
			Size = new System.Drawing.Size(73, 20);
			valor_escala_canal_30.Size = this.Size;
			this.Valor_escala_canal_8.TabIndex = 15;
			this.Valor_escala_canal_8.TextAlign = HorizontalAlignment.Center;
			this.Valor_escala_canal_0.AcceptsTab = true;
			global::System.Windows.Forms.Control valor_escala_canal_31 = this.Valor_escala_canal_0;
valor_escala_canal_31.Location = new global::System.Drawing.Point(79, 73);
			this.Valor_escala_canal_0.Name = "Valor_escala_canal_0";
			global::System.Windows.Forms.Control valor_escala_canal_32 = this.Valor_escala_canal_0;
			Size = new System.Drawing.Size(73, 20);
			valor_escala_canal_32.Size = this.Size;
			this.Valor_escala_canal_0.TabIndex = 7;
			this.Valor_escala_canal_0.TextAlign = HorizontalAlignment.Center;
			this.Label_escala_canal_15.AutoSize = true;
			global::System.Windows.Forms.Control label_escala_canal_ = this.Label_escala_canal_15;
label_escala_canal_.Location = new global::System.Drawing.Point(179, 262);
			this.Label_escala_canal_15.Name = "Label_escala_canal_15";
			global::System.Windows.Forms.Control label_escala_canal_2 = this.Label_escala_canal_15;
			Size = new System.Drawing.Size(55, 13);
			label_escala_canal_2.Size = this.Size;
			this.Label_escala_canal_15.TabIndex = 1;
			this.Label_escala_canal_15.Text = "Canal 15 :";
			this.Label_escala_canal_7.AutoSize = true;
			global::System.Windows.Forms.Control label_escala_canal_3 = this.Label_escala_canal_7;
label_escala_canal_3.Location = new global::System.Drawing.Point(24, 262);
			this.Label_escala_canal_7.Name = "Label_escala_canal_7";
			global::System.Windows.Forms.Control label_escala_canal_4 = this.Label_escala_canal_7;
			Size = new System.Drawing.Size(55, 13);
			label_escala_canal_4.Size = this.Size;
			this.Label_escala_canal_7.TabIndex = 1;
			this.Label_escala_canal_7.Text = "Canal 07 :";
			this.Label_escala_canal_14.AutoSize = true;
			global::System.Windows.Forms.Control label_escala_canal_5 = this.Label_escala_canal_14;
label_escala_canal_5.Location = new global::System.Drawing.Point(179, 235);
			this.Label_escala_canal_14.Name = "Label_escala_canal_14";
			global::System.Windows.Forms.Control label_escala_canal_6 = this.Label_escala_canal_14;
			Size = new System.Drawing.Size(55, 13);
			label_escala_canal_6.Size = this.Size;
			this.Label_escala_canal_14.TabIndex = 1;
			this.Label_escala_canal_14.Text = "Canal 14 :";
			this.Label_escala_canal_6.AutoSize = true;
			global::System.Windows.Forms.Control label_escala_canal_7 = this.Label_escala_canal_6;
label_escala_canal_7.Location = new global::System.Drawing.Point(24, 235);
			this.Label_escala_canal_6.Name = "Label_escala_canal_6";
			global::System.Windows.Forms.Control label_escala_canal_8 = this.Label_escala_canal_6;
			Size = new System.Drawing.Size(55, 13);
			label_escala_canal_8.Size = this.Size;
			this.Label_escala_canal_6.TabIndex = 1;
			this.Label_escala_canal_6.Text = "Canal 06 :";
			this.Label_escala_canal_13.AutoSize = true;
			global::System.Windows.Forms.Control label_escala_canal_9 = this.Label_escala_canal_13;
label_escala_canal_9.Location = new global::System.Drawing.Point(179, 208);
			this.Label_escala_canal_13.Name = "Label_escala_canal_13";
			global::System.Windows.Forms.Control label_escala_canal_10 = this.Label_escala_canal_13;
			Size = new System.Drawing.Size(55, 13);
			label_escala_canal_10.Size = this.Size;
			this.Label_escala_canal_13.TabIndex = 1;
			this.Label_escala_canal_13.Text = "Canal 13 :";
			this.Label_escala_canal_5.AutoSize = true;
			global::System.Windows.Forms.Control label_escala_canal_11 = this.Label_escala_canal_5;
label_escala_canal_11.Location = new global::System.Drawing.Point(24, 208);
			this.Label_escala_canal_5.Name = "Label_escala_canal_5";
			global::System.Windows.Forms.Control label_escala_canal_12 = this.Label_escala_canal_5;
			Size = new System.Drawing.Size(55, 13);
			label_escala_canal_12.Size = this.Size;
			this.Label_escala_canal_5.TabIndex = 1;
			this.Label_escala_canal_5.Text = "Canal 05 :";
			this.Label_escala_canal_12.AutoSize = true;
			global::System.Windows.Forms.Control label_escala_canal_13 = this.Label_escala_canal_12;
label_escala_canal_13.Location = new global::System.Drawing.Point(179, 181);
			this.Label_escala_canal_12.Name = "Label_escala_canal_12";
			global::System.Windows.Forms.Control label_escala_canal_14 = this.Label_escala_canal_12;
			Size = new System.Drawing.Size(55, 13);
			label_escala_canal_14.Size = this.Size;
			this.Label_escala_canal_12.TabIndex = 1;
			this.Label_escala_canal_12.Text = "Canal 12 :";
			this.Label_escala_canal_4.AutoSize = true;
			global::System.Windows.Forms.Control label_escala_canal_15 = this.Label_escala_canal_4;
label_escala_canal_15.Location = new global::System.Drawing.Point(24, 181);
			this.Label_escala_canal_4.Name = "Label_escala_canal_4";
			global::System.Windows.Forms.Control label_escala_canal_16 = this.Label_escala_canal_4;
			Size = new System.Drawing.Size(55, 13);
			label_escala_canal_16.Size = this.Size;
			this.Label_escala_canal_4.TabIndex = 1;
			this.Label_escala_canal_4.Text = "Canal 04 :";
			this.Label_escala_canal_11.AutoSize = true;
			global::System.Windows.Forms.Control label_escala_canal_17 = this.Label_escala_canal_11;
label_escala_canal_17.Location = new global::System.Drawing.Point(179, 153);
			this.Label_escala_canal_11.Name = "Label_escala_canal_11";
			global::System.Windows.Forms.Control label_escala_canal_18 = this.Label_escala_canal_11;
			Size = new System.Drawing.Size(55, 13);
			label_escala_canal_18.Size = this.Size;
			this.Label_escala_canal_11.TabIndex = 1;
			this.Label_escala_canal_11.Text = "Canal 11 :";
			this.Label_escala_canal_3.AutoSize = true;
			global::System.Windows.Forms.Control label_escala_canal_19 = this.Label_escala_canal_3;
label_escala_canal_19.Location = new global::System.Drawing.Point(24, 153);
			this.Label_escala_canal_3.Name = "Label_escala_canal_3";
			global::System.Windows.Forms.Control label_escala_canal_20 = this.Label_escala_canal_3;
			Size = new System.Drawing.Size(55, 13);
			label_escala_canal_20.Size = this.Size;
			this.Label_escala_canal_3.TabIndex = 1;
			this.Label_escala_canal_3.Text = "Canal 03 :";
			this.Label_escala_canal_10.AutoSize = true;
			global::System.Windows.Forms.Control label_escala_canal_21 = this.Label_escala_canal_10;
label_escala_canal_21.Location = new global::System.Drawing.Point(179, 127);
			this.Label_escala_canal_10.Name = "Label_escala_canal_10";
			global::System.Windows.Forms.Control label_escala_canal_22 = this.Label_escala_canal_10;
			Size = new System.Drawing.Size(55, 13);
			label_escala_canal_22.Size = this.Size;
			this.Label_escala_canal_10.TabIndex = 1;
			this.Label_escala_canal_10.Text = "Canal 10 :";
			this.Label_escala_canal_2.AutoSize = true;
			global::System.Windows.Forms.Control label_escala_canal_23 = this.Label_escala_canal_2;
label_escala_canal_23.Location = new global::System.Drawing.Point(24, 127);
			this.Label_escala_canal_2.Name = "Label_escala_canal_2";
			global::System.Windows.Forms.Control label_escala_canal_24 = this.Label_escala_canal_2;
			Size = new System.Drawing.Size(55, 13);
			label_escala_canal_24.Size = this.Size;
			this.Label_escala_canal_2.TabIndex = 1;
			this.Label_escala_canal_2.Text = "Canal 02 :";
			this.Label_escala_canal_9.AutoSize = true;
			global::System.Windows.Forms.Control label_escala_canal_25 = this.Label_escala_canal_9;
label_escala_canal_25.Location = new global::System.Drawing.Point(179, 103);
			this.Label_escala_canal_9.Name = "Label_escala_canal_9";
			global::System.Windows.Forms.Control label_escala_canal_26 = this.Label_escala_canal_9;
			Size = new System.Drawing.Size(55, 13);
			label_escala_canal_26.Size = this.Size;
			this.Label_escala_canal_9.TabIndex = 1;
			this.Label_escala_canal_9.Text = "Canal 09 :";
			this.Label_escala_canal_1.AutoSize = true;
			global::System.Windows.Forms.Control label_escala_canal_27 = this.Label_escala_canal_1;
label_escala_canal_27.Location = new global::System.Drawing.Point(24, 103);
			this.Label_escala_canal_1.Name = "Label_escala_canal_1";
			global::System.Windows.Forms.Control label_escala_canal_28 = this.Label_escala_canal_1;
			Size = new System.Drawing.Size(55, 13);
			label_escala_canal_28.Size = this.Size;
			this.Label_escala_canal_1.TabIndex = 1;
			this.Label_escala_canal_1.Text = "Canal 01 :";
			this.Label_escala_canal_8.AutoSize = true;
			global::System.Windows.Forms.Control label_escala_canal_29 = this.Label_escala_canal_8;
label_escala_canal_29.Location = new global::System.Drawing.Point(179, 76);
			this.Label_escala_canal_8.Name = "Label_escala_canal_8";
			global::System.Windows.Forms.Control label_escala_canal_30 = this.Label_escala_canal_8;
			Size = new System.Drawing.Size(55, 13);
			label_escala_canal_30.Size = this.Size;
			this.Label_escala_canal_8.TabIndex = 1;
			this.Label_escala_canal_8.Text = "Canal 08 :";
			this.Label_escala_canal_0.AutoSize = true;
			global::System.Windows.Forms.Control label_escala_canal_31 = this.Label_escala_canal_0;
label_escala_canal_31.Location = new global::System.Drawing.Point(24, 76);
			this.Label_escala_canal_0.Name = "Label_escala_canal_0";
			global::System.Windows.Forms.Control label_escala_canal_32 = this.Label_escala_canal_0;
			Size = new System.Drawing.Size(55, 13);
			label_escala_canal_32.Size = this.Size;
			this.Label_escala_canal_0.TabIndex = 1;
			this.Label_escala_canal_0.Text = "Canal 00 :";
			global::System.Drawing.SizeF autoScaleDimensions;
			autoScaleDimensions = new global::System.Drawing.SizeF(6f, 13f);
			this.AutoScaleDimensions = autoScaleDimensions;
			this.AutoScaleMode = AutoScaleMode.Font;
			Size = new System.Drawing.Size(359, 558);
			this.ClientSize = Size;
			this.Controls.Add(this.Grupo_ctrl);
			this.Controls.Add(this.grupo_escalas);
			this.Controls.Add(this.grupo_parametros_gerais);
			this.FormBorderStyle = FormBorderStyle.None;
this.Location = new global::System.Drawing.Point(160, 2);
			this.Name = "Equip_VA230_conf";
			this.StartPosition = global::System.Windows.Forms.FormStartPosition.Manual;
			this.Text = "Equipamento VA 230 - Configuração";
			this.grupo_parametros_gerais.ResumeLayout(false);
			this.grupo_parametros_gerais.PerformLayout();
			this.Grupo_ctrl.ResumeLayout(false);
			this.Grupo_ctrl.PerformLayout();
			this.grupo_escalas.ResumeLayout(false);
			this.grupo_escalas.PerformLayout();
			this.ResumeLayout(false);
		}

		// Token: 0x04001B25 RID: 6949
		private global::System.ComponentModel.IContainer components;
	}
}
