using System.Drawing;
using System.Windows.Forms;
﻿namespace iS800
{
	// Token: 0x0200009C RID: 156
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class Equip_VA220_conf : global::System.Windows.Forms.Form
	{
		// Token: 0x06002498 RID: 9368 RVA: 0x0040D474 File Offset: 0x0040B874
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			if (disposing && this.components != null)
			{
				this.components.Dispose();
			}
			base.Dispose(disposing);
		}

		// Token: 0x06002499 RID: 9369 RVA: 0x0040D494 File Offset: 0x0040B894
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.grupo_parametros_gerais = new global::System.Windows.Forms.GroupBox();
			this.Valor_tempo_entre_acionamentos = new global::System.Windows.Forms.TextBox();
			this.Valor_tempo_motor_parado = new global::System.Windows.Forms.TextBox();
			this.Valor_tempo_motor_operando = new global::System.Windows.Forms.TextBox();
			this.Valor_tempo_falha_desligar_motor = new global::System.Windows.Forms.TextBox();
			this.Valor_tempo_falha_ligar_motor = new global::System.Windows.Forms.TextBox();
			this.Valor_max_bombas = new global::System.Windows.Forms.TextBox();
			this.Valor_temp_ptt = new global::System.Windows.Forms.TextBox();
			this.Label_tempo_entre_acionamentos = new global::System.Windows.Forms.Label();
			this.ComboBox_controle_nivel = new global::System.Windows.Forms.ComboBox();
			this.ComboBox_modo_operacao = new global::System.Windows.Forms.ComboBox();
			this.Label_tempo_minimo_motor_parado = new global::System.Windows.Forms.Label();
			this.Label_controle_nivel = new global::System.Windows.Forms.Label();
			this.Label_modo_operacao = new global::System.Windows.Forms.Label();
			this.Label_tempo_minimo_motor_ligado = new global::System.Windows.Forms.Label();
			this.Label_tempo_falha_desligar_motor = new global::System.Windows.Forms.Label();
			this.Label_tempo_falha_ligar_motor = new global::System.Windows.Forms.Label();
			this.Label_Max_bombas = new global::System.Windows.Forms.Label();
			this.Label_tempo_ptt = new global::System.Windows.Forms.Label();
			this.Valor_end_mestre = new global::System.Windows.Forms.TextBox();
			this.Valor_end_est = new global::System.Windows.Forms.TextBox();
			this.Label_end_mestre = new global::System.Windows.Forms.Label();
			this.Label_end_est = new global::System.Windows.Forms.Label();
			this.Grupo_ctrl = new global::System.Windows.Forms.GroupBox();
			this.Box_Msg = new global::System.Windows.Forms.TextBox();
			this.Ler_conf_VA220 = new global::System.Windows.Forms.Button();
			this.grupo_programacao_io = new global::System.Windows.Forms.GroupBox();
			this.GroupBox2 = new global::System.Windows.Forms.GroupBox();
			this.ComboBox_S08 = new global::System.Windows.Forms.ComboBox();
			this.ComboBox_S07 = new global::System.Windows.Forms.ComboBox();
			this.ComboBox_S06 = new global::System.Windows.Forms.ComboBox();
			this.ComboBox_S05 = new global::System.Windows.Forms.ComboBox();
			this.ComboBox_S04 = new global::System.Windows.Forms.ComboBox();
			this.ComboBox_S03 = new global::System.Windows.Forms.ComboBox();
			this.ComboBox_S02 = new global::System.Windows.Forms.ComboBox();
			this.ComboBox_S01 = new global::System.Windows.Forms.ComboBox();
			this.Label_S08 = new global::System.Windows.Forms.Label();
			this.Label_S07 = new global::System.Windows.Forms.Label();
			this.Label_S06 = new global::System.Windows.Forms.Label();
			this.Label_S05 = new global::System.Windows.Forms.Label();
			this.Label_S04 = new global::System.Windows.Forms.Label();
			this.Label_S03 = new global::System.Windows.Forms.Label();
			this.Label_S02 = new global::System.Windows.Forms.Label();
			this.Label_S01 = new global::System.Windows.Forms.Label();
			this.GroupBox1 = new global::System.Windows.Forms.GroupBox();
			this.ComboBox_E08 = new global::System.Windows.Forms.ComboBox();
			this.ComboBox_E07 = new global::System.Windows.Forms.ComboBox();
			this.ComboBox_E06 = new global::System.Windows.Forms.ComboBox();
			this.ComboBox_E05 = new global::System.Windows.Forms.ComboBox();
			this.ComboBox_E04 = new global::System.Windows.Forms.ComboBox();
			this.ComboBox_E03 = new global::System.Windows.Forms.ComboBox();
			this.ComboBox_E02 = new global::System.Windows.Forms.ComboBox();
			this.ComboBox_E01 = new global::System.Windows.Forms.ComboBox();
			this.Label_E08 = new global::System.Windows.Forms.Label();
			this.Label_E07 = new global::System.Windows.Forms.Label();
			this.Label_E06 = new global::System.Windows.Forms.Label();
			this.Label_E05 = new global::System.Windows.Forms.Label();
			this.Label_E04 = new global::System.Windows.Forms.Label();
			this.Label_E03 = new global::System.Windows.Forms.Label();
			this.Label_E02 = new global::System.Windows.Forms.Label();
			this.Label_E01 = new global::System.Windows.Forms.Label();
			global::System.Windows.Forms.Button button = new global::System.Windows.Forms.Button();
			this.grupo_parametros_gerais.SuspendLayout();
			this.Grupo_ctrl.SuspendLayout();
			this.grupo_programacao_io.SuspendLayout();
			this.GroupBox2.SuspendLayout();
			this.GroupBox1.SuspendLayout();
			this.SuspendLayout();
			global::System.Windows.Forms.Control control = button;
			control.Location = new global::System.Drawing.Point(194, 61);
			button.Name = "Esc_conf_VA220";
			global::System.Windows.Forms.Control control2 = button;
			control2.Size = new global::System.Drawing.Size(109, 28);
			button.TabIndex = 34;
			button.Text = "Salvar config.";
			button.UseVisualStyleBackColor = true;
			button.Click += new global::System.EventHandler(this.Esc_conf_VA220_Click);
			this.grupo_parametros_gerais.Controls.Add(this.Valor_tempo_entre_acionamentos);
			this.grupo_parametros_gerais.Controls.Add(this.Valor_tempo_motor_parado);
			this.grupo_parametros_gerais.Controls.Add(this.Valor_tempo_motor_operando);
			this.grupo_parametros_gerais.Controls.Add(this.Valor_tempo_falha_desligar_motor);
			this.grupo_parametros_gerais.Controls.Add(this.Valor_tempo_falha_ligar_motor);
			this.grupo_parametros_gerais.Controls.Add(this.Valor_max_bombas);
			this.grupo_parametros_gerais.Controls.Add(this.Valor_temp_ptt);
			this.grupo_parametros_gerais.Controls.Add(this.Label_tempo_entre_acionamentos);
			this.grupo_parametros_gerais.Controls.Add(this.ComboBox_controle_nivel);
			this.grupo_parametros_gerais.Controls.Add(this.ComboBox_modo_operacao);
			this.grupo_parametros_gerais.Controls.Add(this.Label_tempo_minimo_motor_parado);
			this.grupo_parametros_gerais.Controls.Add(this.Label_controle_nivel);
			this.grupo_parametros_gerais.Controls.Add(this.Label_modo_operacao);
			this.grupo_parametros_gerais.Controls.Add(this.Label_tempo_minimo_motor_ligado);
			this.grupo_parametros_gerais.Controls.Add(this.Label_tempo_falha_desligar_motor);
			this.grupo_parametros_gerais.Controls.Add(this.Label_tempo_falha_ligar_motor);
			this.grupo_parametros_gerais.Controls.Add(this.Label_Max_bombas);
			this.grupo_parametros_gerais.Controls.Add(this.Label_tempo_ptt);
			this.grupo_parametros_gerais.Controls.Add(this.Valor_end_mestre);
			this.grupo_parametros_gerais.Controls.Add(this.Valor_end_est);
			this.grupo_parametros_gerais.Controls.Add(this.Label_end_mestre);
			this.grupo_parametros_gerais.Controls.Add(this.Label_end_est);
			global::System.Windows.Forms.Control grupo_parametros_gerais = this.grupo_parametros_gerais;
grupo_parametros_gerais.Location = new global::System.Drawing.Point(12, 12);
			this.grupo_parametros_gerais.Name = "grupo_parametros_gerais";
			global::System.Windows.Forms.Control grupo_parametros_gerais2 = this.grupo_parametros_gerais;
			Size = new System.Drawing.Size(335, 327);
			grupo_parametros_gerais2.Size = this.Size;
			this.grupo_parametros_gerais.TabIndex = 1;
			this.grupo_parametros_gerais.TabStop = false;
			this.grupo_parametros_gerais.Text = "Parâmetros gerais";
			global::System.Windows.Forms.Control valor_tempo_entre_acionamentos = this.Valor_tempo_entre_acionamentos;
valor_tempo_entre_acionamentos.Location = new global::System.Drawing.Point(243, 234);
			this.Valor_tempo_entre_acionamentos.Name = "Valor_tempo_entre_acionamentos";
			global::System.Windows.Forms.Control valor_tempo_entre_acionamentos2 = this.Valor_tempo_entre_acionamentos;
			Size = new System.Drawing.Size(74, 20);
			valor_tempo_entre_acionamentos2.Size = this.Size;
			this.Valor_tempo_entre_acionamentos.TabIndex = 10;
			this.Valor_tempo_entre_acionamentos.TextAlign = HorizontalAlignment.Center;
			global::System.Windows.Forms.Control valor_tempo_motor_parado = this.Valor_tempo_motor_parado;
valor_tempo_motor_parado.Location = new global::System.Drawing.Point(243, 208);
			this.Valor_tempo_motor_parado.Name = "Valor_tempo_motor_parado";
			global::System.Windows.Forms.Control valor_tempo_motor_parado2 = this.Valor_tempo_motor_parado;
			Size = new System.Drawing.Size(74, 20);
			valor_tempo_motor_parado2.Size = this.Size;
			this.Valor_tempo_motor_parado.TabIndex = 9;
			this.Valor_tempo_motor_parado.TextAlign = HorizontalAlignment.Center;
			global::System.Windows.Forms.Control valor_tempo_motor_operando = this.Valor_tempo_motor_operando;
valor_tempo_motor_operando.Location = new global::System.Drawing.Point(243, 182);
			this.Valor_tempo_motor_operando.Name = "Valor_tempo_motor_operando";
			global::System.Windows.Forms.Control valor_tempo_motor_operando2 = this.Valor_tempo_motor_operando;
			Size = new System.Drawing.Size(74, 20);
			valor_tempo_motor_operando2.Size = this.Size;
			this.Valor_tempo_motor_operando.TabIndex = 8;
			this.Valor_tempo_motor_operando.TextAlign = HorizontalAlignment.Center;
			global::System.Windows.Forms.Control valor_tempo_falha_desligar_motor = this.Valor_tempo_falha_desligar_motor;
valor_tempo_falha_desligar_motor.Location = new global::System.Drawing.Point(243, 156);
			this.Valor_tempo_falha_desligar_motor.Name = "Valor_tempo_falha_desligar_motor";
			global::System.Windows.Forms.Control valor_tempo_falha_desligar_motor2 = this.Valor_tempo_falha_desligar_motor;
			Size = new System.Drawing.Size(74, 20);
			valor_tempo_falha_desligar_motor2.Size = this.Size;
			this.Valor_tempo_falha_desligar_motor.TabIndex = 7;
			this.Valor_tempo_falha_desligar_motor.TextAlign = HorizontalAlignment.Center;
			global::System.Windows.Forms.Control valor_tempo_falha_ligar_motor = this.Valor_tempo_falha_ligar_motor;
valor_tempo_falha_ligar_motor.Location = new global::System.Drawing.Point(243, 130);
			this.Valor_tempo_falha_ligar_motor.Name = "Valor_tempo_falha_ligar_motor";
			global::System.Windows.Forms.Control valor_tempo_falha_ligar_motor2 = this.Valor_tempo_falha_ligar_motor;
			Size = new System.Drawing.Size(74, 20);
			valor_tempo_falha_ligar_motor2.Size = this.Size;
			this.Valor_tempo_falha_ligar_motor.TabIndex = 6;
			this.Valor_tempo_falha_ligar_motor.TextAlign = HorizontalAlignment.Center;
			global::System.Windows.Forms.Control valor_max_bombas = this.Valor_max_bombas;
valor_max_bombas.Location = new global::System.Drawing.Point(243, 104);
			this.Valor_max_bombas.Name = "Valor_max_bombas";
			global::System.Windows.Forms.Control valor_max_bombas2 = this.Valor_max_bombas;
			Size = new System.Drawing.Size(74, 20);
			valor_max_bombas2.Size = this.Size;
			this.Valor_max_bombas.TabIndex = 5;
			this.Valor_max_bombas.TextAlign = HorizontalAlignment.Center;
			global::System.Windows.Forms.Control valor_temp_ptt = this.Valor_temp_ptt;
valor_temp_ptt.Location = new global::System.Drawing.Point(243, 78);
			this.Valor_temp_ptt.Name = "Valor_temp_ptt";
			global::System.Windows.Forms.Control valor_temp_ptt2 = this.Valor_temp_ptt;
			Size = new System.Drawing.Size(74, 20);
			valor_temp_ptt2.Size = this.Size;
			this.Valor_temp_ptt.TabIndex = 4;
			this.Valor_temp_ptt.TextAlign = HorizontalAlignment.Center;
			this.Label_tempo_entre_acionamentos.AutoSize = true;
			global::System.Windows.Forms.Control label_tempo_entre_acionamentos = this.Label_tempo_entre_acionamentos;
label_tempo_entre_acionamentos.Location = new global::System.Drawing.Point(24, 238);
			this.Label_tempo_entre_acionamentos.Name = "Label_tempo_entre_acionamentos";
			global::System.Windows.Forms.Control label_tempo_entre_acionamentos2 = this.Label_tempo_entre_acionamentos;
			Size = new System.Drawing.Size(164, 13);
			label_tempo_entre_acionamentos2.Size = this.Size;
			this.Label_tempo_entre_acionamentos.TabIndex = 4;
			this.Label_tempo_entre_acionamentos.Text = "Tempo entre acionamentos (min):";
			this.ComboBox_controle_nivel.FormattingEnabled = true;
			global::System.Windows.Forms.Control comboBox_controle_nivel = this.ComboBox_controle_nivel;
comboBox_controle_nivel.Location = new global::System.Drawing.Point(228, 286);
			this.ComboBox_controle_nivel.Name = "ComboBox_controle_nivel";
			global::System.Windows.Forms.Control comboBox_controle_nivel2 = this.ComboBox_controle_nivel;
			Size = new System.Drawing.Size(89, 21);
			comboBox_controle_nivel2.Size = this.Size;
			this.ComboBox_controle_nivel.TabIndex = 12;
			this.ComboBox_modo_operacao.FormattingEnabled = true;
			global::System.Windows.Forms.Control comboBox_modo_operacao = this.ComboBox_modo_operacao;
comboBox_modo_operacao.Location = new global::System.Drawing.Point(228, 260);
			this.ComboBox_modo_operacao.Name = "ComboBox_modo_operacao";
			global::System.Windows.Forms.Control comboBox_modo_operacao2 = this.ComboBox_modo_operacao;
			Size = new System.Drawing.Size(89, 21);
			comboBox_modo_operacao2.Size = this.Size;
			this.ComboBox_modo_operacao.TabIndex = 11;
			this.Label_tempo_minimo_motor_parado.AutoSize = true;
			global::System.Windows.Forms.Control label_tempo_minimo_motor_parado = this.Label_tempo_minimo_motor_parado;
label_tempo_minimo_motor_parado.Location = new global::System.Drawing.Point(24, 212);
			this.Label_tempo_minimo_motor_parado.Name = "Label_tempo_minimo_motor_parado";
			global::System.Windows.Forms.Control label_tempo_minimo_motor_parado2 = this.Label_tempo_minimo_motor_parado;
			Size = new System.Drawing.Size(170, 13);
			label_tempo_minimo_motor_parado2.Size = this.Size;
			this.Label_tempo_minimo_motor_parado.TabIndex = 4;
			this.Label_tempo_minimo_motor_parado.Text = "Tempo mínimo motor parado (min):";
			this.Label_controle_nivel.AutoSize = true;
			global::System.Windows.Forms.Control label_controle_nivel = this.Label_controle_nivel;
label_controle_nivel.Location = new global::System.Drawing.Point(24, 290);
			this.Label_controle_nivel.Name = "Label_controle_nivel";
			global::System.Windows.Forms.Control label_controle_nivel2 = this.Label_controle_nivel;
			Size = new System.Drawing.Size(190, 13);
			label_controle_nivel2.Size = this.Size;
			this.Label_controle_nivel.TabIndex = 8;
			this.Label_controle_nivel.Text = "Controle por nível - Reservatório fonte:";
			this.Label_modo_operacao.AutoSize = true;
			global::System.Windows.Forms.Control label_modo_operacao = this.Label_modo_operacao;
label_modo_operacao.Location = new global::System.Drawing.Point(24, 264);
			this.Label_modo_operacao.Name = "Label_modo_operacao";
			global::System.Windows.Forms.Control label_modo_operacao2 = this.Label_modo_operacao;
			Size = new System.Drawing.Size(103, 13);
			label_modo_operacao2.Size = this.Size;
			this.Label_modo_operacao.TabIndex = 8;
			this.Label_modo_operacao.Text = "Modo de operação :";
			this.Label_tempo_minimo_motor_ligado.AutoSize = true;
			global::System.Windows.Forms.Control label_tempo_minimo_motor_ligado = this.Label_tempo_minimo_motor_ligado;
label_tempo_minimo_motor_ligado.Location = new global::System.Drawing.Point(24, 186);
			this.Label_tempo_minimo_motor_ligado.Name = "Label_tempo_minimo_motor_ligado";
			global::System.Windows.Forms.Control label_tempo_minimo_motor_ligado2 = this.Label_tempo_minimo_motor_ligado;
			Size = new System.Drawing.Size(182, 13);
			label_tempo_minimo_motor_ligado2.Size = this.Size;
			this.Label_tempo_minimo_motor_ligado.TabIndex = 4;
			this.Label_tempo_minimo_motor_ligado.Text = "Tempo mínimo motor operando (min):";
			this.Label_tempo_falha_desligar_motor.AutoSize = true;
			global::System.Windows.Forms.Control label_tempo_falha_desligar_motor = this.Label_tempo_falha_desligar_motor;
label_tempo_falha_desligar_motor.Location = new global::System.Drawing.Point(24, 160);
			this.Label_tempo_falha_desligar_motor.Name = "Label_tempo_falha_desligar_motor";
			global::System.Windows.Forms.Control label_tempo_falha_desligar_motor2 = this.Label_tempo_falha_desligar_motor;
			Size = new System.Drawing.Size(208, 13);
			label_tempo_falha_desligar_motor2.Size = this.Size;
			this.Label_tempo_falha_desligar_motor.TabIndex = 4;
			this.Label_tempo_falha_desligar_motor.Text = "Tempo p/ falha - após desligar motor (min):";
			this.Label_tempo_falha_ligar_motor.AutoSize = true;
			global::System.Windows.Forms.Control label_tempo_falha_ligar_motor = this.Label_tempo_falha_ligar_motor;
label_tempo_falha_ligar_motor.Location = new global::System.Drawing.Point(24, 134);
			this.Label_tempo_falha_ligar_motor.Name = "Label_tempo_falha_ligar_motor";
			global::System.Windows.Forms.Control label_tempo_falha_ligar_motor2 = this.Label_tempo_falha_ligar_motor;
			Size = new System.Drawing.Size(191, 13);
			label_tempo_falha_ligar_motor2.Size = this.Size;
			this.Label_tempo_falha_ligar_motor.TabIndex = 4;
			this.Label_tempo_falha_ligar_motor.Text = "Tempo p/ falha - após ligar motor (min):";
			this.Label_Max_bombas.AutoSize = true;
			global::System.Windows.Forms.Control label_Max_bombas = this.Label_Max_bombas;
label_Max_bombas.Location = new global::System.Drawing.Point(24, 108);
			this.Label_Max_bombas.Name = "Label_Max_bombas";
			global::System.Windows.Forms.Control label_Max_bombas2 = this.Label_Max_bombas;
			Size = new System.Drawing.Size(170, 13);
			label_Max_bombas2.Size = this.Size;
			this.Label_Max_bombas.TabIndex = 4;
			this.Label_Max_bombas.Text = "Número max. bombas simultâneas:";
			this.Label_tempo_ptt.AutoSize = true;
			global::System.Windows.Forms.Control label_tempo_ptt = this.Label_tempo_ptt;
label_tempo_ptt.Location = new global::System.Drawing.Point(24, 82);
			this.Label_tempo_ptt.Name = "Label_tempo_ptt";
			global::System.Windows.Forms.Control label_tempo_ptt2 = this.Label_tempo_ptt;
			Size = new System.Drawing.Size(140, 13);
			label_tempo_ptt2.Size = this.Size;
			this.Label_tempo_ptt.TabIndex = 4;
			this.Label_tempo_ptt.Text = "Tempo Espera de PTT (ms):";
			global::System.Windows.Forms.Control valor_end_mestre = this.Valor_end_mestre;
valor_end_mestre.Location = new global::System.Drawing.Point(244, 26);
			this.Valor_end_mestre.Name = "Valor_end_mestre";
			global::System.Windows.Forms.Control valor_end_mestre2 = this.Valor_end_mestre;
			Size = new System.Drawing.Size(73, 20);
			valor_end_mestre2.Size = this.Size;
			this.Valor_end_mestre.TabIndex = 2;
			this.Valor_end_mestre.TextAlign = HorizontalAlignment.Center;
			global::System.Windows.Forms.Control valor_end_est = this.Valor_end_est;
valor_end_est.Location = new global::System.Drawing.Point(243, 52);
			this.Valor_end_est.Name = "Valor_end_est";
			global::System.Windows.Forms.Control valor_end_est2 = this.Valor_end_est;
			Size = new System.Drawing.Size(74, 20);
			valor_end_est2.Size = this.Size;
			this.Valor_end_est.TabIndex = 3;
			this.Valor_end_est.TextAlign = HorizontalAlignment.Center;
			this.Label_end_mestre.AutoSize = true;
			global::System.Windows.Forms.Control label_end_mestre = this.Label_end_mestre;
label_end_mestre.Location = new global::System.Drawing.Point(24, 30);
			this.Label_end_mestre.Name = "Label_end_mestre";
			global::System.Windows.Forms.Control label_end_mestre2 = this.Label_end_mestre;
			Size = new System.Drawing.Size(109, 13);
			label_end_mestre2.Size = this.Size;
			this.Label_end_mestre.TabIndex = 1;
			this.Label_end_mestre.Text = "Endereço do Mestre :";
			this.Label_end_est.AutoSize = true;
			global::System.Windows.Forms.Control label_end_est = this.Label_end_est;
label_end_est.Location = new global::System.Drawing.Point(24, 56);
			this.Label_end_est.Name = "Label_end_est";
			global::System.Windows.Forms.Control label_end_est2 = this.Label_end_est;
			Size = new System.Drawing.Size(116, 13);
			label_end_est2.Size = this.Size;
			this.Label_end_est.TabIndex = 0;
			this.Label_end_est.Text = "Endereço da Estação :";
			this.Grupo_ctrl.Controls.Add(button);
			this.Grupo_ctrl.Controls.Add(this.Box_Msg);
			this.Grupo_ctrl.Controls.Add(this.Ler_conf_VA220);
			global::System.Windows.Forms.Control grupo_ctrl = this.Grupo_ctrl;
grupo_ctrl.Location = new global::System.Drawing.Point(12, 355);
			this.Grupo_ctrl.Name = "Grupo_ctrl";
			global::System.Windows.Forms.Control grupo_ctrl2 = this.Grupo_ctrl;
			Size = new System.Drawing.Size(335, 105);
			grupo_ctrl2.Size = this.Size;
			this.Grupo_ctrl.TabIndex = 32;
			this.Grupo_ctrl.TabStop = false;
			this.Grupo_ctrl.Text = "Comandos e Status";
			global::System.Windows.Forms.Control box_Msg = this.Box_Msg;
box_Msg.Location = new global::System.Drawing.Point(24, 29);
			this.Box_Msg.Name = "Box_Msg";
			global::System.Windows.Forms.Control box_Msg2 = this.Box_Msg;
			Size = new System.Drawing.Size(293, 20);
			box_Msg2.Size = this.Size;
			this.Box_Msg.TabIndex = 5;
			this.Box_Msg.TabStop = false;
			this.Box_Msg.TextAlign = HorizontalAlignment.Right;
			global::System.Windows.Forms.Control ler_conf_VA = this.Ler_conf_VA220;
ler_conf_VA.Location = new global::System.Drawing.Point(41, 61);
			this.Ler_conf_VA220.Name = "Ler_conf_VA220";
			global::System.Windows.Forms.Control ler_conf_VA2 = this.Ler_conf_VA220;
			Size = new System.Drawing.Size(109, 28);
			ler_conf_VA2.Size = this.Size;
			this.Ler_conf_VA220.TabIndex = 33;
			this.Ler_conf_VA220.Text = "Ler configuração";
			this.Ler_conf_VA220.UseVisualStyleBackColor = true;
			this.grupo_programacao_io.Controls.Add(this.GroupBox2);
			this.grupo_programacao_io.Controls.Add(this.GroupBox1);
			global::System.Windows.Forms.Control grupo_programacao_io = this.grupo_programacao_io;
grupo_programacao_io.Location = new global::System.Drawing.Point(374, 12);
			this.grupo_programacao_io.Name = "grupo_programacao_io";
			global::System.Windows.Forms.Control grupo_programacao_io2 = this.grupo_programacao_io;
			Size = new System.Drawing.Size(567, 327);
			grupo_programacao_io2.Size = this.Size;
			this.grupo_programacao_io.TabIndex = 13;
			this.grupo_programacao_io.TabStop = false;
			this.grupo_programacao_io.Text = "Programação de I/O";
			this.GroupBox2.Controls.Add(this.ComboBox_S08);
			this.GroupBox2.Controls.Add(this.ComboBox_S07);
			this.GroupBox2.Controls.Add(this.ComboBox_S06);
			this.GroupBox2.Controls.Add(this.ComboBox_S05);
			this.GroupBox2.Controls.Add(this.ComboBox_S04);
			this.GroupBox2.Controls.Add(this.ComboBox_S03);
			this.GroupBox2.Controls.Add(this.ComboBox_S02);
			this.GroupBox2.Controls.Add(this.ComboBox_S01);
			this.GroupBox2.Controls.Add(this.Label_S08);
			this.GroupBox2.Controls.Add(this.Label_S07);
			this.GroupBox2.Controls.Add(this.Label_S06);
			this.GroupBox2.Controls.Add(this.Label_S05);
			this.GroupBox2.Controls.Add(this.Label_S04);
			this.GroupBox2.Controls.Add(this.Label_S03);
			this.GroupBox2.Controls.Add(this.Label_S02);
			this.GroupBox2.Controls.Add(this.Label_S01);
			global::System.Windows.Forms.Control groupBox = this.GroupBox2;
groupBox.Location = new global::System.Drawing.Point(22, 30);
			this.GroupBox2.Name = "GroupBox2";
			global::System.Windows.Forms.Control groupBox2 = this.GroupBox2;
			Size = new System.Drawing.Size(249, 277);
			groupBox2.Size = this.Size;
			this.GroupBox2.TabIndex = 23;
			this.GroupBox2.TabStop = false;
			this.GroupBox2.Text = "Saídas Digitais";
			this.ComboBox_S08.FormattingEnabled = true;
			global::System.Windows.Forms.Control comboBox_S = this.ComboBox_S08;
comboBox_S.Location = new global::System.Drawing.Point(45, 233);
			this.ComboBox_S08.Name = "ComboBox_S08";
			global::System.Windows.Forms.Control comboBox_S2 = this.ComboBox_S08;
			Size = new System.Drawing.Size(187, 21);
			comboBox_S2.Size = this.Size;
			this.ComboBox_S08.TabIndex = 31;
			this.ComboBox_S07.FormattingEnabled = true;
			global::System.Windows.Forms.Control comboBox_S3 = this.ComboBox_S07;
comboBox_S3.Location = new global::System.Drawing.Point(45, 204);
			this.ComboBox_S07.Name = "ComboBox_S07";
			global::System.Windows.Forms.Control comboBox_S4 = this.ComboBox_S07;
			Size = new System.Drawing.Size(187, 21);
			comboBox_S4.Size = this.Size;
			this.ComboBox_S07.TabIndex = 30;
			this.ComboBox_S06.FormattingEnabled = true;
			global::System.Windows.Forms.Control comboBox_S5 = this.ComboBox_S06;
comboBox_S5.Location = new global::System.Drawing.Point(45, 175);
			this.ComboBox_S06.Name = "ComboBox_S06";
			global::System.Windows.Forms.Control comboBox_S6 = this.ComboBox_S06;
			Size = new System.Drawing.Size(187, 21);
			comboBox_S6.Size = this.Size;
			this.ComboBox_S06.TabIndex = 29;
			this.ComboBox_S05.FormattingEnabled = true;
			global::System.Windows.Forms.Control comboBox_S7 = this.ComboBox_S05;
comboBox_S7.Location = new global::System.Drawing.Point(45, 146);
			this.ComboBox_S05.Name = "ComboBox_S05";
			global::System.Windows.Forms.Control comboBox_S8 = this.ComboBox_S05;
			Size = new System.Drawing.Size(187, 21);
			comboBox_S8.Size = this.Size;
			this.ComboBox_S05.TabIndex = 28;
			this.ComboBox_S04.FormattingEnabled = true;
			global::System.Windows.Forms.Control comboBox_S9 = this.ComboBox_S04;
comboBox_S9.Location = new global::System.Drawing.Point(45, 117);
			this.ComboBox_S04.Name = "ComboBox_S04";
			global::System.Windows.Forms.Control comboBox_S10 = this.ComboBox_S04;
			Size = new System.Drawing.Size(187, 21);
			comboBox_S10.Size = this.Size;
			this.ComboBox_S04.TabIndex = 27;
			this.ComboBox_S03.FormattingEnabled = true;
			global::System.Windows.Forms.Control comboBox_S11 = this.ComboBox_S03;
comboBox_S11.Location = new global::System.Drawing.Point(45, 88);
			this.ComboBox_S03.Name = "ComboBox_S03";
			global::System.Windows.Forms.Control comboBox_S12 = this.ComboBox_S03;
			Size = new System.Drawing.Size(187, 21);
			comboBox_S12.Size = this.Size;
			this.ComboBox_S03.TabIndex = 26;
			this.ComboBox_S02.FormattingEnabled = true;
			global::System.Windows.Forms.Control comboBox_S13 = this.ComboBox_S02;
comboBox_S13.Location = new global::System.Drawing.Point(45, 59);
			this.ComboBox_S02.Name = "ComboBox_S02";
			global::System.Windows.Forms.Control comboBox_S14 = this.ComboBox_S02;
			Size = new System.Drawing.Size(187, 21);
			comboBox_S14.Size = this.Size;
			this.ComboBox_S02.TabIndex = 25;
			this.ComboBox_S01.FormattingEnabled = true;
			global::System.Windows.Forms.Control comboBox_S15 = this.ComboBox_S01;
comboBox_S15.Location = new global::System.Drawing.Point(45, 30);
			this.ComboBox_S01.Name = "ComboBox_S01";
			global::System.Windows.Forms.Control comboBox_S16 = this.ComboBox_S01;
			Size = new System.Drawing.Size(187, 21);
			comboBox_S16.Size = this.Size;
			this.ComboBox_S01.TabIndex = 24;
			this.Label_S08.AutoSize = true;
			global::System.Windows.Forms.Control label_S = this.Label_S08;
label_S.Location = new global::System.Drawing.Point(10, 237);
			this.Label_S08.Name = "Label_S08";
			global::System.Windows.Forms.Control label_S2 = this.Label_S08;
			Size = new System.Drawing.Size(29, 13);
			label_S2.Size = this.Size;
			this.Label_S08.TabIndex = 9;
			this.Label_S08.Text = "S 08";
			this.Label_S07.AutoSize = true;
			global::System.Windows.Forms.Control label_S3 = this.Label_S07;
label_S3.Location = new global::System.Drawing.Point(10, 208);
			this.Label_S07.Name = "Label_S07";
			global::System.Windows.Forms.Control label_S4 = this.Label_S07;
			Size = new System.Drawing.Size(29, 13);
			label_S4.Size = this.Size;
			this.Label_S07.TabIndex = 9;
			this.Label_S07.Text = "S 07";
			this.Label_S06.AutoSize = true;
			global::System.Windows.Forms.Control label_S5 = this.Label_S06;
label_S5.Location = new global::System.Drawing.Point(10, 179);
			this.Label_S06.Name = "Label_S06";
			global::System.Windows.Forms.Control label_S6 = this.Label_S06;
			Size = new System.Drawing.Size(29, 13);
			label_S6.Size = this.Size;
			this.Label_S06.TabIndex = 9;
			this.Label_S06.Text = "S 06";
			this.Label_S05.AutoSize = true;
			global::System.Windows.Forms.Control label_S7 = this.Label_S05;
label_S7.Location = new global::System.Drawing.Point(10, 150);
			this.Label_S05.Name = "Label_S05";
			global::System.Windows.Forms.Control label_S8 = this.Label_S05;
			Size = new System.Drawing.Size(29, 13);
			label_S8.Size = this.Size;
			this.Label_S05.TabIndex = 9;
			this.Label_S05.Text = "S 05";
			this.Label_S04.AutoSize = true;
			global::System.Windows.Forms.Control label_S9 = this.Label_S04;
label_S9.Location = new global::System.Drawing.Point(10, 121);
			this.Label_S04.Name = "Label_S04";
			global::System.Windows.Forms.Control label_S10 = this.Label_S04;
			Size = new System.Drawing.Size(29, 13);
			label_S10.Size = this.Size;
			this.Label_S04.TabIndex = 9;
			this.Label_S04.Text = "S 04";
			this.Label_S03.AutoSize = true;
			global::System.Windows.Forms.Control label_S11 = this.Label_S03;
label_S11.Location = new global::System.Drawing.Point(10, 92);
			this.Label_S03.Name = "Label_S03";
			global::System.Windows.Forms.Control label_S12 = this.Label_S03;
			Size = new System.Drawing.Size(29, 13);
			label_S12.Size = this.Size;
			this.Label_S03.TabIndex = 9;
			this.Label_S03.Text = "S 03";
			this.Label_S02.AutoSize = true;
			global::System.Windows.Forms.Control label_S13 = this.Label_S02;
label_S13.Location = new global::System.Drawing.Point(10, 63);
			this.Label_S02.Name = "Label_S02";
			global::System.Windows.Forms.Control label_S14 = this.Label_S02;
			Size = new System.Drawing.Size(29, 13);
			label_S14.Size = this.Size;
			this.Label_S02.TabIndex = 9;
			this.Label_S02.Text = "S 02";
			this.Label_S01.AutoSize = true;
			global::System.Windows.Forms.Control label_S15 = this.Label_S01;
label_S15.Location = new global::System.Drawing.Point(10, 34);
			this.Label_S01.Name = "Label_S01";
			global::System.Windows.Forms.Control label_S16 = this.Label_S01;
			Size = new System.Drawing.Size(29, 13);
			label_S16.Size = this.Size;
			this.Label_S01.TabIndex = 9;
			this.Label_S01.Text = "S 01";
			this.GroupBox1.Controls.Add(this.ComboBox_E08);
			this.GroupBox1.Controls.Add(this.ComboBox_E07);
			this.GroupBox1.Controls.Add(this.ComboBox_E06);
			this.GroupBox1.Controls.Add(this.ComboBox_E05);
			this.GroupBox1.Controls.Add(this.ComboBox_E04);
			this.GroupBox1.Controls.Add(this.ComboBox_E03);
			this.GroupBox1.Controls.Add(this.ComboBox_E02);
			this.GroupBox1.Controls.Add(this.ComboBox_E01);
			this.GroupBox1.Controls.Add(this.Label_E08);
			this.GroupBox1.Controls.Add(this.Label_E07);
			this.GroupBox1.Controls.Add(this.Label_E06);
			this.GroupBox1.Controls.Add(this.Label_E05);
			this.GroupBox1.Controls.Add(this.Label_E04);
			this.GroupBox1.Controls.Add(this.Label_E03);
			this.GroupBox1.Controls.Add(this.Label_E02);
			this.GroupBox1.Controls.Add(this.Label_E01);
			global::System.Windows.Forms.Control groupBox3 = this.GroupBox1;
groupBox3.Location = new global::System.Drawing.Point(295, 30);
			this.GroupBox1.Name = "GroupBox1";
			global::System.Windows.Forms.Control groupBox4 = this.GroupBox1;
			Size = new System.Drawing.Size(249, 277);
			groupBox4.Size = this.Size;
			this.GroupBox1.TabIndex = 14;
			this.GroupBox1.TabStop = false;
			this.GroupBox1.Text = "Entradas Digitais";
			this.ComboBox_E08.FormattingEnabled = true;
			global::System.Windows.Forms.Control comboBox_E = this.ComboBox_E08;
comboBox_E.Location = new global::System.Drawing.Point(45, 233);
			this.ComboBox_E08.Name = "ComboBox_E08";
			global::System.Windows.Forms.Control comboBox_E2 = this.ComboBox_E08;
			Size = new System.Drawing.Size(187, 21);
			comboBox_E2.Size = this.Size;
			this.ComboBox_E08.TabIndex = 22;
			this.ComboBox_E07.FormattingEnabled = true;
			global::System.Windows.Forms.Control comboBox_E3 = this.ComboBox_E07;
comboBox_E3.Location = new global::System.Drawing.Point(45, 204);
			this.ComboBox_E07.Name = "ComboBox_E07";
			global::System.Windows.Forms.Control comboBox_E4 = this.ComboBox_E07;
			Size = new System.Drawing.Size(187, 21);
			comboBox_E4.Size = this.Size;
			this.ComboBox_E07.TabIndex = 21;
			this.ComboBox_E06.FormattingEnabled = true;
			global::System.Windows.Forms.Control comboBox_E5 = this.ComboBox_E06;
comboBox_E5.Location = new global::System.Drawing.Point(45, 175);
			this.ComboBox_E06.Name = "ComboBox_E06";
			global::System.Windows.Forms.Control comboBox_E6 = this.ComboBox_E06;
			Size = new System.Drawing.Size(187, 21);
			comboBox_E6.Size = this.Size;
			this.ComboBox_E06.TabIndex = 20;
			this.ComboBox_E05.FormattingEnabled = true;
			global::System.Windows.Forms.Control comboBox_E7 = this.ComboBox_E05;
comboBox_E7.Location = new global::System.Drawing.Point(45, 146);
			this.ComboBox_E05.Name = "ComboBox_E05";
			global::System.Windows.Forms.Control comboBox_E8 = this.ComboBox_E05;
			Size = new System.Drawing.Size(187, 21);
			comboBox_E8.Size = this.Size;
			this.ComboBox_E05.TabIndex = 19;
			this.ComboBox_E04.FormattingEnabled = true;
			global::System.Windows.Forms.Control comboBox_E9 = this.ComboBox_E04;
comboBox_E9.Location = new global::System.Drawing.Point(45, 117);
			this.ComboBox_E04.Name = "ComboBox_E04";
			global::System.Windows.Forms.Control comboBox_E10 = this.ComboBox_E04;
			Size = new System.Drawing.Size(187, 21);
			comboBox_E10.Size = this.Size;
			this.ComboBox_E04.TabIndex = 18;
			this.ComboBox_E03.FormattingEnabled = true;
			global::System.Windows.Forms.Control comboBox_E11 = this.ComboBox_E03;
comboBox_E11.Location = new global::System.Drawing.Point(45, 88);
			this.ComboBox_E03.Name = "ComboBox_E03";
			global::System.Windows.Forms.Control comboBox_E12 = this.ComboBox_E03;
			Size = new System.Drawing.Size(187, 21);
			comboBox_E12.Size = this.Size;
			this.ComboBox_E03.TabIndex = 17;
			this.ComboBox_E02.FormattingEnabled = true;
			global::System.Windows.Forms.Control comboBox_E13 = this.ComboBox_E02;
comboBox_E13.Location = new global::System.Drawing.Point(45, 59);
			this.ComboBox_E02.Name = "ComboBox_E02";
			global::System.Windows.Forms.Control comboBox_E14 = this.ComboBox_E02;
			Size = new System.Drawing.Size(187, 21);
			comboBox_E14.Size = this.Size;
			this.ComboBox_E02.TabIndex = 16;
			this.ComboBox_E01.FormattingEnabled = true;
			global::System.Windows.Forms.Control comboBox_E15 = this.ComboBox_E01;
comboBox_E15.Location = new global::System.Drawing.Point(45, 30);
			this.ComboBox_E01.Name = "ComboBox_E01";
			global::System.Windows.Forms.Control comboBox_E16 = this.ComboBox_E01;
			Size = new System.Drawing.Size(187, 21);
			comboBox_E16.Size = this.Size;
			this.ComboBox_E01.TabIndex = 15;
			this.Label_E08.AutoSize = true;
			global::System.Windows.Forms.Control label_E = this.Label_E08;
label_E.Location = new global::System.Drawing.Point(10, 237);
			this.Label_E08.Name = "Label_E08";
			global::System.Windows.Forms.Control label_E2 = this.Label_E08;
			Size = new System.Drawing.Size(29, 13);
			label_E2.Size = this.Size;
			this.Label_E08.TabIndex = 9;
			this.Label_E08.Text = "E 08";
			this.Label_E07.AutoSize = true;
			global::System.Windows.Forms.Control label_E3 = this.Label_E07;
label_E3.Location = new global::System.Drawing.Point(10, 208);
			this.Label_E07.Name = "Label_E07";
			global::System.Windows.Forms.Control label_E4 = this.Label_E07;
			Size = new System.Drawing.Size(29, 13);
			label_E4.Size = this.Size;
			this.Label_E07.TabIndex = 9;
			this.Label_E07.Text = "E 07";
			this.Label_E06.AutoSize = true;
			global::System.Windows.Forms.Control label_E5 = this.Label_E06;
label_E5.Location = new global::System.Drawing.Point(10, 179);
			this.Label_E06.Name = "Label_E06";
			global::System.Windows.Forms.Control label_E6 = this.Label_E06;
			Size = new System.Drawing.Size(29, 13);
			label_E6.Size = this.Size;
			this.Label_E06.TabIndex = 9;
			this.Label_E06.Text = "E 06";
			this.Label_E05.AutoSize = true;
			global::System.Windows.Forms.Control label_E7 = this.Label_E05;
label_E7.Location = new global::System.Drawing.Point(10, 150);
			this.Label_E05.Name = "Label_E05";
			global::System.Windows.Forms.Control label_E8 = this.Label_E05;
			Size = new System.Drawing.Size(29, 13);
			label_E8.Size = this.Size;
			this.Label_E05.TabIndex = 9;
			this.Label_E05.Text = "E 05";
			this.Label_E04.AutoSize = true;
			global::System.Windows.Forms.Control label_E9 = this.Label_E04;
label_E9.Location = new global::System.Drawing.Point(10, 121);
			this.Label_E04.Name = "Label_E04";
			global::System.Windows.Forms.Control label_E10 = this.Label_E04;
			Size = new System.Drawing.Size(29, 13);
			label_E10.Size = this.Size;
			this.Label_E04.TabIndex = 9;
			this.Label_E04.Text = "E 04";
			this.Label_E03.AutoSize = true;
			global::System.Windows.Forms.Control label_E11 = this.Label_E03;
label_E11.Location = new global::System.Drawing.Point(10, 92);
			this.Label_E03.Name = "Label_E03";
			global::System.Windows.Forms.Control label_E12 = this.Label_E03;
			Size = new System.Drawing.Size(29, 13);
			label_E12.Size = this.Size;
			this.Label_E03.TabIndex = 9;
			this.Label_E03.Text = "E 03";
			this.Label_E02.AutoSize = true;
			global::System.Windows.Forms.Control label_E13 = this.Label_E02;
label_E13.Location = new global::System.Drawing.Point(10, 63);
			this.Label_E02.Name = "Label_E02";
			global::System.Windows.Forms.Control label_E14 = this.Label_E02;
			Size = new System.Drawing.Size(29, 13);
			label_E14.Size = this.Size;
			this.Label_E02.TabIndex = 9;
			this.Label_E02.Text = "E 02";
			this.Label_E01.AutoSize = true;
			global::System.Windows.Forms.Control label_E15 = this.Label_E01;
label_E15.Location = new global::System.Drawing.Point(10, 34);
			this.Label_E01.Name = "Label_E01";
			global::System.Windows.Forms.Control label_E16 = this.Label_E01;
			Size = new System.Drawing.Size(29, 13);
			label_E16.Size = this.Size;
			this.Label_E01.TabIndex = 9;
			this.Label_E01.Text = "E 01";
			global::System.Drawing.SizeF autoScaleDimensions;
			autoScaleDimensions = new global::System.Drawing.SizeF(6f, 13f);
			this.AutoScaleDimensions = autoScaleDimensions;
			this.AutoScaleMode = AutoScaleMode.Font;
			Size = new System.Drawing.Size(963, 476);
			this.ClientSize = Size;
			this.Controls.Add(this.grupo_programacao_io);
			this.Controls.Add(this.Grupo_ctrl);
			this.Controls.Add(this.grupo_parametros_gerais);
			this.FormBorderStyle = FormBorderStyle.None;
this.Location = new global::System.Drawing.Point(160, 2);
			this.Name = "Equip_VA220_conf";
			this.StartPosition = global::System.Windows.Forms.FormStartPosition.Manual;
			this.Text = "Equipamento VA 220 - Configuração";
			this.grupo_parametros_gerais.ResumeLayout(false);
			this.grupo_parametros_gerais.PerformLayout();
			this.Grupo_ctrl.ResumeLayout(false);
			this.Grupo_ctrl.PerformLayout();
			this.grupo_programacao_io.ResumeLayout(false);
			this.GroupBox2.ResumeLayout(false);
			this.GroupBox2.PerformLayout();
			this.GroupBox1.ResumeLayout(false);
			this.GroupBox1.PerformLayout();
			this.ResumeLayout(false);
		}

		// Token: 0x04001A42 RID: 6722
		private global::System.ComponentModel.IContainer components;
	}
}
