using System.Drawing;
using System.Windows.Forms;
﻿namespace iS800
{
	// Token: 0x0200007E RID: 126
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class Equip_101_cal : global::System.Windows.Forms.Form
	{
		// Token: 0x06001A69 RID: 6761 RVA: 0x003C10F8 File Offset: 0x003BF4F8
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				if (disposing && this.components != null)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x06001A6A RID: 6762 RVA: 0x003C1138 File Offset: 0x003BF538
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.Grupo_ent_digitais = new global::System.Windows.Forms.GroupBox();
			this.CheckBox_ED8 = new global::System.Windows.Forms.CheckBox();
			this.CheckBox_ED4 = new global::System.Windows.Forms.CheckBox();
			this.CheckBox_ED7 = new global::System.Windows.Forms.CheckBox();
			this.CheckBox_ED3 = new global::System.Windows.Forms.CheckBox();
			this.CheckBox_ED6 = new global::System.Windows.Forms.CheckBox();
			this.CheckBox_ED2 = new global::System.Windows.Forms.CheckBox();
			this.CheckBox_ED5 = new global::System.Windows.Forms.CheckBox();
			this.CheckBox_ED1 = new global::System.Windows.Forms.CheckBox();
			this.Grupo_calibracao = new global::System.Windows.Forms.GroupBox();
			this.Valor_ganho_4 = new global::System.Windows.Forms.TextBox();
			this.Valor_ganho_3 = new global::System.Windows.Forms.TextBox();
			this.Valor_ganho_2 = new global::System.Windows.Forms.TextBox();
			this.Valor_ganho_1 = new global::System.Windows.Forms.TextBox();
			this.Valor_zero_4 = new global::System.Windows.Forms.TextBox();
			this.Valor_zero_3 = new global::System.Windows.Forms.TextBox();
			this.Valor_zero_2 = new global::System.Windows.Forms.TextBox();
			this.Valor_zero_1 = new global::System.Windows.Forms.TextBox();
			this.Label_ganho_4 = new global::System.Windows.Forms.Label();
			this.Label_ganho_3 = new global::System.Windows.Forms.Label();
			this.Label_zero_4 = new global::System.Windows.Forms.Label();
			this.Label_ganho_2 = new global::System.Windows.Forms.Label();
			this.Label_zero_3 = new global::System.Windows.Forms.Label();
			this.Label_ganho_1 = new global::System.Windows.Forms.Label();
			this.Label_zero_2 = new global::System.Windows.Forms.Label();
			this.Label_zero_1 = new global::System.Windows.Forms.Label();
			this.Grupo_cont_sem_nor = new global::System.Windows.Forms.GroupBox();
			this.Valor_sem_nor_EA4 = new global::System.Windows.Forms.TextBox();
			this.Valor_sem_nor_EA3 = new global::System.Windows.Forms.TextBox();
			this.Valor_sem_nor_EA2 = new global::System.Windows.Forms.TextBox();
			this.Valor_sem_nor_EA1 = new global::System.Windows.Forms.TextBox();
			this.Label_sem_nor_EA4 = new global::System.Windows.Forms.Label();
			this.Label_sem_nor_EA3 = new global::System.Windows.Forms.Label();
			this.Label_sem_nor_EA2 = new global::System.Windows.Forms.Label();
			this.Label_sem_nor_EA1 = new global::System.Windows.Forms.Label();
			this.Grupo_cont_normal = new global::System.Windows.Forms.GroupBox();
			this.Valor_nor_EA4 = new global::System.Windows.Forms.TextBox();
			this.Valor_nor_EA3 = new global::System.Windows.Forms.TextBox();
			this.Valor_nor_EA2 = new global::System.Windows.Forms.TextBox();
			this.Valor_nor_EA1 = new global::System.Windows.Forms.TextBox();
			this.Label_nor_EA4 = new global::System.Windows.Forms.Label();
			this.Label_nor_EA3 = new global::System.Windows.Forms.Label();
			this.Label_nor_EA2 = new global::System.Windows.Forms.Label();
			this.Label_nor_EA1 = new global::System.Windows.Forms.Label();
			this.Box_Msg = new global::System.Windows.Forms.TextBox();
			this.Tela_end_estacao = new global::System.Windows.Forms.NumericUpDown();
			this.Label_end_estacao = new global::System.Windows.Forms.Label();
			this.Grupo_medidas_eng = new global::System.Windows.Forms.GroupBox();
			this.GroupBox1 = new global::System.Windows.Forms.GroupBox();
			this.Label_defeito_sensor = new global::System.Windows.Forms.Label();
			this.Label_arrombamento = new global::System.Windows.Forms.Label();
			this.Label_vazio = new global::System.Windows.Forms.Label();
			this.Label_transbordo = new global::System.Windows.Forms.Label();
			this.Label_em_bat = new global::System.Windows.Forms.Label();
			this.Label_nivel_eng = new global::System.Windows.Forms.Label();
			this.Tela_nivel = new global::System.Windows.Forms.TextBox();
			this.Grupo_ctrl_com = new global::System.Windows.Forms.GroupBox();
			this.Comando_hab_cal = new global::System.Windows.Forms.Button();
			this.Grupo_controle_calibracao = new global::System.Windows.Forms.GroupBox();
			this.Button_20_5ma = new global::System.Windows.Forms.Button();
			this.Button_3_5ma = new global::System.Windows.Forms.Button();
			this.Valor_cal_end = new global::System.Windows.Forms.NumericUpDown();
			this.Valor_canal_calibracao = new global::System.Windows.Forms.NumericUpDown();
			this.Label_end_cal = new global::System.Windows.Forms.Label();
			this.Label_canal = new global::System.Windows.Forms.Label();
			this.Grupo_ent_digitais.SuspendLayout();
			this.Grupo_calibracao.SuspendLayout();
			this.Grupo_cont_sem_nor.SuspendLayout();
			this.Grupo_cont_normal.SuspendLayout();
			
			this.Grupo_medidas_eng.SuspendLayout();
			this.GroupBox1.SuspendLayout();
			this.Grupo_ctrl_com.SuspendLayout();
			this.Grupo_controle_calibracao.SuspendLayout();
			
			
			this.SuspendLayout();
			this.Grupo_ent_digitais.Controls.Add(this.CheckBox_ED8);
			this.Grupo_ent_digitais.Controls.Add(this.CheckBox_ED4);
			this.Grupo_ent_digitais.Controls.Add(this.CheckBox_ED7);
			this.Grupo_ent_digitais.Controls.Add(this.CheckBox_ED3);
			this.Grupo_ent_digitais.Controls.Add(this.CheckBox_ED6);
			this.Grupo_ent_digitais.Controls.Add(this.CheckBox_ED2);
			this.Grupo_ent_digitais.Controls.Add(this.CheckBox_ED5);
			this.Grupo_ent_digitais.Controls.Add(this.CheckBox_ED1);
			this.Grupo_ent_digitais.FlatStyle = FlatStyle.System;
			global::System.Windows.Forms.Control grupo_ent_digitais = this.Grupo_ent_digitais;
			grupo_ent_digitais.Location = new global::System.Drawing.Point(506, 198);
			this.Grupo_ent_digitais.Name = "Grupo_ent_digitais";
			global::System.Windows.Forms.Control grupo_ent_digitais2 = this.Grupo_ent_digitais;
			grupo_ent_digitais2.Size = new global::System.Drawing.Size(118, 137);
			this.Grupo_ent_digitais.TabIndex = 8;
			this.Grupo_ent_digitais.TabStop = false;
			this.Grupo_ent_digitais.Text = "Entradas Digitais";
			this.CheckBox_ED8.AutoCheck = false;
			this.CheckBox_ED8.AutoSize = true;
			global::System.Windows.Forms.Control checkBox_ED = this.CheckBox_ED8;
checkBox_ED.Location = new global::System.Drawing.Point(62, 95);
			this.CheckBox_ED8.Name = "CheckBox_ED8";
			global::System.Windows.Forms.Control checkBox_ED2 = this.CheckBox_ED8;
			Size = new System.Drawing.Size(50, 17);
			checkBox_ED2.Size = this.Size;
			this.CheckBox_ED8.TabIndex = 0;
			this.CheckBox_ED8.TabStop = false;
			this.CheckBox_ED8.Text = "ED 8";
			this.CheckBox_ED8.UseVisualStyleBackColor = true;
			this.CheckBox_ED4.AutoCheck = false;
			this.CheckBox_ED4.AutoSize = true;
			global::System.Windows.Forms.Control checkBox_ED3 = this.CheckBox_ED4;
checkBox_ED3.Location = new global::System.Drawing.Point(6, 95);
			this.CheckBox_ED4.Name = "CheckBox_ED4";
			global::System.Windows.Forms.Control checkBox_ED4 = this.CheckBox_ED4;
			Size = new System.Drawing.Size(50, 17);
			checkBox_ED4.Size = this.Size;
			this.CheckBox_ED4.TabIndex = 0;
			this.CheckBox_ED4.TabStop = false;
			this.CheckBox_ED4.Text = "ED 4";
			this.CheckBox_ED4.UseVisualStyleBackColor = true;
			this.CheckBox_ED7.AutoCheck = false;
			this.CheckBox_ED7.AutoSize = true;
			global::System.Windows.Forms.Control checkBox_ED5 = this.CheckBox_ED7;
checkBox_ED5.Location = new global::System.Drawing.Point(62, 72);
			this.CheckBox_ED7.Name = "CheckBox_ED7";
			global::System.Windows.Forms.Control checkBox_ED6 = this.CheckBox_ED7;
			Size = new System.Drawing.Size(50, 17);
			checkBox_ED6.Size = this.Size;
			this.CheckBox_ED7.TabIndex = 0;
			this.CheckBox_ED7.TabStop = false;
			this.CheckBox_ED7.Text = "ED 7";
			this.CheckBox_ED7.UseVisualStyleBackColor = true;
			this.CheckBox_ED3.AutoCheck = false;
			this.CheckBox_ED3.AutoSize = true;
			global::System.Windows.Forms.Control checkBox_ED7 = this.CheckBox_ED3;
checkBox_ED7.Location = new global::System.Drawing.Point(6, 72);
			this.CheckBox_ED3.Name = "CheckBox_ED3";
			global::System.Windows.Forms.Control checkBox_ED8 = this.CheckBox_ED3;
			Size = new System.Drawing.Size(50, 17);
			checkBox_ED8.Size = this.Size;
			this.CheckBox_ED3.TabIndex = 0;
			this.CheckBox_ED3.TabStop = false;
			this.CheckBox_ED3.Text = "ED 3";
			this.CheckBox_ED3.UseVisualStyleBackColor = true;
			this.CheckBox_ED6.AutoCheck = false;
			this.CheckBox_ED6.AutoSize = true;
			global::System.Windows.Forms.Control checkBox_ED9 = this.CheckBox_ED6;
checkBox_ED9.Location = new global::System.Drawing.Point(62, 49);
			this.CheckBox_ED6.Name = "CheckBox_ED6";
			global::System.Windows.Forms.Control checkBox_ED10 = this.CheckBox_ED6;
			Size = new System.Drawing.Size(50, 17);
			checkBox_ED10.Size = this.Size;
			this.CheckBox_ED6.TabIndex = 0;
			this.CheckBox_ED6.TabStop = false;
			this.CheckBox_ED6.Text = "ED 6";
			this.CheckBox_ED6.UseVisualStyleBackColor = true;
			this.CheckBox_ED2.AutoCheck = false;
			this.CheckBox_ED2.AutoSize = true;
			global::System.Windows.Forms.Control checkBox_ED11 = this.CheckBox_ED2;
checkBox_ED11.Location = new global::System.Drawing.Point(6, 49);
			this.CheckBox_ED2.Name = "CheckBox_ED2";
			global::System.Windows.Forms.Control checkBox_ED12 = this.CheckBox_ED2;
			Size = new System.Drawing.Size(50, 17);
			checkBox_ED12.Size = this.Size;
			this.CheckBox_ED2.TabIndex = 0;
			this.CheckBox_ED2.TabStop = false;
			this.CheckBox_ED2.Text = "ED 2";
			this.CheckBox_ED2.UseVisualStyleBackColor = true;
			this.CheckBox_ED5.AutoCheck = false;
			this.CheckBox_ED5.AutoSize = true;
			global::System.Windows.Forms.Control checkBox_ED13 = this.CheckBox_ED5;
checkBox_ED13.Location = new global::System.Drawing.Point(62, 27);
			this.CheckBox_ED5.Name = "CheckBox_ED5";
			global::System.Windows.Forms.Control checkBox_ED14 = this.CheckBox_ED5;
			Size = new System.Drawing.Size(50, 17);
			checkBox_ED14.Size = this.Size;
			this.CheckBox_ED5.TabIndex = 0;
			this.CheckBox_ED5.TabStop = false;
			this.CheckBox_ED5.Text = "ED 5";
			this.CheckBox_ED5.UseVisualStyleBackColor = true;
			this.CheckBox_ED1.AutoCheck = false;
			this.CheckBox_ED1.AutoSize = true;
			global::System.Windows.Forms.Control checkBox_ED15 = this.CheckBox_ED1;
checkBox_ED15.Location = new global::System.Drawing.Point(6, 27);
			this.CheckBox_ED1.Name = "CheckBox_ED1";
			global::System.Windows.Forms.Control checkBox_ED16 = this.CheckBox_ED1;
			Size = new System.Drawing.Size(50, 17);
			checkBox_ED16.Size = this.Size;
			this.CheckBox_ED1.TabIndex = 0;
			this.CheckBox_ED1.TabStop = false;
			this.CheckBox_ED1.Text = "ED 1";
			this.CheckBox_ED1.UseVisualStyleBackColor = true;
			this.Grupo_calibracao.Controls.Add(this.Valor_ganho_4);
			this.Grupo_calibracao.Controls.Add(this.Valor_ganho_3);
			this.Grupo_calibracao.Controls.Add(this.Valor_ganho_2);
			this.Grupo_calibracao.Controls.Add(this.Valor_ganho_1);
			this.Grupo_calibracao.Controls.Add(this.Valor_zero_4);
			this.Grupo_calibracao.Controls.Add(this.Valor_zero_3);
			this.Grupo_calibracao.Controls.Add(this.Valor_zero_2);
			this.Grupo_calibracao.Controls.Add(this.Valor_zero_1);
			this.Grupo_calibracao.Controls.Add(this.Label_ganho_4);
			this.Grupo_calibracao.Controls.Add(this.Label_ganho_3);
			this.Grupo_calibracao.Controls.Add(this.Label_zero_4);
			this.Grupo_calibracao.Controls.Add(this.Label_ganho_2);
			this.Grupo_calibracao.Controls.Add(this.Label_zero_3);
			this.Grupo_calibracao.Controls.Add(this.Label_ganho_1);
			this.Grupo_calibracao.Controls.Add(this.Label_zero_2);
			this.Grupo_calibracao.Controls.Add(this.Label_zero_1);
			global::System.Windows.Forms.Control grupo_calibracao = this.Grupo_calibracao;
grupo_calibracao.Location = new global::System.Drawing.Point(49, 341);
			this.Grupo_calibracao.Name = "Grupo_calibracao";
			global::System.Windows.Forms.Control grupo_calibracao2 = this.Grupo_calibracao;
			Size = new System.Drawing.Size(576, 126);
			grupo_calibracao2.Size = this.Size;
			this.Grupo_calibracao.TabIndex = 7;
			this.Grupo_calibracao.TabStop = false;
			this.Grupo_calibracao.Text = "Fatores de calibração";
			this.Valor_ganho_4.AcceptsReturn = true;
			this.Valor_ganho_4.BackColor = global::System.Drawing.SystemColors.ButtonHighlight;
			global::System.Windows.Forms.Control valor_ganho_ = this.Valor_ganho_4;
valor_ganho_.Location = new global::System.Drawing.Point(448, 94);
			this.Valor_ganho_4.Name = "Valor_ganho_4";
			this.Valor_ganho_4.ReadOnly = true;
			global::System.Windows.Forms.Control valor_ganho_2 = this.Valor_ganho_4;
			Size = new System.Drawing.Size(90, 20);
			valor_ganho_2.Size = this.Size;
			this.Valor_ganho_4.TabIndex = 10;
			this.Valor_ganho_4.TabStop = false;
			this.Valor_ganho_4.TextAlign = HorizontalAlignment.Center;
			this.Valor_ganho_3.AcceptsReturn = true;
			this.Valor_ganho_3.BackColor = global::System.Drawing.SystemColors.ButtonHighlight;
			global::System.Windows.Forms.Control valor_ganho_3 = this.Valor_ganho_3;
valor_ganho_3.Location = new global::System.Drawing.Point(448, 71);
			this.Valor_ganho_3.Name = "Valor_ganho_3";
			this.Valor_ganho_3.ReadOnly = true;
			global::System.Windows.Forms.Control valor_ganho_4 = this.Valor_ganho_3;
			Size = new System.Drawing.Size(90, 20);
			valor_ganho_4.Size = this.Size;
			this.Valor_ganho_3.TabIndex = 9;
			this.Valor_ganho_3.TabStop = false;
			this.Valor_ganho_3.TextAlign = HorizontalAlignment.Center;
			this.Valor_ganho_2.AcceptsReturn = true;
			this.Valor_ganho_2.BackColor = global::System.Drawing.SystemColors.ButtonHighlight;
			global::System.Windows.Forms.Control valor_ganho_5 = this.Valor_ganho_2;
valor_ganho_5.Location = new global::System.Drawing.Point(448, 47);
			this.Valor_ganho_2.Name = "Valor_ganho_2";
			this.Valor_ganho_2.ReadOnly = true;
			global::System.Windows.Forms.Control valor_ganho_6 = this.Valor_ganho_2;
			Size = new System.Drawing.Size(90, 20);
			valor_ganho_6.Size = this.Size;
			this.Valor_ganho_2.TabIndex = 8;
			this.Valor_ganho_2.TabStop = false;
			this.Valor_ganho_2.TextAlign = HorizontalAlignment.Center;
			this.Valor_ganho_1.AcceptsReturn = true;
			this.Valor_ganho_1.BackColor = global::System.Drawing.SystemColors.ButtonHighlight;
			global::System.Windows.Forms.Control valor_ganho_7 = this.Valor_ganho_1;
valor_ganho_7.Location = new global::System.Drawing.Point(448, 22);
			this.Valor_ganho_1.Name = "Valor_ganho_1";
			this.Valor_ganho_1.ReadOnly = true;
			global::System.Windows.Forms.Control valor_ganho_8 = this.Valor_ganho_1;
			Size = new System.Drawing.Size(90, 20);
			valor_ganho_8.Size = this.Size;
			this.Valor_ganho_1.TabIndex = 7;
			this.Valor_ganho_1.TabStop = false;
			this.Valor_ganho_1.TextAlign = HorizontalAlignment.Center;
			this.Valor_zero_4.AcceptsReturn = true;
			this.Valor_zero_4.BackColor = global::System.Drawing.SystemColors.ButtonHighlight;
			global::System.Windows.Forms.Control valor_zero_ = this.Valor_zero_4;
valor_zero_.Location = new global::System.Drawing.Point(154, 92);
			this.Valor_zero_4.Name = "Valor_zero_4";
			this.Valor_zero_4.ReadOnly = true;
			global::System.Windows.Forms.Control valor_zero_2 = this.Valor_zero_4;
			Size = new System.Drawing.Size(90, 20);
			valor_zero_2.Size = this.Size;
			this.Valor_zero_4.TabIndex = 6;
			this.Valor_zero_4.TabStop = false;
			this.Valor_zero_4.TextAlign = HorizontalAlignment.Center;
			this.Valor_zero_3.AcceptsReturn = true;
			this.Valor_zero_3.BackColor = global::System.Drawing.SystemColors.ButtonHighlight;
			global::System.Windows.Forms.Control valor_zero_3 = this.Valor_zero_3;
valor_zero_3.Location = new global::System.Drawing.Point(154, 69);
			this.Valor_zero_3.Name = "Valor_zero_3";
			this.Valor_zero_3.ReadOnly = true;
			global::System.Windows.Forms.Control valor_zero_4 = this.Valor_zero_3;
			Size = new System.Drawing.Size(90, 20);
			valor_zero_4.Size = this.Size;
			this.Valor_zero_3.TabIndex = 5;
			this.Valor_zero_3.TabStop = false;
			this.Valor_zero_3.TextAlign = HorizontalAlignment.Center;
			this.Valor_zero_2.AcceptsReturn = true;
			this.Valor_zero_2.BackColor = global::System.Drawing.SystemColors.ButtonHighlight;
			global::System.Windows.Forms.Control valor_zero_5 = this.Valor_zero_2;
valor_zero_5.Location = new global::System.Drawing.Point(154, 45);
			this.Valor_zero_2.Name = "Valor_zero_2";
			this.Valor_zero_2.ReadOnly = true;
			global::System.Windows.Forms.Control valor_zero_6 = this.Valor_zero_2;
			Size = new System.Drawing.Size(90, 20);
			valor_zero_6.Size = this.Size;
			this.Valor_zero_2.TabIndex = 4;
			this.Valor_zero_2.TabStop = false;
			this.Valor_zero_2.TextAlign = HorizontalAlignment.Center;
			this.Valor_zero_1.AcceptsReturn = true;
			this.Valor_zero_1.BackColor = global::System.Drawing.SystemColors.ButtonHighlight;
			global::System.Windows.Forms.Control valor_zero_7 = this.Valor_zero_1;
valor_zero_7.Location = new global::System.Drawing.Point(154, 23);
			this.Valor_zero_1.Name = "Valor_zero_1";
			this.Valor_zero_1.ReadOnly = true;
			global::System.Windows.Forms.Control valor_zero_8 = this.Valor_zero_1;
			Size = new System.Drawing.Size(90, 20);
			valor_zero_8.Size = this.Size;
			this.Valor_zero_1.TabIndex = 3;
			this.Valor_zero_1.TabStop = false;
			this.Valor_zero_1.TextAlign = HorizontalAlignment.Center;
			this.Label_ganho_4.AutoSize = true;
			global::System.Windows.Forms.Control label_ganho_ = this.Label_ganho_4;
label_ganho_.Location = new global::System.Drawing.Point(305, 98);
			this.Label_ganho_4.Name = "Label_ganho_4";
			global::System.Windows.Forms.Control label_ganho_2 = this.Label_ganho_4;
			Size = new System.Drawing.Size(128, 13);
			label_ganho_2.Size = this.Size;
			this.Label_ganho_4.TabIndex = 0;
			this.Label_ganho_4.Text = "Ent. Analog. 4 - GANHO :";
			this.Label_ganho_3.AutoSize = true;
			global::System.Windows.Forms.Control label_ganho_3 = this.Label_ganho_3;
label_ganho_3.Location = new global::System.Drawing.Point(305, 75);
			this.Label_ganho_3.Name = "Label_ganho_3";
			global::System.Windows.Forms.Control label_ganho_4 = this.Label_ganho_3;
			Size = new System.Drawing.Size(128, 13);
			label_ganho_4.Size = this.Size;
			this.Label_ganho_3.TabIndex = 0;
			this.Label_ganho_3.Text = "Ent. Analog. 3 - GANHO :";
			this.Label_zero_4.AutoSize = true;
			global::System.Windows.Forms.Control label_zero_ = this.Label_zero_4;
label_zero_.Location = new global::System.Drawing.Point(29, 96);
			this.Label_zero_4.Name = "Label_zero_4";
			global::System.Windows.Forms.Control label_zero_2 = this.Label_zero_4;
			Size = new System.Drawing.Size(119, 13);
			label_zero_2.Size = this.Size;
			this.Label_zero_4.TabIndex = 0;
			this.Label_zero_4.Text = "Ent. Analog. 4 - ZERO :";
			this.Label_ganho_2.AutoSize = true;
			global::System.Windows.Forms.Control label_ganho_5 = this.Label_ganho_2;
label_ganho_5.Location = new global::System.Drawing.Point(305, 51);
			this.Label_ganho_2.Name = "Label_ganho_2";
			global::System.Windows.Forms.Control label_ganho_6 = this.Label_ganho_2;
			Size = new System.Drawing.Size(128, 13);
			label_ganho_6.Size = this.Size;
			this.Label_ganho_2.TabIndex = 0;
			this.Label_ganho_2.Text = "Ent. Analog. 2 - GANHO :";
			this.Label_zero_3.AutoSize = true;
			global::System.Windows.Forms.Control label_zero_3 = this.Label_zero_3;
label_zero_3.Location = new global::System.Drawing.Point(29, 73);
			this.Label_zero_3.Name = "Label_zero_3";
			global::System.Windows.Forms.Control label_zero_4 = this.Label_zero_3;
			Size = new System.Drawing.Size(119, 13);
			label_zero_4.Size = this.Size;
			this.Label_zero_3.TabIndex = 0;
			this.Label_zero_3.Text = "Ent. Analog. 3 - ZERO :";
			this.Label_ganho_1.AutoSize = true;
			global::System.Windows.Forms.Control label_ganho_7 = this.Label_ganho_1;
label_ganho_7.Location = new global::System.Drawing.Point(305, 26);
			this.Label_ganho_1.Name = "Label_ganho_1";
			global::System.Windows.Forms.Control label_ganho_8 = this.Label_ganho_1;
			Size = new System.Drawing.Size(128, 13);
			label_ganho_8.Size = this.Size;
			this.Label_ganho_1.TabIndex = 0;
			this.Label_ganho_1.Text = "Ent. Analog. 1 - GANHO :";
			this.Label_zero_2.AutoSize = true;
			global::System.Windows.Forms.Control label_zero_5 = this.Label_zero_2;
label_zero_5.Location = new global::System.Drawing.Point(29, 49);
			this.Label_zero_2.Name = "Label_zero_2";
			global::System.Windows.Forms.Control label_zero_6 = this.Label_zero_2;
			Size = new System.Drawing.Size(119, 13);
			label_zero_6.Size = this.Size;
			this.Label_zero_2.TabIndex = 0;
			this.Label_zero_2.Text = "Ent. Analog. 2 - ZERO :";
			this.Label_zero_1.AutoSize = true;
			global::System.Windows.Forms.Control label_zero_7 = this.Label_zero_1;
label_zero_7.Location = new global::System.Drawing.Point(29, 27);
			this.Label_zero_1.Name = "Label_zero_1";
			global::System.Windows.Forms.Control label_zero_8 = this.Label_zero_1;
			Size = new System.Drawing.Size(119, 13);
			label_zero_8.Size = this.Size;
			this.Label_zero_1.TabIndex = 0;
			this.Label_zero_1.Text = "Ent. Analog. 1 - ZERO :";
			this.Grupo_cont_sem_nor.Controls.Add(this.Valor_sem_nor_EA4);
			this.Grupo_cont_sem_nor.Controls.Add(this.Valor_sem_nor_EA3);
			this.Grupo_cont_sem_nor.Controls.Add(this.Valor_sem_nor_EA2);
			this.Grupo_cont_sem_nor.Controls.Add(this.Valor_sem_nor_EA1);
			this.Grupo_cont_sem_nor.Controls.Add(this.Label_sem_nor_EA4);
			this.Grupo_cont_sem_nor.Controls.Add(this.Label_sem_nor_EA3);
			this.Grupo_cont_sem_nor.Controls.Add(this.Label_sem_nor_EA2);
			this.Grupo_cont_sem_nor.Controls.Add(this.Label_sem_nor_EA1);
			global::System.Windows.Forms.Control grupo_cont_sem_nor = this.Grupo_cont_sem_nor;
grupo_cont_sem_nor.Location = new global::System.Drawing.Point(49, 197);
			this.Grupo_cont_sem_nor.Name = "Grupo_cont_sem_nor";
			global::System.Windows.Forms.Control grupo_cont_sem_nor2 = this.Grupo_cont_sem_nor;
			Size = new System.Drawing.Size(214, 138);
			grupo_cont_sem_nor2.Size = this.Size;
			this.Grupo_cont_sem_nor.TabIndex = 5;
			this.Grupo_cont_sem_nor.TabStop = false;
			this.Grupo_cont_sem_nor.Text = "Contagens sem normalização";
			this.Valor_sem_nor_EA4.AcceptsReturn = true;
			this.Valor_sem_nor_EA4.BackColor = global::System.Drawing.SystemColors.ButtonHighlight;
			global::System.Windows.Forms.Control valor_sem_nor_EA = this.Valor_sem_nor_EA4;
valor_sem_nor_EA.Location = new global::System.Drawing.Point(99, 101);
			this.Valor_sem_nor_EA4.Name = "Valor_sem_nor_EA4";
			this.Valor_sem_nor_EA4.ReadOnly = true;
			global::System.Windows.Forms.Control valor_sem_nor_EA2 = this.Valor_sem_nor_EA4;
			Size = new System.Drawing.Size(90, 20);
			valor_sem_nor_EA2.Size = this.Size;
			this.Valor_sem_nor_EA4.TabIndex = 2;
			this.Valor_sem_nor_EA4.TabStop = false;
			this.Valor_sem_nor_EA4.TextAlign = HorizontalAlignment.Center;
			this.Valor_sem_nor_EA3.BackColor = global::System.Drawing.SystemColors.ButtonHighlight;
			global::System.Windows.Forms.Control valor_sem_nor_EA3 = this.Valor_sem_nor_EA3;
valor_sem_nor_EA3.Location = new global::System.Drawing.Point(99, 75);
			this.Valor_sem_nor_EA3.Name = "Valor_sem_nor_EA3";
			this.Valor_sem_nor_EA3.ReadOnly = true;
			global::System.Windows.Forms.Control valor_sem_nor_EA4 = this.Valor_sem_nor_EA3;
			Size = new System.Drawing.Size(90, 20);
			valor_sem_nor_EA4.Size = this.Size;
			this.Valor_sem_nor_EA3.TabIndex = 2;
			this.Valor_sem_nor_EA3.TabStop = false;
			this.Valor_sem_nor_EA3.TextAlign = HorizontalAlignment.Center;
			this.Valor_sem_nor_EA2.BackColor = global::System.Drawing.SystemColors.ButtonHighlight;
			global::System.Windows.Forms.Control valor_sem_nor_EA5 = this.Valor_sem_nor_EA2;
valor_sem_nor_EA5.Location = new global::System.Drawing.Point(99, 49);
			this.Valor_sem_nor_EA2.Name = "Valor_sem_nor_EA2";
			this.Valor_sem_nor_EA2.ReadOnly = true;
			global::System.Windows.Forms.Control valor_sem_nor_EA6 = this.Valor_sem_nor_EA2;
			Size = new System.Drawing.Size(90, 20);
			valor_sem_nor_EA6.Size = this.Size;
			this.Valor_sem_nor_EA2.TabIndex = 2;
			this.Valor_sem_nor_EA2.TabStop = false;
			this.Valor_sem_nor_EA2.TextAlign = HorizontalAlignment.Center;
			this.Valor_sem_nor_EA1.BackColor = global::System.Drawing.SystemColors.ButtonHighlight;
			global::System.Windows.Forms.Control valor_sem_nor_EA7 = this.Valor_sem_nor_EA1;
valor_sem_nor_EA7.Location = new global::System.Drawing.Point(99, 23);
			this.Valor_sem_nor_EA1.Name = "Valor_sem_nor_EA1";
			this.Valor_sem_nor_EA1.ReadOnly = true;
			global::System.Windows.Forms.Control valor_sem_nor_EA8 = this.Valor_sem_nor_EA1;
			Size = new System.Drawing.Size(90, 20);
			valor_sem_nor_EA8.Size = this.Size;
			this.Valor_sem_nor_EA1.TabIndex = 1;
			this.Valor_sem_nor_EA1.TabStop = false;
			this.Valor_sem_nor_EA1.TextAlign = HorizontalAlignment.Center;
			this.Label_sem_nor_EA4.AutoSize = true;
			global::System.Windows.Forms.Control label_sem_nor_EA = this.Label_sem_nor_EA4;
label_sem_nor_EA.Location = new global::System.Drawing.Point(13, 105);
			this.Label_sem_nor_EA4.Name = "Label_sem_nor_EA4";
			global::System.Windows.Forms.Control label_sem_nor_EA2 = this.Label_sem_nor_EA4;
			Size = new System.Drawing.Size(80, 13);
			label_sem_nor_EA2.Size = this.Size;
			this.Label_sem_nor_EA4.TabIndex = 0;
			this.Label_sem_nor_EA4.Text = "Ent. Analog. 4 :";
			this.Label_sem_nor_EA3.AutoSize = true;
			global::System.Windows.Forms.Control label_sem_nor_EA3 = this.Label_sem_nor_EA3;
label_sem_nor_EA3.Location = new global::System.Drawing.Point(13, 79);
			this.Label_sem_nor_EA3.Name = "Label_sem_nor_EA3";
			global::System.Windows.Forms.Control label_sem_nor_EA4 = this.Label_sem_nor_EA3;
			Size = new System.Drawing.Size(80, 13);
			label_sem_nor_EA4.Size = this.Size;
			this.Label_sem_nor_EA3.TabIndex = 0;
			this.Label_sem_nor_EA3.Text = "Ent. Analog. 3 :";
			this.Label_sem_nor_EA2.AutoSize = true;
			global::System.Windows.Forms.Control label_sem_nor_EA5 = this.Label_sem_nor_EA2;
label_sem_nor_EA5.Location = new global::System.Drawing.Point(13, 53);
			this.Label_sem_nor_EA2.Name = "Label_sem_nor_EA2";
			global::System.Windows.Forms.Control label_sem_nor_EA6 = this.Label_sem_nor_EA2;
			Size = new System.Drawing.Size(80, 13);
			label_sem_nor_EA6.Size = this.Size;
			this.Label_sem_nor_EA2.TabIndex = 0;
			this.Label_sem_nor_EA2.Text = "Ent. Analog. 2 :";
			this.Label_sem_nor_EA1.AutoSize = true;
			global::System.Windows.Forms.Control label_sem_nor_EA7 = this.Label_sem_nor_EA1;
label_sem_nor_EA7.Location = new global::System.Drawing.Point(13, 27);
			this.Label_sem_nor_EA1.Name = "Label_sem_nor_EA1";
			global::System.Windows.Forms.Control label_sem_nor_EA8 = this.Label_sem_nor_EA1;
			Size = new System.Drawing.Size(80, 13);
			label_sem_nor_EA8.Size = this.Size;
			this.Label_sem_nor_EA1.TabIndex = 0;
			this.Label_sem_nor_EA1.Text = "Ent. Analog. 1 :";
			this.Grupo_cont_normal.Controls.Add(this.Valor_nor_EA4);
			this.Grupo_cont_normal.Controls.Add(this.Valor_nor_EA3);
			this.Grupo_cont_normal.Controls.Add(this.Valor_nor_EA2);
			this.Grupo_cont_normal.Controls.Add(this.Valor_nor_EA1);
			this.Grupo_cont_normal.Controls.Add(this.Label_nor_EA4);
			this.Grupo_cont_normal.Controls.Add(this.Label_nor_EA3);
			this.Grupo_cont_normal.Controls.Add(this.Label_nor_EA2);
			this.Grupo_cont_normal.Controls.Add(this.Label_nor_EA1);
			global::System.Windows.Forms.Control grupo_cont_normal = this.Grupo_cont_normal;
grupo_cont_normal.Location = new global::System.Drawing.Point(277, 197);
			this.Grupo_cont_normal.Name = "Grupo_cont_normal";
			global::System.Windows.Forms.Control grupo_cont_normal2 = this.Grupo_cont_normal;
			Size = new System.Drawing.Size(214, 138);
			grupo_cont_normal2.Size = this.Size;
			this.Grupo_cont_normal.TabIndex = 6;
			this.Grupo_cont_normal.TabStop = false;
			this.Grupo_cont_normal.Text = "Contagens normalizadas";
			this.Valor_nor_EA4.BackColor = global::System.Drawing.SystemColors.ButtonHighlight;
			global::System.Windows.Forms.Control valor_nor_EA = this.Valor_nor_EA4;
valor_nor_EA.Location = new global::System.Drawing.Point(100, 101);
			this.Valor_nor_EA4.Name = "Valor_nor_EA4";
			this.Valor_nor_EA4.ReadOnly = true;
			global::System.Windows.Forms.Control valor_nor_EA2 = this.Valor_nor_EA4;
			Size = new System.Drawing.Size(90, 20);
			valor_nor_EA2.Size = this.Size;
			this.Valor_nor_EA4.TabIndex = 2;
			this.Valor_nor_EA4.TabStop = false;
			this.Valor_nor_EA4.TextAlign = HorizontalAlignment.Center;
			this.Valor_nor_EA3.BackColor = global::System.Drawing.SystemColors.ButtonHighlight;
			global::System.Windows.Forms.Control valor_nor_EA3 = this.Valor_nor_EA3;
valor_nor_EA3.Location = new global::System.Drawing.Point(100, 75);
			this.Valor_nor_EA3.Name = "Valor_nor_EA3";
			this.Valor_nor_EA3.ReadOnly = true;
			global::System.Windows.Forms.Control valor_nor_EA4 = this.Valor_nor_EA3;
			Size = new System.Drawing.Size(90, 20);
			valor_nor_EA4.Size = this.Size;
			this.Valor_nor_EA3.TabIndex = 2;
			this.Valor_nor_EA3.TabStop = false;
			this.Valor_nor_EA3.TextAlign = HorizontalAlignment.Center;
			this.Valor_nor_EA2.BackColor = global::System.Drawing.SystemColors.ButtonHighlight;
			global::System.Windows.Forms.Control valor_nor_EA5 = this.Valor_nor_EA2;
valor_nor_EA5.Location = new global::System.Drawing.Point(100, 49);
			this.Valor_nor_EA2.Name = "Valor_nor_EA2";
			this.Valor_nor_EA2.ReadOnly = true;
			global::System.Windows.Forms.Control valor_nor_EA6 = this.Valor_nor_EA2;
			Size = new System.Drawing.Size(90, 20);
			valor_nor_EA6.Size = this.Size;
			this.Valor_nor_EA2.TabIndex = 2;
			this.Valor_nor_EA2.TabStop = false;
			this.Valor_nor_EA2.TextAlign = HorizontalAlignment.Center;
			this.Valor_nor_EA1.BackColor = global::System.Drawing.SystemColors.ButtonHighlight;
			global::System.Windows.Forms.Control valor_nor_EA7 = this.Valor_nor_EA1;
valor_nor_EA7.Location = new global::System.Drawing.Point(100, 23);
			this.Valor_nor_EA1.Name = "Valor_nor_EA1";
			this.Valor_nor_EA1.ReadOnly = true;
			global::System.Windows.Forms.Control valor_nor_EA8 = this.Valor_nor_EA1;
			Size = new System.Drawing.Size(90, 20);
			valor_nor_EA8.Size = this.Size;
			this.Valor_nor_EA1.TabIndex = 1;
			this.Valor_nor_EA1.TabStop = false;
			this.Valor_nor_EA1.TextAlign = HorizontalAlignment.Center;
			this.Label_nor_EA4.AutoSize = true;
			global::System.Windows.Forms.Control label_nor_EA = this.Label_nor_EA4;
label_nor_EA.Location = new global::System.Drawing.Point(14, 105);
			this.Label_nor_EA4.Name = "Label_nor_EA4";
			global::System.Windows.Forms.Control label_nor_EA2 = this.Label_nor_EA4;
			Size = new System.Drawing.Size(80, 13);
			label_nor_EA2.Size = this.Size;
			this.Label_nor_EA4.TabIndex = 0;
			this.Label_nor_EA4.Text = "Ent. Analog. 4 :";
			this.Label_nor_EA3.AutoSize = true;
			global::System.Windows.Forms.Control label_nor_EA3 = this.Label_nor_EA3;
label_nor_EA3.Location = new global::System.Drawing.Point(14, 79);
			this.Label_nor_EA3.Name = "Label_nor_EA3";
			global::System.Windows.Forms.Control label_nor_EA4 = this.Label_nor_EA3;
			Size = new System.Drawing.Size(80, 13);
			label_nor_EA4.Size = this.Size;
			this.Label_nor_EA3.TabIndex = 0;
			this.Label_nor_EA3.Text = "Ent. Analog. 3 :";
			this.Label_nor_EA2.AutoSize = true;
			global::System.Windows.Forms.Control label_nor_EA5 = this.Label_nor_EA2;
label_nor_EA5.Location = new global::System.Drawing.Point(14, 53);
			this.Label_nor_EA2.Name = "Label_nor_EA2";
			global::System.Windows.Forms.Control label_nor_EA6 = this.Label_nor_EA2;
			Size = new System.Drawing.Size(80, 13);
			label_nor_EA6.Size = this.Size;
			this.Label_nor_EA2.TabIndex = 0;
			this.Label_nor_EA2.Text = "Ent. Analog. 2 :";
			this.Label_nor_EA1.AutoSize = true;
			global::System.Windows.Forms.Control label_nor_EA7 = this.Label_nor_EA1;
label_nor_EA7.Location = new global::System.Drawing.Point(14, 27);
			this.Label_nor_EA1.Name = "Label_nor_EA1";
			global::System.Windows.Forms.Control label_nor_EA8 = this.Label_nor_EA1;
			Size = new System.Drawing.Size(80, 13);
			label_nor_EA8.Size = this.Size;
			this.Label_nor_EA1.TabIndex = 0;
			this.Label_nor_EA1.Text = "Ent. Analog. 1 :";
			global::System.Windows.Forms.Control box_Msg = this.Box_Msg;
box_Msg.Location = new global::System.Drawing.Point(16, 80);
			this.Box_Msg.Name = "Box_Msg";
			global::System.Windows.Forms.Control box_Msg2 = this.Box_Msg;
			Size = new System.Drawing.Size(181, 20);
			box_Msg2.Size = this.Size;
			this.Box_Msg.TabIndex = 10;
			this.Box_Msg.TextAlign = HorizontalAlignment.Right;
			global::System.Windows.Forms.Control tela_end_estacao = this.Tela_end_estacao;
tela_end_estacao.Location = new global::System.Drawing.Point(129, 33);
			global::System.Windows.Forms.NumericUpDown tela_end_estacao2 = this.Tela_end_estacao;
			decimal num;
			num = new decimal(new int[]
			{
				200,
				0,
				0,
				0
			});
			tela_end_estacao2.Maximum = num;
			this.Tela_end_estacao.Name = "Tela_end_estacao";
			global::System.Windows.Forms.Control tela_end_estacao3 = this.Tela_end_estacao;
			Size = new System.Drawing.Size(78, 20);
			tela_end_estacao3.Size = this.Size;
			this.Tela_end_estacao.TabIndex = 12;
			this.Tela_end_estacao.TextAlign = HorizontalAlignment.Right;
			this.Label_end_estacao.AutoSize = true;
			global::System.Windows.Forms.Control label_end_estacao = this.Label_end_estacao;
label_end_estacao.Location = new global::System.Drawing.Point(22, 35);
			this.Label_end_estacao.Name = "Label_end_estacao";
			global::System.Windows.Forms.Control label_end_estacao2 = this.Label_end_estacao;
			Size = new System.Drawing.Size(101, 13);
			label_end_estacao2.Size = this.Size;
			this.Label_end_estacao.TabIndex = 11;
			this.Label_end_estacao.Text = "Endereço Estação :";
			this.Grupo_medidas_eng.Controls.Add(this.GroupBox1);
			this.Grupo_medidas_eng.Controls.Add(this.Label_nivel_eng);
			this.Grupo_medidas_eng.Controls.Add(this.Tela_nivel);
			global::System.Windows.Forms.Control grupo_medidas_eng = this.Grupo_medidas_eng;
grupo_medidas_eng.Location = new global::System.Drawing.Point(277, 12);
			this.Grupo_medidas_eng.Name = "Grupo_medidas_eng";
			global::System.Windows.Forms.Control grupo_medidas_eng2 = this.Grupo_medidas_eng;
			Size = new System.Drawing.Size(347, 158);
			grupo_medidas_eng2.Size = this.Size;
			this.Grupo_medidas_eng.TabIndex = 14;
			this.Grupo_medidas_eng.TabStop = false;
			this.Grupo_medidas_eng.Text = "Medidas em Unidade de Engenharia e Alarmes";
			this.GroupBox1.Controls.Add(this.Label_defeito_sensor);
			this.GroupBox1.Controls.Add(this.Label_arrombamento);
			this.GroupBox1.Controls.Add(this.Label_vazio);
			this.GroupBox1.Controls.Add(this.Label_transbordo);
			this.GroupBox1.Controls.Add(this.Label_em_bat);
			global::System.Windows.Forms.Control groupBox = this.GroupBox1;
groupBox.Location = new global::System.Drawing.Point(18, 54);
			this.GroupBox1.Name = "GroupBox1";
			global::System.Windows.Forms.Control groupBox2 = this.GroupBox1;
			Size = new System.Drawing.Size(307, 82);
			groupBox2.Size = this.Size;
			this.GroupBox1.TabIndex = 4;
			this.GroupBox1.TabStop = false;
			this.GroupBox1.Text = "Alarmes";
			this.Label_defeito_sensor.AutoSize = true;
			this.Label_defeito_sensor.BackColor = global::System.Drawing.SystemColors.Control;
			this.Label_defeito_sensor.BorderStyle = BorderStyle.Fixed3D;
			global::System.Windows.Forms.Control label_defeito_sensor = this.Label_defeito_sensor;
label_defeito_sensor.Location = new global::System.Drawing.Point(210, 26);
			this.Label_defeito_sensor.Name = "Label_defeito_sensor";
			global::System.Windows.Forms.Control label_defeito_sensor2 = this.Label_defeito_sensor;
			Size = new System.Drawing.Size(75, 15);
			label_defeito_sensor2.Size = this.Size;
			this.Label_defeito_sensor.TabIndex = 8;
			this.Label_defeito_sensor.Text = " Falha sensor ";
			this.Label_defeito_sensor.TextAlign = ContentAlignment.MiddleRight;
			this.Label_arrombamento.AutoSize = true;
			this.Label_arrombamento.BackColor = global::System.Drawing.SystemColors.Control;
			this.Label_arrombamento.BorderStyle = BorderStyle.Fixed3D;
			global::System.Windows.Forms.Control label_arrombamento = this.Label_arrombamento;
label_arrombamento.Location = new global::System.Drawing.Point(26, 51);
			this.Label_arrombamento.Name = "Label_arrombamento";
			global::System.Windows.Forms.Control label_arrombamento2 = this.Label_arrombamento;
			Size = new System.Drawing.Size(77, 15);
			label_arrombamento2.Size = this.Size;
			this.Label_arrombamento.TabIndex = 7;
			this.Label_arrombamento.Text = "Arrombamento";
			this.Label_vazio.AutoSize = true;
			this.Label_vazio.BackColor = global::System.Drawing.SystemColors.Control;
			this.Label_vazio.BorderStyle = BorderStyle.Fixed3D;
			global::System.Windows.Forms.Control label_vazio = this.Label_vazio;
label_vazio.Location = new global::System.Drawing.Point(119, 51);
			this.Label_vazio.Name = "Label_vazio";
			global::System.Windows.Forms.Control label_vazio2 = this.Label_vazio;
			Size = new System.Drawing.Size(77, 15);
			label_vazio2.Size = this.Size;
			this.Label_vazio.TabIndex = 6;
			this.Label_vazio.Text = "       Vazio       ";
			this.Label_vazio.TextAlign = ContentAlignment.MiddleRight;
			this.Label_transbordo.AutoSize = true;
			this.Label_transbordo.BackColor = global::System.Drawing.SystemColors.Control;
			this.Label_transbordo.BorderStyle = BorderStyle.Fixed3D;
			global::System.Windows.Forms.Control label_transbordo = this.Label_transbordo;
label_transbordo.Location = new global::System.Drawing.Point(118, 26);
			this.Label_transbordo.Name = "Label_transbordo";
			global::System.Windows.Forms.Control label_transbordo2 = this.Label_transbordo;
			Size = new System.Drawing.Size(78, 15);
			label_transbordo2.Size = this.Size;
			this.Label_transbordo.TabIndex = 5;
			this.Label_transbordo.Text = "   Transbordo  ";
			this.Label_em_bat.AutoSize = true;
			this.Label_em_bat.BackColor = global::System.Drawing.Color.Gainsboro;
			this.Label_em_bat.BorderStyle = BorderStyle.Fixed3D;
			global::System.Windows.Forms.Control label_em_bat = this.Label_em_bat;
label_em_bat.Location = new global::System.Drawing.Point(26, 26);
			this.Label_em_bat.Name = "Label_em_bat";
			global::System.Windows.Forms.Control label_em_bat2 = this.Label_em_bat;
			Size = new System.Drawing.Size(78, 15);
			label_em_bat2.Size = this.Size;
			this.Label_em_bat.TabIndex = 4;
			this.Label_em_bat.Text = "   Em Bateria   ";
			this.Label_nivel_eng.AutoSize = true;
			global::System.Windows.Forms.Control label_nivel_eng = this.Label_nivel_eng;
label_nivel_eng.Location = new global::System.Drawing.Point(27, 31);
			this.Label_nivel_eng.Name = "Label_nivel_eng";
			global::System.Windows.Forms.Control label_nivel_eng2 = this.Label_nivel_eng;
			Size = new System.Drawing.Size(56, 13);
			label_nivel_eng2.Size = this.Size;
			this.Label_nivel_eng.TabIndex = 3;
			this.Label_nivel_eng.Text = "Nível (%) :";
			this.Tela_nivel.BackColor = global::System.Drawing.SystemColors.ButtonHighlight;
			global::System.Windows.Forms.Control tela_nivel = this.Tela_nivel;
tela_nivel.Location = new global::System.Drawing.Point(89, 28);
			this.Tela_nivel.Name = "Tela_nivel";
			this.Tela_nivel.ReadOnly = true;
			global::System.Windows.Forms.Control tela_nivel2 = this.Tela_nivel;
			Size = new System.Drawing.Size(66, 20);
			tela_nivel2.Size = this.Size;
			this.Tela_nivel.TabIndex = 1;
			this.Tela_nivel.TabStop = false;
			this.Tela_nivel.TextAlign = HorizontalAlignment.Center;
			this.Grupo_ctrl_com.Controls.Add(this.Box_Msg);
			this.Grupo_ctrl_com.Controls.Add(this.Comando_hab_cal);
			this.Grupo_ctrl_com.Controls.Add(this.Tela_end_estacao);
			this.Grupo_ctrl_com.Controls.Add(this.Label_end_estacao);
			global::System.Windows.Forms.Control grupo_ctrl_com = this.Grupo_ctrl_com;
grupo_ctrl_com.Location = new global::System.Drawing.Point(49, 12);
			this.Grupo_ctrl_com.Name = "Grupo_ctrl_com";
			global::System.Windows.Forms.Control grupo_ctrl_com2 = this.Grupo_ctrl_com;
			Size = new System.Drawing.Size(214, 158);
			grupo_ctrl_com2.Size = this.Size;
			this.Grupo_ctrl_com.TabIndex = 13;
			this.Grupo_ctrl_com.TabStop = false;
			this.Grupo_ctrl_com.Text = "Controle de comunicação";
			global::System.Windows.Forms.Control comando_hab_cal = this.Comando_hab_cal;
comando_hab_cal.Location = new global::System.Drawing.Point(25, 117);
			this.Comando_hab_cal.Name = "Comando_hab_cal";
			global::System.Windows.Forms.Control comando_hab_cal2 = this.Comando_hab_cal;
			Size = new System.Drawing.Size(167, 26);
			comando_hab_cal2.Size = this.Size;
			this.Comando_hab_cal.TabIndex = 2;
			this.Comando_hab_cal.Text = "Ler";
			this.Comando_hab_cal.UseVisualStyleBackColor = true;
			this.Grupo_controle_calibracao.Controls.Add(this.Button_20_5ma);
			this.Grupo_controle_calibracao.Controls.Add(this.Button_3_5ma);
			this.Grupo_controle_calibracao.Controls.Add(this.Valor_cal_end);
			this.Grupo_controle_calibracao.Controls.Add(this.Valor_canal_calibracao);
			this.Grupo_controle_calibracao.Controls.Add(this.Label_end_cal);
			this.Grupo_controle_calibracao.Controls.Add(this.Label_canal);
			global::System.Windows.Forms.Control grupo_controle_calibracao = this.Grupo_controle_calibracao;
grupo_controle_calibracao.Location = new global::System.Drawing.Point(49, 473);
			this.Grupo_controle_calibracao.Name = "Grupo_controle_calibracao";
			global::System.Windows.Forms.Control grupo_controle_calibracao2 = this.Grupo_controle_calibracao;
			Size = new System.Drawing.Size(576, 113);
			grupo_controle_calibracao2.Size = this.Size;
			this.Grupo_controle_calibracao.TabIndex = 22;
			this.Grupo_controle_calibracao.TabStop = false;
			this.Grupo_controle_calibracao.Text = "Controle de calibração";
			this.Button_20_5ma.Enabled = false;
			global::System.Windows.Forms.Control button_20_5ma = this.Button_20_5ma;
button_20_5ma.Location = new global::System.Drawing.Point(301, 66);
			this.Button_20_5ma.Name = "Button_20_5ma";
			global::System.Windows.Forms.Control button_20_5ma2 = this.Button_20_5ma;
			Size = new System.Drawing.Size(133, 27);
			button_20_5ma2.Size = this.Size;
			this.Button_20_5ma.TabIndex = 15;
			this.Button_20_5ma.Tag = " ";
			this.Button_20_5ma.Text = "Calibra 20,5 mA";
			this.Button_20_5ma.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control button_3_5ma = this.Button_3_5ma;
button_3_5ma.Location = new global::System.Drawing.Point(136, 66);
			this.Button_3_5ma.Name = "Button_3_5ma";
			global::System.Windows.Forms.Control button_3_5ma2 = this.Button_3_5ma;
			Size = new System.Drawing.Size(133, 27);
			button_3_5ma2.Size = this.Size;
			this.Button_3_5ma.TabIndex = 15;
			this.Button_3_5ma.Tag = " ";
			this.Button_3_5ma.Text = "Calibra 3,5 mA";
			this.Button_3_5ma.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control valor_cal_end = this.Valor_cal_end;
valor_cal_end.Location = new global::System.Drawing.Point(240, 25);
			global::System.Windows.Forms.NumericUpDown valor_cal_end2 = this.Valor_cal_end;
			num = new decimal(new int[]
			{
				200,
				0,
				0,
				0
			});
			valor_cal_end2.Maximum = num;
			this.Valor_cal_end.Name = "Valor_cal_end";
			global::System.Windows.Forms.Control valor_cal_end3 = this.Valor_cal_end;
			Size = new System.Drawing.Size(61, 20);
			valor_cal_end3.Size = this.Size;
			this.Valor_cal_end.TabIndex = 12;
			this.Valor_cal_end.TextAlign = HorizontalAlignment.Right;
			global::System.Windows.Forms.Control valor_canal_calibracao = this.Valor_canal_calibracao;
valor_canal_calibracao.Location = new global::System.Drawing.Point(371, 25);
			global::System.Windows.Forms.NumericUpDown valor_canal_calibracao2 = this.Valor_canal_calibracao;
			num = new decimal(new int[]
			{
				4,
				0,
				0,
				0
			});
			valor_canal_calibracao2.Maximum = num;
			global::System.Windows.Forms.NumericUpDown valor_canal_calibracao3 = this.Valor_canal_calibracao;
			num = new decimal(new int[]
			{
				1,
				0,
				0,
				0
			});
			valor_canal_calibracao3.Minimum = num;
			this.Valor_canal_calibracao.Name = "Valor_canal_calibracao";
			global::System.Windows.Forms.Control valor_canal_calibracao4 = this.Valor_canal_calibracao;
			Size = new System.Drawing.Size(63, 20);
			valor_canal_calibracao4.Size = this.Size;
			this.Valor_canal_calibracao.TabIndex = 14;
			this.Valor_canal_calibracao.TextAlign = HorizontalAlignment.Right;
			global::System.Windows.Forms.NumericUpDown valor_canal_calibracao5 = this.Valor_canal_calibracao;
			num = new decimal(new int[]
			{
				1,
				0,
				0,
				0
			});
			valor_canal_calibracao5.Value = num;
			this.Label_end_cal.AutoSize = true;
			global::System.Windows.Forms.Control label_end_cal = this.Label_end_cal;
label_end_cal.Location = new global::System.Drawing.Point(133, 27);
			this.Label_end_cal.Name = "Label_end_cal";
			global::System.Windows.Forms.Control label_end_cal2 = this.Label_end_cal;
			Size = new System.Drawing.Size(101, 13);
			label_end_cal2.Size = this.Size;
			this.Label_end_cal.TabIndex = 11;
			this.Label_end_cal.Text = "Endereço Estação :";
			this.Label_canal.AutoSize = true;
			global::System.Windows.Forms.Control label_canal = this.Label_canal;
label_canal.Location = new global::System.Drawing.Point(325, 27);
			this.Label_canal.Name = "Label_canal";
			global::System.Windows.Forms.Control label_canal2 = this.Label_canal;
			Size = new System.Drawing.Size(40, 13);
			label_canal2.Size = this.Size;
			this.Label_canal.TabIndex = 13;
			this.Label_canal.Text = "Canal :";
			global::System.Drawing.SizeF autoScaleDimensions;
			autoScaleDimensions = new global::System.Drawing.SizeF(6f, 13f);
			this.AutoScaleDimensions = autoScaleDimensions;
			this.AutoScaleMode = AutoScaleMode.Font;
			Size = new System.Drawing.Size(666, 606);
			this.ClientSize = Size;
			this.Controls.Add(this.Grupo_controle_calibracao);
			this.Controls.Add(this.Grupo_medidas_eng);
			this.Controls.Add(this.Grupo_ctrl_com);
			this.Controls.Add(this.Grupo_ent_digitais);
			this.Controls.Add(this.Grupo_calibracao);
			this.Controls.Add(this.Grupo_cont_sem_nor);
			this.Controls.Add(this.Grupo_cont_normal);
			this.FormBorderStyle = FormBorderStyle.None;
this.Location = new global::System.Drawing.Point(160, 2);
			this.Name = "Equip_101_cal";
			this.StartPosition = global::System.Windows.Forms.FormStartPosition.Manual;
			this.Text = "Form1";
			this.Grupo_ent_digitais.ResumeLayout(false);
			this.Grupo_ent_digitais.PerformLayout();
			this.Grupo_calibracao.ResumeLayout(false);
			this.Grupo_calibracao.PerformLayout();
			this.Grupo_cont_sem_nor.ResumeLayout(false);
			this.Grupo_cont_sem_nor.PerformLayout();
			this.Grupo_cont_normal.ResumeLayout(false);
			this.Grupo_cont_normal.PerformLayout();
			
			this.Grupo_medidas_eng.ResumeLayout(false);
			this.Grupo_medidas_eng.PerformLayout();
			this.GroupBox1.ResumeLayout(false);
			this.GroupBox1.PerformLayout();
			this.Grupo_ctrl_com.ResumeLayout(false);
			this.Grupo_ctrl_com.PerformLayout();
			this.Grupo_controle_calibracao.ResumeLayout(false);
			this.Grupo_controle_calibracao.PerformLayout();
			
			
			this.ResumeLayout(false);
		}

		// Token: 0x04001488 RID: 5256
		private global::System.ComponentModel.IContainer components;
	}
}
