using System.Drawing;
using System.Windows.Forms;
﻿namespace iS800
{
	// Token: 0x02000039 RID: 57
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class GC_82x_calib : global::System.Windows.Forms.Form
	{
		// Token: 0x06000BF1 RID: 3057 RVA: 0x002F1C2C File Offset: 0x002F002C
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				if (disposing && this.components != null)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x06000BF2 RID: 3058 RVA: 0x002F1C6C File Offset: 0x002F006C
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::iS800.GC_82x_calib));
			this.GroupBox1 = new global::System.Windows.Forms.GroupBox();
			this.bt_busca = new global::System.Windows.Forms.Button();
			this.nud_estacao = new global::System.Windows.Forms.NumericUpDown();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.GroupBox4 = new global::System.Windows.Forms.GroupBox();
			this.rb_channel2 = new global::System.Windows.Forms.RadioButton();
			this.rb_channel1 = new global::System.Windows.Forms.RadioButton();
			this.GroupBox5 = new global::System.Windows.Forms.GroupBox();
			this.nud_contagens = new global::System.Windows.Forms.NumericUpDown();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.GroupBox6 = new global::System.Windows.Forms.GroupBox();
			this.Button3 = new global::System.Windows.Forms.Button();
			this.Button4 = new global::System.Windows.Forms.Button();
			this.bt_envia = new global::System.Windows.Forms.Button();
			this.GroupBox7 = new global::System.Windows.Forms.GroupBox();
			this.GroupBox8 = new global::System.Windows.Forms.GroupBox();
			this.Button5 = new global::System.Windows.Forms.Button();
			this.Button6 = new global::System.Windows.Forms.Button();
			this.bt_confirma_4 = new global::System.Windows.Forms.Button();
			this.bt_confirma_20 = new global::System.Windows.Forms.Button();
			this.GroupBox9 = new global::System.Windows.Forms.GroupBox();
			this.GroupBox10 = new global::System.Windows.Forms.GroupBox();
			this.Button9 = new global::System.Windows.Forms.Button();
			this.Button10 = new global::System.Windows.Forms.Button();
			this.bt_finaliza = new global::System.Windows.Forms.Button();
			this.GroupBox11 = new global::System.Windows.Forms.GroupBox();
			this.Bt_inic_20 = new global::System.Windows.Forms.Button();
			this.Bt_inic_4 = new global::System.Windows.Forms.Button();
			this.GroupBox2 = new global::System.Windows.Forms.GroupBox();
			this.mensagens = new global::System.Windows.Forms.TextBox();
			this.GroupBox3 = new global::System.Windows.Forms.GroupBox();
			this.tb_corrente1 = new global::System.Windows.Forms.TrackBar();
			this.tb_corrente2 = new global::System.Windows.Forms.TrackBar();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.Label4 = new global::System.Windows.Forms.Label();
			this.lb_corrente1 = new global::System.Windows.Forms.Label();
			this.lb_corrente2 = new global::System.Windows.Forms.Label();
			this.Label5 = new global::System.Windows.Forms.Label();
			this.Label6 = new global::System.Windows.Forms.Label();
			this.Label7 = new global::System.Windows.Forms.Label();
			this.Label8 = new global::System.Windows.Forms.Label();
			this.Label9 = new global::System.Windows.Forms.Label();
			this.tb_escreve_corrente = new global::System.Windows.Forms.Button();
			this.GroupBox1.SuspendLayout();
			
			this.GroupBox4.SuspendLayout();
			this.GroupBox5.SuspendLayout();
			
			this.GroupBox6.SuspendLayout();
			this.GroupBox7.SuspendLayout();
			this.GroupBox8.SuspendLayout();
			this.GroupBox9.SuspendLayout();
			this.GroupBox10.SuspendLayout();
			this.GroupBox11.SuspendLayout();
			this.GroupBox2.SuspendLayout();
			this.GroupBox3.SuspendLayout();
			
			
			this.SuspendLayout();
			this.GroupBox1.Controls.Add(this.bt_busca);
			this.GroupBox1.Controls.Add(this.nud_estacao);
			this.GroupBox1.Controls.Add(this.Label1);
			global::System.Windows.Forms.Control groupBox = this.GroupBox1;
			groupBox.Location = new global::System.Drawing.Point(12, 28);
			this.GroupBox1.Name = "GroupBox1";
			global::System.Windows.Forms.Control groupBox2 = this.GroupBox1;
			groupBox2.Size = new global::System.Drawing.Size(337, 60);
			this.GroupBox1.TabIndex = 0;
			this.GroupBox1.TabStop = false;
			this.GroupBox1.Text = "Endereço do Equipamento";
			global::System.Windows.Forms.Control bt_busca = this.bt_busca;
bt_busca.Location = new global::System.Drawing.Point(251, 23);
			this.bt_busca.Name = "bt_busca";
			global::System.Windows.Forms.Control bt_busca2 = this.bt_busca;
			Size = new System.Drawing.Size(75, 23);
			bt_busca2.Size = this.Size;
			this.bt_busca.TabIndex = 2;
			this.bt_busca.Text = "Busca";
			this.bt_busca.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control nud_estacao = this.nud_estacao;
nud_estacao.Location = new global::System.Drawing.Point(77, 26);
			global::System.Windows.Forms.NumericUpDown nud_estacao2 = this.nud_estacao;
			decimal maximum;
			maximum = new decimal(new int[]
			{
				207,
				0,
				0,
				0
			});
			nud_estacao2.Maximum = maximum;
			this.nud_estacao.Name = "nud_estacao";
			global::System.Windows.Forms.Control nud_estacao3 = this.nud_estacao;
			Size = new System.Drawing.Size(83, 20);
			nud_estacao3.Size = this.Size;
			this.nud_estacao.TabIndex = 1;
			this.Label1.AutoSize = true;
			global::System.Windows.Forms.Control label = this.Label1;
label.Location = new global::System.Drawing.Point(15, 28);
			this.Label1.Name = "Label1";
			global::System.Windows.Forms.Control label2 = this.Label1;
			Size = new System.Drawing.Size(56, 13);
			label2.Size = this.Size;
			this.Label1.TabIndex = 0;
			this.Label1.Text = "Endereço:";
			this.GroupBox4.Controls.Add(this.rb_channel2);
			this.GroupBox4.Controls.Add(this.rb_channel1);
			global::System.Windows.Forms.Control groupBox3 = this.GroupBox4;
groupBox3.Location = new global::System.Drawing.Point(12, 160);
			this.GroupBox4.Name = "GroupBox4";
			global::System.Windows.Forms.Control groupBox4 = this.GroupBox4;
			Size = new System.Drawing.Size(337, 60);
			groupBox4.Size = this.Size;
			this.GroupBox4.TabIndex = 5;
			this.GroupBox4.TabStop = false;
			this.GroupBox4.Text = "Seleção de Saída Analógica";
			this.rb_channel2.AutoSize = true;
			global::System.Windows.Forms.Control rb_channel = this.rb_channel2;
rb_channel.Location = new global::System.Drawing.Point(251, 26);
			this.rb_channel2.Name = "rb_channel2";
			global::System.Windows.Forms.Control rb_channel2 = this.rb_channel2;
			Size = new System.Drawing.Size(61, 17);
			rb_channel2.Size = this.Size;
			this.rb_channel2.TabIndex = 1;
			this.rb_channel2.Text = "Canal 2";
			this.rb_channel2.UseVisualStyleBackColor = true;
			this.rb_channel1.AutoSize = true;
			this.rb_channel1.Checked = true;
			global::System.Windows.Forms.Control rb_channel3 = this.rb_channel1;
rb_channel3.Location = new global::System.Drawing.Point(18, 26);
			this.rb_channel1.Name = "rb_channel1";
			global::System.Windows.Forms.Control rb_channel4 = this.rb_channel1;
			Size = new System.Drawing.Size(61, 17);
			rb_channel4.Size = this.Size;
			this.rb_channel1.TabIndex = 0;
			this.rb_channel1.TabStop = true;
			this.rb_channel1.Text = "Canal 1";
			this.rb_channel1.UseVisualStyleBackColor = true;
			this.GroupBox5.Controls.Add(this.nud_contagens);
			this.GroupBox5.Controls.Add(this.Label2);
			this.GroupBox5.Controls.Add(this.GroupBox6);
			this.GroupBox5.Controls.Add(this.bt_envia);
			global::System.Windows.Forms.Control groupBox5 = this.GroupBox5;
groupBox5.Location = new global::System.Drawing.Point(12, 226);
			this.GroupBox5.Name = "GroupBox5";
			global::System.Windows.Forms.Control groupBox6 = this.GroupBox5;
			Size = new System.Drawing.Size(337, 60);
			groupBox6.Size = this.Size;
			this.GroupBox5.TabIndex = 5;
			this.GroupBox5.TabStop = false;
			this.GroupBox5.Text = "Escrita de contagens de calibração";
			global::System.Windows.Forms.Control nud_contagens = this.nud_contagens;
nud_contagens.Location = new global::System.Drawing.Point(77, 26);
			global::System.Windows.Forms.NumericUpDown nud_contagens2 = this.nud_contagens;
			maximum = new decimal(new int[]
			{
				65535,
				0,
				0,
				0
			});
			nud_contagens2.Maximum = maximum;
			this.nud_contagens.Name = "nud_contagens";
			global::System.Windows.Forms.Control nud_contagens3 = this.nud_contagens;
			Size = new System.Drawing.Size(83, 20);
			nud_contagens3.Size = this.Size;
			this.nud_contagens.TabIndex = 6;
			this.Label2.AutoSize = true;
			global::System.Windows.Forms.Control label3 = this.Label2;
label3.Location = new global::System.Drawing.Point(15, 28);
			this.Label2.Name = "Label2";
			global::System.Windows.Forms.Control label4 = this.Label2;
			Size = new System.Drawing.Size(61, 13);
			label4.Size = this.Size;
			this.Label2.TabIndex = 5;
			this.Label2.Text = "Contagens:";
			this.GroupBox6.Controls.Add(this.Button3);
			this.GroupBox6.Controls.Add(this.Button4);
			global::System.Windows.Forms.Control groupBox7 = this.GroupBox6;
groupBox7.Location = new global::System.Drawing.Point(0, 71);
			this.GroupBox6.Name = "GroupBox6";
			global::System.Windows.Forms.Control groupBox8 = this.GroupBox6;
			Size = new System.Drawing.Size(392, 60);
			groupBox8.Size = this.Size;
			this.GroupBox6.TabIndex = 4;
			this.GroupBox6.TabStop = false;
			this.GroupBox6.Text = "Inicia calibração";
			global::System.Windows.Forms.Control button = this.Button3;
button.Location = new global::System.Drawing.Point(18, 23);
			this.Button3.Name = "Button3";
			global::System.Windows.Forms.Control button2 = this.Button3;
			Size = new System.Drawing.Size(75, 23);
			button2.Size = this.Size;
			this.Button3.TabIndex = 3;
			this.Button3.Text = "4 mA";
			this.Button3.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control button3 = this.Button4;
button3.Location = new global::System.Drawing.Point(296, 23);
			this.Button4.Name = "Button4";
			global::System.Windows.Forms.Control button4 = this.Button4;
			Size = new System.Drawing.Size(75, 23);
			button4.Size = this.Size;
			this.Button4.TabIndex = 2;
			this.Button4.Text = "Busca";
			this.Button4.UseVisualStyleBackColor = true;
			this.bt_envia.Enabled = false;
			global::System.Windows.Forms.Control bt_envia = this.bt_envia;
bt_envia.Location = new global::System.Drawing.Point(176, 23);
			this.bt_envia.Name = "bt_envia";
			global::System.Windows.Forms.Control bt_envia2 = this.bt_envia;
			Size = new System.Drawing.Size(150, 23);
			bt_envia2.Size = this.Size;
			this.bt_envia.TabIndex = 2;
			this.bt_envia.Text = "Escreve";
			this.bt_envia.UseVisualStyleBackColor = true;
			this.GroupBox7.Controls.Add(this.GroupBox8);
			this.GroupBox7.Controls.Add(this.bt_confirma_4);
			this.GroupBox7.Controls.Add(this.bt_confirma_20);
			global::System.Windows.Forms.Control groupBox9 = this.GroupBox7;
groupBox9.Location = new global::System.Drawing.Point(14, 297);
			this.GroupBox7.Name = "GroupBox7";
			global::System.Windows.Forms.Control groupBox10 = this.GroupBox7;
			Size = new System.Drawing.Size(335, 60);
			groupBox10.Size = this.Size;
			this.GroupBox7.TabIndex = 5;
			this.GroupBox7.TabStop = false;
			this.GroupBox7.Text = "Confirma calibração";
			this.GroupBox8.Controls.Add(this.Button5);
			this.GroupBox8.Controls.Add(this.Button6);
			global::System.Windows.Forms.Control groupBox11 = this.GroupBox8;
groupBox11.Location = new global::System.Drawing.Point(0, 71);
			this.GroupBox8.Name = "GroupBox8";
			global::System.Windows.Forms.Control groupBox12 = this.GroupBox8;
			Size = new System.Drawing.Size(392, 60);
			groupBox12.Size = this.Size;
			this.GroupBox8.TabIndex = 4;
			this.GroupBox8.TabStop = false;
			this.GroupBox8.Text = "Inicia calibração";
			global::System.Windows.Forms.Control button5 = this.Button5;
button5.Location = new global::System.Drawing.Point(18, 23);
			this.Button5.Name = "Button5";
			global::System.Windows.Forms.Control button6 = this.Button5;
			Size = new System.Drawing.Size(75, 23);
			button6.Size = this.Size;
			this.Button5.TabIndex = 3;
			this.Button5.Text = "4 mA";
			this.Button5.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control button7 = this.Button6;
button7.Location = new global::System.Drawing.Point(296, 23);
			this.Button6.Name = "Button6";
			global::System.Windows.Forms.Control button8 = this.Button6;
			Size = new System.Drawing.Size(75, 23);
			button8.Size = this.Size;
			this.Button6.TabIndex = 2;
			this.Button6.Text = "Busca";
			this.Button6.UseVisualStyleBackColor = true;
			this.bt_confirma_4.Enabled = false;
			global::System.Windows.Forms.Control bt_confirma_ = this.bt_confirma_4;
bt_confirma_.Location = new global::System.Drawing.Point(18, 23);
			this.bt_confirma_4.Name = "bt_confirma_4";
			global::System.Windows.Forms.Control bt_confirma_2 = this.bt_confirma_4;
			Size = new System.Drawing.Size(75, 23);
			bt_confirma_2.Size = this.Size;
			this.bt_confirma_4.TabIndex = 3;
			this.bt_confirma_4.Text = "4 mA";
			this.bt_confirma_4.UseVisualStyleBackColor = true;
			this.bt_confirma_20.Enabled = false;
			global::System.Windows.Forms.Control bt_confirma_3 = this.bt_confirma_20;
bt_confirma_3.Location = new global::System.Drawing.Point(249, 23);
			this.bt_confirma_20.Name = "bt_confirma_20";
			global::System.Windows.Forms.Control bt_confirma_4 = this.bt_confirma_20;
			Size = new System.Drawing.Size(75, 23);
			bt_confirma_4.Size = this.Size;
			this.bt_confirma_20.TabIndex = 2;
			this.bt_confirma_20.Text = "20 mA";
			this.bt_confirma_20.UseVisualStyleBackColor = true;
			this.GroupBox9.Controls.Add(this.GroupBox10);
			this.GroupBox9.Controls.Add(this.bt_finaliza);
			global::System.Windows.Forms.Control groupBox13 = this.GroupBox9;
groupBox13.Location = new global::System.Drawing.Point(12, 363);
			this.GroupBox9.Name = "GroupBox9";
			global::System.Windows.Forms.Control groupBox14 = this.GroupBox9;
			Size = new System.Drawing.Size(335, 60);
			groupBox14.Size = this.Size;
			this.GroupBox9.TabIndex = 6;
			this.GroupBox9.TabStop = false;
			this.GroupBox9.Text = "Finaliza calibração";
			this.GroupBox10.Controls.Add(this.Button9);
			this.GroupBox10.Controls.Add(this.Button10);
			global::System.Windows.Forms.Control groupBox15 = this.GroupBox10;
groupBox15.Location = new global::System.Drawing.Point(0, 71);
			this.GroupBox10.Name = "GroupBox10";
			global::System.Windows.Forms.Control groupBox16 = this.GroupBox10;
			Size = new System.Drawing.Size(392, 60);
			groupBox16.Size = this.Size;
			this.GroupBox10.TabIndex = 4;
			this.GroupBox10.TabStop = false;
			this.GroupBox10.Text = "Inicia calibração";
			global::System.Windows.Forms.Control button9 = this.Button9;
button9.Location = new global::System.Drawing.Point(18, 23);
			this.Button9.Name = "Button9";
			global::System.Windows.Forms.Control button10 = this.Button9;
			Size = new System.Drawing.Size(75, 23);
			button10.Size = this.Size;
			this.Button9.TabIndex = 3;
			this.Button9.Text = "4 mA";
			this.Button9.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control button11 = this.Button10;
button11.Location = new global::System.Drawing.Point(296, 23);
			this.Button10.Name = "Button10";
			global::System.Windows.Forms.Control button12 = this.Button10;
			Size = new System.Drawing.Size(75, 23);
			button12.Size = this.Size;
			this.Button10.TabIndex = 2;
			this.Button10.Text = "Busca";
			this.Button10.UseVisualStyleBackColor = true;
			this.bt_finaliza.Enabled = false;
			global::System.Windows.Forms.Control bt_finaliza = this.bt_finaliza;
bt_finaliza.Location = new global::System.Drawing.Point(134, 19);
			this.bt_finaliza.Name = "bt_finaliza";
			global::System.Windows.Forms.Control bt_finaliza2 = this.bt_finaliza;
			Size = new System.Drawing.Size(75, 23);
			bt_finaliza2.Size = this.Size;
			this.bt_finaliza.TabIndex = 2;
			this.bt_finaliza.Text = "Finalização";
			this.bt_finaliza.UseVisualStyleBackColor = true;
			this.GroupBox11.Controls.Add(this.Bt_inic_20);
			this.GroupBox11.Controls.Add(this.Bt_inic_4);
			global::System.Windows.Forms.Control groupBox17 = this.GroupBox11;
groupBox17.Location = new global::System.Drawing.Point(12, 94);
			this.GroupBox11.Name = "GroupBox11";
			global::System.Windows.Forms.Control groupBox18 = this.GroupBox11;
			Size = new System.Drawing.Size(337, 60);
			groupBox18.Size = this.Size;
			this.GroupBox11.TabIndex = 6;
			this.GroupBox11.TabStop = false;
			this.GroupBox11.Text = "Início Calibração";
			this.Bt_inic_20.Enabled = false;
			global::System.Windows.Forms.Control bt_inic_ = this.Bt_inic_20;
bt_inic_.Location = new global::System.Drawing.Point(251, 24);
			this.Bt_inic_20.Name = "Bt_inic_20";
			global::System.Windows.Forms.Control bt_inic_2 = this.Bt_inic_20;
			Size = new System.Drawing.Size(75, 23);
			bt_inic_2.Size = this.Size;
			this.Bt_inic_20.TabIndex = 5;
			this.Bt_inic_20.Text = "20 mA";
			this.Bt_inic_20.UseVisualStyleBackColor = true;
			this.Bt_inic_4.Enabled = false;
			global::System.Windows.Forms.Control bt_inic_3 = this.Bt_inic_4;
bt_inic_3.Location = new global::System.Drawing.Point(18, 24);
			this.Bt_inic_4.Name = "Bt_inic_4";
			global::System.Windows.Forms.Control bt_inic_4 = this.Bt_inic_4;
			Size = new System.Drawing.Size(75, 23);
			bt_inic_4.Size = this.Size;
			this.Bt_inic_4.TabIndex = 4;
			this.Bt_inic_4.Text = "4 mA";
			this.Bt_inic_4.UseVisualStyleBackColor = true;
			this.GroupBox2.Controls.Add(this.mensagens);
			global::System.Windows.Forms.Control groupBox19 = this.GroupBox2;
groupBox19.Location = new global::System.Drawing.Point(12, 434);
			this.GroupBox2.Name = "GroupBox2";
			global::System.Windows.Forms.Control groupBox20 = this.GroupBox2;
			Size = new System.Drawing.Size(337, 74);
			groupBox20.Size = this.Size;
			this.GroupBox2.TabIndex = 7;
			this.GroupBox2.TabStop = false;
			this.GroupBox2.Text = "Mensagens";
			this.mensagens.BackColor = global::System.Drawing.Color.Cornsilk;
			global::System.Windows.Forms.Control mensagens = this.mensagens;
mensagens.Location = new global::System.Drawing.Point(8, 19);
			this.mensagens.Multiline = true;
			this.mensagens.Name = "mensagens";
			global::System.Windows.Forms.Control mensagens2 = this.mensagens;
			Size = new System.Drawing.Size(323, 49);
			mensagens2.Size = this.Size;
			this.mensagens.TabIndex = 0;
			this.GroupBox3.Controls.Add(this.tb_escreve_corrente);
			this.GroupBox3.Controls.Add(this.Label9);
			this.GroupBox3.Controls.Add(this.Label8);
			this.GroupBox3.Controls.Add(this.Label7);
			this.GroupBox3.Controls.Add(this.Label6);
			this.GroupBox3.Controls.Add(this.Label5);
			this.GroupBox3.Controls.Add(this.lb_corrente2);
			this.GroupBox3.Controls.Add(this.lb_corrente1);
			this.GroupBox3.Controls.Add(this.Label4);
			this.GroupBox3.Controls.Add(this.Label3);
			this.GroupBox3.Controls.Add(this.tb_corrente2);
			this.GroupBox3.Controls.Add(this.tb_corrente1);
			global::System.Windows.Forms.Control groupBox21 = this.GroupBox3;
groupBox21.Location = new global::System.Drawing.Point(14, 514);
			this.GroupBox3.Name = "GroupBox3";
			global::System.Windows.Forms.Control groupBox22 = this.GroupBox3;
			Size = new System.Drawing.Size(333, 130);
			groupBox22.Size = this.Size;
			this.GroupBox3.TabIndex = 8;
			this.GroupBox3.TabStop = false;
			this.GroupBox3.Text = "Envio de Corrente (4-20mA) após calibração";
			global::System.Windows.Forms.Control tb_corrente = this.tb_corrente1;
tb_corrente.Location = new global::System.Drawing.Point(55, 20);
			this.tb_corrente1.Maximum = 16;
			this.tb_corrente1.Name = "tb_corrente1";
			global::System.Windows.Forms.Control tb_corrente2 = this.tb_corrente1;
			Size = new System.Drawing.Size(140, 45);
			tb_corrente2.Size = this.Size;
			this.tb_corrente1.TabIndex = 0;
			this.tb_corrente1.TickFrequency = 4;
			this.tb_corrente1.Value = 4;
			global::System.Windows.Forms.Control tb_corrente3 = this.tb_corrente2;
tb_corrente3.Location = new global::System.Drawing.Point(55, 82);
			this.tb_corrente2.Maximum = 16;
			this.tb_corrente2.Name = "tb_corrente2";
			global::System.Windows.Forms.Control tb_corrente4 = this.tb_corrente2;
			Size = new System.Drawing.Size(140, 45);
			tb_corrente4.Size = this.Size;
			this.tb_corrente2.TabIndex = 1;
			this.tb_corrente2.TickFrequency = 4;
			this.tb_corrente2.Value = 4;
			this.Label3.AutoSize = true;
			global::System.Windows.Forms.Control label5 = this.Label3;
label5.Location = new global::System.Drawing.Point(6, 28);
			this.Label3.Name = "Label3";
			global::System.Windows.Forms.Control label6 = this.Label3;
			Size = new System.Drawing.Size(43, 13);
			label6.Size = this.Size;
			this.Label3.TabIndex = 2;
			this.Label3.Text = "Canal 1";
			this.Label4.AutoSize = true;
			global::System.Windows.Forms.Control label7 = this.Label4;
label7.Location = new global::System.Drawing.Point(6, 86);
			this.Label4.Name = "Label4";
			global::System.Windows.Forms.Control label8 = this.Label4;
			Size = new System.Drawing.Size(43, 13);
			label8.Size = this.Size;
			this.Label4.TabIndex = 3;
			this.Label4.Text = "Canal 2";
			this.lb_corrente1.AutoSize = true;
			global::System.Windows.Forms.Control lb_corrente = this.lb_corrente1;
lb_corrente.Location = new global::System.Drawing.Point(194, 28);
			this.lb_corrente1.Name = "lb_corrente1";
			global::System.Windows.Forms.Control lb_corrente2 = this.lb_corrente1;
			Size = new System.Drawing.Size(43, 13);
			lb_corrente2.Size = this.Size;
			this.lb_corrente1.TabIndex = 4;
			this.lb_corrente1.Text = "Canal 1";
			this.lb_corrente2.AutoSize = true;
			global::System.Windows.Forms.Control lb_corrente3 = this.lb_corrente2;
lb_corrente3.Location = new global::System.Drawing.Point(194, 86);
			this.lb_corrente2.Name = "lb_corrente2";
			global::System.Windows.Forms.Control lb_corrente4 = this.lb_corrente2;
			Size = new System.Drawing.Size(43, 13);
			lb_corrente4.Size = this.Size;
			this.lb_corrente2.TabIndex = 5;
			this.lb_corrente2.Text = "Canal 2";
			this.Label5.AutoSize = true;
			global::System.Windows.Forms.Control label9 = this.Label5;
label9.Location = new global::System.Drawing.Point(62, 58);
			this.Label5.Name = "Label5";
			global::System.Windows.Forms.Control label10 = this.Label5;
			Size = new System.Drawing.Size(13, 13);
			label10.Size = this.Size;
			this.Label5.TabIndex = 6;
			this.Label5.Text = "4";
			this.Label6.AutoSize = true;
			global::System.Windows.Forms.Control label11 = this.Label6;
label11.Location = new global::System.Drawing.Point(90, 58);
			this.Label6.Name = "Label6";
			global::System.Windows.Forms.Control label12 = this.Label6;
			Size = new System.Drawing.Size(13, 13);
			label12.Size = this.Size;
			this.Label6.TabIndex = 7;
			this.Label6.Text = "8";
			this.Label7.AutoSize = true;
			global::System.Windows.Forms.Control label13 = this.Label7;
label13.Location = new global::System.Drawing.Point(118, 58);
			this.Label7.Name = "Label7";
			global::System.Windows.Forms.Control label14 = this.Label7;
			Size = new System.Drawing.Size(19, 13);
			label14.Size = this.Size;
			this.Label7.TabIndex = 8;
			this.Label7.Text = "12";
			this.Label8.AutoSize = true;
			global::System.Windows.Forms.Control label15 = this.Label8;
label15.Location = new global::System.Drawing.Point(143, 58);
			this.Label8.Name = "Label8";
			global::System.Windows.Forms.Control label16 = this.Label8;
			Size = new System.Drawing.Size(19, 13);
			label16.Size = this.Size;
			this.Label8.TabIndex = 9;
			this.Label8.Text = "16";
			this.Label9.AutoSize = true;
			global::System.Windows.Forms.Control label17 = this.Label9;
label17.Location = new global::System.Drawing.Point(171, 58);
			this.Label9.Name = "Label9";
			global::System.Windows.Forms.Control label18 = this.Label9;
			Size = new System.Drawing.Size(19, 13);
			label18.Size = this.Size;
			this.Label9.TabIndex = 10;
			this.Label9.Text = "20";
			global::System.Windows.Forms.Control tb_escreve_corrente = this.tb_escreve_corrente;
tb_escreve_corrente.Location = new global::System.Drawing.Point(249, 53);
			this.tb_escreve_corrente.Name = "tb_escreve_corrente";
			global::System.Windows.Forms.Control tb_escreve_corrente2 = this.tb_escreve_corrente;
			Size = new System.Drawing.Size(75, 23);
			tb_escreve_corrente2.Size = this.Size;
			this.tb_escreve_corrente.TabIndex = 11;
			this.tb_escreve_corrente.Text = "Escreve";
			this.tb_escreve_corrente.UseVisualStyleBackColor = true;
			global::System.Drawing.SizeF autoScaleDimensions;
			autoScaleDimensions = new global::System.Drawing.SizeF(6f, 13f);
			this.AutoScaleDimensions = autoScaleDimensions;
			this.AutoScaleMode = AutoScaleMode.Font;
			Size = new System.Drawing.Size(361, 653);
			this.ClientSize = Size;
			this.Controls.Add(this.GroupBox3);
			this.Controls.Add(this.GroupBox2);
			this.Controls.Add(this.GroupBox11);
			this.Controls.Add(this.GroupBox9);
			this.Controls.Add(this.GroupBox7);
			this.Controls.Add(this.GroupBox5);
			this.Controls.Add(this.GroupBox4);
			this.Controls.Add(this.GroupBox1);
			this.Icon = (global::System.Drawing.Icon)componentResourceManager.GetObject("$this.Icon");
			this.Name = "GC_82x_calib";
			this.Text = "GC_82x_calib";
			this.GroupBox1.ResumeLayout(false);
			this.GroupBox1.PerformLayout();
			
			this.GroupBox4.ResumeLayout(false);
			this.GroupBox4.PerformLayout();
			this.GroupBox5.ResumeLayout(false);
			this.GroupBox5.PerformLayout();
			
			this.GroupBox6.ResumeLayout(false);
			this.GroupBox7.ResumeLayout(false);
			this.GroupBox8.ResumeLayout(false);
			this.GroupBox9.ResumeLayout(false);
			this.GroupBox10.ResumeLayout(false);
			this.GroupBox11.ResumeLayout(false);
			this.GroupBox2.ResumeLayout(false);
			this.GroupBox2.PerformLayout();
			this.GroupBox3.ResumeLayout(false);
			this.GroupBox3.PerformLayout();
			
			
			this.ResumeLayout(false);
		}

		// Token: 0x04000771 RID: 1905
		private global::System.ComponentModel.IContainer components;
	}
}
