namespace iS800
{
	// Token: 0x0200003C RID: 60
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class IER_856_conf : global::System.Windows.Forms.Form
	{
		// Token: 0x06000DFE RID: 3582 RVA: 0x0030075C File Offset: 0x002FEB5C
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				if (disposing && this.components != null)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x06000DFF RID: 3583 RVA: 0x0030079C File Offset: 0x002FEB9C
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.components = new global::System.ComponentModel.Container();
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::iS800.IER_856_conf));
			this.TabControl_810 = new global::System.Windows.Forms.TabControl();
			this.TabPage_geral = new global::System.Windows.Forms.TabPage();
			this.GroupBox2 = new global::System.Windows.Forms.GroupBox();
			this.ComboBox_baudrate = new global::System.Windows.Forms.ComboBox();
			this.Label36 = new global::System.Windows.Forms.Label();
			this.GroupBox_ModoOperacao = new global::System.Windows.Forms.GroupBox();
			this.GroupBox3 = new global::System.Windows.Forms.GroupBox();
			this.tb_static_sm = new global::System.Windows.Forms.TextBox();
			this.Label4 = new global::System.Windows.Forms.Label();
			this.tb_static_gw = new global::System.Windows.Forms.TextBox();
			this.Label5 = new global::System.Windows.Forms.Label();
			this.tb_static_ip = new global::System.Windows.Forms.TextBox();
			this.Label6 = new global::System.Windows.Forms.Label();
			this.GroupBox1 = new global::System.Windows.Forms.GroupBox();
			this.tb_dhcp_sm = new global::System.Windows.Forms.TextBox();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.tb_dhcp_gw = new global::System.Windows.Forms.TextBox();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.tb_dhcp_ip = new global::System.Windows.Forms.TextBox();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.ComboBox_Modo_Operacao = new global::System.Windows.Forms.ComboBox();
			this.Label_MetodoOperacao = new global::System.Windows.Forms.Label();
			this.GroupBox_informacoes = new global::System.Windows.Forms.GroupBox();
			this.tbMAC5 = new global::System.Windows.Forms.TextBox();
			this.tbMAC4 = new global::System.Windows.Forms.TextBox();
			this.tbMAC3 = new global::System.Windows.Forms.TextBox();
			this.tbMAC2 = new global::System.Windows.Forms.TextBox();
			this.tbMAC1 = new global::System.Windows.Forms.TextBox();
			this.tbMAC0 = new global::System.Windows.Forms.TextBox();
			this.tbMAC = new global::System.Windows.Forms.Label();
			this.Label17 = new global::System.Windows.Forms.Label();
			this.Label26 = new global::System.Windows.Forms.Label();
			this.TextBox_equipamento = new global::System.Windows.Forms.TextBox();
			this.Label_equipamento = new global::System.Windows.Forms.Label();
			this.TextBox_release = new global::System.Windows.Forms.TextBox();
			this.Label_release = new global::System.Windows.Forms.Label();
			this.TextBox_build = new global::System.Windows.Forms.TextBox();
			this.Label_build = new global::System.Windows.Forms.Label();
			this.TextBox_versao = new global::System.Windows.Forms.TextBox();
			this.Label_versao = new global::System.Windows.Forms.Label();
			this.ToolStri_RT_810 = new global::System.Windows.Forms.ToolStrip();
			this.ToolStripButton_RT_810_novo = new global::System.Windows.Forms.ToolStripButton();
			this.ToolStripButton_RT_810_Abrir = new global::System.Windows.Forms.ToolStripButton();
			this.ToolStripButton_RT_810_Salvar = new global::System.Windows.Forms.ToolStripButton();
			this.ToolStripSeparator1 = new global::System.Windows.Forms.ToolStripSeparator();
			this.ToolStripButton_RT_810_Download = new global::System.Windows.Forms.ToolStripButton();
			this.ToolStripButton_RT_810_Upload = new global::System.Windows.Forms.ToolStripButton();
			this.ToolStripSeparator2 = new global::System.Windows.Forms.ToolStripSeparator();
			this.ToolStripButton_RT_810_Imprimir = new global::System.Windows.Forms.ToolStripButton();
			this.ToolStripSeparator3 = new global::System.Windows.Forms.ToolStripSeparator();
			this.ToolStripLabel_ID = new global::System.Windows.Forms.ToolStripLabel();
			this.ToolStripSeparator4 = new global::System.Windows.Forms.ToolStripSeparator();
			this.ToolStripTextBox_RT_810_Msg = new global::System.Windows.Forms.ToolStripTextBox();
			this.ToolStripProgressBar_RT_810 = new global::System.Windows.Forms.ToolStripProgressBar();
			this.OpenFileDialog_RT_810 = new global::System.Windows.Forms.OpenFileDialog();
			this.SaveFileDialog_RT_810 = new global::System.Windows.Forms.SaveFileDialog();
			this.Timer_limpa_MSG = new global::System.Windows.Forms.Timer(this.components);
			this.PrintDocument1 = new global::System.Drawing.Printing.PrintDocument();
			this.PrintPreviewDialog1 = new global::System.Windows.Forms.PrintPreviewDialog();
			this.RepetidoraBindingSource1 = new global::System.Windows.Forms.BindingSource(this.components);
			this.TabControl_810.SuspendLayout();
			this.TabPage_geral.SuspendLayout();
			this.GroupBox2.SuspendLayout();
			this.GroupBox_ModoOperacao.SuspendLayout();
			this.GroupBox3.SuspendLayout();
			this.GroupBox1.SuspendLayout();
			this.GroupBox_informacoes.SuspendLayout();
			this.ToolStri_RT_810.SuspendLayout();
			this.RepetidoraBindingSource1.BeginInit();
			this.SuspendLayout();
			this.TabControl_810.Controls.Add(this.TabPage_geral);
			this.TabControl_810.HotTrack = true;
			global::System.Windows.Forms.Control tabControl_ = this.TabControl_810;
			global::System.Drawing.Point location;
			location = new global::System.Drawing.Point(10, 66);
			tabControl_.Location = location;
			this.TabControl_810.Name = "TabControl_810";
			this.TabControl_810.SelectedIndex = 0;
			global::System.Windows.Forms.Control tabControl_2 = this.TabControl_810;
			global::System.Drawing.Size size;
			size = new global::System.Drawing.Size(1136, 531);
			tabControl_2.Size = size;
			this.TabControl_810.TabIndex = 1;
			this.TabPage_geral.BackColor = global::System.Drawing.SystemColors.ControlLight;
			this.TabPage_geral.Controls.Add(this.GroupBox2);
			this.TabPage_geral.Controls.Add(this.GroupBox_ModoOperacao);
			this.TabPage_geral.Controls.Add(this.GroupBox_informacoes);
			global::System.Windows.Forms.TabPage tabPage_geral = this.TabPage_geral;
			location = new global::System.Drawing.Point(4, 22);
			tabPage_geral.Location = location;
			this.TabPage_geral.Name = "TabPage_geral";
			global::System.Windows.Forms.Control tabPage_geral2 = this.TabPage_geral;
			global::System.Windows.Forms.Padding padding;
			padding = new global::System.Windows.Forms.Padding(3);
			tabPage_geral2.Padding = padding;
			global::System.Windows.Forms.Control tabPage_geral3 = this.TabPage_geral;
			size = new global::System.Drawing.Size(1128, 505);
			tabPage_geral3.Size = size;
			this.TabPage_geral.TabIndex = 0;
			this.TabPage_geral.Text = "Geral";
			this.TabPage_geral.UseVisualStyleBackColor = true;
			this.GroupBox2.Controls.Add(this.ComboBox_baudrate);
			this.GroupBox2.Controls.Add(this.Label36);
			global::System.Windows.Forms.Control groupBox = this.GroupBox2;
			location = new global::System.Drawing.Point(20, 12);
			groupBox.Location = location;
			this.GroupBox2.Name = "GroupBox2";
			global::System.Windows.Forms.Control groupBox2 = this.GroupBox2;
			size = new global::System.Drawing.Size(291, 65);
			groupBox2.Size = size;
			this.GroupBox2.TabIndex = 11;
			this.GroupBox2.TabStop = false;
			this.GroupBox2.Text = "Parâmetros da Interface RS232";
			this.ComboBox_baudrate.FormattingEnabled = true;
			global::System.Windows.Forms.Control comboBox_baudrate = this.ComboBox_baudrate;
			location = new global::System.Drawing.Point(152, 25);
			comboBox_baudrate.Location = location;
			this.ComboBox_baudrate.Name = "ComboBox_baudrate";
			global::System.Windows.Forms.Control comboBox_baudrate2 = this.ComboBox_baudrate;
			size = new global::System.Drawing.Size(121, 21);
			comboBox_baudrate2.Size = size;
			this.ComboBox_baudrate.TabIndex = 12;
			this.Label36.AutoSize = true;
			global::System.Windows.Forms.Control label = this.Label36;
			location = new global::System.Drawing.Point(18, 30);
			label.Location = location;
			this.Label36.Name = "Label36";
			global::System.Windows.Forms.Control label2 = this.Label36;
			size = new global::System.Drawing.Size(53, 13);
			label2.Size = size;
			this.Label36.TabIndex = 11;
			this.Label36.Text = "Baudrate:";
			this.GroupBox_ModoOperacao.Controls.Add(this.GroupBox3);
			this.GroupBox_ModoOperacao.Controls.Add(this.GroupBox1);
			this.GroupBox_ModoOperacao.Controls.Add(this.ComboBox_Modo_Operacao);
			this.GroupBox_ModoOperacao.Controls.Add(this.Label_MetodoOperacao);
			global::System.Windows.Forms.Control groupBox_ModoOperacao = this.GroupBox_ModoOperacao;
			location = new global::System.Drawing.Point(20, 108);
			groupBox_ModoOperacao.Location = location;
			this.GroupBox_ModoOperacao.Name = "GroupBox_ModoOperacao";
			global::System.Windows.Forms.Control groupBox_ModoOperacao2 = this.GroupBox_ModoOperacao;
			size = new global::System.Drawing.Size(291, 333);
			groupBox_ModoOperacao2.Size = size;
			this.GroupBox_ModoOperacao.TabIndex = 8;
			this.GroupBox_ModoOperacao.TabStop = false;
			this.GroupBox_ModoOperacao.Text = "Parâmetros da Interface ETHERNET";
			this.GroupBox3.Controls.Add(this.tb_static_sm);
			this.GroupBox3.Controls.Add(this.Label4);
			this.GroupBox3.Controls.Add(this.tb_static_gw);
			this.GroupBox3.Controls.Add(this.Label5);
			this.GroupBox3.Controls.Add(this.tb_static_ip);
			this.GroupBox3.Controls.Add(this.Label6);
			global::System.Windows.Forms.Control groupBox3 = this.GroupBox3;
			location = new global::System.Drawing.Point(21, 183);
			groupBox3.Location = location;
			this.GroupBox3.Name = "GroupBox3";
			global::System.Windows.Forms.Control groupBox4 = this.GroupBox3;
			size = new global::System.Drawing.Size(255, 100);
			groupBox4.Size = size;
			this.GroupBox3.TabIndex = 6;
			this.GroupBox3.TabStop = false;
			this.GroupBox3.Text = "STATIC:";
			global::System.Windows.Forms.Control tb_static_sm = this.tb_static_sm;
			location = new global::System.Drawing.Point(46, 72);
			tb_static_sm.Location = location;
			this.tb_static_sm.Name = "tb_static_sm";
			this.tb_static_sm.ReadOnly = true;
			global::System.Windows.Forms.Control tb_static_sm2 = this.tb_static_sm;
			size = new global::System.Drawing.Size(116, 20);
			tb_static_sm2.Size = size;
			this.tb_static_sm.TabIndex = 5;
			this.tb_static_sm.TextAlign = 1;
			this.Label4.AutoSize = true;
			global::System.Windows.Forms.Control label3 = this.Label4;
			location = new global::System.Drawing.Point(6, 75);
			label3.Location = location;
			this.Label4.Name = "Label4";
			global::System.Windows.Forms.Control label4 = this.Label4;
			size = new global::System.Drawing.Size(26, 13);
			label4.Size = size;
			this.Label4.TabIndex = 4;
			this.Label4.Text = "SM:";
			global::System.Windows.Forms.Control tb_static_gw = this.tb_static_gw;
			location = new global::System.Drawing.Point(46, 46);
			tb_static_gw.Location = location;
			this.tb_static_gw.Name = "tb_static_gw";
			this.tb_static_gw.ReadOnly = true;
			global::System.Windows.Forms.Control tb_static_gw2 = this.tb_static_gw;
			size = new global::System.Drawing.Size(116, 20);
			tb_static_gw2.Size = size;
			this.tb_static_gw.TabIndex = 3;
			this.tb_static_gw.TextAlign = 1;
			this.Label5.AutoSize = true;
			global::System.Windows.Forms.Control label5 = this.Label5;
			location = new global::System.Drawing.Point(6, 49);
			label5.Location = location;
			this.Label5.Name = "Label5";
			global::System.Windows.Forms.Control label6 = this.Label5;
			size = new global::System.Drawing.Size(29, 13);
			label6.Size = size;
			this.Label5.TabIndex = 2;
			this.Label5.Text = "GW:";
			global::System.Windows.Forms.Control tb_static_ip = this.tb_static_ip;
			location = new global::System.Drawing.Point(46, 19);
			tb_static_ip.Location = location;
			this.tb_static_ip.Name = "tb_static_ip";
			this.tb_static_ip.ReadOnly = true;
			global::System.Windows.Forms.Control tb_static_ip2 = this.tb_static_ip;
			size = new global::System.Drawing.Size(116, 20);
			tb_static_ip2.Size = size;
			this.tb_static_ip.TabIndex = 1;
			this.tb_static_ip.TextAlign = 1;
			this.Label6.AutoSize = true;
			global::System.Windows.Forms.Control label7 = this.Label6;
			location = new global::System.Drawing.Point(6, 22);
			label7.Location = location;
			this.Label6.Name = "Label6";
			global::System.Windows.Forms.Control label8 = this.Label6;
			size = new global::System.Drawing.Size(20, 13);
			label8.Size = size;
			this.Label6.TabIndex = 0;
			this.Label6.Text = "IP:";
			this.GroupBox1.Controls.Add(this.tb_dhcp_sm);
			this.GroupBox1.Controls.Add(this.Label3);
			this.GroupBox1.Controls.Add(this.tb_dhcp_gw);
			this.GroupBox1.Controls.Add(this.Label2);
			this.GroupBox1.Controls.Add(this.tb_dhcp_ip);
			this.GroupBox1.Controls.Add(this.Label1);
			global::System.Windows.Forms.Control groupBox5 = this.GroupBox1;
			location = new global::System.Drawing.Point(21, 66);
			groupBox5.Location = location;
			this.GroupBox1.Name = "GroupBox1";
			global::System.Windows.Forms.Control groupBox6 = this.GroupBox1;
			size = new global::System.Drawing.Size(255, 100);
			groupBox6.Size = size;
			this.GroupBox1.TabIndex = 4;
			this.GroupBox1.TabStop = false;
			this.GroupBox1.Text = "DHCP:";
			global::System.Windows.Forms.Control tb_dhcp_sm = this.tb_dhcp_sm;
			location = new global::System.Drawing.Point(46, 72);
			tb_dhcp_sm.Location = location;
			this.tb_dhcp_sm.Name = "tb_dhcp_sm";
			this.tb_dhcp_sm.ReadOnly = true;
			global::System.Windows.Forms.Control tb_dhcp_sm2 = this.tb_dhcp_sm;
			size = new global::System.Drawing.Size(116, 20);
			tb_dhcp_sm2.Size = size;
			this.tb_dhcp_sm.TabIndex = 5;
			this.tb_dhcp_sm.TextAlign = 1;
			this.Label3.AutoSize = true;
			global::System.Windows.Forms.Control label9 = this.Label3;
			location = new global::System.Drawing.Point(6, 75);
			label9.Location = location;
			this.Label3.Name = "Label3";
			global::System.Windows.Forms.Control label10 = this.Label3;
			size = new global::System.Drawing.Size(26, 13);
			label10.Size = size;
			this.Label3.TabIndex = 4;
			this.Label3.Text = "SM:";
			global::System.Windows.Forms.Control tb_dhcp_gw = this.tb_dhcp_gw;
			location = new global::System.Drawing.Point(46, 46);
			tb_dhcp_gw.Location = location;
			this.tb_dhcp_gw.Name = "tb_dhcp_gw";
			this.tb_dhcp_gw.ReadOnly = true;
			global::System.Windows.Forms.Control tb_dhcp_gw2 = this.tb_dhcp_gw;
			size = new global::System.Drawing.Size(116, 20);
			tb_dhcp_gw2.Size = size;
			this.tb_dhcp_gw.TabIndex = 3;
			this.tb_dhcp_gw.TextAlign = 1;
			this.Label2.AutoSize = true;
			global::System.Windows.Forms.Control label11 = this.Label2;
			location = new global::System.Drawing.Point(6, 49);
			label11.Location = location;
			this.Label2.Name = "Label2";
			global::System.Windows.Forms.Control label12 = this.Label2;
			size = new global::System.Drawing.Size(29, 13);
			label12.Size = size;
			this.Label2.TabIndex = 2;
			this.Label2.Text = "GW:";
			global::System.Windows.Forms.Control tb_dhcp_ip = this.tb_dhcp_ip;
			location = new global::System.Drawing.Point(46, 19);
			tb_dhcp_ip.Location = location;
			this.tb_dhcp_ip.Name = "tb_dhcp_ip";
			this.tb_dhcp_ip.ReadOnly = true;
			global::System.Windows.Forms.Control tb_dhcp_ip2 = this.tb_dhcp_ip;
			size = new global::System.Drawing.Size(116, 20);
			tb_dhcp_ip2.Size = size;
			this.tb_dhcp_ip.TabIndex = 1;
			this.tb_dhcp_ip.TextAlign = 1;
			this.Label1.AutoSize = true;
			global::System.Windows.Forms.Control label13 = this.Label1;
			location = new global::System.Drawing.Point(6, 22);
			label13.Location = location;
			this.Label1.Name = "Label1";
			global::System.Windows.Forms.Control label14 = this.Label1;
			size = new global::System.Drawing.Size(20, 13);
			label14.Size = size;
			this.Label1.TabIndex = 0;
			this.Label1.Text = "IP:";
			this.ComboBox_Modo_Operacao.FormattingEnabled = true;
			global::System.Windows.Forms.Control comboBox_Modo_Operacao = this.ComboBox_Modo_Operacao;
			location = new global::System.Drawing.Point(132, 28);
			comboBox_Modo_Operacao.Location = location;
			this.ComboBox_Modo_Operacao.Name = "ComboBox_Modo_Operacao";
			global::System.Windows.Forms.Control comboBox_Modo_Operacao2 = this.ComboBox_Modo_Operacao;
			size = new global::System.Drawing.Size(144, 21);
			comboBox_Modo_Operacao2.Size = size;
			this.ComboBox_Modo_Operacao.TabIndex = 0;
			this.Label_MetodoOperacao.AutoSize = true;
			global::System.Windows.Forms.Control label_MetodoOperacao = this.Label_MetodoOperacao;
			location = new global::System.Drawing.Point(21, 31);
			label_MetodoOperacao.Location = location;
			this.Label_MetodoOperacao.Name = "Label_MetodoOperacao";
			global::System.Windows.Forms.Control label_MetodoOperacao2 = this.Label_MetodoOperacao;
			size = new global::System.Drawing.Size(73, 13);
			label_MetodoOperacao2.Size = size;
			this.Label_MetodoOperacao.TabIndex = 3;
			this.Label_MetodoOperacao.Text = "Atribuição IP :";
			this.GroupBox_informacoes.Controls.Add(this.tbMAC5);
			this.GroupBox_informacoes.Controls.Add(this.tbMAC4);
			this.GroupBox_informacoes.Controls.Add(this.tbMAC3);
			this.GroupBox_informacoes.Controls.Add(this.tbMAC2);
			this.GroupBox_informacoes.Controls.Add(this.tbMAC1);
			this.GroupBox_informacoes.Controls.Add(this.tbMAC0);
			this.GroupBox_informacoes.Controls.Add(this.tbMAC);
			this.GroupBox_informacoes.Controls.Add(this.Label17);
			this.GroupBox_informacoes.Controls.Add(this.Label26);
			this.GroupBox_informacoes.Controls.Add(this.TextBox_equipamento);
			this.GroupBox_informacoes.Controls.Add(this.Label_equipamento);
			this.GroupBox_informacoes.Controls.Add(this.TextBox_release);
			this.GroupBox_informacoes.Controls.Add(this.Label_release);
			this.GroupBox_informacoes.Controls.Add(this.TextBox_build);
			this.GroupBox_informacoes.Controls.Add(this.Label_build);
			this.GroupBox_informacoes.Controls.Add(this.TextBox_versao);
			this.GroupBox_informacoes.Controls.Add(this.Label_versao);
			this.GroupBox_informacoes.Enabled = false;
			global::System.Windows.Forms.Control groupBox_informacoes = this.GroupBox_informacoes;
			location = new global::System.Drawing.Point(336, 10);
			groupBox_informacoes.Location = location;
			this.GroupBox_informacoes.Name = "GroupBox_informacoes";
			global::System.Windows.Forms.Control groupBox_informacoes2 = this.GroupBox_informacoes;
			size = new global::System.Drawing.Size(456, 147);
			groupBox_informacoes2.Size = size;
			this.GroupBox_informacoes.TabIndex = 2;
			this.GroupBox_informacoes.TabStop = false;
			this.GroupBox_informacoes.Text = "Versão de Software";
			global::System.Windows.Forms.Control tbMAC = this.tbMAC5;
			location = new global::System.Drawing.Point(149, 109);
			tbMAC.Location = location;
			this.tbMAC5.Name = "tbMAC5";
			this.tbMAC5.ReadOnly = true;
			global::System.Windows.Forms.Control tbMAC2 = this.tbMAC5;
			size = new global::System.Drawing.Size(34, 20);
			tbMAC2.Size = size;
			this.tbMAC5.TabIndex = 25;
			global::System.Windows.Forms.Control tbMAC3 = this.tbMAC4;
			location = new global::System.Drawing.Point(189, 109);
			tbMAC3.Location = location;
			this.tbMAC4.Name = "tbMAC4";
			this.tbMAC4.ReadOnly = true;
			global::System.Windows.Forms.Control tbMAC4 = this.tbMAC4;
			size = new global::System.Drawing.Size(34, 20);
			tbMAC4.Size = size;
			this.tbMAC4.TabIndex = 24;
			global::System.Windows.Forms.Control tbMAC5 = this.tbMAC3;
			location = new global::System.Drawing.Point(229, 109);
			tbMAC5.Location = location;
			this.tbMAC3.Name = "tbMAC3";
			this.tbMAC3.ReadOnly = true;
			global::System.Windows.Forms.Control tbMAC6 = this.tbMAC3;
			size = new global::System.Drawing.Size(34, 20);
			tbMAC6.Size = size;
			this.tbMAC3.TabIndex = 23;
			global::System.Windows.Forms.Control tbMAC7 = this.tbMAC2;
			location = new global::System.Drawing.Point(269, 109);
			tbMAC7.Location = location;
			this.tbMAC2.Name = "tbMAC2";
			this.tbMAC2.ReadOnly = true;
			global::System.Windows.Forms.Control tbMAC8 = this.tbMAC2;
			size = new global::System.Drawing.Size(34, 20);
			tbMAC8.Size = size;
			this.tbMAC2.TabIndex = 22;
			global::System.Windows.Forms.Control tbMAC9 = this.tbMAC1;
			location = new global::System.Drawing.Point(310, 109);
			tbMAC9.Location = location;
			this.tbMAC1.Name = "tbMAC1";
			this.tbMAC1.ReadOnly = true;
			global::System.Windows.Forms.Control tbMAC10 = this.tbMAC1;
			size = new global::System.Drawing.Size(34, 20);
			tbMAC10.Size = size;
			this.tbMAC1.TabIndex = 21;
			global::System.Windows.Forms.Control tbMAC11 = this.tbMAC0;
			location = new global::System.Drawing.Point(350, 109);
			tbMAC11.Location = location;
			this.tbMAC0.Name = "tbMAC0";
			this.tbMAC0.ReadOnly = true;
			global::System.Windows.Forms.Control tbMAC12 = this.tbMAC0;
			size = new global::System.Drawing.Size(34, 20);
			tbMAC12.Size = size;
			this.tbMAC0.TabIndex = 20;
			this.tbMAC.AutoSize = true;
			this.tbMAC.Font = new global::System.Drawing.Font("Arial Narrow", 8.25f, 0, 3, 0);
			global::System.Windows.Forms.Control tbMAC13 = this.tbMAC;
			location = new global::System.Drawing.Point(106, 111);
			tbMAC13.Location = location;
			this.tbMAC.Name = "tbMAC";
			global::System.Windows.Forms.Control tbMAC14 = this.tbMAC;
			size = new global::System.Drawing.Size(28, 15);
			tbMAC14.Size = size;
			this.tbMAC.TabIndex = 19;
			this.tbMAC.Text = "MAC";
			this.Label17.AutoSize = true;
			this.Label17.Font = new global::System.Drawing.Font("Arial Narrow", 12f, 1, 3, 0);
			global::System.Windows.Forms.Control label15 = this.Label17;
			location = new global::System.Drawing.Point(105, 73);
			label15.Location = location;
			this.Label17.Name = "Label17";
			global::System.Windows.Forms.Control label16 = this.Label17;
			size = new global::System.Drawing.Size(295, 20);
			label16.Size = size;
			this.Label17.TabIndex = 18;
			this.Label17.Text = "Interface Ethernet para Remotas de Telemetria";
			this.Label26.AutoSize = true;
			this.Label26.Font = new global::System.Drawing.Font("Arial Narrow", 8.25f, 0, 3, 0);
			global::System.Windows.Forms.Control label17 = this.Label26;
			location = new global::System.Drawing.Point(106, 50);
			label17.Location = location;
			this.Label26.Name = "Label26";
			global::System.Windows.Forms.Control label18 = this.Label26;
			size = new global::System.Drawing.Size(22, 15);
			label18.Size = size;
			this.Label26.TabIndex = 17;
			this.Label26.Text = "IER";
			this.TextBox_equipamento.BackColor = global::System.Drawing.Color.LightCyan;
			this.TextBox_equipamento.Font = new global::System.Drawing.Font("Arial Narrow", 8.25f, 0, 3, 0);
			global::System.Windows.Forms.Control textBox_equipamento = this.TextBox_equipamento;
			location = new global::System.Drawing.Point(141, 47);
			textBox_equipamento.Location = location;
			this.TextBox_equipamento.Name = "TextBox_equipamento";
			this.TextBox_equipamento.ReadOnly = true;
			global::System.Windows.Forms.Control textBox_equipamento2 = this.TextBox_equipamento;
			size = new global::System.Drawing.Size(47, 20);
			textBox_equipamento2.Size = size;
			this.TextBox_equipamento.TabIndex = 16;
			this.TextBox_equipamento.TabStop = false;
			this.TextBox_equipamento.TextAlign = 2;
			this.Label_equipamento.AutoSize = true;
			global::System.Windows.Forms.Control label_equipamento = this.Label_equipamento;
			location = new global::System.Drawing.Point(106, 29);
			label_equipamento.Location = location;
			this.Label_equipamento.Name = "Label_equipamento";
			global::System.Windows.Forms.Control label_equipamento2 = this.Label_equipamento;
			size = new global::System.Drawing.Size(69, 13);
			label_equipamento2.Size = size;
			this.Label_equipamento.TabIndex = 15;
			this.Label_equipamento.Text = "Equipamento";
			this.TextBox_release.BackColor = global::System.Drawing.Color.LightCyan;
			this.TextBox_release.Font = new global::System.Drawing.Font("Arial Narrow", 8.25f, 0, 3, 0);
			global::System.Windows.Forms.Control textBox_release = this.TextBox_release;
			location = new global::System.Drawing.Point(297, 47);
			textBox_release.Location = location;
			this.TextBox_release.Name = "TextBox_release";
			this.TextBox_release.ReadOnly = true;
			global::System.Windows.Forms.Control textBox_release2 = this.TextBox_release;
			size = new global::System.Drawing.Size(47, 20);
			textBox_release2.Size = size;
			this.TextBox_release.TabIndex = 14;
			this.TextBox_release.TabStop = false;
			this.TextBox_release.TextAlign = 2;
			this.Label_release.AutoSize = true;
			global::System.Windows.Forms.Control label_release = this.Label_release;
			location = new global::System.Drawing.Point(300, 29);
			label_release.Location = location;
			this.Label_release.Name = "Label_release";
			global::System.Windows.Forms.Control label_release2 = this.Label_release;
			size = new global::System.Drawing.Size(46, 13);
			label_release2.Size = size;
			this.Label_release.TabIndex = 13;
			this.Label_release.Text = "Release";
			this.TextBox_build.BackColor = global::System.Drawing.Color.LightCyan;
			this.TextBox_build.Font = new global::System.Drawing.Font("Arial Narrow", 8.25f, 0, 3, 0);
			global::System.Windows.Forms.Control textBox_build = this.TextBox_build;
			location = new global::System.Drawing.Point(245, 47);
			textBox_build.Location = location;
			this.TextBox_build.Name = "TextBox_build";
			this.TextBox_build.ReadOnly = true;
			global::System.Windows.Forms.Control textBox_build2 = this.TextBox_build;
			size = new global::System.Drawing.Size(47, 20);
			textBox_build2.Size = size;
			this.TextBox_build.TabIndex = 12;
			this.TextBox_build.TabStop = false;
			this.TextBox_build.TextAlign = 2;
			this.Label_build.AutoSize = true;
			global::System.Windows.Forms.Control label_build = this.Label_build;
			location = new global::System.Drawing.Point(254, 29);
			label_build.Location = location;
			this.Label_build.Name = "Label_build";
			global::System.Windows.Forms.Control label_build2 = this.Label_build;
			size = new global::System.Drawing.Size(30, 13);
			label_build2.Size = size;
			this.Label_build.TabIndex = 11;
			this.Label_build.Text = "Build";
			this.TextBox_versao.BackColor = global::System.Drawing.Color.LightCyan;
			this.TextBox_versao.Font = new global::System.Drawing.Font("Arial Narrow", 8.25f, 0, 3, 0);
			global::System.Windows.Forms.Control textBox_versao = this.TextBox_versao;
			location = new global::System.Drawing.Point(193, 47);
			textBox_versao.Location = location;
			this.TextBox_versao.Name = "TextBox_versao";
			this.TextBox_versao.ReadOnly = true;
			global::System.Windows.Forms.Control textBox_versao2 = this.TextBox_versao;
			size = new global::System.Drawing.Size(47, 20);
			textBox_versao2.Size = size;
			this.TextBox_versao.TabIndex = 10;
			this.TextBox_versao.TabStop = false;
			this.TextBox_versao.TextAlign = 2;
			this.Label_versao.AutoSize = true;
			global::System.Windows.Forms.Control label_versao = this.Label_versao;
			location = new global::System.Drawing.Point(196, 29);
			label_versao.Location = location;
			this.Label_versao.Name = "Label_versao";
			global::System.Windows.Forms.Control label_versao2 = this.Label_versao;
			size = new global::System.Drawing.Size(40, 13);
			label_versao2.Size = size;
			this.Label_versao.TabIndex = 9;
			this.Label_versao.Text = "Versão";
			this.ToolStri_RT_810.BackColor = global::System.Drawing.Color.Transparent;
			this.ToolStri_RT_810.GripStyle = 0;
			global::System.Windows.Forms.ToolStrip toolStri_RT_ = this.ToolStri_RT_810;
			size = new global::System.Drawing.Size(48, 48);
			toolStri_RT_.ImageScalingSize = size;
			this.ToolStri_RT_810.Items.AddRange(new global::System.Windows.Forms.ToolStripItem[]
			{
				this.ToolStripButton_RT_810_novo,
				this.ToolStripButton_RT_810_Abrir,
				this.ToolStripButton_RT_810_Salvar,
				this.ToolStripSeparator1,
				this.ToolStripButton_RT_810_Download,
				this.ToolStripButton_RT_810_Upload,
				this.ToolStripSeparator2,
				this.ToolStripButton_RT_810_Imprimir,
				this.ToolStripSeparator3,
				this.ToolStripLabel_ID,
				this.ToolStripSeparator4,
				this.ToolStripTextBox_RT_810_Msg,
				this.ToolStripProgressBar_RT_810
			});
			this.ToolStri_RT_810.LayoutStyle = 3;
			global::System.Windows.Forms.Control toolStri_RT_2 = this.ToolStri_RT_810;
			location = new global::System.Drawing.Point(0, 0);
			toolStri_RT_2.Location = location;
			this.ToolStri_RT_810.Name = "ToolStri_RT_810";
			global::System.Windows.Forms.Control toolStri_RT_3 = this.ToolStri_RT_810;
			size = new global::System.Drawing.Size(1158, 55);
			toolStri_RT_3.Size = size;
			this.ToolStri_RT_810.Stretch = true;
			this.ToolStri_RT_810.TabIndex = 0;
			this.ToolStri_RT_810.Text = "ToolStrip1";
			this.ToolStripButton_RT_810_novo.AutoToolTip = false;
			this.ToolStripButton_RT_810_novo.DisplayStyle = 2;
			this.ToolStripButton_RT_810_novo.Image = global::iS800.My.Resources.Resources.folder_add_icon1;
			this.ToolStripButton_RT_810_novo.ImageTransparentColor = global::System.Drawing.Color.Magenta;
			global::System.Windows.Forms.ToolStripItem toolStripButton_RT_810_novo = this.ToolStripButton_RT_810_novo;
			padding = new global::System.Windows.Forms.Padding(10, 1, 0, 2);
			toolStripButton_RT_810_novo.Margin = padding;
			this.ToolStripButton_RT_810_novo.Name = "ToolStripButton_RT_810_novo";
			global::System.Windows.Forms.ToolStripItem toolStripButton_RT_810_novo2 = this.ToolStripButton_RT_810_novo;
			size = new global::System.Drawing.Size(52, 52);
			toolStripButton_RT_810_novo2.Size = size;
			this.ToolStripButton_RT_810_novo.Text = "Novo";
			this.ToolStripButton_RT_810_novo.ToolTipText = "Novo arquivo";
			this.ToolStripButton_RT_810_Abrir.AutoToolTip = false;
			this.ToolStripButton_RT_810_Abrir.DisplayStyle = 2;
			this.ToolStripButton_RT_810_Abrir.Image = global::iS800.My.Resources.Resources.folder_up_icon;
			this.ToolStripButton_RT_810_Abrir.ImageTransparentColor = global::System.Drawing.Color.Magenta;
			this.ToolStripButton_RT_810_Abrir.Name = "ToolStripButton_RT_810_Abrir";
			global::System.Windows.Forms.ToolStripItem toolStripButton_RT_810_Abrir = this.ToolStripButton_RT_810_Abrir;
			size = new global::System.Drawing.Size(52, 52);
			toolStripButton_RT_810_Abrir.Size = size;
			this.ToolStripButton_RT_810_Abrir.Text = "Abrir Arquivo";
			this.ToolStripButton_RT_810_Abrir.ToolTipText = "Abrir arquivo";
			this.ToolStripButton_RT_810_Salvar.AutoToolTip = false;
			this.ToolStripButton_RT_810_Salvar.DisplayStyle = 2;
			this.ToolStripButton_RT_810_Salvar.Image = global::iS800.My.Resources.Resources.folder_down_icon;
			this.ToolStripButton_RT_810_Salvar.ImageTransparentColor = global::System.Drawing.Color.Magenta;
			this.ToolStripButton_RT_810_Salvar.Name = "ToolStripButton_RT_810_Salvar";
			global::System.Windows.Forms.ToolStripItem toolStripButton_RT_810_Salvar = this.ToolStripButton_RT_810_Salvar;
			size = new global::System.Drawing.Size(52, 52);
			toolStripButton_RT_810_Salvar.Size = size;
			this.ToolStripButton_RT_810_Salvar.Text = "Salvar Arquivo";
			this.ToolStripButton_RT_810_Salvar.ToolTipText = "Salvar arquivo";
			this.ToolStripSeparator1.AutoSize = false;
			global::System.Windows.Forms.ToolStripItem toolStripSeparator = this.ToolStripSeparator1;
			padding = new global::System.Windows.Forms.Padding(10, 0, 0, 0);
			toolStripSeparator.Margin = padding;
			this.ToolStripSeparator1.Name = "ToolStripSeparator1";
			global::System.Windows.Forms.ToolStripItem toolStripSeparator2 = this.ToolStripSeparator1;
			size = new global::System.Drawing.Size(6, 52);
			toolStripSeparator2.Size = size;
			this.ToolStripButton_RT_810_Download.DisplayStyle = 2;
			this.ToolStripButton_RT_810_Download.Image = global::iS800.My.Resources.Resources.Upload_icon;
			this.ToolStripButton_RT_810_Download.ImageTransparentColor = global::System.Drawing.Color.Magenta;
			global::System.Windows.Forms.ToolStripItem toolStripButton_RT_810_Download = this.ToolStripButton_RT_810_Download;
			padding = new global::System.Windows.Forms.Padding(10, 1, 0, 2);
			toolStripButton_RT_810_Download.Margin = padding;
			this.ToolStripButton_RT_810_Download.Name = "ToolStripButton_RT_810_Download";
			global::System.Windows.Forms.ToolStripItem toolStripButton_RT_810_Download2 = this.ToolStripButton_RT_810_Download;
			size = new global::System.Drawing.Size(52, 52);
			toolStripButton_RT_810_Download2.Size = size;
			this.ToolStripButton_RT_810_Download.Text = "Ler Equipamento";
			this.ToolStripButton_RT_810_Upload.DisplayStyle = 2;
			this.ToolStripButton_RT_810_Upload.Image = global::iS800.My.Resources.Resources.Download_icon;
			this.ToolStripButton_RT_810_Upload.ImageTransparentColor = global::System.Drawing.Color.Magenta;
			this.ToolStripButton_RT_810_Upload.Name = "ToolStripButton_RT_810_Upload";
			global::System.Windows.Forms.ToolStripItem toolStripButton_RT_810_Upload = this.ToolStripButton_RT_810_Upload;
			size = new global::System.Drawing.Size(52, 52);
			toolStripButton_RT_810_Upload.Size = size;
			this.ToolStripButton_RT_810_Upload.Text = "Gravar no equipamento";
			this.ToolStripSeparator2.AutoSize = false;
			global::System.Windows.Forms.ToolStripItem toolStripSeparator3 = this.ToolStripSeparator2;
			padding = new global::System.Windows.Forms.Padding(10, 0, 0, 0);
			toolStripSeparator3.Margin = padding;
			this.ToolStripSeparator2.Name = "ToolStripSeparator2";
			global::System.Windows.Forms.ToolStripItem toolStripSeparator4 = this.ToolStripSeparator2;
			size = new global::System.Drawing.Size(6, 52);
			toolStripSeparator4.Size = size;
			this.ToolStripButton_RT_810_Imprimir.DisplayStyle = 2;
			this.ToolStripButton_RT_810_Imprimir.Image = global::iS800.My.Resources.Resources.Hardware_Printer_Text_Icon_128;
			this.ToolStripButton_RT_810_Imprimir.ImageTransparentColor = global::System.Drawing.Color.Magenta;
			this.ToolStripButton_RT_810_Imprimir.Name = "ToolStripButton_RT_810_Imprimir";
			global::System.Windows.Forms.ToolStripItem toolStripButton_RT_810_Imprimir = this.ToolStripButton_RT_810_Imprimir;
			size = new global::System.Drawing.Size(52, 52);
			toolStripButton_RT_810_Imprimir.Size = size;
			this.ToolStripButton_RT_810_Imprimir.Text = "Impressão da ficha de configuração";
			this.ToolStripSeparator3.AutoSize = false;
			this.ToolStripSeparator3.Name = "ToolStripSeparator3";
			global::System.Windows.Forms.ToolStripItem toolStripSeparator5 = this.ToolStripSeparator3;
			size = new global::System.Drawing.Size(6, 52);
			toolStripSeparator5.Size = size;
			this.ToolStripLabel_ID.Font = new global::System.Drawing.Font("Arial Narrow", 18f, 2, 3, 0);
			this.ToolStripLabel_ID.ForeColor = global::System.Drawing.Color.FromArgb(192, 0, 0);
			global::System.Windows.Forms.ToolStripItem toolStripLabel_ID = this.ToolStripLabel_ID;
			padding = new global::System.Windows.Forms.Padding(5, 13, 0, 2);
			toolStripLabel_ID.Margin = padding;
			this.ToolStripLabel_ID.Name = "ToolStripLabel_ID";
			global::System.Windows.Forms.ToolStripItem toolStripLabel_ID2 = this.ToolStripLabel_ID;
			size = new global::System.Drawing.Size(116, 29);
			toolStripLabel_ID2.Size = size;
			this.ToolStripLabel_ID.Text = "IER856/300";
			this.ToolStripSeparator4.AutoSize = false;
			this.ToolStripSeparator4.Name = "ToolStripSeparator4";
			global::System.Windows.Forms.ToolStripItem toolStripSeparator6 = this.ToolStripSeparator4;
			size = new global::System.Drawing.Size(6, 52);
			toolStripSeparator6.Size = size;
			this.ToolStripTextBox_RT_810_Msg.BackColor = global::System.Drawing.Color.LightCyan;
			this.ToolStripTextBox_RT_810_Msg.BorderStyle = 1;
			global::System.Windows.Forms.ToolStripItem toolStripTextBox_RT_810_Msg = this.ToolStripTextBox_RT_810_Msg;
			padding = new global::System.Windows.Forms.Padding(10, 15, 1, 0);
			toolStripTextBox_RT_810_Msg.Margin = padding;
			this.ToolStripTextBox_RT_810_Msg.Name = "ToolStripTextBox_RT_810_Msg";
			this.ToolStripTextBox_RT_810_Msg.ReadOnly = true;
			global::System.Windows.Forms.ToolStripControlHost toolStripTextBox_RT_810_Msg2 = this.ToolStripTextBox_RT_810_Msg;
			size = new global::System.Drawing.Size(250, 23);
			toolStripTextBox_RT_810_Msg2.Size = size;
			this.ToolStripTextBox_RT_810_Msg.TextBoxTextAlign = 2;
			this.ToolStripProgressBar_RT_810.BackColor = global::System.Drawing.SystemColors.Control;
			global::System.Windows.Forms.ToolStripItem toolStripProgressBar_RT_ = this.ToolStripProgressBar_RT_810;
			padding = new global::System.Windows.Forms.Padding(20, 15, 1, 1);
			toolStripProgressBar_RT_.Margin = padding;
			this.ToolStripProgressBar_RT_810.Name = "ToolStripProgressBar_RT_810";
			global::System.Windows.Forms.ToolStripControlHost toolStripProgressBar_RT_2 = this.ToolStripProgressBar_RT_810;
			size = new global::System.Drawing.Size(180, 20);
			toolStripProgressBar_RT_2.Size = size;
			this.ToolStripProgressBar_RT_810.ToolTipText = "Progresso da operação";
			this.OpenFileDialog_RT_810.FileName = "OpenFileDialog1";
			this.Timer_limpa_MSG.Interval = 2000;
			global::System.Windows.Forms.PrintPreviewDialog printPreviewDialog = this.PrintPreviewDialog1;
			size = new global::System.Drawing.Size(0, 0);
			printPreviewDialog.AutoScrollMargin = size;
			global::System.Windows.Forms.PrintPreviewDialog printPreviewDialog2 = this.PrintPreviewDialog1;
			size = new global::System.Drawing.Size(0, 0);
			printPreviewDialog2.AutoScrollMinSize = size;
			global::System.Windows.Forms.Form printPreviewDialog3 = this.PrintPreviewDialog1;
			size = new global::System.Drawing.Size(400, 300);
			printPreviewDialog3.ClientSize = size;
			this.PrintPreviewDialog1.Document = this.PrintDocument1;
			this.PrintPreviewDialog1.Enabled = true;
			this.PrintPreviewDialog1.Icon = (global::System.Drawing.Icon)componentResourceManager.GetObject("PrintPreviewDialog1.Icon");
			this.PrintPreviewDialog1.Name = "PrintPreviewDialog1";
			this.PrintPreviewDialog1.Visible = false;
			global::System.Drawing.SizeF autoScaleDimensions;
			autoScaleDimensions = new global::System.Drawing.SizeF(6f, 13f);
			this.AutoScaleDimensions = autoScaleDimensions;
			this.AutoScaleMode = 1;
			this.BackColor = global::System.Drawing.SystemColors.ControlLight;
			size = new global::System.Drawing.Size(1158, 609);
			this.ClientSize = size;
			this.Controls.Add(this.ToolStri_RT_810);
			this.Controls.Add(this.TabControl_810);
			this.FormBorderStyle = 1;
			this.Name = "IER_856_conf";
			this.RightToLeftLayout = true;
			this.ShowIcon = false;
			this.StartPosition = 0;
			this.Text = "Configuração";
			this.TabControl_810.ResumeLayout(false);
			this.TabPage_geral.ResumeLayout(false);
			this.GroupBox2.ResumeLayout(false);
			this.GroupBox2.PerformLayout();
			this.GroupBox_ModoOperacao.ResumeLayout(false);
			this.GroupBox_ModoOperacao.PerformLayout();
			this.GroupBox3.ResumeLayout(false);
			this.GroupBox3.PerformLayout();
			this.GroupBox1.ResumeLayout(false);
			this.GroupBox1.PerformLayout();
			this.GroupBox_informacoes.ResumeLayout(false);
			this.GroupBox_informacoes.PerformLayout();
			this.ToolStri_RT_810.ResumeLayout(false);
			this.ToolStri_RT_810.PerformLayout();
			this.RepetidoraBindingSource1.EndInit();
			this.ResumeLayout(false);
			this.PerformLayout();
		}

		// Token: 0x0400081A RID: 2074
		private global::System.ComponentModel.IContainer components;
	}
}
