from pathlib import Path
import re

root = Path(".")

patterns = [
    # var..ctor(...) -> var = new var(...)
    (re.compile(r'(\b[A-Za-z_][A-Za-z0-9_]*)\.\.ctor\((.*?)\);', re.DOTALL), r'\1 = new \1(\2);'),

    # typed locals created from lowercase aliases generated by decompilation
    # e.g. location = new location(1, 2); -> location = new global::System.Drawing.Point(1, 2);
    (re.compile(r'(global::[A-Za-z0-9_.]+)\s+([A-Za-z_][A-Za-z0-9_]*)\s*;\s*\2\s*=\s*new\s+\2\(', re.DOTALL), r'\1 \2;\n\t\t\t\2 = new \1('),
]

count_files = 0
count_replacements = 0

for path in root.rglob("*.cs"):
    if path.name == "tmp_fix_decompiled_syntax.py":
        continue

    text = path.read_text(encoding="utf-8", errors="ignore")
    original = text

    changed = True
    while changed:
        changed = False
        for pattern, repl in patterns:
            text, n = pattern.subn(repl, text)
            if n:
                changed = True
                count_replacements += n

    if text != original:
        path.write_text(text, encoding="utf-8")
        count_files += 1

print(f"updated_files={count_files}")
print(f"replacements={count_replacements}")
