namespace iS800
{
	// Token: 0x0200009E RID: 158
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class Equip_VA220_ope : global::System.Windows.Forms.Form
	{
		// Token: 0x0600256A RID: 9578 RVA: 0x0041537C File Offset: 0x0041377C
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			if (disposing && this.components != null)
			{
				this.components.Dispose();
			}
			base.Dispose(disposing);
		}

		// Token: 0x0600256B RID: 9579 RVA: 0x0041539C File Offset: 0x0041379C
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.components = new global::System.ComponentModel.Container();
			this.CheckBox_setpoints = new global::System.Windows.Forms.CheckBox();
			this.Grupo_endereco = new global::System.Windows.Forms.GroupBox();
			this.Box_Msg = new global::System.Windows.Forms.TextBox();
			this.Button_escrever = new global::System.Windows.Forms.Button();
			this.Button_ler = new global::System.Windows.Forms.Button();
			this.GroupBox_opcoes = new global::System.Windows.Forms.GroupBox();
			this.CheckBox_relogio = new global::System.Windows.Forms.CheckBox();
			this.CheckBox_temperatura = new global::System.Windows.Forms.CheckBox();
			this.CheckBox_alarmes = new global::System.Windows.Forms.CheckBox();
			this.CheckBox_ponta = new global::System.Windows.Forms.CheckBox();
			this.CheckBox_timer = new global::System.Windows.Forms.CheckBox();
			this.Label_end_mestre = new global::System.Windows.Forms.Label();
			this.Label_end_estacao = new global::System.Windows.Forms.Label();
			this.VScroll_end_mestre = new global::System.Windows.Forms.VScrollBar();
			this.VScroll_end_estacao = new global::System.Windows.Forms.VScrollBar();
			this.Valor_end_mestre = new global::System.Windows.Forms.TextBox();
			this.Valor_end_estacao = new global::System.Windows.Forms.TextBox();
			this.Grupo_setpoint = new global::System.Windows.Forms.GroupBox();
			this.Grupo_gerais = new global::System.Windows.Forms.GroupBox();
			this.Label_pressao_controle = new global::System.Windows.Forms.Label();
			this.Label_pressao_succao = new global::System.Windows.Forms.Label();
			this.Label_tempo_mais_motor = new global::System.Windows.Forms.Label();
			this.Valor_pressao_controle = new global::System.Windows.Forms.TextBox();
			this.Valor_pressao_succao = new global::System.Windows.Forms.TextBox();
			this.Valor_tempo_mais_bomba = new global::System.Windows.Forms.TextBox();
			this.Grupo_niveis = new global::System.Windows.Forms.GroupBox();
			this.Label_nivel_bomba_4 = new global::System.Windows.Forms.Label();
			this.Label_nivel_bomba_3 = new global::System.Windows.Forms.Label();
			this.Label_nivel_bomba_2 = new global::System.Windows.Forms.Label();
			this.Label_nivel_bomba_1 = new global::System.Windows.Forms.Label();
			this.Label_nivel_desejado = new global::System.Windows.Forms.Label();
			this.Valor_nivel_B4 = new global::System.Windows.Forms.TextBox();
			this.Valor_nivel_B3 = new global::System.Windows.Forms.TextBox();
			this.Valor_nivel_B2 = new global::System.Windows.Forms.TextBox();
			this.Valor_nivel_B1 = new global::System.Windows.Forms.TextBox();
			this.Valor_nivel_desejado = new global::System.Windows.Forms.TextBox();
			this.Grupo_origem = new global::System.Windows.Forms.GroupBox();
			this.Label_nivel_ligamento = new global::System.Windows.Forms.Label();
			this.Label_nivel_desligamento = new global::System.Windows.Forms.Label();
			this.Valor_nivel_ligamento = new global::System.Windows.Forms.TextBox();
			this.Valor_nivel_desligamento = new global::System.Windows.Forms.TextBox();
			this.Grupo_alarmes = new global::System.Windows.Forms.GroupBox();
			this.GroupBox_nivel_alto = new global::System.Windows.Forms.GroupBox();
			this.Valor_NA_T = new global::System.Windows.Forms.TextBox();
			this.Valor_NA_B4 = new global::System.Windows.Forms.TextBox();
			this.Valor_NA_B3 = new global::System.Windows.Forms.TextBox();
			this.Valor_NA_B2 = new global::System.Windows.Forms.TextBox();
			this.Valor_NA_B1 = new global::System.Windows.Forms.TextBox();
			this.GroupBox_nivel_baixo = new global::System.Windows.Forms.GroupBox();
			this.Valor_NB_T = new global::System.Windows.Forms.TextBox();
			this.Valor_NB_B4 = new global::System.Windows.Forms.TextBox();
			this.Valor_NB_B3 = new global::System.Windows.Forms.TextBox();
			this.Valor_NB_B2 = new global::System.Windows.Forms.TextBox();
			this.Valor_NB_B1 = new global::System.Windows.Forms.TextBox();
			this.CheckBox_alm_rq = new global::System.Windows.Forms.CheckBox();
			this.Label_alm_tensao = new global::System.Windows.Forms.Label();
			this.Label_alm_bomba_4 = new global::System.Windows.Forms.Label();
			this.Label_alm_bomba_3 = new global::System.Windows.Forms.Label();
			this.Label_alm_bomba_2 = new global::System.Windows.Forms.Label();
			this.Label_alm_bomba_1 = new global::System.Windows.Forms.Label();
			this.GroupBox_timer_1 = new global::System.Windows.Forms.GroupBox();
			this.GroupBox_Desliga_B1 = new global::System.Windows.Forms.GroupBox();
			this.Valor_desliga_faixa4_b1 = new global::System.Windows.Forms.TextBox();
			this.Valor_desliga_faixa3_b1 = new global::System.Windows.Forms.TextBox();
			this.Valor_desliga_faixa2_b1 = new global::System.Windows.Forms.TextBox();
			this.Valor_desliga_faixa1_b1 = new global::System.Windows.Forms.TextBox();
			this.GroupBox_Liga_B1 = new global::System.Windows.Forms.GroupBox();
			this.Valor_liga_faixa4_b1 = new global::System.Windows.Forms.TextBox();
			this.Valor_liga_faixa3_b1 = new global::System.Windows.Forms.TextBox();
			this.Valor_liga_faixa2_b1 = new global::System.Windows.Forms.TextBox();
			this.Valor_liga_faixa1_b1 = new global::System.Windows.Forms.TextBox();
			this.Label_faixa4_B1 = new global::System.Windows.Forms.Label();
			this.Label_faixa3_B1 = new global::System.Windows.Forms.Label();
			this.Label_faixa2_B1 = new global::System.Windows.Forms.Label();
			this.Label_faixa1_B1 = new global::System.Windows.Forms.Label();
			this.GroupBox_timer_2 = new global::System.Windows.Forms.GroupBox();
			this.GroupBox2 = new global::System.Windows.Forms.GroupBox();
			this.Valor_desliga_faixa4_b2 = new global::System.Windows.Forms.TextBox();
			this.Valor_desliga_faixa3_b2 = new global::System.Windows.Forms.TextBox();
			this.Valor_desliga_faixa2_b2 = new global::System.Windows.Forms.TextBox();
			this.Valor_desliga_faixa1_b2 = new global::System.Windows.Forms.TextBox();
			this.GroupBox3 = new global::System.Windows.Forms.GroupBox();
			this.Valor_liga_faixa4_b2 = new global::System.Windows.Forms.TextBox();
			this.Valor_liga_faixa3_b2 = new global::System.Windows.Forms.TextBox();
			this.Valor_liga_faixa2_b2 = new global::System.Windows.Forms.TextBox();
			this.Valor_liga_faixa1_b2 = new global::System.Windows.Forms.TextBox();
			this.Label_faixa4_B2 = new global::System.Windows.Forms.Label();
			this.Label_faixa3_B2 = new global::System.Windows.Forms.Label();
			this.Label_faixa2_B2 = new global::System.Windows.Forms.Label();
			this.Label_faixa1_B2 = new global::System.Windows.Forms.Label();
			this.GroupBox_timer_4 = new global::System.Windows.Forms.GroupBox();
			this.GroupBox5 = new global::System.Windows.Forms.GroupBox();
			this.Valor_desliga_faixa4_b4 = new global::System.Windows.Forms.TextBox();
			this.Valor_desliga_faixa3_b4 = new global::System.Windows.Forms.TextBox();
			this.Valor_desliga_faixa2_b4 = new global::System.Windows.Forms.TextBox();
			this.Valor_desliga_faixa1_b4 = new global::System.Windows.Forms.TextBox();
			this.GroupBox6 = new global::System.Windows.Forms.GroupBox();
			this.Valor_liga_faixa4_b4 = new global::System.Windows.Forms.TextBox();
			this.Valor_liga_faixa3_b4 = new global::System.Windows.Forms.TextBox();
			this.Valor_liga_faixa2_b4 = new global::System.Windows.Forms.TextBox();
			this.Valor_liga_faixa1_b4 = new global::System.Windows.Forms.TextBox();
			this.Label_faixa4_B4 = new global::System.Windows.Forms.Label();
			this.Label_faixa3_B4 = new global::System.Windows.Forms.Label();
			this.Label_faixa2_B4 = new global::System.Windows.Forms.Label();
			this.Label_faixa1_B4 = new global::System.Windows.Forms.Label();
			this.GroupBox_timer_3 = new global::System.Windows.Forms.GroupBox();
			this.GroupBox8 = new global::System.Windows.Forms.GroupBox();
			this.Valor_desliga_faixa4_b3 = new global::System.Windows.Forms.TextBox();
			this.Valor_desliga_faixa3_b3 = new global::System.Windows.Forms.TextBox();
			this.Valor_desliga_faixa2_b3 = new global::System.Windows.Forms.TextBox();
			this.Valor_desliga_faixa1_b3 = new global::System.Windows.Forms.TextBox();
			this.GroupBox9 = new global::System.Windows.Forms.GroupBox();
			this.Valor_liga_faixa4_b3 = new global::System.Windows.Forms.TextBox();
			this.Valor_liga_faixa3_b3 = new global::System.Windows.Forms.TextBox();
			this.Valor_liga_faixa2_b3 = new global::System.Windows.Forms.TextBox();
			this.Valor_liga_faixa1_b3 = new global::System.Windows.Forms.TextBox();
			this.Label_faixa4_B3 = new global::System.Windows.Forms.Label();
			this.Label_faixa3_B3 = new global::System.Windows.Forms.Label();
			this.Label_faixa2_B3 = new global::System.Windows.Forms.Label();
			this.Label_faixa1_B3 = new global::System.Windows.Forms.Label();
			this.GroupBox_ponta = new global::System.Windows.Forms.GroupBox();
			this.CheckBox_horario_ponta = new global::System.Windows.Forms.CheckBox();
			this.Desliga_ponta = new global::System.Windows.Forms.GroupBox();
			this.Valor_desliga_ponta = new global::System.Windows.Forms.TextBox();
			this.Liga_ponta = new global::System.Windows.Forms.GroupBox();
			this.Valor_liga_ponta = new global::System.Windows.Forms.TextBox();
			this.Grupo_temperaturas = new global::System.Windows.Forms.GroupBox();
			this.Grupo_temp = new global::System.Windows.Forms.GroupBox();
			this.Valor_Temp_B4 = new global::System.Windows.Forms.TextBox();
			this.Valor_Temp_B3 = new global::System.Windows.Forms.TextBox();
			this.Valor_Temp_B2 = new global::System.Windows.Forms.TextBox();
			this.Valor_Temp_B1 = new global::System.Windows.Forms.TextBox();
			this.CheckBox_habilita_temperatura = new global::System.Windows.Forms.CheckBox();
			this.Label_temp_bomba_4 = new global::System.Windows.Forms.Label();
			this.Label_temp_bomba_3 = new global::System.Windows.Forms.Label();
			this.Label_temp_bomba_2 = new global::System.Windows.Forms.Label();
			this.Label_temp_bomba_1 = new global::System.Windows.Forms.Label();
			this.Grupo_relogio = new global::System.Windows.Forms.GroupBox();
			this.Button_atualiza_relogio_micro = new global::System.Windows.Forms.Button();
			this.Button_bloqueio_relogio = new global::System.Windows.Forms.Button();
			this.Label_hora = new global::System.Windows.Forms.Label();
			this.Label_data = new global::System.Windows.Forms.Label();
			this.Valor_hora = new global::System.Windows.Forms.TextBox();
			this.Valor_data = new global::System.Windows.Forms.TextBox();
			this.Ctrl_relogio = new global::System.Windows.Forms.Timer(this.components);
			this.Grupo_endereco.SuspendLayout();
			this.GroupBox_opcoes.SuspendLayout();
			this.Grupo_setpoint.SuspendLayout();
			this.Grupo_gerais.SuspendLayout();
			this.Grupo_niveis.SuspendLayout();
			this.Grupo_origem.SuspendLayout();
			this.Grupo_alarmes.SuspendLayout();
			this.GroupBox_nivel_alto.SuspendLayout();
			this.GroupBox_nivel_baixo.SuspendLayout();
			this.GroupBox_timer_1.SuspendLayout();
			this.GroupBox_Desliga_B1.SuspendLayout();
			this.GroupBox_Liga_B1.SuspendLayout();
			this.GroupBox_timer_2.SuspendLayout();
			this.GroupBox2.SuspendLayout();
			this.GroupBox3.SuspendLayout();
			this.GroupBox_timer_4.SuspendLayout();
			this.GroupBox5.SuspendLayout();
			this.GroupBox6.SuspendLayout();
			this.GroupBox_timer_3.SuspendLayout();
			this.GroupBox8.SuspendLayout();
			this.GroupBox9.SuspendLayout();
			this.GroupBox_ponta.SuspendLayout();
			this.Desliga_ponta.SuspendLayout();
			this.Liga_ponta.SuspendLayout();
			this.Grupo_temperaturas.SuspendLayout();
			this.Grupo_temp.SuspendLayout();
			this.Grupo_relogio.SuspendLayout();
			this.SuspendLayout();
			this.CheckBox_setpoints.AutoSize = true;
			this.CheckBox_setpoints.Checked = true;
			this.CheckBox_setpoints.CheckState = (System.Windows.Forms.CheckState)1;
			global::System.Windows.Forms.Control checkBox_setpoints = this.CheckBox_setpoints;
			global::System.Drawing.Point location;
			location = new global::System.Drawing.Point(9, 19);
			checkBox_setpoints.Location = location;
			this.CheckBox_setpoints.Name = "CheckBox_setpoints";
			global::System.Windows.Forms.Control checkBox_setpoints2 = this.CheckBox_setpoints;
			global::System.Drawing.Size size;
			size = new global::System.Drawing.Size(94, 17);
			checkBox_setpoints2.Size = size;
			this.CheckBox_setpoints.TabIndex = (HorizontalAlignment)4;
			this.CheckBox_setpoints.Text = "Hab. setpoints";
			this.CheckBox_setpoints.UseVisualStyleBackColor = true;
			this.Grupo_endereco.Controls.Add(this.Box_Msg);
			this.Grupo_endereco.Controls.Add(this.Button_escrever);
			this.Grupo_endereco.Controls.Add(this.Button_ler);
			this.Grupo_endereco.Controls.Add(this.GroupBox_opcoes);
			this.Grupo_endereco.Controls.Add(this.Label_end_mestre);
			this.Grupo_endereco.Controls.Add(this.Label_end_estacao);
			this.Grupo_endereco.Controls.Add(this.VScroll_end_mestre);
			this.Grupo_endereco.Controls.Add(this.VScroll_end_estacao);
			this.Grupo_endereco.Controls.Add(this.Valor_end_mestre);
			this.Grupo_endereco.Controls.Add(this.Valor_end_estacao);
			global::System.Windows.Forms.Control grupo_endereco = this.Grupo_endereco;
			location = new location(619, 12);
			grupo_endereco.Location = location;
			this.Grupo_endereco.Name = "Grupo_endereco";
			global::System.Windows.Forms.Control grupo_endereco2 = this.Grupo_endereco;
			size = new size(310, 194);
			grupo_endereco2.Size = size;
			this.Grupo_endereco.TabIndex = (HorizontalAlignment)1;
			this.Grupo_endereco.TabStop = false;
			this.Grupo_endereco.Text = "Endereço da estação";
			global::System.Windows.Forms.Control box_Msg = this.Box_Msg;
			location = new location(10, 164);
			box_Msg.Location = location;
			this.Box_Msg.Name = "Box_Msg";
			global::System.Windows.Forms.Control box_Msg2 = this.Box_Msg;
			size = new size(286, 20);
			box_Msg2.Size = size;
			this.Box_Msg.TabIndex = (HorizontalAlignment)11;
			this.Box_Msg.TabStop = false;
			this.Box_Msg.TextAlign = HorizontalAlignment.Right;
			global::System.Windows.Forms.Control button_escrever = this.Button_escrever;
			location = new location(34, 126);
			button_escrever.Location = location;
			this.Button_escrever.Name = "Button_escrever";
			global::System.Windows.Forms.Control button_escrever2 = this.Button_escrever;
			size = new size(127, 28);
			button_escrever2.Size = size;
			this.Button_escrever.TabIndex = (HorizontalAlignment)10;
			this.Button_escrever.Text = "Escrever";
			this.Button_escrever.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control button_ler = this.Button_ler;
			location = new location(34, 90);
			button_ler.Location = location;
			this.Button_ler.Name = "Button_ler";
			global::System.Windows.Forms.Control button_ler2 = this.Button_ler;
			size = new size(127, 28);
			button_ler2.Size = size;
			this.Button_ler.TabIndex = (HorizontalAlignment)9;
			this.Button_ler.Text = "Ler";
			this.Button_ler.UseVisualStyleBackColor = true;
			this.GroupBox_opcoes.Controls.Add(this.CheckBox_relogio);
			this.GroupBox_opcoes.Controls.Add(this.CheckBox_temperatura);
			this.GroupBox_opcoes.Controls.Add(this.CheckBox_alarmes);
			this.GroupBox_opcoes.Controls.Add(this.CheckBox_ponta);
			this.GroupBox_opcoes.Controls.Add(this.CheckBox_timer);
			this.GroupBox_opcoes.Controls.Add(this.CheckBox_setpoints);
			global::System.Windows.Forms.Control groupBox_opcoes = this.GroupBox_opcoes;
			location = new location(187, 14);
			groupBox_opcoes.Location = location;
			this.GroupBox_opcoes.Name = "GroupBox_opcoes";
			global::System.Windows.Forms.Control groupBox_opcoes2 = this.GroupBox_opcoes;
			size = new size(109, 142);
			groupBox_opcoes2.Size = size;
			this.GroupBox_opcoes.TabIndex = (HorizontalAlignment)3;
			this.GroupBox_opcoes.TabStop = false;
			this.GroupBox_opcoes.Text = "Opções";
			this.CheckBox_relogio.AutoSize = true;
			global::System.Windows.Forms.Control checkBox_relogio = this.CheckBox_relogio;
			location = new location(9, 119);
			checkBox_relogio.Location = location;
			this.CheckBox_relogio.Name = "CheckBox_relogio";
			global::System.Windows.Forms.Control checkBox_relogio2 = this.CheckBox_relogio;
			size = new size(83, 17);
			checkBox_relogio2.Size = size;
			this.CheckBox_relogio.TabIndex = (HorizontalAlignment)9;
			this.CheckBox_relogio.Text = "Hab. relógio";
			this.CheckBox_relogio.UseVisualStyleBackColor = true;
			this.CheckBox_temperatura.AutoSize = true;
			global::System.Windows.Forms.Control checkBox_temperatura = this.CheckBox_temperatura;
			location = new location(9, 99);
			checkBox_temperatura.Location = location;
			this.CheckBox_temperatura.Name = "CheckBox_temperatura";
			global::System.Windows.Forms.Control checkBox_temperatura2 = this.CheckBox_temperatura;
			size = new size(78, 17);
			checkBox_temperatura2.Size = size;
			this.CheckBox_temperatura.TabIndex = (HorizontalAlignment)8;
			this.CheckBox_temperatura.Text = "Hab. temp.";
			this.CheckBox_temperatura.UseVisualStyleBackColor = true;
			this.CheckBox_alarmes.AutoSize = true;
			global::System.Windows.Forms.Control checkBox_alarmes = this.CheckBox_alarmes;
			location = new location(9, 79);
			checkBox_alarmes.Location = location;
			this.CheckBox_alarmes.Name = "CheckBox_alarmes";
			global::System.Windows.Forms.Control checkBox_alarmes2 = this.CheckBox_alarmes;
			size = new size(88, 17);
			checkBox_alarmes2.Size = size;
			this.CheckBox_alarmes.TabIndex = (HorizontalAlignment)7;
			this.CheckBox_alarmes.Text = "Hab. alarmes";
			this.CheckBox_alarmes.UseVisualStyleBackColor = true;
			this.CheckBox_ponta.AutoSize = true;
			global::System.Windows.Forms.Control checkBox_ponta = this.CheckBox_ponta;
			location = new location(9, 59);
			checkBox_ponta.Location = location;
			this.CheckBox_ponta.Name = "CheckBox_ponta";
			global::System.Windows.Forms.Control checkBox_ponta2 = this.CheckBox_ponta;
			size = new size(79, 17);
			checkBox_ponta2.Size = size;
			this.CheckBox_ponta.TabIndex = (HorizontalAlignment)6;
			this.CheckBox_ponta.Text = "Hab. ponta";
			this.CheckBox_ponta.UseVisualStyleBackColor = true;
			this.CheckBox_timer.AutoSize = true;
			global::System.Windows.Forms.Control checkBox_timer = this.CheckBox_timer;
			location = new location(9, 39);
			checkBox_timer.Location = location;
			this.CheckBox_timer.Name = "CheckBox_timer";
			global::System.Windows.Forms.Control checkBox_timer2 = this.CheckBox_timer;
			size = new size(74, 17);
			checkBox_timer2.Size = size;
			this.CheckBox_timer.TabIndex = (HorizontalAlignment)5;
			this.CheckBox_timer.Text = "Hab. timer";
			this.CheckBox_timer.UseVisualStyleBackColor = true;
			this.Label_end_mestre.AutoSize = true;
			global::System.Windows.Forms.Control label_end_mestre = this.Label_end_mestre;
			location = new location(16, 57);
			label_end_mestre.Location = location;
			this.Label_end_mestre.Name = "Label_end_mestre";
			global::System.Windows.Forms.Control label_end_mestre2 = this.Label_end_mestre;
			size = new size(70, 13);
			label_end_mestre2.Size = size;
			this.Label_end_mestre.TabIndex = (HorizontalAlignment)2;
			this.Label_end_mestre.Text = "End. Mestre :";
			this.Label_end_estacao.AutoSize = true;
			global::System.Windows.Forms.Control label_end_estacao = this.Label_end_estacao;
			location = new location(16, 29);
			label_end_estacao.Location = location;
			this.Label_end_estacao.Name = "Label_end_estacao";
			global::System.Windows.Forms.Control label_end_estacao2 = this.Label_end_estacao;
			size = new size(77, 13);
			label_end_estacao2.Size = size;
			this.Label_end_estacao.TabIndex = (HorizontalAlignment)2;
			this.Label_end_estacao.Text = "End. Estação :";
			global::System.Windows.Forms.Control vscroll_end_mestre = this.VScroll_end_mestre;
			location = new location(144, 53);
			vscroll_end_mestre.Location = location;
			this.VScroll_end_mestre.Name = "VScroll_end_mestre";
			global::System.Windows.Forms.Control vscroll_end_mestre2 = this.VScroll_end_mestre;
			size = new size(26, 21);
			vscroll_end_mestre2.Size = size;
			this.VScroll_end_mestre.TabIndex = (HorizontalAlignment)1;
			global::System.Windows.Forms.Control vscroll_end_estacao = this.VScroll_end_estacao;
			location = new location(144, 25);
			vscroll_end_estacao.Location = location;
			this.VScroll_end_estacao.Name = "VScroll_end_estacao";
			global::System.Windows.Forms.Control vscroll_end_estacao2 = this.VScroll_end_estacao;
			size = new size(26, 21);
			vscroll_end_estacao2.Size = size;
			this.VScroll_end_estacao.TabIndex = (HorizontalAlignment)1;
			global::System.Windows.Forms.Control valor_end_mestre = this.Valor_end_mestre;
			location = new location(94, 53);
			valor_end_mestre.Location = location;
			this.Valor_end_mestre.Name = "Valor_end_mestre";
			global::System.Windows.Forms.Control valor_end_mestre2 = this.Valor_end_mestre;
			size = new size(41, 20);
			valor_end_mestre2.Size = size;
			this.Valor_end_mestre.TabIndex = (HorizontalAlignment)2;
			this.Valor_end_mestre.TextAlign = HorizontalAlignment.Center;
			global::System.Windows.Forms.Control valor_end_estacao = this.Valor_end_estacao;
			location = new location(94, 25);
			valor_end_estacao.Location = location;
			this.Valor_end_estacao.Name = "Valor_end_estacao";
			global::System.Windows.Forms.Control valor_end_estacao2 = this.Valor_end_estacao;
			size = new size(41, 20);
			valor_end_estacao2.Size = size;
			this.Valor_end_estacao.TabIndex = (HorizontalAlignment)2;
			this.Valor_end_estacao.TextAlign = HorizontalAlignment.Center;
			this.Grupo_setpoint.Controls.Add(this.Grupo_gerais);
			this.Grupo_setpoint.Controls.Add(this.Grupo_niveis);
			this.Grupo_setpoint.Controls.Add(this.Grupo_origem);
			global::System.Windows.Forms.Control grupo_setpoint = this.Grupo_setpoint;
			location = new location(12, 12);
			grupo_setpoint.Location = location;
			this.Grupo_setpoint.Name = "Grupo_setpoint";
			global::System.Windows.Forms.Control grupo_setpoint2 = this.Grupo_setpoint;
			size = new size(400, 409);
			grupo_setpoint2.Size = size;
			this.Grupo_setpoint.TabIndex = (HorizontalAlignment)11;
			this.Grupo_setpoint.TabStop = false;
			this.Grupo_setpoint.Text = "Setpoints";
			this.Grupo_gerais.Controls.Add(this.Label_pressao_controle);
			this.Grupo_gerais.Controls.Add(this.Label_pressao_succao);
			this.Grupo_gerais.Controls.Add(this.Label_tempo_mais_motor);
			this.Grupo_gerais.Controls.Add(this.Valor_pressao_controle);
			this.Grupo_gerais.Controls.Add(this.Valor_pressao_succao);
			this.Grupo_gerais.Controls.Add(this.Valor_tempo_mais_bomba);
			global::System.Windows.Forms.Control grupo_gerais = this.Grupo_gerais;
			location = new location(19, 281);
			grupo_gerais.Location = location;
			this.Grupo_gerais.Name = "Grupo_gerais";
			global::System.Windows.Forms.Control grupo_gerais2 = this.Grupo_gerais;
			size = new size(359, 102);
			grupo_gerais2.Size = size;
			this.Grupo_gerais.TabIndex = (HorizontalAlignment)21;
			this.Grupo_gerais.TabStop = false;
			this.Grupo_gerais.Text = "Controles gerais";
			this.Label_pressao_controle.AutoSize = true;
			global::System.Windows.Forms.Control label_pressao_controle = this.Label_pressao_controle;
			location = new location(21, 71);
			label_pressao_controle.Location = location;
			this.Label_pressao_controle.Name = "Label_pressao_controle";
			global::System.Windows.Forms.Control label_pressao_controle2 = this.Label_pressao_controle;
			size = new size(188, 13);
			label_pressao_controle2.Size = size;
			this.Label_pressao_controle.TabIndex = (HorizontalAlignment)6;
			this.Label_pressao_controle.Text = "Pressão mínima de controle (5 - 30%) :";
			this.Label_pressao_succao.AutoSize = true;
			global::System.Windows.Forms.Control label_pressao_succao = this.Label_pressao_succao;
			location = new location(21, 48);
			label_pressao_succao.Location = location;
			this.Label_pressao_succao.Name = "Label_pressao_succao";
			global::System.Windows.Forms.Control label_pressao_succao2 = this.Label_pressao_succao;
			size = new size(185, 13);
			label_pressao_succao2.Size = size;
			this.Label_pressao_succao.TabIndex = (HorizontalAlignment)7;
			this.Label_pressao_succao.Text = "Pressão mínima de sucção (5 - 30%) :";
			this.Label_tempo_mais_motor.AutoSize = true;
			global::System.Windows.Forms.Control label_tempo_mais_motor = this.Label_tempo_mais_motor;
			location = new location(21, 25);
			label_tempo_mais_motor.Location = location;
			this.Label_tempo_mais_motor.Name = "Label_tempo_mais_motor";
			global::System.Windows.Forms.Control label_tempo_mais_motor2 = this.Label_tempo_mais_motor;
			size = new size(210, 13);
			label_tempo_mais_motor2.Size = size;
			this.Label_tempo_mais_motor.TabIndex = (HorizontalAlignment)8;
			this.Label_tempo_mais_motor.Text = "Tempo p/ ligar + uma bomba (0 - 180 min) :";
			global::System.Windows.Forms.Control valor_pressao_controle = this.Valor_pressao_controle;
			location = new location(268, 67);
			valor_pressao_controle.Location = location;
			this.Valor_pressao_controle.Name = "Valor_pressao_controle";
			global::System.Windows.Forms.Control valor_pressao_controle2 = this.Valor_pressao_controle;
			size = new size(66, 20);
			valor_pressao_controle2.Size = size;
			this.Valor_pressao_controle.TabIndex = (HorizontalAlignment)24;
			this.Valor_pressao_controle.TextAlign = HorizontalAlignment.Center;
			global::System.Windows.Forms.Control valor_pressao_succao = this.Valor_pressao_succao;
			location = new location(268, 44);
			valor_pressao_succao.Location = location;
			this.Valor_pressao_succao.Name = "Valor_pressao_succao";
			global::System.Windows.Forms.Control valor_pressao_succao2 = this.Valor_pressao_succao;
			size = new size(66, 20);
			valor_pressao_succao2.Size = size;
			this.Valor_pressao_succao.TabIndex = (HorizontalAlignment)23;
			this.Valor_pressao_succao.TextAlign = HorizontalAlignment.Center;
			global::System.Windows.Forms.Control valor_tempo_mais_bomba = this.Valor_tempo_mais_bomba;
			location = new location(268, 21);
			valor_tempo_mais_bomba.Location = location;
			this.Valor_tempo_mais_bomba.Name = "Valor_tempo_mais_bomba";
			global::System.Windows.Forms.Control valor_tempo_mais_bomba2 = this.Valor_tempo_mais_bomba;
			size = new size(66, 20);
			valor_tempo_mais_bomba2.Size = size;
			this.Valor_tempo_mais_bomba.TabIndex = (HorizontalAlignment)22;
			this.Valor_tempo_mais_bomba.TextAlign = HorizontalAlignment.Center;
			this.Grupo_niveis.Controls.Add(this.Label_nivel_bomba_4);
			this.Grupo_niveis.Controls.Add(this.Label_nivel_bomba_3);
			this.Grupo_niveis.Controls.Add(this.Label_nivel_bomba_2);
			this.Grupo_niveis.Controls.Add(this.Label_nivel_bomba_1);
			this.Grupo_niveis.Controls.Add(this.Label_nivel_desejado);
			this.Grupo_niveis.Controls.Add(this.Valor_nivel_B4);
			this.Grupo_niveis.Controls.Add(this.Valor_nivel_B3);
			this.Grupo_niveis.Controls.Add(this.Valor_nivel_B2);
			this.Grupo_niveis.Controls.Add(this.Valor_nivel_B1);
			this.Grupo_niveis.Controls.Add(this.Valor_nivel_desejado);
			global::System.Windows.Forms.Control grupo_niveis = this.Grupo_niveis;
			location = new location(19, 28);
			grupo_niveis.Location = location;
			this.Grupo_niveis.Name = "Grupo_niveis";
			global::System.Windows.Forms.Control grupo_niveis2 = this.Grupo_niveis;
			size = new size(359, 158);
			grupo_niveis2.Size = size;
			this.Grupo_niveis.TabIndex = (HorizontalAlignment)12;
			this.Grupo_niveis.TabStop = false;
			this.Grupo_niveis.Text = "Controles das bombas";
			this.Label_nivel_bomba_4.AutoSize = true;
			global::System.Windows.Forms.Control label_nivel_bomba_ = this.Label_nivel_bomba_4;
			location = new location(21, 128);
			label_nivel_bomba_.Location = location;
			this.Label_nivel_bomba_4.Name = "Label_nivel_bomba_4";
			global::System.Windows.Forms.Control label_nivel_bomba_2 = this.Label_nivel_bomba_4;
			size = new size(169, 13);
			label_nivel_bomba_2.Size = size;
			this.Label_nivel_bomba_4.TabIndex = (HorizontalAlignment)9;
			this.Label_nivel_bomba_4.Text = "Nível p/ ligar bomba 4 (0 - 100%) :";
			this.Label_nivel_bomba_3.AutoSize = true;
			global::System.Windows.Forms.Control label_nivel_bomba_3 = this.Label_nivel_bomba_3;
			location = new location(21, 103);
			label_nivel_bomba_3.Location = location;
			this.Label_nivel_bomba_3.Name = "Label_nivel_bomba_3";
			global::System.Windows.Forms.Control label_nivel_bomba_4 = this.Label_nivel_bomba_3;
			size = new size(169, 13);
			label_nivel_bomba_4.Size = size;
			this.Label_nivel_bomba_3.TabIndex = (HorizontalAlignment)8;
			this.Label_nivel_bomba_3.Text = "Nível p/ ligar bomba 3 (0 - 100%) :";
			this.Label_nivel_bomba_2.AutoSize = true;
			global::System.Windows.Forms.Control label_nivel_bomba_5 = this.Label_nivel_bomba_2;
			location = new location(21, 78);
			label_nivel_bomba_5.Location = location;
			this.Label_nivel_bomba_2.Name = "Label_nivel_bomba_2";
			global::System.Windows.Forms.Control label_nivel_bomba_6 = this.Label_nivel_bomba_2;
			size = new size(169, 13);
			label_nivel_bomba_6.Size = size;
			this.Label_nivel_bomba_2.TabIndex = (HorizontalAlignment)10;
			this.Label_nivel_bomba_2.Text = "Nível p/ ligar bomba 2 (0 - 100%) :";
			this.Label_nivel_bomba_1.AutoSize = true;
			global::System.Windows.Forms.Control label_nivel_bomba_7 = this.Label_nivel_bomba_1;
			location = new location(21, 53);
			label_nivel_bomba_7.Location = location;
			this.Label_nivel_bomba_1.Name = "Label_nivel_bomba_1";
			global::System.Windows.Forms.Control label_nivel_bomba_8 = this.Label_nivel_bomba_1;
			size = new size(169, 13);
			label_nivel_bomba_8.Size = size;
			this.Label_nivel_bomba_1.TabIndex = (HorizontalAlignment)12;
			this.Label_nivel_bomba_1.Text = "Nível p/ ligar bomba 1 (0 - 100%) :";
			this.Label_nivel_desejado.AutoSize = true;
			global::System.Windows.Forms.Control label_nivel_desejado = this.Label_nivel_desejado;
			location = new location(21, 28);
			label_nivel_desejado.Location = location;
			this.Label_nivel_desejado.Name = "Label_nivel_desejado";
			global::System.Windows.Forms.Control label_nivel_desejado2 = this.Label_nivel_desejado;
			size = new size(198, 13);
			label_nivel_desejado2.Size = size;
			this.Label_nivel_desejado.TabIndex = (HorizontalAlignment)11;
			this.Label_nivel_desejado.Text = "Nível desejado para desligar (0 - 100%) :";
			global::System.Windows.Forms.Control valor_nivel_B = this.Valor_nivel_B4;
			location = new location(268, 124);
			valor_nivel_B.Location = location;
			this.Valor_nivel_B4.Name = "Valor_nivel_B4";
			global::System.Windows.Forms.Control valor_nivel_B2 = this.Valor_nivel_B4;
			size = new size(66, 20);
			valor_nivel_B2.Size = size;
			this.Valor_nivel_B4.TabIndex = (HorizontalAlignment)17;
			this.Valor_nivel_B4.TextAlign = HorizontalAlignment.Center;
			global::System.Windows.Forms.Control valor_nivel_B3 = this.Valor_nivel_B3;
			location = new location(268, 99);
			valor_nivel_B3.Location = location;
			this.Valor_nivel_B3.Name = "Valor_nivel_B3";
			global::System.Windows.Forms.Control valor_nivel_B4 = this.Valor_nivel_B3;
			size = new size(66, 20);
			valor_nivel_B4.Size = size;
			this.Valor_nivel_B3.TabIndex = (HorizontalAlignment)16;
			this.Valor_nivel_B3.TextAlign = HorizontalAlignment.Center;
			global::System.Windows.Forms.Control valor_nivel_B5 = this.Valor_nivel_B2;
			location = new location(268, 74);
			valor_nivel_B5.Location = location;
			this.Valor_nivel_B2.Name = "Valor_nivel_B2";
			global::System.Windows.Forms.Control valor_nivel_B6 = this.Valor_nivel_B2;
			size = new size(66, 20);
			valor_nivel_B6.Size = size;
			this.Valor_nivel_B2.TabIndex = (HorizontalAlignment)15;
			this.Valor_nivel_B2.TextAlign = HorizontalAlignment.Center;
			global::System.Windows.Forms.Control valor_nivel_B7 = this.Valor_nivel_B1;
			location = new location(268, 49);
			valor_nivel_B7.Location = location;
			this.Valor_nivel_B1.Name = "Valor_nivel_B1";
			global::System.Windows.Forms.Control valor_nivel_B8 = this.Valor_nivel_B1;
			size = new size(66, 20);
			valor_nivel_B8.Size = size;
			this.Valor_nivel_B1.TabIndex = (HorizontalAlignment)14;
			this.Valor_nivel_B1.TextAlign = HorizontalAlignment.Center;
			global::System.Windows.Forms.Control valor_nivel_desejado = this.Valor_nivel_desejado;
			location = new location(268, 24);
			valor_nivel_desejado.Location = location;
			this.Valor_nivel_desejado.Name = "Valor_nivel_desejado";
			global::System.Windows.Forms.Control valor_nivel_desejado2 = this.Valor_nivel_desejado;
			size = new size(66, 20);
			valor_nivel_desejado2.Size = size;
			this.Valor_nivel_desejado.TabIndex = (HorizontalAlignment)13;
			this.Valor_nivel_desejado.TextAlign = HorizontalAlignment.Center;
			this.Grupo_origem.Controls.Add(this.Label_nivel_ligamento);
			this.Grupo_origem.Controls.Add(this.Label_nivel_desligamento);
			this.Grupo_origem.Controls.Add(this.Valor_nivel_ligamento);
			this.Grupo_origem.Controls.Add(this.Valor_nivel_desligamento);
			global::System.Windows.Forms.Control grupo_origem = this.Grupo_origem;
			location = new location(19, 192);
			grupo_origem.Location = location;
			this.Grupo_origem.Name = "Grupo_origem";
			global::System.Windows.Forms.Control grupo_origem2 = this.Grupo_origem;
			size = new size(359, 83);
			grupo_origem2.Size = size;
			this.Grupo_origem.TabIndex = (HorizontalAlignment)18;
			this.Grupo_origem.TabStop = false;
			this.Grupo_origem.Text = "Controles relacionados com nível fonte";
			this.Label_nivel_ligamento.AutoSize = true;
			global::System.Windows.Forms.Control label_nivel_ligamento = this.Label_nivel_ligamento;
			location = new location(21, 53);
			label_nivel_ligamento.Location = location;
			this.Label_nivel_ligamento.Name = "Label_nivel_ligamento";
			global::System.Windows.Forms.Control label_nivel_ligamento2 = this.Label_nivel_ligamento;
			size = new size(137, 13);
			label_nivel_ligamento2.Size = size;
			this.Label_nivel_ligamento.TabIndex = (HorizontalAlignment)5;
			this.Label_nivel_ligamento.Text = "Nível ligamento (0 - 100%) :";
			this.Label_nivel_desligamento.AutoSize = true;
			global::System.Windows.Forms.Control label_nivel_desligamento = this.Label_nivel_desligamento;
			location = new location(21, 29);
			label_nivel_desligamento.Location = location;
			this.Label_nivel_desligamento.Name = "Label_nivel_desligamento";
			global::System.Windows.Forms.Control label_nivel_desligamento2 = this.Label_nivel_desligamento;
			size = new size(154, 13);
			label_nivel_desligamento2.Size = size;
			this.Label_nivel_desligamento.TabIndex = (HorizontalAlignment)6;
			this.Label_nivel_desligamento.Text = "Nível desligamento (0 - 100%) :";
			global::System.Windows.Forms.Control valor_nivel_ligamento = this.Valor_nivel_ligamento;
			location = new location(268, 49);
			valor_nivel_ligamento.Location = location;
			this.Valor_nivel_ligamento.Name = "Valor_nivel_ligamento";
			global::System.Windows.Forms.Control valor_nivel_ligamento2 = this.Valor_nivel_ligamento;
			size = new size(66, 20);
			valor_nivel_ligamento2.Size = size;
			this.Valor_nivel_ligamento.TabIndex = (HorizontalAlignment)20;
			this.Valor_nivel_ligamento.TextAlign = HorizontalAlignment.Center;
			global::System.Windows.Forms.Control valor_nivel_desligamento = this.Valor_nivel_desligamento;
			location = new location(268, 25);
			valor_nivel_desligamento.Location = location;
			this.Valor_nivel_desligamento.Name = "Valor_nivel_desligamento";
			global::System.Windows.Forms.Control valor_nivel_desligamento2 = this.Valor_nivel_desligamento;
			size = new size(66, 20);
			valor_nivel_desligamento2.Size = size;
			this.Valor_nivel_desligamento.TabIndex = (HorizontalAlignment)19;
			this.Valor_nivel_desligamento.TextAlign = HorizontalAlignment.Center;
			this.Grupo_alarmes.Controls.Add(this.GroupBox_nivel_alto);
			this.Grupo_alarmes.Controls.Add(this.GroupBox_nivel_baixo);
			this.Grupo_alarmes.Controls.Add(this.CheckBox_alm_rq);
			this.Grupo_alarmes.Controls.Add(this.Label_alm_tensao);
			this.Grupo_alarmes.Controls.Add(this.Label_alm_bomba_4);
			this.Grupo_alarmes.Controls.Add(this.Label_alm_bomba_3);
			this.Grupo_alarmes.Controls.Add(this.Label_alm_bomba_2);
			this.Grupo_alarmes.Controls.Add(this.Label_alm_bomba_1);
			this.Grupo_alarmes.Enabled = false;
			global::System.Windows.Forms.Control grupo_alarmes = this.Grupo_alarmes;
			location = new location(619, 212);
			grupo_alarmes.Location = location;
			this.Grupo_alarmes.Name = "Grupo_alarmes";
			global::System.Windows.Forms.Control grupo_alarmes2 = this.Grupo_alarmes;
			size = new size(310, 210);
			grupo_alarmes2.Size = size;
			this.Grupo_alarmes.TabIndex = (HorizontalAlignment)82;
			this.Grupo_alarmes.TabStop = false;
			this.Grupo_alarmes.Text = "Alarmes";
			this.GroupBox_nivel_alto.Controls.Add(this.Valor_NA_T);
			this.GroupBox_nivel_alto.Controls.Add(this.Valor_NA_B4);
			this.GroupBox_nivel_alto.Controls.Add(this.Valor_NA_B3);
			this.GroupBox_nivel_alto.Controls.Add(this.Valor_NA_B2);
			this.GroupBox_nivel_alto.Controls.Add(this.Valor_NA_B1);
			global::System.Windows.Forms.Control groupBox_nivel_alto = this.GroupBox_nivel_alto;
			location = new location(189, 42);
			groupBox_nivel_alto.Location = location;
			this.GroupBox_nivel_alto.Name = "GroupBox_nivel_alto";
			global::System.Windows.Forms.Control groupBox_nivel_alto2 = this.GroupBox_nivel_alto;
			size = new size(99, 151);
			groupBox_nivel_alto2.Size = size;
			this.GroupBox_nivel_alto.TabIndex = (HorizontalAlignment)90;
			this.GroupBox_nivel_alto.TabStop = false;
			this.GroupBox_nivel_alto.Text = "Nível Alto";
			global::System.Windows.Forms.Control valor_NA_T = this.Valor_NA_T;
			location = new location(16, 121);
			valor_NA_T.Location = location;
			this.Valor_NA_T.Name = "Valor_NA_T";
			global::System.Windows.Forms.Control valor_NA_T2 = this.Valor_NA_T;
			size = new size(66, 20);
			valor_NA_T2.Size = size;
			this.Valor_NA_T.TabIndex = (HorizontalAlignment)95;
			this.Valor_NA_T.TextAlign = HorizontalAlignment.Center;
			global::System.Windows.Forms.Control valor_NA_B = this.Valor_NA_B4;
			location = new location(16, 96);
			valor_NA_B.Location = location;
			this.Valor_NA_B4.Name = "Valor_NA_B4";
			global::System.Windows.Forms.Control valor_NA_B2 = this.Valor_NA_B4;
			size = new size(66, 20);
			valor_NA_B2.Size = size;
			this.Valor_NA_B4.TabIndex = (HorizontalAlignment)94;
			this.Valor_NA_B4.TextAlign = HorizontalAlignment.Center;
			global::System.Windows.Forms.Control valor_NA_B3 = this.Valor_NA_B3;
			location = new location(16, 71);
			valor_NA_B3.Location = location;
			this.Valor_NA_B3.Name = "Valor_NA_B3";
			global::System.Windows.Forms.Control valor_NA_B4 = this.Valor_NA_B3;
			size = new size(66, 20);
			valor_NA_B4.Size = size;
			this.Valor_NA_B3.TabIndex = (HorizontalAlignment)93;
			this.Valor_NA_B3.TextAlign = HorizontalAlignment.Center;
			global::System.Windows.Forms.Control valor_NA_B5 = this.Valor_NA_B2;
			location = new location(16, 46);
			valor_NA_B5.Location = location;
			this.Valor_NA_B2.Name = "Valor_NA_B2";
			global::System.Windows.Forms.Control valor_NA_B6 = this.Valor_NA_B2;
			size = new size(66, 20);
			valor_NA_B6.Size = size;
			this.Valor_NA_B2.TabIndex = (HorizontalAlignment)92;
			this.Valor_NA_B2.TextAlign = HorizontalAlignment.Center;
			global::System.Windows.Forms.Control valor_NA_B7 = this.Valor_NA_B1;
			location = new location(16, 21);
			valor_NA_B7.Location = location;
			this.Valor_NA_B1.Name = "Valor_NA_B1";
			global::System.Windows.Forms.Control valor_NA_B8 = this.Valor_NA_B1;
			size = new size(66, 20);
			valor_NA_B8.Size = size;
			this.Valor_NA_B1.TabIndex = (HorizontalAlignment)91;
			this.Valor_NA_B1.TextAlign = HorizontalAlignment.Center;
			this.GroupBox_nivel_baixo.Controls.Add(this.Valor_NB_T);
			this.GroupBox_nivel_baixo.Controls.Add(this.Valor_NB_B4);
			this.GroupBox_nivel_baixo.Controls.Add(this.Valor_NB_B3);
			this.GroupBox_nivel_baixo.Controls.Add(this.Valor_NB_B2);
			this.GroupBox_nivel_baixo.Controls.Add(this.Valor_NB_B1);
			global::System.Windows.Forms.Control groupBox_nivel_baixo = this.GroupBox_nivel_baixo;
			location = new location(84, 42);
			groupBox_nivel_baixo.Location = location;
			this.GroupBox_nivel_baixo.Name = "GroupBox_nivel_baixo";
			global::System.Windows.Forms.Control groupBox_nivel_baixo2 = this.GroupBox_nivel_baixo;
			size = new size(99, 151);
			groupBox_nivel_baixo2.Size = size;
			this.GroupBox_nivel_baixo.TabIndex = (HorizontalAlignment)84;
			this.GroupBox_nivel_baixo.TabStop = false;
			this.GroupBox_nivel_baixo.Text = "Nível Baixo";
			global::System.Windows.Forms.Control valor_NB_T = this.Valor_NB_T;
			location = new location(16, 121);
			valor_NB_T.Location = location;
			this.Valor_NB_T.Name = "Valor_NB_T";
			global::System.Windows.Forms.Control valor_NB_T2 = this.Valor_NB_T;
			size = new size(66, 20);
			valor_NB_T2.Size = size;
			this.Valor_NB_T.TabIndex = (HorizontalAlignment)89;
			this.Valor_NB_T.TextAlign = HorizontalAlignment.Center;
			global::System.Windows.Forms.Control valor_NB_B = this.Valor_NB_B4;
			location = new location(16, 96);
			valor_NB_B.Location = location;
			this.Valor_NB_B4.Name = "Valor_NB_B4";
			global::System.Windows.Forms.Control valor_NB_B2 = this.Valor_NB_B4;
			size = new size(66, 20);
			valor_NB_B2.Size = size;
			this.Valor_NB_B4.TabIndex = (HorizontalAlignment)88;
			this.Valor_NB_B4.TextAlign = HorizontalAlignment.Center;
			global::System.Windows.Forms.Control valor_NB_B3 = this.Valor_NB_B3;
			location = new location(16, 71);
			valor_NB_B3.Location = location;
			this.Valor_NB_B3.Name = "Valor_NB_B3";
			global::System.Windows.Forms.Control valor_NB_B4 = this.Valor_NB_B3;
			size = new size(66, 20);
			valor_NB_B4.Size = size;
			this.Valor_NB_B3.TabIndex = (HorizontalAlignment)87;
			this.Valor_NB_B3.TextAlign = HorizontalAlignment.Center;
			global::System.Windows.Forms.Control valor_NB_B5 = this.Valor_NB_B2;
			location = new location(16, 46);
			valor_NB_B5.Location = location;
			this.Valor_NB_B2.Name = "Valor_NB_B2";
			global::System.Windows.Forms.Control valor_NB_B6 = this.Valor_NB_B2;
			size = new size(66, 20);
			valor_NB_B6.Size = size;
			this.Valor_NB_B2.TabIndex = (HorizontalAlignment)86;
			this.Valor_NB_B2.TextAlign = HorizontalAlignment.Center;
			global::System.Windows.Forms.Control valor_NB_B7 = this.Valor_NB_B1;
			location = new location(16, 21);
			valor_NB_B7.Location = location;
			this.Valor_NB_B1.Name = "Valor_NB_B1";
			global::System.Windows.Forms.Control valor_NB_B8 = this.Valor_NB_B1;
			size = new size(66, 20);
			valor_NB_B8.Size = size;
			this.Valor_NB_B1.TabIndex = (HorizontalAlignment)85;
			this.Valor_NB_B1.TextAlign = HorizontalAlignment.Center;
			this.CheckBox_alm_rq.AutoSize = true;
			global::System.Windows.Forms.Control checkBox_alm_rq = this.CheckBox_alm_rq;
			location = new location(26, 20);
			checkBox_alm_rq.Location = location;
			this.CheckBox_alm_rq.Name = "CheckBox_alm_rq";
			global::System.Windows.Forms.Control checkBox_alm_rq2 = this.CheckBox_alm_rq;
			size = new size(158, 17);
			checkBox_alm_rq2.Size = size;
			this.CheckBox_alm_rq.TabIndex = (HorizontalAlignment)83;
			this.CheckBox_alm_rq.Text = "Habilita bloqueio de alarmes";
			this.CheckBox_alm_rq.UseVisualStyleBackColor = true;
			this.Label_alm_tensao.AutoSize = true;
			global::System.Windows.Forms.Control label_alm_tensao = this.Label_alm_tensao;
			location = new location(23, 166);
			label_alm_tensao.Location = location;
			this.Label_alm_tensao.Name = "Label_alm_tensao";
			global::System.Windows.Forms.Control label_alm_tensao2 = this.Label_alm_tensao;
			size = new size(49, 13);
			label_alm_tensao2.Size = size;
			this.Label_alm_tensao.TabIndex = (HorizontalAlignment)2;
			this.Label_alm_tensao.Text = "Tensão :";
			this.Label_alm_bomba_4.AutoSize = true;
			global::System.Windows.Forms.Control label_alm_bomba_ = this.Label_alm_bomba_4;
			location = new location(23, 141);
			label_alm_bomba_.Location = location;
			this.Label_alm_bomba_4.Name = "Label_alm_bomba_4";
			global::System.Windows.Forms.Control label_alm_bomba_2 = this.Label_alm_bomba_4;
			size = new size(62, 13);
			label_alm_bomba_2.Size = size;
			this.Label_alm_bomba_4.TabIndex = (HorizontalAlignment)2;
			this.Label_alm_bomba_4.Text = "Corrente 4 :";
			this.Label_alm_bomba_3.AutoSize = true;
			global::System.Windows.Forms.Control label_alm_bomba_3 = this.Label_alm_bomba_3;
			location = new location(23, 116);
			label_alm_bomba_3.Location = location;
			this.Label_alm_bomba_3.Name = "Label_alm_bomba_3";
			global::System.Windows.Forms.Control label_alm_bomba_4 = this.Label_alm_bomba_3;
			size = new size(62, 13);
			label_alm_bomba_4.Size = size;
			this.Label_alm_bomba_3.TabIndex = (HorizontalAlignment)2;
			this.Label_alm_bomba_3.Text = "Corrente 3 :";
			this.Label_alm_bomba_2.AutoSize = true;
			global::System.Windows.Forms.Control label_alm_bomba_5 = this.Label_alm_bomba_2;
			location = new location(23, 91);
			label_alm_bomba_5.Location = location;
			this.Label_alm_bomba_2.Name = "Label_alm_bomba_2";
			global::System.Windows.Forms.Control label_alm_bomba_6 = this.Label_alm_bomba_2;
			size = new size(59, 13);
			label_alm_bomba_6.Size = size;
			this.Label_alm_bomba_2.TabIndex = (HorizontalAlignment)2;
			this.Label_alm_bomba_2.Text = "Corrente 2:";
			this.Label_alm_bomba_1.AutoSize = true;
			global::System.Windows.Forms.Control label_alm_bomba_7 = this.Label_alm_bomba_1;
			location = new location(23, 66);
			label_alm_bomba_7.Location = location;
			this.Label_alm_bomba_1.Name = "Label_alm_bomba_1";
			global::System.Windows.Forms.Control label_alm_bomba_8 = this.Label_alm_bomba_1;
			size = new size(62, 13);
			label_alm_bomba_8.Size = size;
			this.Label_alm_bomba_1.TabIndex = (HorizontalAlignment)2;
			this.Label_alm_bomba_1.Text = "Corrente 1 :";
			this.GroupBox_timer_1.Controls.Add(this.GroupBox_Desliga_B1);
			this.GroupBox_timer_1.Controls.Add(this.GroupBox_Liga_B1);
			this.GroupBox_timer_1.Controls.Add(this.Label_faixa4_B1);
			this.GroupBox_timer_1.Controls.Add(this.Label_faixa3_B1);
			this.GroupBox_timer_1.Controls.Add(this.Label_faixa2_B1);
			this.GroupBox_timer_1.Controls.Add(this.Label_faixa1_B1);
			this.GroupBox_timer_1.Enabled = false;
			global::System.Windows.Forms.Control groupBox_timer_ = this.GroupBox_timer_1;
			location = new location(12, 439);
			groupBox_timer_.Location = location;
			this.GroupBox_timer_1.Name = "GroupBox_timer_1";
			global::System.Windows.Forms.Control groupBox_timer_2 = this.GroupBox_timer_1;
			size = new size(225, 159);
			groupBox_timer_2.Size = size;
			this.GroupBox_timer_1.TabIndex = (HorizontalAlignment)25;
			this.GroupBox_timer_1.TabStop = false;
			this.GroupBox_timer_1.Text = "Controle timer - Bomba 1";
			this.GroupBox_Desliga_B1.Controls.Add(this.Valor_desliga_faixa4_b1);
			this.GroupBox_Desliga_B1.Controls.Add(this.Valor_desliga_faixa3_b1);
			this.GroupBox_Desliga_B1.Controls.Add(this.Valor_desliga_faixa2_b1);
			this.GroupBox_Desliga_B1.Controls.Add(this.Valor_desliga_faixa1_b1);
			global::System.Windows.Forms.Control groupBox_Desliga_B = this.GroupBox_Desliga_B1;
			location = new location(138, 19);
			groupBox_Desliga_B.Location = location;
			this.GroupBox_Desliga_B1.Name = "GroupBox_Desliga_B1";
			global::System.Windows.Forms.Control groupBox_Desliga_B2 = this.GroupBox_Desliga_B1;
			size = new size(73, 128);
			groupBox_Desliga_B2.Size = size;
			this.GroupBox_Desliga_B1.TabIndex = (HorizontalAlignment)31;
			this.GroupBox_Desliga_B1.TabStop = false;
			this.GroupBox_Desliga_B1.Text = "Desliga";
			global::System.Windows.Forms.Control valor_desliga_faixa4_b = this.Valor_desliga_faixa4_b1;
			location = new location(17, 97);
			valor_desliga_faixa4_b.Location = location;
			this.Valor_desliga_faixa4_b1.Name = "Valor_desliga_faixa4_b1";
			global::System.Windows.Forms.Control valor_desliga_faixa4_b2 = this.Valor_desliga_faixa4_b1;
			size = new size(39, 20);
			valor_desliga_faixa4_b2.Size = size;
			this.Valor_desliga_faixa4_b1.TabIndex = (HorizontalAlignment)35;
			this.Valor_desliga_faixa4_b1.TextAlign = HorizontalAlignment.Right;
			global::System.Windows.Forms.Control valor_desliga_faixa3_b = this.Valor_desliga_faixa3_b1;
			location = new location(17, 71);
			valor_desliga_faixa3_b.Location = location;
			this.Valor_desliga_faixa3_b1.Name = "Valor_desliga_faixa3_b1";
			global::System.Windows.Forms.Control valor_desliga_faixa3_b2 = this.Valor_desliga_faixa3_b1;
			size = new size(39, 20);
			valor_desliga_faixa3_b2.Size = size;
			this.Valor_desliga_faixa3_b1.TabIndex = (HorizontalAlignment)34;
			this.Valor_desliga_faixa3_b1.TextAlign = HorizontalAlignment.Right;
			global::System.Windows.Forms.Control valor_desliga_faixa2_b = this.Valor_desliga_faixa2_b1;
			location = new location(17, 45);
			valor_desliga_faixa2_b.Location = location;
			this.Valor_desliga_faixa2_b1.Name = "Valor_desliga_faixa2_b1";
			global::System.Windows.Forms.Control valor_desliga_faixa2_b2 = this.Valor_desliga_faixa2_b1;
			size = new size(39, 20);
			valor_desliga_faixa2_b2.Size = size;
			this.Valor_desliga_faixa2_b1.TabIndex = (HorizontalAlignment)33;
			this.Valor_desliga_faixa2_b1.TextAlign = HorizontalAlignment.Right;
			global::System.Windows.Forms.Control valor_desliga_faixa1_b = this.Valor_desliga_faixa1_b1;
			location = new location(17, 19);
			valor_desliga_faixa1_b.Location = location;
			this.Valor_desliga_faixa1_b1.Name = "Valor_desliga_faixa1_b1";
			global::System.Windows.Forms.Control valor_desliga_faixa1_b2 = this.Valor_desliga_faixa1_b1;
			size = new size(39, 20);
			valor_desliga_faixa1_b2.Size = size;
			this.Valor_desliga_faixa1_b1.TabIndex = (HorizontalAlignment)32;
			this.Valor_desliga_faixa1_b1.TextAlign = HorizontalAlignment.Right;
			this.GroupBox_Liga_B1.Controls.Add(this.Valor_liga_faixa4_b1);
			this.GroupBox_Liga_B1.Controls.Add(this.Valor_liga_faixa3_b1);
			this.GroupBox_Liga_B1.Controls.Add(this.Valor_liga_faixa2_b1);
			this.GroupBox_Liga_B1.Controls.Add(this.Valor_liga_faixa1_b1);
			global::System.Windows.Forms.Control groupBox_Liga_B = this.GroupBox_Liga_B1;
			location = new location(59, 19);
			groupBox_Liga_B.Location = location;
			this.GroupBox_Liga_B1.Name = "GroupBox_Liga_B1";
			global::System.Windows.Forms.Control groupBox_Liga_B2 = this.GroupBox_Liga_B1;
			size = new size(73, 128);
			groupBox_Liga_B2.Size = size;
			this.GroupBox_Liga_B1.TabIndex = (HorizontalAlignment)26;
			this.GroupBox_Liga_B1.TabStop = false;
			this.GroupBox_Liga_B1.Text = "Liga";
			global::System.Windows.Forms.Control valor_liga_faixa4_b = this.Valor_liga_faixa4_b1;
			location = new location(17, 97);
			valor_liga_faixa4_b.Location = location;
			this.Valor_liga_faixa4_b1.Name = "Valor_liga_faixa4_b1";
			global::System.Windows.Forms.Control valor_liga_faixa4_b2 = this.Valor_liga_faixa4_b1;
			size = new size(39, 20);
			valor_liga_faixa4_b2.Size = size;
			this.Valor_liga_faixa4_b1.TabIndex = (HorizontalAlignment)30;
			this.Valor_liga_faixa4_b1.TextAlign = HorizontalAlignment.Right;
			global::System.Windows.Forms.Control valor_liga_faixa3_b = this.Valor_liga_faixa3_b1;
			location = new location(17, 71);
			valor_liga_faixa3_b.Location = location;
			this.Valor_liga_faixa3_b1.Name = "Valor_liga_faixa3_b1";
			global::System.Windows.Forms.Control valor_liga_faixa3_b2 = this.Valor_liga_faixa3_b1;
			size = new size(39, 20);
			valor_liga_faixa3_b2.Size = size;
			this.Valor_liga_faixa3_b1.TabIndex = (HorizontalAlignment)29;
			this.Valor_liga_faixa3_b1.TextAlign = HorizontalAlignment.Right;
			global::System.Windows.Forms.Control valor_liga_faixa2_b = this.Valor_liga_faixa2_b1;
			location = new location(17, 45);
			valor_liga_faixa2_b.Location = location;
			this.Valor_liga_faixa2_b1.Name = "Valor_liga_faixa2_b1";
			global::System.Windows.Forms.Control valor_liga_faixa2_b2 = this.Valor_liga_faixa2_b1;
			size = new size(39, 20);
			valor_liga_faixa2_b2.Size = size;
			this.Valor_liga_faixa2_b1.TabIndex = (HorizontalAlignment)28;
			this.Valor_liga_faixa2_b1.TextAlign = HorizontalAlignment.Right;
			global::System.Windows.Forms.Control valor_liga_faixa1_b = this.Valor_liga_faixa1_b1;
			location = new location(17, 19);
			valor_liga_faixa1_b.Location = location;
			this.Valor_liga_faixa1_b1.Name = "Valor_liga_faixa1_b1";
			global::System.Windows.Forms.Control valor_liga_faixa1_b2 = this.Valor_liga_faixa1_b1;
			size = new size(39, 20);
			valor_liga_faixa1_b2.Size = size;
			this.Valor_liga_faixa1_b1.TabIndex = (HorizontalAlignment)27;
			this.Valor_liga_faixa1_b1.TextAlign = HorizontalAlignment.Right;
			this.Label_faixa4_B1.AutoSize = true;
			global::System.Windows.Forms.Control label_faixa4_B = this.Label_faixa4_B1;
			location = new location(6, 119);
			label_faixa4_B.Location = location;
			this.Label_faixa4_B1.Name = "Label_faixa4_B1";
			global::System.Windows.Forms.Control label_faixa4_B2 = this.Label_faixa4_B1;
			size = new size(47, 13);
			label_faixa4_B2.Size = size;
			this.Label_faixa4_B1.TabIndex = (HorizontalAlignment)2;
			this.Label_faixa4_B1.Text = "Faixa 4 :";
			this.Label_faixa3_B1.AutoSize = true;
			global::System.Windows.Forms.Control label_faixa3_B = this.Label_faixa3_B1;
			location = new location(6, 93);
			label_faixa3_B.Location = location;
			this.Label_faixa3_B1.Name = "Label_faixa3_B1";
			global::System.Windows.Forms.Control label_faixa3_B2 = this.Label_faixa3_B1;
			size = new size(47, 13);
			label_faixa3_B2.Size = size;
			this.Label_faixa3_B1.TabIndex = (HorizontalAlignment)2;
			this.Label_faixa3_B1.Text = "Faixa 3 :";
			this.Label_faixa2_B1.AutoSize = true;
			global::System.Windows.Forms.Control label_faixa2_B = this.Label_faixa2_B1;
			location = new location(6, 67);
			label_faixa2_B.Location = location;
			this.Label_faixa2_B1.Name = "Label_faixa2_B1";
			global::System.Windows.Forms.Control label_faixa2_B2 = this.Label_faixa2_B1;
			size = new size(47, 13);
			label_faixa2_B2.Size = size;
			this.Label_faixa2_B1.TabIndex = (HorizontalAlignment)2;
			this.Label_faixa2_B1.Text = "Faixa 2 :";
			this.Label_faixa1_B1.AutoSize = true;
			global::System.Windows.Forms.Control label_faixa1_B = this.Label_faixa1_B1;
			location = new location(6, 41);
			label_faixa1_B.Location = location;
			this.Label_faixa1_B1.Name = "Label_faixa1_B1";
			global::System.Windows.Forms.Control label_faixa1_B2 = this.Label_faixa1_B1;
			size = new size(47, 13);
			label_faixa1_B2.Size = size;
			this.Label_faixa1_B1.TabIndex = (HorizontalAlignment)2;
			this.Label_faixa1_B1.Text = "Faixa 1 :";
			this.GroupBox_timer_2.Controls.Add(this.GroupBox2);
			this.GroupBox_timer_2.Controls.Add(this.GroupBox3);
			this.GroupBox_timer_2.Controls.Add(this.Label_faixa4_B2);
			this.GroupBox_timer_2.Controls.Add(this.Label_faixa3_B2);
			this.GroupBox_timer_2.Controls.Add(this.Label_faixa2_B2);
			this.GroupBox_timer_2.Controls.Add(this.Label_faixa1_B2);
			this.GroupBox_timer_2.Enabled = false;
			global::System.Windows.Forms.Control groupBox_timer_3 = this.GroupBox_timer_2;
			location = new location(243, 439);
			groupBox_timer_3.Location = location;
			this.GroupBox_timer_2.Name = "GroupBox_timer_2";
			global::System.Windows.Forms.Control groupBox_timer_4 = this.GroupBox_timer_2;
			size = new size(225, 159);
			groupBox_timer_4.Size = size;
			this.GroupBox_timer_2.TabIndex = (HorizontalAlignment)36;
			this.GroupBox_timer_2.TabStop = false;
			this.GroupBox_timer_2.Text = "Controle timer - Bomba 2";
			this.GroupBox2.Controls.Add(this.Valor_desliga_faixa4_b2);
			this.GroupBox2.Controls.Add(this.Valor_desliga_faixa3_b2);
			this.GroupBox2.Controls.Add(this.Valor_desliga_faixa2_b2);
			this.GroupBox2.Controls.Add(this.Valor_desliga_faixa1_b2);
			global::System.Windows.Forms.Control groupBox = this.GroupBox2;
			location = new location(138, 19);
			groupBox.Location = location;
			this.GroupBox2.Name = "GroupBox2";
			global::System.Windows.Forms.Control groupBox2 = this.GroupBox2;
			size = new size(73, 128);
			groupBox2.Size = size;
			this.GroupBox2.TabIndex = (HorizontalAlignment)42;
			this.GroupBox2.TabStop = false;
			this.GroupBox2.Text = "Desliga";
			global::System.Windows.Forms.Control valor_desliga_faixa4_b3 = this.Valor_desliga_faixa4_b2;
			location = new location(17, 97);
			valor_desliga_faixa4_b3.Location = location;
			this.Valor_desliga_faixa4_b2.Name = "Valor_desliga_faixa4_b2";
			global::System.Windows.Forms.Control valor_desliga_faixa4_b4 = this.Valor_desliga_faixa4_b2;
			size = new size(39, 20);
			valor_desliga_faixa4_b4.Size = size;
			this.Valor_desliga_faixa4_b2.TabIndex = (HorizontalAlignment)46;
			this.Valor_desliga_faixa4_b2.TextAlign = HorizontalAlignment.Right;
			global::System.Windows.Forms.Control valor_desliga_faixa3_b3 = this.Valor_desliga_faixa3_b2;
			location = new location(17, 71);
			valor_desliga_faixa3_b3.Location = location;
			this.Valor_desliga_faixa3_b2.Name = "Valor_desliga_faixa3_b2";
			global::System.Windows.Forms.Control valor_desliga_faixa3_b4 = this.Valor_desliga_faixa3_b2;
			size = new size(39, 20);
			valor_desliga_faixa3_b4.Size = size;
			this.Valor_desliga_faixa3_b2.TabIndex = (HorizontalAlignment)45;
			this.Valor_desliga_faixa3_b2.TextAlign = HorizontalAlignment.Right;
			global::System.Windows.Forms.Control valor_desliga_faixa2_b3 = this.Valor_desliga_faixa2_b2;
			location = new location(17, 45);
			valor_desliga_faixa2_b3.Location = location;
			this.Valor_desliga_faixa2_b2.Name = "Valor_desliga_faixa2_b2";
			global::System.Windows.Forms.Control valor_desliga_faixa2_b4 = this.Valor_desliga_faixa2_b2;
			size = new size(39, 20);
			valor_desliga_faixa2_b4.Size = size;
			this.Valor_desliga_faixa2_b2.TabIndex = (HorizontalAlignment)44;
			this.Valor_desliga_faixa2_b2.TextAlign = HorizontalAlignment.Right;
			global::System.Windows.Forms.Control valor_desliga_faixa1_b3 = this.Valor_desliga_faixa1_b2;
			location = new location(17, 19);
			valor_desliga_faixa1_b3.Location = location;
			this.Valor_desliga_faixa1_b2.Name = "Valor_desliga_faixa1_b2";
			global::System.Windows.Forms.Control valor_desliga_faixa1_b4 = this.Valor_desliga_faixa1_b2;
			size = new size(39, 20);
			valor_desliga_faixa1_b4.Size = size;
			this.Valor_desliga_faixa1_b2.TabIndex = (HorizontalAlignment)43;
			this.Valor_desliga_faixa1_b2.TextAlign = HorizontalAlignment.Right;
			this.GroupBox3.Controls.Add(this.Valor_liga_faixa4_b2);
			this.GroupBox3.Controls.Add(this.Valor_liga_faixa3_b2);
			this.GroupBox3.Controls.Add(this.Valor_liga_faixa2_b2);
			this.GroupBox3.Controls.Add(this.Valor_liga_faixa1_b2);
			global::System.Windows.Forms.Control groupBox3 = this.GroupBox3;
			location = new location(59, 19);
			groupBox3.Location = location;
			this.GroupBox3.Name = "GroupBox3";
			global::System.Windows.Forms.Control groupBox4 = this.GroupBox3;
			size = new size(73, 128);
			groupBox4.Size = size;
			this.GroupBox3.TabIndex = (HorizontalAlignment)37;
			this.GroupBox3.TabStop = false;
			this.GroupBox3.Text = "Liga";
			global::System.Windows.Forms.Control valor_liga_faixa4_b3 = this.Valor_liga_faixa4_b2;
			location = new location(17, 97);
			valor_liga_faixa4_b3.Location = location;
			this.Valor_liga_faixa4_b2.Name = "Valor_liga_faixa4_b2";
			global::System.Windows.Forms.Control valor_liga_faixa4_b4 = this.Valor_liga_faixa4_b2;
			size = new size(39, 20);
			valor_liga_faixa4_b4.Size = size;
			this.Valor_liga_faixa4_b2.TabIndex = (HorizontalAlignment)41;
			this.Valor_liga_faixa4_b2.TextAlign = HorizontalAlignment.Right;
			global::System.Windows.Forms.Control valor_liga_faixa3_b3 = this.Valor_liga_faixa3_b2;
			location = new location(17, 71);
			valor_liga_faixa3_b3.Location = location;
			this.Valor_liga_faixa3_b2.Name = "Valor_liga_faixa3_b2";
			global::System.Windows.Forms.Control valor_liga_faixa3_b4 = this.Valor_liga_faixa3_b2;
			size = new size(39, 20);
			valor_liga_faixa3_b4.Size = size;
			this.Valor_liga_faixa3_b2.TabIndex = (HorizontalAlignment)40;
			this.Valor_liga_faixa3_b2.TextAlign = HorizontalAlignment.Right;
			global::System.Windows.Forms.Control valor_liga_faixa2_b3 = this.Valor_liga_faixa2_b2;
			location = new location(17, 45);
			valor_liga_faixa2_b3.Location = location;
			this.Valor_liga_faixa2_b2.Name = "Valor_liga_faixa2_b2";
			global::System.Windows.Forms.Control valor_liga_faixa2_b4 = this.Valor_liga_faixa2_b2;
			size = new size(39, 20);
			valor_liga_faixa2_b4.Size = size;
			this.Valor_liga_faixa2_b2.TabIndex = (HorizontalAlignment)39;
			this.Valor_liga_faixa2_b2.TextAlign = HorizontalAlignment.Right;
			global::System.Windows.Forms.Control valor_liga_faixa1_b3 = this.Valor_liga_faixa1_b2;
			location = new location(17, 19);
			valor_liga_faixa1_b3.Location = location;
			this.Valor_liga_faixa1_b2.Name = "Valor_liga_faixa1_b2";
			global::System.Windows.Forms.Control valor_liga_faixa1_b4 = this.Valor_liga_faixa1_b2;
			size = new size(39, 20);
			valor_liga_faixa1_b4.Size = size;
			this.Valor_liga_faixa1_b2.TabIndex = (HorizontalAlignment)38;
			this.Valor_liga_faixa1_b2.TextAlign = HorizontalAlignment.Right;
			this.Label_faixa4_B2.AutoSize = true;
			global::System.Windows.Forms.Control label_faixa4_B3 = this.Label_faixa4_B2;
			location = new location(6, 119);
			label_faixa4_B3.Location = location;
			this.Label_faixa4_B2.Name = "Label_faixa4_B2";
			global::System.Windows.Forms.Control label_faixa4_B4 = this.Label_faixa4_B2;
			size = new size(47, 13);
			label_faixa4_B4.Size = size;
			this.Label_faixa4_B2.TabIndex = (HorizontalAlignment)2;
			this.Label_faixa4_B2.Text = "Faixa 4 :";
			this.Label_faixa3_B2.AutoSize = true;
			global::System.Windows.Forms.Control label_faixa3_B3 = this.Label_faixa3_B2;
			location = new location(6, 93);
			label_faixa3_B3.Location = location;
			this.Label_faixa3_B2.Name = "Label_faixa3_B2";
			global::System.Windows.Forms.Control label_faixa3_B4 = this.Label_faixa3_B2;
			size = new size(47, 13);
			label_faixa3_B4.Size = size;
			this.Label_faixa3_B2.TabIndex = (HorizontalAlignment)2;
			this.Label_faixa3_B2.Text = "Faixa 3 :";
			this.Label_faixa2_B2.AutoSize = true;
			global::System.Windows.Forms.Control label_faixa2_B3 = this.Label_faixa2_B2;
			location = new location(6, 67);
			label_faixa2_B3.Location = location;
			this.Label_faixa2_B2.Name = "Label_faixa2_B2";
			global::System.Windows.Forms.Control label_faixa2_B4 = this.Label_faixa2_B2;
			size = new size(47, 13);
			label_faixa2_B4.Size = size;
			this.Label_faixa2_B2.TabIndex = (HorizontalAlignment)2;
			this.Label_faixa2_B2.Text = "Faixa 2 :";
			this.Label_faixa1_B2.AutoSize = true;
			global::System.Windows.Forms.Control label_faixa1_B3 = this.Label_faixa1_B2;
			location = new location(6, 41);
			label_faixa1_B3.Location = location;
			this.Label_faixa1_B2.Name = "Label_faixa1_B2";
			global::System.Windows.Forms.Control label_faixa1_B4 = this.Label_faixa1_B2;
			size = new size(47, 13);
			label_faixa1_B4.Size = size;
			this.Label_faixa1_B2.TabIndex = (HorizontalAlignment)2;
			this.Label_faixa1_B2.Text = "Faixa 1 :";
			this.GroupBox_timer_4.Controls.Add(this.GroupBox5);
			this.GroupBox_timer_4.Controls.Add(this.GroupBox6);
			this.GroupBox_timer_4.Controls.Add(this.Label_faixa4_B4);
			this.GroupBox_timer_4.Controls.Add(this.Label_faixa3_B4);
			this.GroupBox_timer_4.Controls.Add(this.Label_faixa2_B4);
			this.GroupBox_timer_4.Controls.Add(this.Label_faixa1_B4);
			this.GroupBox_timer_4.Enabled = false;
			global::System.Windows.Forms.Control groupBox_timer_5 = this.GroupBox_timer_4;
			location = new location(704, 439);
			groupBox_timer_5.Location = location;
			this.GroupBox_timer_4.Name = "GroupBox_timer_4";
			global::System.Windows.Forms.Control groupBox_timer_6 = this.GroupBox_timer_4;
			size = new size(225, 159);
			groupBox_timer_6.Size = size;
			this.GroupBox_timer_4.TabIndex = (HorizontalAlignment)58;
			this.GroupBox_timer_4.TabStop = false;
			this.GroupBox_timer_4.Text = "Controle timer - Bomba 4";
			this.GroupBox5.Controls.Add(this.Valor_desliga_faixa4_b4);
			this.GroupBox5.Controls.Add(this.Valor_desliga_faixa3_b4);
			this.GroupBox5.Controls.Add(this.Valor_desliga_faixa2_b4);
			this.GroupBox5.Controls.Add(this.Valor_desliga_faixa1_b4);
			global::System.Windows.Forms.Control groupBox5 = this.GroupBox5;
			location = new location(138, 19);
			groupBox5.Location = location;
			this.GroupBox5.Name = "GroupBox5";
			global::System.Windows.Forms.Control groupBox6 = this.GroupBox5;
			size = new size(73, 128);
			groupBox6.Size = size;
			this.GroupBox5.TabIndex = (HorizontalAlignment)64;
			this.GroupBox5.TabStop = false;
			this.GroupBox5.Text = "Desliga";
			global::System.Windows.Forms.Control valor_desliga_faixa4_b5 = this.Valor_desliga_faixa4_b4;
			location = new location(17, 97);
			valor_desliga_faixa4_b5.Location = location;
			this.Valor_desliga_faixa4_b4.Name = "Valor_desliga_faixa4_b4";
			global::System.Windows.Forms.Control valor_desliga_faixa4_b6 = this.Valor_desliga_faixa4_b4;
			size = new size(39, 20);
			valor_desliga_faixa4_b6.Size = size;
			this.Valor_desliga_faixa4_b4.TabIndex = (HorizontalAlignment)68;
			this.Valor_desliga_faixa4_b4.TextAlign = HorizontalAlignment.Right;
			global::System.Windows.Forms.Control valor_desliga_faixa3_b5 = this.Valor_desliga_faixa3_b4;
			location = new location(17, 71);
			valor_desliga_faixa3_b5.Location = location;
			this.Valor_desliga_faixa3_b4.Name = "Valor_desliga_faixa3_b4";
			global::System.Windows.Forms.Control valor_desliga_faixa3_b6 = this.Valor_desliga_faixa3_b4;
			size = new size(39, 20);
			valor_desliga_faixa3_b6.Size = size;
			this.Valor_desliga_faixa3_b4.TabIndex = (HorizontalAlignment)67;
			this.Valor_desliga_faixa3_b4.TextAlign = HorizontalAlignment.Right;
			global::System.Windows.Forms.Control valor_desliga_faixa2_b5 = this.Valor_desliga_faixa2_b4;
			location = new location(17, 45);
			valor_desliga_faixa2_b5.Location = location;
			this.Valor_desliga_faixa2_b4.Name = "Valor_desliga_faixa2_b4";
			global::System.Windows.Forms.Control valor_desliga_faixa2_b6 = this.Valor_desliga_faixa2_b4;
			size = new size(39, 20);
			valor_desliga_faixa2_b6.Size = size;
			this.Valor_desliga_faixa2_b4.TabIndex = (HorizontalAlignment)66;
			this.Valor_desliga_faixa2_b4.TextAlign = HorizontalAlignment.Right;
			global::System.Windows.Forms.Control valor_desliga_faixa1_b5 = this.Valor_desliga_faixa1_b4;
			location = new location(17, 19);
			valor_desliga_faixa1_b5.Location = location;
			this.Valor_desliga_faixa1_b4.Name = "Valor_desliga_faixa1_b4";
			global::System.Windows.Forms.Control valor_desliga_faixa1_b6 = this.Valor_desliga_faixa1_b4;
			size = new size(39, 20);
			valor_desliga_faixa1_b6.Size = size;
			this.Valor_desliga_faixa1_b4.TabIndex = (HorizontalAlignment)65;
			this.Valor_desliga_faixa1_b4.TextAlign = HorizontalAlignment.Right;
			this.GroupBox6.Controls.Add(this.Valor_liga_faixa4_b4);
			this.GroupBox6.Controls.Add(this.Valor_liga_faixa3_b4);
			this.GroupBox6.Controls.Add(this.Valor_liga_faixa2_b4);
			this.GroupBox6.Controls.Add(this.Valor_liga_faixa1_b4);
			global::System.Windows.Forms.Control groupBox7 = this.GroupBox6;
			location = new location(59, 19);
			groupBox7.Location = location;
			this.GroupBox6.Name = "GroupBox6";
			global::System.Windows.Forms.Control groupBox8 = this.GroupBox6;
			size = new size(73, 128);
			groupBox8.Size = size;
			this.GroupBox6.TabIndex = (HorizontalAlignment)59;
			this.GroupBox6.TabStop = false;
			this.GroupBox6.Text = "Liga";
			global::System.Windows.Forms.Control valor_liga_faixa4_b5 = this.Valor_liga_faixa4_b4;
			location = new location(17, 97);
			valor_liga_faixa4_b5.Location = location;
			this.Valor_liga_faixa4_b4.Name = "Valor_liga_faixa4_b4";
			global::System.Windows.Forms.Control valor_liga_faixa4_b6 = this.Valor_liga_faixa4_b4;
			size = new size(39, 20);
			valor_liga_faixa4_b6.Size = size;
			this.Valor_liga_faixa4_b4.TabIndex = (HorizontalAlignment)63;
			this.Valor_liga_faixa4_b4.TextAlign = HorizontalAlignment.Right;
			global::System.Windows.Forms.Control valor_liga_faixa3_b5 = this.Valor_liga_faixa3_b4;
			location = new location(17, 71);
			valor_liga_faixa3_b5.Location = location;
			this.Valor_liga_faixa3_b4.Name = "Valor_liga_faixa3_b4";
			global::System.Windows.Forms.Control valor_liga_faixa3_b6 = this.Valor_liga_faixa3_b4;
			size = new size(39, 20);
			valor_liga_faixa3_b6.Size = size;
			this.Valor_liga_faixa3_b4.TabIndex = (HorizontalAlignment)62;
			this.Valor_liga_faixa3_b4.TextAlign = HorizontalAlignment.Right;
			global::System.Windows.Forms.Control valor_liga_faixa2_b5 = this.Valor_liga_faixa2_b4;
			location = new location(17, 45);
			valor_liga_faixa2_b5.Location = location;
			this.Valor_liga_faixa2_b4.Name = "Valor_liga_faixa2_b4";
			global::System.Windows.Forms.Control valor_liga_faixa2_b6 = this.Valor_liga_faixa2_b4;
			size = new size(39, 20);
			valor_liga_faixa2_b6.Size = size;
			this.Valor_liga_faixa2_b4.TabIndex = (HorizontalAlignment)61;
			this.Valor_liga_faixa2_b4.TextAlign = HorizontalAlignment.Right;
			global::System.Windows.Forms.Control valor_liga_faixa1_b5 = this.Valor_liga_faixa1_b4;
			location = new location(17, 19);
			valor_liga_faixa1_b5.Location = location;
			this.Valor_liga_faixa1_b4.Name = "Valor_liga_faixa1_b4";
			global::System.Windows.Forms.Control valor_liga_faixa1_b6 = this.Valor_liga_faixa1_b4;
			size = new size(39, 20);
			valor_liga_faixa1_b6.Size = size;
			this.Valor_liga_faixa1_b4.TabIndex = (HorizontalAlignment)60;
			this.Valor_liga_faixa1_b4.TextAlign = HorizontalAlignment.Right;
			this.Label_faixa4_B4.AutoSize = true;
			global::System.Windows.Forms.Control label_faixa4_B5 = this.Label_faixa4_B4;
			location = new location(6, 119);
			label_faixa4_B5.Location = location;
			this.Label_faixa4_B4.Name = "Label_faixa4_B4";
			global::System.Windows.Forms.Control label_faixa4_B6 = this.Label_faixa4_B4;
			size = new size(47, 13);
			label_faixa4_B6.Size = size;
			this.Label_faixa4_B4.TabIndex = (HorizontalAlignment)2;
			this.Label_faixa4_B4.Text = "Faixa 4 :";
			this.Label_faixa3_B4.AutoSize = true;
			global::System.Windows.Forms.Control label_faixa3_B5 = this.Label_faixa3_B4;
			location = new location(6, 93);
			label_faixa3_B5.Location = location;
			this.Label_faixa3_B4.Name = "Label_faixa3_B4";
			global::System.Windows.Forms.Control label_faixa3_B6 = this.Label_faixa3_B4;
			size = new size(47, 13);
			label_faixa3_B6.Size = size;
			this.Label_faixa3_B4.TabIndex = (HorizontalAlignment)2;
			this.Label_faixa3_B4.Text = "Faixa 3 :";
			this.Label_faixa2_B4.AutoSize = true;
			global::System.Windows.Forms.Control label_faixa2_B5 = this.Label_faixa2_B4;
			location = new location(6, 67);
			label_faixa2_B5.Location = location;
			this.Label_faixa2_B4.Name = "Label_faixa2_B4";
			global::System.Windows.Forms.Control label_faixa2_B6 = this.Label_faixa2_B4;
			size = new size(47, 13);
			label_faixa2_B6.Size = size;
			this.Label_faixa2_B4.TabIndex = (HorizontalAlignment)2;
			this.Label_faixa2_B4.Text = "Faixa 2 :";
			this.Label_faixa1_B4.AutoSize = true;
			global::System.Windows.Forms.Control label_faixa1_B5 = this.Label_faixa1_B4;
			location = new location(6, 41);
			label_faixa1_B5.Location = location;
			this.Label_faixa1_B4.Name = "Label_faixa1_B4";
			global::System.Windows.Forms.Control label_faixa1_B6 = this.Label_faixa1_B4;
			size = new size(47, 13);
			label_faixa1_B6.Size = size;
			this.Label_faixa1_B4.TabIndex = (HorizontalAlignment)2;
			this.Label_faixa1_B4.Text = "Faixa 1 :";
			this.GroupBox_timer_3.Controls.Add(this.GroupBox8);
			this.GroupBox_timer_3.Controls.Add(this.GroupBox9);
			this.GroupBox_timer_3.Controls.Add(this.Label_faixa4_B3);
			this.GroupBox_timer_3.Controls.Add(this.Label_faixa3_B3);
			this.GroupBox_timer_3.Controls.Add(this.Label_faixa2_B3);
			this.GroupBox_timer_3.Controls.Add(this.Label_faixa1_B3);
			this.GroupBox_timer_3.Enabled = false;
			global::System.Windows.Forms.Control groupBox_timer_7 = this.GroupBox_timer_3;
			location = new location(474, 439);
			groupBox_timer_7.Location = location;
			this.GroupBox_timer_3.Name = "GroupBox_timer_3";
			global::System.Windows.Forms.Control groupBox_timer_8 = this.GroupBox_timer_3;
			size = new size(225, 159);
			groupBox_timer_8.Size = size;
			this.GroupBox_timer_3.TabIndex = (HorizontalAlignment)47;
			this.GroupBox_timer_3.TabStop = false;
			this.GroupBox_timer_3.Text = "Controle timer - Bomba 3";
			this.GroupBox8.Controls.Add(this.Valor_desliga_faixa4_b3);
			this.GroupBox8.Controls.Add(this.Valor_desliga_faixa3_b3);
			this.GroupBox8.Controls.Add(this.Valor_desliga_faixa2_b3);
			this.GroupBox8.Controls.Add(this.Valor_desliga_faixa1_b3);
			global::System.Windows.Forms.Control groupBox9 = this.GroupBox8;
			location = new location(138, 19);
			groupBox9.Location = location;
			this.GroupBox8.Name = "GroupBox8";
			global::System.Windows.Forms.Control groupBox10 = this.GroupBox8;
			size = new size(73, 128);
			groupBox10.Size = size;
			this.GroupBox8.TabIndex = (HorizontalAlignment)53;
			this.GroupBox8.TabStop = false;
			this.GroupBox8.Text = "Desliga";
			global::System.Windows.Forms.Control valor_desliga_faixa4_b7 = this.Valor_desliga_faixa4_b3;
			location = new location(17, 97);
			valor_desliga_faixa4_b7.Location = location;
			this.Valor_desliga_faixa4_b3.Name = "Valor_desliga_faixa4_b3";
			global::System.Windows.Forms.Control valor_desliga_faixa4_b8 = this.Valor_desliga_faixa4_b3;
			size = new size(39, 20);
			valor_desliga_faixa4_b8.Size = size;
			this.Valor_desliga_faixa4_b3.TabIndex = (HorizontalAlignment)57;
			this.Valor_desliga_faixa4_b3.TextAlign = HorizontalAlignment.Right;
			global::System.Windows.Forms.Control valor_desliga_faixa3_b7 = this.Valor_desliga_faixa3_b3;
			location = new location(17, 71);
			valor_desliga_faixa3_b7.Location = location;
			this.Valor_desliga_faixa3_b3.Name = "Valor_desliga_faixa3_b3";
			global::System.Windows.Forms.Control valor_desliga_faixa3_b8 = this.Valor_desliga_faixa3_b3;
			size = new size(39, 20);
			valor_desliga_faixa3_b8.Size = size;
			this.Valor_desliga_faixa3_b3.TabIndex = (HorizontalAlignment)56;
			this.Valor_desliga_faixa3_b3.TextAlign = HorizontalAlignment.Right;
			global::System.Windows.Forms.Control valor_desliga_faixa2_b7 = this.Valor_desliga_faixa2_b3;
			location = new location(17, 45);
			valor_desliga_faixa2_b7.Location = location;
			this.Valor_desliga_faixa2_b3.Name = "Valor_desliga_faixa2_b3";
			global::System.Windows.Forms.Control valor_desliga_faixa2_b8 = this.Valor_desliga_faixa2_b3;
			size = new size(39, 20);
			valor_desliga_faixa2_b8.Size = size;
			this.Valor_desliga_faixa2_b3.TabIndex = (HorizontalAlignment)55;
			this.Valor_desliga_faixa2_b3.TextAlign = HorizontalAlignment.Right;
			global::System.Windows.Forms.Control valor_desliga_faixa1_b7 = this.Valor_desliga_faixa1_b3;
			location = new location(17, 19);
			valor_desliga_faixa1_b7.Location = location;
			this.Valor_desliga_faixa1_b3.Name = "Valor_desliga_faixa1_b3";
			global::System.Windows.Forms.Control valor_desliga_faixa1_b8 = this.Valor_desliga_faixa1_b3;
			size = new size(39, 20);
			valor_desliga_faixa1_b8.Size = size;
			this.Valor_desliga_faixa1_b3.TabIndex = (HorizontalAlignment)54;
			this.Valor_desliga_faixa1_b3.TextAlign = HorizontalAlignment.Right;
			this.GroupBox9.Controls.Add(this.Valor_liga_faixa4_b3);
			this.GroupBox9.Controls.Add(this.Valor_liga_faixa3_b3);
			this.GroupBox9.Controls.Add(this.Valor_liga_faixa2_b3);
			this.GroupBox9.Controls.Add(this.Valor_liga_faixa1_b3);
			global::System.Windows.Forms.Control groupBox11 = this.GroupBox9;
			location = new location(59, 19);
			groupBox11.Location = location;
			this.GroupBox9.Name = "GroupBox9";
			global::System.Windows.Forms.Control groupBox12 = this.GroupBox9;
			size = new size(73, 128);
			groupBox12.Size = size;
			this.GroupBox9.TabIndex = (HorizontalAlignment)48;
			this.GroupBox9.TabStop = false;
			this.GroupBox9.Text = "Liga";
			global::System.Windows.Forms.Control valor_liga_faixa4_b7 = this.Valor_liga_faixa4_b3;
			location = new location(17, 97);
			valor_liga_faixa4_b7.Location = location;
			this.Valor_liga_faixa4_b3.Name = "Valor_liga_faixa4_b3";
			global::System.Windows.Forms.Control valor_liga_faixa4_b8 = this.Valor_liga_faixa4_b3;
			size = new size(39, 20);
			valor_liga_faixa4_b8.Size = size;
			this.Valor_liga_faixa4_b3.TabIndex = (HorizontalAlignment)52;
			this.Valor_liga_faixa4_b3.TextAlign = HorizontalAlignment.Right;
			global::System.Windows.Forms.Control valor_liga_faixa3_b7 = this.Valor_liga_faixa3_b3;
			location = new location(17, 71);
			valor_liga_faixa3_b7.Location = location;
			this.Valor_liga_faixa3_b3.Name = "Valor_liga_faixa3_b3";
			global::System.Windows.Forms.Control valor_liga_faixa3_b8 = this.Valor_liga_faixa3_b3;
			size = new size(39, 20);
			valor_liga_faixa3_b8.Size = size;
			this.Valor_liga_faixa3_b3.TabIndex = (HorizontalAlignment)51;
			this.Valor_liga_faixa3_b3.TextAlign = HorizontalAlignment.Right;
			global::System.Windows.Forms.Control valor_liga_faixa2_b7 = this.Valor_liga_faixa2_b3;
			location = new location(17, 45);
			valor_liga_faixa2_b7.Location = location;
			this.Valor_liga_faixa2_b3.Name = "Valor_liga_faixa2_b3";
			global::System.Windows.Forms.Control valor_liga_faixa2_b8 = this.Valor_liga_faixa2_b3;
			size = new size(39, 20);
			valor_liga_faixa2_b8.Size = size;
			this.Valor_liga_faixa2_b3.TabIndex = (HorizontalAlignment)50;
			this.Valor_liga_faixa2_b3.TextAlign = HorizontalAlignment.Right;
			global::System.Windows.Forms.Control valor_liga_faixa1_b7 = this.Valor_liga_faixa1_b3;
			location = new location(17, 19);
			valor_liga_faixa1_b7.Location = location;
			this.Valor_liga_faixa1_b3.Name = "Valor_liga_faixa1_b3";
			global::System.Windows.Forms.Control valor_liga_faixa1_b8 = this.Valor_liga_faixa1_b3;
			size = new size(39, 20);
			valor_liga_faixa1_b8.Size = size;
			this.Valor_liga_faixa1_b3.TabIndex = (HorizontalAlignment)49;
			this.Valor_liga_faixa1_b3.TextAlign = HorizontalAlignment.Right;
			this.Label_faixa4_B3.AutoSize = true;
			global::System.Windows.Forms.Control label_faixa4_B7 = this.Label_faixa4_B3;
			location = new location(6, 119);
			label_faixa4_B7.Location = location;
			this.Label_faixa4_B3.Name = "Label_faixa4_B3";
			global::System.Windows.Forms.Control label_faixa4_B8 = this.Label_faixa4_B3;
			size = new size(47, 13);
			label_faixa4_B8.Size = size;
			this.Label_faixa4_B3.TabIndex = (HorizontalAlignment)2;
			this.Label_faixa4_B3.Text = "Faixa 4 :";
			this.Label_faixa3_B3.AutoSize = true;
			global::System.Windows.Forms.Control label_faixa3_B7 = this.Label_faixa3_B3;
			location = new location(6, 93);
			label_faixa3_B7.Location = location;
			this.Label_faixa3_B3.Name = "Label_faixa3_B3";
			global::System.Windows.Forms.Control label_faixa3_B8 = this.Label_faixa3_B3;
			size = new size(47, 13);
			label_faixa3_B8.Size = size;
			this.Label_faixa3_B3.TabIndex = (HorizontalAlignment)2;
			this.Label_faixa3_B3.Text = "Faixa 3 :";
			this.Label_faixa2_B3.AutoSize = true;
			global::System.Windows.Forms.Control label_faixa2_B7 = this.Label_faixa2_B3;
			location = new location(6, 67);
			label_faixa2_B7.Location = location;
			this.Label_faixa2_B3.Name = "Label_faixa2_B3";
			global::System.Windows.Forms.Control label_faixa2_B8 = this.Label_faixa2_B3;
			size = new size(47, 13);
			label_faixa2_B8.Size = size;
			this.Label_faixa2_B3.TabIndex = (HorizontalAlignment)2;
			this.Label_faixa2_B3.Text = "Faixa 2 :";
			this.Label_faixa1_B3.AutoSize = true;
			global::System.Windows.Forms.Control label_faixa1_B7 = this.Label_faixa1_B3;
			location = new location(6, 41);
			label_faixa1_B7.Location = location;
			this.Label_faixa1_B3.Name = "Label_faixa1_B3";
			global::System.Windows.Forms.Control label_faixa1_B8 = this.Label_faixa1_B3;
			size = new size(47, 13);
			label_faixa1_B8.Size = size;
			this.Label_faixa1_B3.TabIndex = (HorizontalAlignment)2;
			this.Label_faixa1_B3.Text = "Faixa 1 :";
			this.GroupBox_ponta.Controls.Add(this.CheckBox_horario_ponta);
			this.GroupBox_ponta.Controls.Add(this.Desliga_ponta);
			this.GroupBox_ponta.Controls.Add(this.Liga_ponta);
			this.GroupBox_ponta.Enabled = false;
			global::System.Windows.Forms.Control groupBox_ponta = this.GroupBox_ponta;
			location = new location(425, 12);
			groupBox_ponta.Location = location;
			this.GroupBox_ponta.Name = "GroupBox_ponta";
			global::System.Windows.Forms.Control groupBox_ponta2 = this.GroupBox_ponta;
			size = new size(183, 97);
			groupBox_ponta2.Size = size;
			this.GroupBox_ponta.TabIndex = (HorizontalAlignment)69;
			this.GroupBox_ponta.TabStop = false;
			this.GroupBox_ponta.Text = "Controle horário de ponta";
			this.CheckBox_horario_ponta.AutoSize = true;
			global::System.Windows.Forms.Control checkBox_horario_ponta = this.CheckBox_horario_ponta;
			location = new location(24, 20);
			checkBox_horario_ponta.Location = location;
			this.CheckBox_horario_ponta.Name = "CheckBox_horario_ponta";
			global::System.Windows.Forms.Control checkBox_horario_ponta2 = this.CheckBox_horario_ponta;
			size = new size(116, 17);
			checkBox_horario_ponta2.Size = size;
			this.CheckBox_horario_ponta.TabIndex = (HorizontalAlignment)70;
			this.CheckBox_horario_ponta.Text = "Habilita verificação";
			this.CheckBox_horario_ponta.UseVisualStyleBackColor = true;
			this.Desliga_ponta.Controls.Add(this.Valor_desliga_ponta);
			global::System.Windows.Forms.Control desliga_ponta = this.Desliga_ponta;
			location = new location(98, 42);
			desliga_ponta.Location = location;
			this.Desliga_ponta.Name = "Desliga_ponta";
			global::System.Windows.Forms.Control desliga_ponta2 = this.Desliga_ponta;
			size = new size(73, 42);
			desliga_ponta2.Size = size;
			this.Desliga_ponta.TabIndex = (HorizontalAlignment)73;
			this.Desliga_ponta.TabStop = false;
			this.Desliga_ponta.Text = "Desliga";
			global::System.Windows.Forms.Control valor_desliga_ponta = this.Valor_desliga_ponta;
			location = new location(17, 15);
			valor_desliga_ponta.Location = location;
			this.Valor_desliga_ponta.Name = "Valor_desliga_ponta";
			global::System.Windows.Forms.Control valor_desliga_ponta2 = this.Valor_desliga_ponta;
			size = new size(39, 20);
			valor_desliga_ponta2.Size = size;
			this.Valor_desliga_ponta.TabIndex = (HorizontalAlignment)74;
			this.Valor_desliga_ponta.TextAlign = HorizontalAlignment.Right;
			this.Liga_ponta.Controls.Add(this.Valor_liga_ponta);
			global::System.Windows.Forms.Control liga_ponta = this.Liga_ponta;
			location = new location(14, 42);
			liga_ponta.Location = location;
			this.Liga_ponta.Name = "Liga_ponta";
			global::System.Windows.Forms.Control liga_ponta2 = this.Liga_ponta;
			size = new size(73, 42);
			liga_ponta2.Size = size;
			this.Liga_ponta.TabIndex = (HorizontalAlignment)71;
			this.Liga_ponta.TabStop = false;
			this.Liga_ponta.Text = "Liga";
			global::System.Windows.Forms.Control valor_liga_ponta = this.Valor_liga_ponta;
			location = new location(14, 15);
			valor_liga_ponta.Location = location;
			this.Valor_liga_ponta.Name = "Valor_liga_ponta";
			global::System.Windows.Forms.Control valor_liga_ponta2 = this.Valor_liga_ponta;
			size = new size(39, 20);
			valor_liga_ponta2.Size = size;
			this.Valor_liga_ponta.TabIndex = (HorizontalAlignment)75;
			this.Valor_liga_ponta.TextAlign = HorizontalAlignment.Right;
			this.Grupo_temperaturas.Controls.Add(this.Grupo_temp);
			this.Grupo_temperaturas.Controls.Add(this.CheckBox_habilita_temperatura);
			this.Grupo_temperaturas.Controls.Add(this.Label_temp_bomba_4);
			this.Grupo_temperaturas.Controls.Add(this.Label_temp_bomba_3);
			this.Grupo_temperaturas.Controls.Add(this.Label_temp_bomba_2);
			this.Grupo_temperaturas.Controls.Add(this.Label_temp_bomba_1);
			this.Grupo_temperaturas.Enabled = false;
			global::System.Windows.Forms.Control grupo_temperaturas = this.Grupo_temperaturas;
			location = new location(425, 240);
			grupo_temperaturas.Location = location;
			this.Grupo_temperaturas.Name = "Grupo_temperaturas";
			global::System.Windows.Forms.Control grupo_temperaturas2 = this.Grupo_temperaturas;
			size = new size(183, 182);
			grupo_temperaturas2.Size = size;
			this.Grupo_temperaturas.TabIndex = (HorizontalAlignment)75;
			this.Grupo_temperaturas.TabStop = false;
			this.Grupo_temperaturas.Text = "Controle de temperaturas";
			this.Grupo_temp.Controls.Add(this.Valor_Temp_B4);
			this.Grupo_temp.Controls.Add(this.Valor_Temp_B3);
			this.Grupo_temp.Controls.Add(this.Valor_Temp_B2);
			this.Grupo_temp.Controls.Add(this.Valor_Temp_B1);
			global::System.Windows.Forms.Control grupo_temp = this.Grupo_temp;
			location = new location(74, 45);
			grupo_temp.Location = location;
			this.Grupo_temp.Name = "Grupo_temp";
			global::System.Windows.Forms.Control grupo_temp2 = this.Grupo_temp;
			size = new size(99, 128);
			grupo_temp2.Size = size;
			this.Grupo_temp.TabIndex = (HorizontalAlignment)77;
			this.Grupo_temp.TabStop = false;
			this.Grupo_temp.Text = "Temperatura";
			global::System.Windows.Forms.Control valor_Temp_B = this.Valor_Temp_B4;
			location = new location(16, 96);
			valor_Temp_B.Location = location;
			this.Valor_Temp_B4.Name = "Valor_Temp_B4";
			global::System.Windows.Forms.Control valor_Temp_B2 = this.Valor_Temp_B4;
			size = new size(66, 20);
			valor_Temp_B2.Size = size;
			this.Valor_Temp_B4.TabIndex = (HorizontalAlignment)81;
			this.Valor_Temp_B4.TextAlign = HorizontalAlignment.Center;
			global::System.Windows.Forms.Control valor_Temp_B3 = this.Valor_Temp_B3;
			location = new location(16, 71);
			valor_Temp_B3.Location = location;
			this.Valor_Temp_B3.Name = "Valor_Temp_B3";
			global::System.Windows.Forms.Control valor_Temp_B4 = this.Valor_Temp_B3;
			size = new size(66, 20);
			valor_Temp_B4.Size = size;
			this.Valor_Temp_B3.TabIndex = (HorizontalAlignment)80;
			this.Valor_Temp_B3.TextAlign = HorizontalAlignment.Center;
			global::System.Windows.Forms.Control valor_Temp_B5 = this.Valor_Temp_B2;
			location = new location(16, 46);
			valor_Temp_B5.Location = location;
			this.Valor_Temp_B2.Name = "Valor_Temp_B2";
			global::System.Windows.Forms.Control valor_Temp_B6 = this.Valor_Temp_B2;
			size = new size(66, 20);
			valor_Temp_B6.Size = size;
			this.Valor_Temp_B2.TabIndex = (HorizontalAlignment)79;
			this.Valor_Temp_B2.TextAlign = HorizontalAlignment.Center;
			global::System.Windows.Forms.Control valor_Temp_B7 = this.Valor_Temp_B1;
			location = new location(16, 21);
			valor_Temp_B7.Location = location;
			this.Valor_Temp_B1.Name = "Valor_Temp_B1";
			global::System.Windows.Forms.Control valor_Temp_B8 = this.Valor_Temp_B1;
			size = new size(66, 20);
			valor_Temp_B8.Size = size;
			this.Valor_Temp_B1.TabIndex = (HorizontalAlignment)78;
			this.Valor_Temp_B1.TextAlign = HorizontalAlignment.Center;
			this.CheckBox_habilita_temperatura.AutoSize = true;
			global::System.Windows.Forms.Control checkBox_habilita_temperatura = this.CheckBox_habilita_temperatura;
			location = new location(17, 23);
			checkBox_habilita_temperatura.Location = location;
			this.CheckBox_habilita_temperatura.Name = "CheckBox_habilita_temperatura";
			global::System.Windows.Forms.Control checkBox_habilita_temperatura2 = this.CheckBox_habilita_temperatura;
			size = new size(116, 17);
			checkBox_habilita_temperatura2.Size = size;
			this.CheckBox_habilita_temperatura.TabIndex = (HorizontalAlignment)76;
			this.CheckBox_habilita_temperatura.Text = "Habilita verificação";
			this.CheckBox_habilita_temperatura.UseVisualStyleBackColor = true;
			this.Label_temp_bomba_4.AutoSize = true;
			global::System.Windows.Forms.Control label_temp_bomba_ = this.Label_temp_bomba_4;
			location = new location(13, 145);
			label_temp_bomba_.Location = location;
			this.Label_temp_bomba_4.Name = "Label_temp_bomba_4";
			global::System.Windows.Forms.Control label_temp_bomba_2 = this.Label_temp_bomba_4;
			size = new size(55, 13);
			label_temp_bomba_2.Size = size;
			this.Label_temp_bomba_4.TabIndex = (HorizontalAlignment)2;
			this.Label_temp_bomba_4.Text = "Bomba 4 :";
			this.Label_temp_bomba_3.AutoSize = true;
			global::System.Windows.Forms.Control label_temp_bomba_3 = this.Label_temp_bomba_3;
			location = new location(13, 120);
			label_temp_bomba_3.Location = location;
			this.Label_temp_bomba_3.Name = "Label_temp_bomba_3";
			global::System.Windows.Forms.Control label_temp_bomba_4 = this.Label_temp_bomba_3;
			size = new size(55, 13);
			label_temp_bomba_4.Size = size;
			this.Label_temp_bomba_3.TabIndex = (HorizontalAlignment)2;
			this.Label_temp_bomba_3.Text = "Bomba 3 :";
			this.Label_temp_bomba_2.AutoSize = true;
			global::System.Windows.Forms.Control label_temp_bomba_5 = this.Label_temp_bomba_2;
			location = new location(13, 95);
			label_temp_bomba_5.Location = location;
			this.Label_temp_bomba_2.Name = "Label_temp_bomba_2";
			global::System.Windows.Forms.Control label_temp_bomba_6 = this.Label_temp_bomba_2;
			size = new size(55, 13);
			label_temp_bomba_6.Size = size;
			this.Label_temp_bomba_2.TabIndex = (HorizontalAlignment)2;
			this.Label_temp_bomba_2.Text = "Bomba 2 :";
			this.Label_temp_bomba_1.AutoSize = true;
			global::System.Windows.Forms.Control label_temp_bomba_7 = this.Label_temp_bomba_1;
			location = new location(13, 71);
			label_temp_bomba_7.Location = location;
			this.Label_temp_bomba_1.Name = "Label_temp_bomba_1";
			global::System.Windows.Forms.Control label_temp_bomba_8 = this.Label_temp_bomba_1;
			size = new size(55, 13);
			label_temp_bomba_8.Size = size;
			this.Label_temp_bomba_1.TabIndex = (HorizontalAlignment)2;
			this.Label_temp_bomba_1.Text = "Bomba 1 :";
			this.Grupo_relogio.Controls.Add(this.Button_atualiza_relogio_micro);
			this.Grupo_relogio.Controls.Add(this.Button_bloqueio_relogio);
			this.Grupo_relogio.Controls.Add(this.Label_hora);
			this.Grupo_relogio.Controls.Add(this.Label_data);
			this.Grupo_relogio.Controls.Add(this.Valor_hora);
			this.Grupo_relogio.Controls.Add(this.Valor_data);
			this.Grupo_relogio.Enabled = false;
			global::System.Windows.Forms.Control grupo_relogio = this.Grupo_relogio;
			location = new location(425, 115);
			grupo_relogio.Location = location;
			this.Grupo_relogio.Name = "Grupo_relogio";
			global::System.Windows.Forms.Control grupo_relogio2 = this.Grupo_relogio;
			size = new size(183, 119);
			grupo_relogio2.Size = size;
			this.Grupo_relogio.TabIndex = (HorizontalAlignment)83;
			this.Grupo_relogio.TabStop = false;
			this.Grupo_relogio.Text = "Relógio";
			global::System.Windows.Forms.Control button_atualiza_relogio_micro = this.Button_atualiza_relogio_micro;
			location = new location(101, 89);
			button_atualiza_relogio_micro.Location = location;
			this.Button_atualiza_relogio_micro.Name = "Button_atualiza_relogio_micro";
			global::System.Windows.Forms.Control button_atualiza_relogio_micro2 = this.Button_atualiza_relogio_micro;
			size = new size(70, 21);
			button_atualiza_relogio_micro2.Size = size;
			this.Button_atualiza_relogio_micro.TabIndex = (HorizontalAlignment)20;
			this.Button_atualiza_relogio_micro.Text = "Atualiza";
			this.Button_atualiza_relogio_micro.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control button_bloqueio_relogio = this.Button_bloqueio_relogio;
			location = new location(14, 89);
			button_bloqueio_relogio.Location = location;
			this.Button_bloqueio_relogio.Name = "Button_bloqueio_relogio";
			global::System.Windows.Forms.Control button_bloqueio_relogio2 = this.Button_bloqueio_relogio;
			size = new size(70, 21);
			button_bloqueio_relogio2.Size = size;
			this.Button_bloqueio_relogio.TabIndex = (HorizontalAlignment)20;
			this.Button_bloqueio_relogio.Text = "Libera";
			this.Button_bloqueio_relogio.UseVisualStyleBackColor = true;
			this.Label_hora.AutoSize = true;
			global::System.Windows.Forms.Control label_hora = this.Label_hora;
			location = new location(27, 55);
			label_hora.Location = location;
			this.Label_hora.Name = "Label_hora";
			global::System.Windows.Forms.Control label_hora2 = this.Label_hora;
			size = new size(36, 13);
			label_hora2.Size = size;
			this.Label_hora.TabIndex = (HorizontalAlignment)19;
			this.Label_hora.Text = "Hora :";
			this.Label_data.AutoSize = true;
			global::System.Windows.Forms.Control label_data = this.Label_data;
			location = new location(27, 28);
			label_data.Location = location;
			this.Label_data.Name = "Label_data";
			global::System.Windows.Forms.Control label_data2 = this.Label_data;
			size = new size(36, 13);
			label_data2.Size = size;
			this.Label_data.TabIndex = (HorizontalAlignment)19;
			this.Label_data.Text = "Data :";
			global::System.Windows.Forms.Control valor_hora = this.Valor_hora;
			location = new location(76, 52);
			valor_hora.Location = location;
			this.Valor_hora.Name = "Valor_hora";
			global::System.Windows.Forms.Control valor_hora2 = this.Valor_hora;
			size = new size(86, 20);
			valor_hora2.Size = size;
			this.Valor_hora.TabIndex = (HorizontalAlignment)18;
			this.Valor_hora.TextAlign = HorizontalAlignment.Right;
			global::System.Windows.Forms.Control valor_data = this.Valor_data;
			location = new location(76, 25);
			valor_data.Location = location;
			this.Valor_data.Name = "Valor_data";
			global::System.Windows.Forms.Control valor_data2 = this.Valor_data;
			size = new size(86, 20);
			valor_data2.Size = size;
			this.Valor_data.TabIndex = (HorizontalAlignment)18;
			this.Valor_data.TextAlign = HorizontalAlignment.Right;
			this.Ctrl_relogio.Interval = (HorizontalAlignment)2000;
			global::System.Drawing.SizeF autoScaleDimensions;
			autoScaleDimensions = new global::System.Drawing.SizeF(6f, 13f);
			this.AutoScaleDimensions = autoScaleDimensions;
			this.AutoScaleMode = AutoScaleMode.Font;
			size = new size(943, 610);
			this.ClientSize = size;
			this.Controls.Add(this.Grupo_relogio);
			this.Controls.Add(this.Grupo_setpoint);
			this.Controls.Add(this.Grupo_temperaturas);
			this.Controls.Add(this.Grupo_alarmes);
			this.Controls.Add(this.GroupBox_timer_3);
			this.Controls.Add(this.GroupBox_ponta);
			this.Controls.Add(this.GroupBox_timer_4);
			this.Controls.Add(this.GroupBox_timer_2);
			this.Controls.Add(this.GroupBox_timer_1);
			this.Controls.Add(this.Grupo_endereco);
			this.FormBorderStyle = FormBorderStyle.None;
			location = new location(160, 2);
			this.Location = location;
			this.Name = "Equip_VA220_ope";
			this.StartPosition = FormStartPosition.Manual;
			this.Text = "Equip_220_ope";
			this.Grupo_endereco.ResumeLayout(false);
			this.Grupo_endereco.PerformLayout();
			this.GroupBox_opcoes.ResumeLayout(false);
			this.GroupBox_opcoes.PerformLayout();
			this.Grupo_setpoint.ResumeLayout(false);
			this.Grupo_gerais.ResumeLayout(false);
			this.Grupo_gerais.PerformLayout();
			this.Grupo_niveis.ResumeLayout(false);
			this.Grupo_niveis.PerformLayout();
			this.Grupo_origem.ResumeLayout(false);
			this.Grupo_origem.PerformLayout();
			this.Grupo_alarmes.ResumeLayout(false);
			this.Grupo_alarmes.PerformLayout();
			this.GroupBox_nivel_alto.ResumeLayout(false);
			this.GroupBox_nivel_alto.PerformLayout();
			this.GroupBox_nivel_baixo.ResumeLayout(false);
			this.GroupBox_nivel_baixo.PerformLayout();
			this.GroupBox_timer_1.ResumeLayout(false);
			this.GroupBox_timer_1.PerformLayout();
			this.GroupBox_Desliga_B1.ResumeLayout(false);
			this.GroupBox_Desliga_B1.PerformLayout();
			this.GroupBox_Liga_B1.ResumeLayout(false);
			this.GroupBox_Liga_B1.PerformLayout();
			this.GroupBox_timer_2.ResumeLayout(false);
			this.GroupBox_timer_2.PerformLayout();
			this.GroupBox2.ResumeLayout(false);
			this.GroupBox2.PerformLayout();
			this.GroupBox3.ResumeLayout(false);
			this.GroupBox3.PerformLayout();
			this.GroupBox_timer_4.ResumeLayout(false);
			this.GroupBox_timer_4.PerformLayout();
			this.GroupBox5.ResumeLayout(false);
			this.GroupBox5.PerformLayout();
			this.GroupBox6.ResumeLayout(false);
			this.GroupBox6.PerformLayout();
			this.GroupBox_timer_3.ResumeLayout(false);
			this.GroupBox_timer_3.PerformLayout();
			this.GroupBox8.ResumeLayout(false);
			this.GroupBox8.PerformLayout();
			this.GroupBox9.ResumeLayout(false);
			this.GroupBox9.PerformLayout();
			this.GroupBox_ponta.ResumeLayout(false);
			this.GroupBox_ponta.PerformLayout();
			this.Desliga_ponta.ResumeLayout(false);
			this.Desliga_ponta.PerformLayout();
			this.Liga_ponta.ResumeLayout(false);
			this.Liga_ponta.PerformLayout();
			this.Grupo_temperaturas.ResumeLayout(false);
			this.Grupo_temperaturas.PerformLayout();
			this.Grupo_temp.ResumeLayout(false);
			this.Grupo_temp.PerformLayout();
			this.Grupo_relogio.ResumeLayout(false);
			this.Grupo_relogio.PerformLayout();
			this.ResumeLayout(false);
		}

		// Token: 0x04001A93 RID: 6803
		private global::System.ComponentModel.IContainer components;
	}
}
