namespace iS800
{
	// Token: 0x0200009F RID: 159
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class Equip_VA230_conf : global::System.Windows.Forms.Form
	{
		// Token: 0x060026E7 RID: 9959 RVA: 0x0041FEA0 File Offset: 0x0041E2A0
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			if (disposing && this.components != null)
			{
				this.components.Dispose();
			}
			base.Dispose(disposing);
		}

		// Token: 0x060026E8 RID: 9960 RVA: 0x0041FEC0 File Offset: 0x0041E2C0
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.grupo_parametros_gerais = new global::System.Windows.Forms.GroupBox();
			this.Valor_intervalo_varredura = new global::System.Windows.Forms.TextBox();
			this.Label_intervalo_varredura = new global::System.Windows.Forms.Label();
			this.Valor_end_origem = new global::System.Windows.Forms.TextBox();
			this.Valor_numero_recalques = new global::System.Windows.Forms.TextBox();
			this.Label_end_origem = new global::System.Windows.Forms.Label();
			this.Label_numero_recalques = new global::System.Windows.Forms.Label();
			this.Grupo_ctrl = new global::System.Windows.Forms.GroupBox();
			this.Esc_conf_md_201 = new global::System.Windows.Forms.Button();
			this.Box_Msg = new global::System.Windows.Forms.TextBox();
			this.Ler_conf_md_201 = new global::System.Windows.Forms.Button();
			this.grupo_escalas = new global::System.Windows.Forms.GroupBox();
			this.Label_end_estacao = new global::System.Windows.Forms.Label();
			this.VScroll_end_estacao = new global::System.Windows.Forms.VScrollBar();
			this.Valor_end_estacao = new global::System.Windows.Forms.TextBox();
			this.Valor_escala_canal_15 = new global::System.Windows.Forms.TextBox();
			this.Valor_escala_canal_7 = new global::System.Windows.Forms.TextBox();
			this.Valor_escala_canal_14 = new global::System.Windows.Forms.TextBox();
			this.Valor_escala_canal_6 = new global::System.Windows.Forms.TextBox();
			this.Valor_escala_canal_13 = new global::System.Windows.Forms.TextBox();
			this.Valor_escala_canal_5 = new global::System.Windows.Forms.TextBox();
			this.Valor_escala_canal_12 = new global::System.Windows.Forms.TextBox();
			this.Valor_escala_canal_4 = new global::System.Windows.Forms.TextBox();
			this.Valor_escala_canal_11 = new global::System.Windows.Forms.TextBox();
			this.Valor_escala_canal_3 = new global::System.Windows.Forms.TextBox();
			this.Valor_escala_canal_10 = new global::System.Windows.Forms.TextBox();
			this.Valor_escala_canal_2 = new global::System.Windows.Forms.TextBox();
			this.Valor_escala_canal_9 = new global::System.Windows.Forms.TextBox();
			this.Valor_escala_canal_1 = new global::System.Windows.Forms.TextBox();
			this.Valor_escala_canal_8 = new global::System.Windows.Forms.TextBox();
			this.Valor_escala_canal_0 = new global::System.Windows.Forms.TextBox();
			this.Label_escala_canal_15 = new global::System.Windows.Forms.Label();
			this.Label_escala_canal_7 = new global::System.Windows.Forms.Label();
			this.Label_escala_canal_14 = new global::System.Windows.Forms.Label();
			this.Label_escala_canal_6 = new global::System.Windows.Forms.Label();
			this.Label_escala_canal_13 = new global::System.Windows.Forms.Label();
			this.Label_escala_canal_5 = new global::System.Windows.Forms.Label();
			this.Label_escala_canal_12 = new global::System.Windows.Forms.Label();
			this.Label_escala_canal_4 = new global::System.Windows.Forms.Label();
			this.Label_escala_canal_11 = new global::System.Windows.Forms.Label();
			this.Label_escala_canal_3 = new global::System.Windows.Forms.Label();
			this.Label_escala_canal_10 = new global::System.Windows.Forms.Label();
			this.Label_escala_canal_2 = new global::System.Windows.Forms.Label();
			this.Label_escala_canal_9 = new global::System.Windows.Forms.Label();
			this.Label_escala_canal_1 = new global::System.Windows.Forms.Label();
			this.Label_escala_canal_8 = new global::System.Windows.Forms.Label();
			this.Label_escala_canal_0 = new global::System.Windows.Forms.Label();
			this.grupo_parametros_gerais.SuspendLayout();
			this.Grupo_ctrl.SuspendLayout();
			this.grupo_escalas.SuspendLayout();
			this.SuspendLayout();
			this.grupo_parametros_gerais.Controls.Add(this.Valor_intervalo_varredura);
			this.grupo_parametros_gerais.Controls.Add(this.Label_intervalo_varredura);
			this.grupo_parametros_gerais.Controls.Add(this.Valor_end_origem);
			this.grupo_parametros_gerais.Controls.Add(this.Valor_numero_recalques);
			this.grupo_parametros_gerais.Controls.Add(this.Label_end_origem);
			this.grupo_parametros_gerais.Controls.Add(this.Label_numero_recalques);
			global::System.Windows.Forms.Control grupo_parametros_gerais = this.grupo_parametros_gerais;
			global::System.Drawing.Point location;
			location = new global::System.Drawing.Point(12, 12);
			grupo_parametros_gerais.Location = location;
			this.grupo_parametros_gerais.Name = "grupo_parametros_gerais";
			global::System.Windows.Forms.Control grupo_parametros_gerais2 = this.grupo_parametros_gerais;
			global::System.Drawing.Size size;
			size = new global::System.Drawing.Size(335, 125);
			grupo_parametros_gerais2.Size = size;
			this.grupo_parametros_gerais.TabIndex = (HorizontalAlignment)1;
			this.grupo_parametros_gerais.TabStop = false;
			this.grupo_parametros_gerais.Text = "Parâmetros gerais";
			global::System.Windows.Forms.Control valor_intervalo_varredura = this.Valor_intervalo_varredura;
			location = new location(243, 78);
			valor_intervalo_varredura.Location = location;
			this.Valor_intervalo_varredura.Name = "Valor_intervalo_varredura";
			global::System.Windows.Forms.Control valor_intervalo_varredura2 = this.Valor_intervalo_varredura;
			size = new size(74, 20);
			valor_intervalo_varredura2.Size = size;
			this.Valor_intervalo_varredura.TabIndex = (HorizontalAlignment)4;
			this.Valor_intervalo_varredura.TextAlign = HorizontalAlignment.Center;
			this.Label_intervalo_varredura.AutoSize = true;
			global::System.Windows.Forms.Control label_intervalo_varredura = this.Label_intervalo_varredura;
			location = new location(24, 82);
			label_intervalo_varredura.Location = location;
			this.Label_intervalo_varredura.Name = "Label_intervalo_varredura";
			global::System.Windows.Forms.Control label_intervalo_varredura2 = this.Label_intervalo_varredura;
			size = new size(128, 13);
			label_intervalo_varredura2.Size = size;
			this.Label_intervalo_varredura.TabIndex = (HorizontalAlignment)4;
			this.Label_intervalo_varredura.Text = "Intervalo de varredura (s):";
			global::System.Windows.Forms.Control valor_end_origem = this.Valor_end_origem;
			location = new location(244, 26);
			valor_end_origem.Location = location;
			this.Valor_end_origem.Name = "Valor_end_origem";
			global::System.Windows.Forms.Control valor_end_origem2 = this.Valor_end_origem;
			size = new size(73, 20);
			valor_end_origem2.Size = size;
			this.Valor_end_origem.TabIndex = (HorizontalAlignment)2;
			this.Valor_end_origem.TextAlign = HorizontalAlignment.Center;
			global::System.Windows.Forms.Control valor_numero_recalques = this.Valor_numero_recalques;
			location = new location(243, 52);
			valor_numero_recalques.Location = location;
			this.Valor_numero_recalques.Name = "Valor_numero_recalques";
			global::System.Windows.Forms.Control valor_numero_recalques2 = this.Valor_numero_recalques;
			size = new size(74, 20);
			valor_numero_recalques2.Size = size;
			this.Valor_numero_recalques.TabIndex = (HorizontalAlignment)3;
			this.Valor_numero_recalques.TextAlign = HorizontalAlignment.Center;
			this.Label_end_origem.AutoSize = true;
			global::System.Windows.Forms.Control label_end_origem = this.Label_end_origem;
			location = new location(24, 30);
			label_end_origem.Location = location;
			this.Label_end_origem.Name = "Label_end_origem";
			global::System.Windows.Forms.Control label_end_origem2 = this.Label_end_origem;
			size = new size(108, 13);
			label_end_origem2.Size = size;
			this.Label_end_origem.TabIndex = (HorizontalAlignment)1;
			this.Label_end_origem.Text = "Endereço de origem :";
			this.Label_numero_recalques.AutoSize = true;
			global::System.Windows.Forms.Control label_numero_recalques = this.Label_numero_recalques;
			location = new location(24, 56);
			label_numero_recalques.Location = location;
			this.Label_numero_recalques.Name = "Label_numero_recalques";
			global::System.Windows.Forms.Control label_numero_recalques2 = this.Label_numero_recalques;
			size = new size(162, 13);
			label_numero_recalques2.Size = size;
			this.Label_numero_recalques.TabIndex = (HorizontalAlignment)0;
			this.Label_numero_recalques.Text = "Número de estação de recalque:";
			this.Grupo_ctrl.Controls.Add(this.Esc_conf_md_201);
			this.Grupo_ctrl.Controls.Add(this.Box_Msg);
			this.Grupo_ctrl.Controls.Add(this.Ler_conf_md_201);
			global::System.Windows.Forms.Control grupo_ctrl = this.Grupo_ctrl;
			location = new location(12, 443);
			grupo_ctrl.Location = location;
			this.Grupo_ctrl.Name = "Grupo_ctrl";
			global::System.Windows.Forms.Control grupo_ctrl2 = this.Grupo_ctrl;
			size = new size(335, 105);
			grupo_ctrl2.Size = size;
			this.Grupo_ctrl.TabIndex = (HorizontalAlignment)23;
			this.Grupo_ctrl.TabStop = false;
			this.Grupo_ctrl.Text = "Comandos e Status";
			global::System.Windows.Forms.Control esc_conf_md_ = this.Esc_conf_md_201;
			location = new location(194, 61);
			esc_conf_md_.Location = location;
			this.Esc_conf_md_201.Name = "Esc_conf_md_201";
			global::System.Windows.Forms.Control esc_conf_md_2 = this.Esc_conf_md_201;
			size = new size(109, 28);
			esc_conf_md_2.Size = size;
			this.Esc_conf_md_201.TabIndex = (HorizontalAlignment)25;
			this.Esc_conf_md_201.Text = "Salvar config.";
			this.Esc_conf_md_201.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control box_Msg = this.Box_Msg;
			location = new location(24, 29);
			box_Msg.Location = location;
			this.Box_Msg.Name = "Box_Msg";
			global::System.Windows.Forms.Control box_Msg2 = this.Box_Msg;
			size = new size(293, 20);
			box_Msg2.Size = size;
			this.Box_Msg.TabIndex = (HorizontalAlignment)5;
			this.Box_Msg.TabStop = false;
			this.Box_Msg.TextAlign = HorizontalAlignment.Right;
			global::System.Windows.Forms.Control ler_conf_md_ = this.Ler_conf_md_201;
			location = new location(41, 61);
			ler_conf_md_.Location = location;
			this.Ler_conf_md_201.Name = "Ler_conf_md_201";
			global::System.Windows.Forms.Control ler_conf_md_2 = this.Ler_conf_md_201;
			size = new size(109, 28);
			ler_conf_md_2.Size = size;
			this.Ler_conf_md_201.TabIndex = (HorizontalAlignment)24;
			this.Ler_conf_md_201.Text = "Ler configuração";
			this.Ler_conf_md_201.UseVisualStyleBackColor = true;
			this.grupo_escalas.Controls.Add(this.Label_end_estacao);
			this.grupo_escalas.Controls.Add(this.VScroll_end_estacao);
			this.grupo_escalas.Controls.Add(this.Valor_end_estacao);
			this.grupo_escalas.Controls.Add(this.Valor_escala_canal_15);
			this.grupo_escalas.Controls.Add(this.Valor_escala_canal_7);
			this.grupo_escalas.Controls.Add(this.Valor_escala_canal_14);
			this.grupo_escalas.Controls.Add(this.Valor_escala_canal_6);
			this.grupo_escalas.Controls.Add(this.Valor_escala_canal_13);
			this.grupo_escalas.Controls.Add(this.Valor_escala_canal_5);
			this.grupo_escalas.Controls.Add(this.Valor_escala_canal_12);
			this.grupo_escalas.Controls.Add(this.Valor_escala_canal_4);
			this.grupo_escalas.Controls.Add(this.Valor_escala_canal_11);
			this.grupo_escalas.Controls.Add(this.Valor_escala_canal_3);
			this.grupo_escalas.Controls.Add(this.Valor_escala_canal_10);
			this.grupo_escalas.Controls.Add(this.Valor_escala_canal_2);
			this.grupo_escalas.Controls.Add(this.Valor_escala_canal_9);
			this.grupo_escalas.Controls.Add(this.Valor_escala_canal_1);
			this.grupo_escalas.Controls.Add(this.Valor_escala_canal_8);
			this.grupo_escalas.Controls.Add(this.Valor_escala_canal_0);
			this.grupo_escalas.Controls.Add(this.Label_escala_canal_15);
			this.grupo_escalas.Controls.Add(this.Label_escala_canal_7);
			this.grupo_escalas.Controls.Add(this.Label_escala_canal_14);
			this.grupo_escalas.Controls.Add(this.Label_escala_canal_6);
			this.grupo_escalas.Controls.Add(this.Label_escala_canal_13);
			this.grupo_escalas.Controls.Add(this.Label_escala_canal_5);
			this.grupo_escalas.Controls.Add(this.Label_escala_canal_12);
			this.grupo_escalas.Controls.Add(this.Label_escala_canal_4);
			this.grupo_escalas.Controls.Add(this.Label_escala_canal_11);
			this.grupo_escalas.Controls.Add(this.Label_escala_canal_3);
			this.grupo_escalas.Controls.Add(this.Label_escala_canal_10);
			this.grupo_escalas.Controls.Add(this.Label_escala_canal_2);
			this.grupo_escalas.Controls.Add(this.Label_escala_canal_9);
			this.grupo_escalas.Controls.Add(this.Label_escala_canal_1);
			this.grupo_escalas.Controls.Add(this.Label_escala_canal_8);
			this.grupo_escalas.Controls.Add(this.Label_escala_canal_0);
			global::System.Windows.Forms.Control grupo_escalas = this.grupo_escalas;
			location = new location(12, 143);
			grupo_escalas.Location = location;
			this.grupo_escalas.Name = "grupo_escalas";
			global::System.Windows.Forms.Control grupo_escalas2 = this.grupo_escalas;
			size = new size(335, 294);
			grupo_escalas2.Size = size;
			this.grupo_escalas.TabIndex = (HorizontalAlignment)5;
			this.grupo_escalas.TabStop = false;
			this.grupo_escalas.Text = "Configuração dos Fundos de Escala";
			this.Label_end_estacao.AutoSize = true;
			global::System.Windows.Forms.Control label_end_estacao = this.Label_end_estacao;
			location = new location(24, 35);
			label_end_estacao.Location = location;
			this.Label_end_estacao.Name = "Label_end_estacao";
			global::System.Windows.Forms.Control label_end_estacao2 = this.Label_end_estacao;
			size = new size(135, 13);
			label_end_estacao2.Size = size;
			this.Label_end_estacao.TabIndex = (HorizontalAlignment)9;
			this.Label_end_estacao.Text = "End. estação de recalque :";
			this.VScroll_end_estacao.LargeChange = (HorizontalAlignment)1;
			global::System.Windows.Forms.Control vscroll_end_estacao = this.VScroll_end_estacao;
			location = new location(232, 32);
			vscroll_end_estacao.Location = location;
			this.VScroll_end_estacao.Name = "VScroll_end_estacao";
			global::System.Windows.Forms.Control vscroll_end_estacao2 = this.VScroll_end_estacao;
			size = new size(26, 21);
			vscroll_end_estacao2.Size = size;
			this.VScroll_end_estacao.TabIndex = (HorizontalAlignment)8;
			global::System.Windows.Forms.Control valor_end_estacao = this.Valor_end_estacao;
			location = new location(165, 32);
			valor_end_estacao.Location = location;
			this.Valor_end_estacao.Name = "Valor_end_estacao";
			global::System.Windows.Forms.Control valor_end_estacao2 = this.Valor_end_estacao;
			size = new size(66, 20);
			valor_end_estacao2.Size = size;
			this.Valor_end_estacao.TabIndex = (HorizontalAlignment)6;
			this.Valor_end_estacao.TextAlign = HorizontalAlignment.Center;
			this.Valor_escala_canal_15.AcceptsTab = true;
			global::System.Windows.Forms.Control valor_escala_canal_ = this.Valor_escala_canal_15;
			location = new location(234, 259);
			valor_escala_canal_.Location = location;
			this.Valor_escala_canal_15.Name = "Valor_escala_canal_15";
			global::System.Windows.Forms.Control valor_escala_canal_2 = this.Valor_escala_canal_15;
			size = new size(73, 20);
			valor_escala_canal_2.Size = size;
			this.Valor_escala_canal_15.TabIndex = (HorizontalAlignment)22;
			this.Valor_escala_canal_15.TextAlign = HorizontalAlignment.Center;
			this.Valor_escala_canal_7.AcceptsTab = true;
			global::System.Windows.Forms.Control valor_escala_canal_3 = this.Valor_escala_canal_7;
			location = new location(79, 259);
			valor_escala_canal_3.Location = location;
			this.Valor_escala_canal_7.Name = "Valor_escala_canal_7";
			global::System.Windows.Forms.Control valor_escala_canal_4 = this.Valor_escala_canal_7;
			size = new size(73, 20);
			valor_escala_canal_4.Size = size;
			this.Valor_escala_canal_7.TabIndex = (HorizontalAlignment)14;
			this.Valor_escala_canal_7.TextAlign = HorizontalAlignment.Center;
			this.Valor_escala_canal_14.AcceptsTab = true;
			global::System.Windows.Forms.Control valor_escala_canal_5 = this.Valor_escala_canal_14;
			location = new location(234, 232);
			valor_escala_canal_5.Location = location;
			this.Valor_escala_canal_14.Name = "Valor_escala_canal_14";
			global::System.Windows.Forms.Control valor_escala_canal_6 = this.Valor_escala_canal_14;
			size = new size(73, 20);
			valor_escala_canal_6.Size = size;
			this.Valor_escala_canal_14.TabIndex = (HorizontalAlignment)21;
			this.Valor_escala_canal_14.TextAlign = HorizontalAlignment.Center;
			this.Valor_escala_canal_6.AcceptsTab = true;
			global::System.Windows.Forms.Control valor_escala_canal_7 = this.Valor_escala_canal_6;
			location = new location(79, 232);
			valor_escala_canal_7.Location = location;
			this.Valor_escala_canal_6.Name = "Valor_escala_canal_6";
			global::System.Windows.Forms.Control valor_escala_canal_8 = this.Valor_escala_canal_6;
			size = new size(73, 20);
			valor_escala_canal_8.Size = size;
			this.Valor_escala_canal_6.TabIndex = (HorizontalAlignment)13;
			this.Valor_escala_canal_6.TextAlign = HorizontalAlignment.Center;
			this.Valor_escala_canal_13.AcceptsTab = true;
			global::System.Windows.Forms.Control valor_escala_canal_9 = this.Valor_escala_canal_13;
			location = new location(234, 205);
			valor_escala_canal_9.Location = location;
			this.Valor_escala_canal_13.Name = "Valor_escala_canal_13";
			global::System.Windows.Forms.Control valor_escala_canal_10 = this.Valor_escala_canal_13;
			size = new size(73, 20);
			valor_escala_canal_10.Size = size;
			this.Valor_escala_canal_13.TabIndex = (HorizontalAlignment)20;
			this.Valor_escala_canal_13.TextAlign = HorizontalAlignment.Center;
			this.Valor_escala_canal_5.AcceptsTab = true;
			global::System.Windows.Forms.Control valor_escala_canal_11 = this.Valor_escala_canal_5;
			location = new location(79, 205);
			valor_escala_canal_11.Location = location;
			this.Valor_escala_canal_5.Name = "Valor_escala_canal_5";
			global::System.Windows.Forms.Control valor_escala_canal_12 = this.Valor_escala_canal_5;
			size = new size(73, 20);
			valor_escala_canal_12.Size = size;
			this.Valor_escala_canal_5.TabIndex = (HorizontalAlignment)12;
			this.Valor_escala_canal_5.TextAlign = HorizontalAlignment.Center;
			this.Valor_escala_canal_12.AcceptsTab = true;
			global::System.Windows.Forms.Control valor_escala_canal_13 = this.Valor_escala_canal_12;
			location = new location(234, 178);
			valor_escala_canal_13.Location = location;
			this.Valor_escala_canal_12.Name = "Valor_escala_canal_12";
			global::System.Windows.Forms.Control valor_escala_canal_14 = this.Valor_escala_canal_12;
			size = new size(73, 20);
			valor_escala_canal_14.Size = size;
			this.Valor_escala_canal_12.TabIndex = (HorizontalAlignment)19;
			this.Valor_escala_canal_12.TextAlign = HorizontalAlignment.Center;
			this.Valor_escala_canal_4.AcceptsTab = true;
			global::System.Windows.Forms.Control valor_escala_canal_15 = this.Valor_escala_canal_4;
			location = new location(79, 178);
			valor_escala_canal_15.Location = location;
			this.Valor_escala_canal_4.Name = "Valor_escala_canal_4";
			global::System.Windows.Forms.Control valor_escala_canal_16 = this.Valor_escala_canal_4;
			size = new size(73, 20);
			valor_escala_canal_16.Size = size;
			this.Valor_escala_canal_4.TabIndex = (HorizontalAlignment)11;
			this.Valor_escala_canal_4.TextAlign = HorizontalAlignment.Center;
			this.Valor_escala_canal_11.AcceptsTab = true;
			global::System.Windows.Forms.Control valor_escala_canal_17 = this.Valor_escala_canal_11;
			location = new location(234, 150);
			valor_escala_canal_17.Location = location;
			this.Valor_escala_canal_11.Name = "Valor_escala_canal_11";
			global::System.Windows.Forms.Control valor_escala_canal_18 = this.Valor_escala_canal_11;
			size = new size(73, 20);
			valor_escala_canal_18.Size = size;
			this.Valor_escala_canal_11.TabIndex = (HorizontalAlignment)18;
			this.Valor_escala_canal_11.TextAlign = HorizontalAlignment.Center;
			this.Valor_escala_canal_3.AcceptsTab = true;
			global::System.Windows.Forms.Control valor_escala_canal_19 = this.Valor_escala_canal_3;
			location = new location(79, 150);
			valor_escala_canal_19.Location = location;
			this.Valor_escala_canal_3.Name = "Valor_escala_canal_3";
			global::System.Windows.Forms.Control valor_escala_canal_20 = this.Valor_escala_canal_3;
			size = new size(73, 20);
			valor_escala_canal_20.Size = size;
			this.Valor_escala_canal_3.TabIndex = (HorizontalAlignment)10;
			this.Valor_escala_canal_3.TextAlign = HorizontalAlignment.Center;
			this.Valor_escala_canal_10.AcceptsTab = true;
			global::System.Windows.Forms.Control valor_escala_canal_21 = this.Valor_escala_canal_10;
			location = new location(234, 124);
			valor_escala_canal_21.Location = location;
			this.Valor_escala_canal_10.Name = "Valor_escala_canal_10";
			global::System.Windows.Forms.Control valor_escala_canal_22 = this.Valor_escala_canal_10;
			size = new size(73, 20);
			valor_escala_canal_22.Size = size;
			this.Valor_escala_canal_10.TabIndex = (HorizontalAlignment)17;
			this.Valor_escala_canal_10.TextAlign = HorizontalAlignment.Center;
			this.Valor_escala_canal_2.AcceptsTab = true;
			global::System.Windows.Forms.Control valor_escala_canal_23 = this.Valor_escala_canal_2;
			location = new location(79, 124);
			valor_escala_canal_23.Location = location;
			this.Valor_escala_canal_2.Name = "Valor_escala_canal_2";
			global::System.Windows.Forms.Control valor_escala_canal_24 = this.Valor_escala_canal_2;
			size = new size(73, 20);
			valor_escala_canal_24.Size = size;
			this.Valor_escala_canal_2.TabIndex = (HorizontalAlignment)9;
			this.Valor_escala_canal_2.TextAlign = HorizontalAlignment.Center;
			this.Valor_escala_canal_9.AcceptsTab = true;
			global::System.Windows.Forms.Control valor_escala_canal_25 = this.Valor_escala_canal_9;
			location = new location(234, 100);
			valor_escala_canal_25.Location = location;
			this.Valor_escala_canal_9.Name = "Valor_escala_canal_9";
			global::System.Windows.Forms.Control valor_escala_canal_26 = this.Valor_escala_canal_9;
			size = new size(73, 20);
			valor_escala_canal_26.Size = size;
			this.Valor_escala_canal_9.TabIndex = (HorizontalAlignment)16;
			this.Valor_escala_canal_9.TextAlign = HorizontalAlignment.Center;
			this.Valor_escala_canal_1.AcceptsTab = true;
			global::System.Windows.Forms.Control valor_escala_canal_27 = this.Valor_escala_canal_1;
			location = new location(79, 100);
			valor_escala_canal_27.Location = location;
			this.Valor_escala_canal_1.Name = "Valor_escala_canal_1";
			global::System.Windows.Forms.Control valor_escala_canal_28 = this.Valor_escala_canal_1;
			size = new size(73, 20);
			valor_escala_canal_28.Size = size;
			this.Valor_escala_canal_1.TabIndex = (HorizontalAlignment)8;
			this.Valor_escala_canal_1.TextAlign = HorizontalAlignment.Center;
			this.Valor_escala_canal_8.AcceptsTab = true;
			global::System.Windows.Forms.Control valor_escala_canal_29 = this.Valor_escala_canal_8;
			location = new location(234, 73);
			valor_escala_canal_29.Location = location;
			this.Valor_escala_canal_8.Name = "Valor_escala_canal_8";
			global::System.Windows.Forms.Control valor_escala_canal_30 = this.Valor_escala_canal_8;
			size = new size(73, 20);
			valor_escala_canal_30.Size = size;
			this.Valor_escala_canal_8.TabIndex = (HorizontalAlignment)15;
			this.Valor_escala_canal_8.TextAlign = HorizontalAlignment.Center;
			this.Valor_escala_canal_0.AcceptsTab = true;
			global::System.Windows.Forms.Control valor_escala_canal_31 = this.Valor_escala_canal_0;
			location = new location(79, 73);
			valor_escala_canal_31.Location = location;
			this.Valor_escala_canal_0.Name = "Valor_escala_canal_0";
			global::System.Windows.Forms.Control valor_escala_canal_32 = this.Valor_escala_canal_0;
			size = new size(73, 20);
			valor_escala_canal_32.Size = size;
			this.Valor_escala_canal_0.TabIndex = (HorizontalAlignment)7;
			this.Valor_escala_canal_0.TextAlign = HorizontalAlignment.Center;
			this.Label_escala_canal_15.AutoSize = true;
			global::System.Windows.Forms.Control label_escala_canal_ = this.Label_escala_canal_15;
			location = new location(179, 262);
			label_escala_canal_.Location = location;
			this.Label_escala_canal_15.Name = "Label_escala_canal_15";
			global::System.Windows.Forms.Control label_escala_canal_2 = this.Label_escala_canal_15;
			size = new size(55, 13);
			label_escala_canal_2.Size = size;
			this.Label_escala_canal_15.TabIndex = (HorizontalAlignment)1;
			this.Label_escala_canal_15.Text = "Canal 15 :";
			this.Label_escala_canal_7.AutoSize = true;
			global::System.Windows.Forms.Control label_escala_canal_3 = this.Label_escala_canal_7;
			location = new location(24, 262);
			label_escala_canal_3.Location = location;
			this.Label_escala_canal_7.Name = "Label_escala_canal_7";
			global::System.Windows.Forms.Control label_escala_canal_4 = this.Label_escala_canal_7;
			size = new size(55, 13);
			label_escala_canal_4.Size = size;
			this.Label_escala_canal_7.TabIndex = (HorizontalAlignment)1;
			this.Label_escala_canal_7.Text = "Canal 07 :";
			this.Label_escala_canal_14.AutoSize = true;
			global::System.Windows.Forms.Control label_escala_canal_5 = this.Label_escala_canal_14;
			location = new location(179, 235);
			label_escala_canal_5.Location = location;
			this.Label_escala_canal_14.Name = "Label_escala_canal_14";
			global::System.Windows.Forms.Control label_escala_canal_6 = this.Label_escala_canal_14;
			size = new size(55, 13);
			label_escala_canal_6.Size = size;
			this.Label_escala_canal_14.TabIndex = (HorizontalAlignment)1;
			this.Label_escala_canal_14.Text = "Canal 14 :";
			this.Label_escala_canal_6.AutoSize = true;
			global::System.Windows.Forms.Control label_escala_canal_7 = this.Label_escala_canal_6;
			location = new location(24, 235);
			label_escala_canal_7.Location = location;
			this.Label_escala_canal_6.Name = "Label_escala_canal_6";
			global::System.Windows.Forms.Control label_escala_canal_8 = this.Label_escala_canal_6;
			size = new size(55, 13);
			label_escala_canal_8.Size = size;
			this.Label_escala_canal_6.TabIndex = (HorizontalAlignment)1;
			this.Label_escala_canal_6.Text = "Canal 06 :";
			this.Label_escala_canal_13.AutoSize = true;
			global::System.Windows.Forms.Control label_escala_canal_9 = this.Label_escala_canal_13;
			location = new location(179, 208);
			label_escala_canal_9.Location = location;
			this.Label_escala_canal_13.Name = "Label_escala_canal_13";
			global::System.Windows.Forms.Control label_escala_canal_10 = this.Label_escala_canal_13;
			size = new size(55, 13);
			label_escala_canal_10.Size = size;
			this.Label_escala_canal_13.TabIndex = (HorizontalAlignment)1;
			this.Label_escala_canal_13.Text = "Canal 13 :";
			this.Label_escala_canal_5.AutoSize = true;
			global::System.Windows.Forms.Control label_escala_canal_11 = this.Label_escala_canal_5;
			location = new location(24, 208);
			label_escala_canal_11.Location = location;
			this.Label_escala_canal_5.Name = "Label_escala_canal_5";
			global::System.Windows.Forms.Control label_escala_canal_12 = this.Label_escala_canal_5;
			size = new size(55, 13);
			label_escala_canal_12.Size = size;
			this.Label_escala_canal_5.TabIndex = (HorizontalAlignment)1;
			this.Label_escala_canal_5.Text = "Canal 05 :";
			this.Label_escala_canal_12.AutoSize = true;
			global::System.Windows.Forms.Control label_escala_canal_13 = this.Label_escala_canal_12;
			location = new location(179, 181);
			label_escala_canal_13.Location = location;
			this.Label_escala_canal_12.Name = "Label_escala_canal_12";
			global::System.Windows.Forms.Control label_escala_canal_14 = this.Label_escala_canal_12;
			size = new size(55, 13);
			label_escala_canal_14.Size = size;
			this.Label_escala_canal_12.TabIndex = (HorizontalAlignment)1;
			this.Label_escala_canal_12.Text = "Canal 12 :";
			this.Label_escala_canal_4.AutoSize = true;
			global::System.Windows.Forms.Control label_escala_canal_15 = this.Label_escala_canal_4;
			location = new location(24, 181);
			label_escala_canal_15.Location = location;
			this.Label_escala_canal_4.Name = "Label_escala_canal_4";
			global::System.Windows.Forms.Control label_escala_canal_16 = this.Label_escala_canal_4;
			size = new size(55, 13);
			label_escala_canal_16.Size = size;
			this.Label_escala_canal_4.TabIndex = (HorizontalAlignment)1;
			this.Label_escala_canal_4.Text = "Canal 04 :";
			this.Label_escala_canal_11.AutoSize = true;
			global::System.Windows.Forms.Control label_escala_canal_17 = this.Label_escala_canal_11;
			location = new location(179, 153);
			label_escala_canal_17.Location = location;
			this.Label_escala_canal_11.Name = "Label_escala_canal_11";
			global::System.Windows.Forms.Control label_escala_canal_18 = this.Label_escala_canal_11;
			size = new size(55, 13);
			label_escala_canal_18.Size = size;
			this.Label_escala_canal_11.TabIndex = (HorizontalAlignment)1;
			this.Label_escala_canal_11.Text = "Canal 11 :";
			this.Label_escala_canal_3.AutoSize = true;
			global::System.Windows.Forms.Control label_escala_canal_19 = this.Label_escala_canal_3;
			location = new location(24, 153);
			label_escala_canal_19.Location = location;
			this.Label_escala_canal_3.Name = "Label_escala_canal_3";
			global::System.Windows.Forms.Control label_escala_canal_20 = this.Label_escala_canal_3;
			size = new size(55, 13);
			label_escala_canal_20.Size = size;
			this.Label_escala_canal_3.TabIndex = (HorizontalAlignment)1;
			this.Label_escala_canal_3.Text = "Canal 03 :";
			this.Label_escala_canal_10.AutoSize = true;
			global::System.Windows.Forms.Control label_escala_canal_21 = this.Label_escala_canal_10;
			location = new location(179, 127);
			label_escala_canal_21.Location = location;
			this.Label_escala_canal_10.Name = "Label_escala_canal_10";
			global::System.Windows.Forms.Control label_escala_canal_22 = this.Label_escala_canal_10;
			size = new size(55, 13);
			label_escala_canal_22.Size = size;
			this.Label_escala_canal_10.TabIndex = (HorizontalAlignment)1;
			this.Label_escala_canal_10.Text = "Canal 10 :";
			this.Label_escala_canal_2.AutoSize = true;
			global::System.Windows.Forms.Control label_escala_canal_23 = this.Label_escala_canal_2;
			location = new location(24, 127);
			label_escala_canal_23.Location = location;
			this.Label_escala_canal_2.Name = "Label_escala_canal_2";
			global::System.Windows.Forms.Control label_escala_canal_24 = this.Label_escala_canal_2;
			size = new size(55, 13);
			label_escala_canal_24.Size = size;
			this.Label_escala_canal_2.TabIndex = (HorizontalAlignment)1;
			this.Label_escala_canal_2.Text = "Canal 02 :";
			this.Label_escala_canal_9.AutoSize = true;
			global::System.Windows.Forms.Control label_escala_canal_25 = this.Label_escala_canal_9;
			location = new location(179, 103);
			label_escala_canal_25.Location = location;
			this.Label_escala_canal_9.Name = "Label_escala_canal_9";
			global::System.Windows.Forms.Control label_escala_canal_26 = this.Label_escala_canal_9;
			size = new size(55, 13);
			label_escala_canal_26.Size = size;
			this.Label_escala_canal_9.TabIndex = (HorizontalAlignment)1;
			this.Label_escala_canal_9.Text = "Canal 09 :";
			this.Label_escala_canal_1.AutoSize = true;
			global::System.Windows.Forms.Control label_escala_canal_27 = this.Label_escala_canal_1;
			location = new location(24, 103);
			label_escala_canal_27.Location = location;
			this.Label_escala_canal_1.Name = "Label_escala_canal_1";
			global::System.Windows.Forms.Control label_escala_canal_28 = this.Label_escala_canal_1;
			size = new size(55, 13);
			label_escala_canal_28.Size = size;
			this.Label_escala_canal_1.TabIndex = (HorizontalAlignment)1;
			this.Label_escala_canal_1.Text = "Canal 01 :";
			this.Label_escala_canal_8.AutoSize = true;
			global::System.Windows.Forms.Control label_escala_canal_29 = this.Label_escala_canal_8;
			location = new location(179, 76);
			label_escala_canal_29.Location = location;
			this.Label_escala_canal_8.Name = "Label_escala_canal_8";
			global::System.Windows.Forms.Control label_escala_canal_30 = this.Label_escala_canal_8;
			size = new size(55, 13);
			label_escala_canal_30.Size = size;
			this.Label_escala_canal_8.TabIndex = (HorizontalAlignment)1;
			this.Label_escala_canal_8.Text = "Canal 08 :";
			this.Label_escala_canal_0.AutoSize = true;
			global::System.Windows.Forms.Control label_escala_canal_31 = this.Label_escala_canal_0;
			location = new location(24, 76);
			label_escala_canal_31.Location = location;
			this.Label_escala_canal_0.Name = "Label_escala_canal_0";
			global::System.Windows.Forms.Control label_escala_canal_32 = this.Label_escala_canal_0;
			size = new size(55, 13);
			label_escala_canal_32.Size = size;
			this.Label_escala_canal_0.TabIndex = (HorizontalAlignment)1;
			this.Label_escala_canal_0.Text = "Canal 00 :";
			global::System.Drawing.SizeF autoScaleDimensions;
			autoScaleDimensions = new global::System.Drawing.SizeF(6f, 13f);
			this.AutoScaleDimensions = autoScaleDimensions;
			this.AutoScaleMode = AutoScaleMode.Font;
			size = new size(359, 558);
			this.ClientSize = size;
			this.Controls.Add(this.Grupo_ctrl);
			this.Controls.Add(this.grupo_escalas);
			this.Controls.Add(this.grupo_parametros_gerais);
			this.FormBorderStyle = FormBorderStyle.None;
			location = new location(160, 2);
			this.Location = location;
			this.Name = "Equip_VA230_conf";
			this.StartPosition = FormStartPosition.Manual;
			this.Text = "Equipamento VA 230 - Configuração";
			this.grupo_parametros_gerais.ResumeLayout(false);
			this.grupo_parametros_gerais.PerformLayout();
			this.Grupo_ctrl.ResumeLayout(false);
			this.Grupo_ctrl.PerformLayout();
			this.grupo_escalas.ResumeLayout(false);
			this.grupo_escalas.PerformLayout();
			this.ResumeLayout(false);
		}

		// Token: 0x04001B25 RID: 6949
		private global::System.ComponentModel.IContainer components;
	}
}
