namespace iS800
{
	// Token: 0x02000080 RID: 128
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class Equip_101_mon : global::System.Windows.Forms.Form
	{
		// Token: 0x06001BAD RID: 7085 RVA: 0x003CAF10 File Offset: 0x003C9310
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			if (disposing && this.components != null)
			{
				this.components.Dispose();
			}
			base.Dispose(disposing);
		}

		// Token: 0x06001BAE RID: 7086 RVA: 0x003CAF30 File Offset: 0x003C9330
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.components = new global::System.ComponentModel.Container();
			this.Grupo_ctrl_com = new global::System.Windows.Forms.GroupBox();
			this.Tela_end_estacao = new global::System.Windows.Forms.NumericUpDown();
			this.Tela_endereco_mestre = new global::System.Windows.Forms.NumericUpDown();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.Label_end_estacao = new global::System.Windows.Forms.Label();
			this.msg = new global::System.Windows.Forms.TextBox();
			this.Comando_hab_monitoracao = new global::System.Windows.Forms.Button();
			this.Grupo_medidas_eng = new global::System.Windows.Forms.GroupBox();
			this.GroupBox1 = new global::System.Windows.Forms.GroupBox();
			this.Label_defeito_sensor = new global::System.Windows.Forms.Label();
			this.Label_arrombamento = new global::System.Windows.Forms.Label();
			this.Label_vazio = new global::System.Windows.Forms.Label();
			this.Label_transbordo = new global::System.Windows.Forms.Label();
			this.Label_em_bat = new global::System.Windows.Forms.Label();
			this.Label_nivel_eng = new global::System.Windows.Forms.Label();
			this.Tela_nivel = new global::System.Windows.Forms.TextBox();
			this.Timer_monitoracao = new global::System.Windows.Forms.Timer(this.components);
			this.Grupo_estatistica = new global::System.Windows.Forms.GroupBox();
			this.Label_Est_retry = new global::System.Windows.Forms.Label();
			this.Est_retry = new global::System.Windows.Forms.TextBox();
			this.Est_eficiencia = new global::System.Windows.Forms.TextBox();
			this.Button_limpa_estatistica = new global::System.Windows.Forms.Button();
			this.Label_Est_RX = new global::System.Windows.Forms.Label();
			this.Label_Est_Eficiencia = new global::System.Windows.Forms.Label();
			this.Label_Est_TX = new global::System.Windows.Forms.Label();
			this.Est_Rx = new global::System.Windows.Forms.TextBox();
			this.Est_TX = new global::System.Windows.Forms.TextBox();
			this.Grupo_ctrl_com.SuspendLayout();
			this.Tela_end_estacao.BeginInit();
			this.Tela_endereco_mestre.BeginInit();
			this.Grupo_medidas_eng.SuspendLayout();
			this.GroupBox1.SuspendLayout();
			this.Grupo_estatistica.SuspendLayout();
			this.SuspendLayout();
			this.Grupo_ctrl_com.Controls.Add(this.Tela_end_estacao);
			this.Grupo_ctrl_com.Controls.Add(this.Tela_endereco_mestre);
			this.Grupo_ctrl_com.Controls.Add(this.Label2);
			this.Grupo_ctrl_com.Controls.Add(this.Label_end_estacao);
			this.Grupo_ctrl_com.Controls.Add(this.msg);
			this.Grupo_ctrl_com.Controls.Add(this.Comando_hab_monitoracao);
			global::System.Windows.Forms.Control grupo_ctrl_com = this.Grupo_ctrl_com;
			global::System.Drawing.Point location;
			location = new global::System.Drawing.Point(22, 12);
			grupo_ctrl_com.Location = location;
			this.Grupo_ctrl_com.Name = "Grupo_ctrl_com";
			global::System.Windows.Forms.Control grupo_ctrl_com2 = this.Grupo_ctrl_com;
			global::System.Drawing.Size size;
			size = new global::System.Drawing.Size(232, 205);
			grupo_ctrl_com2.Size = size;
			this.Grupo_ctrl_com.TabIndex = (HorizontalAlignment)0;
			this.Grupo_ctrl_com.TabStop = false;
			this.Grupo_ctrl_com.Text = "Controle de comunicação";
			global::System.Windows.Forms.Control tela_end_estacao = this.Tela_end_estacao;
			location = new location(129, 78);
			tela_end_estacao.Location = location;
			global::System.Windows.Forms.NumericUpDown tela_end_estacao2 = this.Tela_end_estacao;
			decimal maximum;
			maximum = new decimal(new int[]
			{
				200,
				0,
				0,
				0
			});
			tela_end_estacao2.Maximum = maximum;
			this.Tela_end_estacao.Name = "Tela_end_estacao";
			global::System.Windows.Forms.Control tela_end_estacao3 = this.Tela_end_estacao;
			size = new size(78, 20);
			tela_end_estacao3.Size = size;
			this.Tela_end_estacao.TabIndex = (HorizontalAlignment)9;
			this.Tela_end_estacao.TextAlign = HorizontalAlignment.Right;
			global::System.Windows.Forms.Control tela_endereco_mestre = this.Tela_endereco_mestre;
			location = new location(129, 40);
			tela_endereco_mestre.Location = location;
			global::System.Windows.Forms.NumericUpDown tela_endereco_mestre2 = this.Tela_endereco_mestre;
			maximum = new decimal(new int[]
			{
				200,
				0,
				0,
				0
			});
			tela_endereco_mestre2.Maximum = maximum;
			this.Tela_endereco_mestre.Name = "Tela_endereco_mestre";
			global::System.Windows.Forms.Control tela_endereco_mestre3 = this.Tela_endereco_mestre;
			size = new size(78, 20);
			tela_endereco_mestre3.Size = size;
			this.Tela_endereco_mestre.TabIndex = (HorizontalAlignment)10;
			this.Tela_endereco_mestre.TextAlign = HorizontalAlignment.Right;
			this.Label2.AutoSize = true;
			global::System.Windows.Forms.Control label = this.Label2;
			location = new location(22, 42);
			label.Location = location;
			this.Label2.Name = "Label2";
			global::System.Windows.Forms.Control label2 = this.Label2;
			size = new size(94, 13);
			label2.Size = size;
			this.Label2.TabIndex = (HorizontalAlignment)8;
			this.Label2.Text = "Endereço Mestre :";
			this.Label_end_estacao.AutoSize = true;
			global::System.Windows.Forms.Control label_end_estacao = this.Label_end_estacao;
			location = new location(22, 80);
			label_end_estacao.Location = location;
			this.Label_end_estacao.Name = "Label_end_estacao";
			global::System.Windows.Forms.Control label_end_estacao2 = this.Label_end_estacao;
			size = new size(101, 13);
			label_end_estacao2.Size = size;
			this.Label_end_estacao.TabIndex = (HorizontalAlignment)7;
			this.Label_end_estacao.Text = "Endereço Estação :";
			this.msg.BackColor = global::System.Drawing.Color.Beige;
			global::System.Windows.Forms.Control msg = this.msg;
			location = new location(25, 125);
			msg.Location = location;
			this.msg.Name = "msg";
			this.msg.ReadOnly = true;
			global::System.Windows.Forms.Control msg2 = this.msg;
			size = new size(182, 20);
			msg2.Size = size;
			this.msg.TabIndex = (HorizontalAlignment)3;
			this.msg.TextAlign = HorizontalAlignment.Right;
			global::System.Windows.Forms.Control comando_hab_monitoracao = this.Comando_hab_monitoracao;
			location = new location(25, 162);
			comando_hab_monitoracao.Location = location;
			this.Comando_hab_monitoracao.Name = "Comando_hab_monitoracao";
			global::System.Windows.Forms.Control comando_hab_monitoracao2 = this.Comando_hab_monitoracao;
			size = new size(182, 26);
			comando_hab_monitoracao2.Size = size;
			this.Comando_hab_monitoracao.TabIndex = (HorizontalAlignment)2;
			this.Comando_hab_monitoracao.Text = "Iniciar";
			this.Comando_hab_monitoracao.UseVisualStyleBackColor = true;
			this.Grupo_medidas_eng.Controls.Add(this.GroupBox1);
			this.Grupo_medidas_eng.Controls.Add(this.Label_nivel_eng);
			this.Grupo_medidas_eng.Controls.Add(this.Tela_nivel);
			global::System.Windows.Forms.Control grupo_medidas_eng = this.Grupo_medidas_eng;
			location = new location(275, 12);
			grupo_medidas_eng.Location = location;
			this.Grupo_medidas_eng.Name = "Grupo_medidas_eng";
			global::System.Windows.Forms.Control grupo_medidas_eng2 = this.Grupo_medidas_eng;
			size = new size(350, 205);
			grupo_medidas_eng2.Size = size;
			this.Grupo_medidas_eng.TabIndex = (HorizontalAlignment)1;
			this.Grupo_medidas_eng.TabStop = false;
			this.Grupo_medidas_eng.Text = "Medidas em Unidade de Engenharia e Alarmes";
			this.GroupBox1.Controls.Add(this.Label_defeito_sensor);
			this.GroupBox1.Controls.Add(this.Label_arrombamento);
			this.GroupBox1.Controls.Add(this.Label_vazio);
			this.GroupBox1.Controls.Add(this.Label_transbordo);
			this.GroupBox1.Controls.Add(this.Label_em_bat);
			global::System.Windows.Forms.Control groupBox = this.GroupBox1;
			location = new location(20, 90);
			groupBox.Location = location;
			this.GroupBox1.Name = "GroupBox1";
			global::System.Windows.Forms.Control groupBox2 = this.GroupBox1;
			size = new size(307, 82);
			groupBox2.Size = size;
			this.GroupBox1.TabIndex = (HorizontalAlignment)4;
			this.GroupBox1.TabStop = false;
			this.GroupBox1.Text = "Alarmes";
			this.Label_defeito_sensor.AutoSize = true;
			this.Label_defeito_sensor.BackColor = global::System.Drawing.SystemColors.Control;
			this.Label_defeito_sensor.BorderStyle = (HorizontalAlignment)2;
			global::System.Windows.Forms.Control label_defeito_sensor = this.Label_defeito_sensor;
			location = new location(210, 26);
			label_defeito_sensor.Location = location;
			this.Label_defeito_sensor.Name = "Label_defeito_sensor";
			global::System.Windows.Forms.Control label_defeito_sensor2 = this.Label_defeito_sensor;
			size = new size(75, 15);
			label_defeito_sensor2.Size = size;
			this.Label_defeito_sensor.TabIndex = (HorizontalAlignment)8;
			this.Label_defeito_sensor.Text = " Falha sensor ";
			this.Label_defeito_sensor.TextAlign = ContentAlignment.MiddleRight;
			this.Label_arrombamento.AutoSize = true;
			this.Label_arrombamento.BackColor = global::System.Drawing.SystemColors.Control;
			this.Label_arrombamento.BorderStyle = (HorizontalAlignment)2;
			global::System.Windows.Forms.Control label_arrombamento = this.Label_arrombamento;
			location = new location(26, 51);
			label_arrombamento.Location = location;
			this.Label_arrombamento.Name = "Label_arrombamento";
			global::System.Windows.Forms.Control label_arrombamento2 = this.Label_arrombamento;
			size = new size(77, 15);
			label_arrombamento2.Size = size;
			this.Label_arrombamento.TabIndex = (HorizontalAlignment)7;
			this.Label_arrombamento.Text = "Arrombamento";
			this.Label_vazio.AutoSize = true;
			this.Label_vazio.BackColor = global::System.Drawing.SystemColors.Control;
			this.Label_vazio.BorderStyle = (HorizontalAlignment)2;
			global::System.Windows.Forms.Control label_vazio = this.Label_vazio;
			location = new location(119, 51);
			label_vazio.Location = location;
			this.Label_vazio.Name = "Label_vazio";
			global::System.Windows.Forms.Control label_vazio2 = this.Label_vazio;
			size = new size(77, 15);
			label_vazio2.Size = size;
			this.Label_vazio.TabIndex = (HorizontalAlignment)6;
			this.Label_vazio.Text = "       Vazio       ";
			this.Label_vazio.TextAlign = ContentAlignment.MiddleRight;
			this.Label_transbordo.AutoSize = true;
			this.Label_transbordo.BackColor = global::System.Drawing.SystemColors.Control;
			this.Label_transbordo.BorderStyle = (HorizontalAlignment)2;
			global::System.Windows.Forms.Control label_transbordo = this.Label_transbordo;
			location = new location(118, 26);
			label_transbordo.Location = location;
			this.Label_transbordo.Name = "Label_transbordo";
			global::System.Windows.Forms.Control label_transbordo2 = this.Label_transbordo;
			size = new size(78, 15);
			label_transbordo2.Size = size;
			this.Label_transbordo.TabIndex = (HorizontalAlignment)5;
			this.Label_transbordo.Text = "   Transbordo  ";
			this.Label_em_bat.AutoSize = true;
			this.Label_em_bat.BackColor = global::System.Drawing.Color.Gainsboro;
			this.Label_em_bat.BorderStyle = (HorizontalAlignment)2;
			global::System.Windows.Forms.Control label_em_bat = this.Label_em_bat;
			location = new location(26, 26);
			label_em_bat.Location = location;
			this.Label_em_bat.Name = "Label_em_bat";
			global::System.Windows.Forms.Control label_em_bat2 = this.Label_em_bat;
			size = new size(78, 15);
			label_em_bat2.Size = size;
			this.Label_em_bat.TabIndex = (HorizontalAlignment)4;
			this.Label_em_bat.Text = "   Em Bateria   ";
			this.Label_nivel_eng.AutoSize = true;
			global::System.Windows.Forms.Control label_nivel_eng = this.Label_nivel_eng;
			location = new location(22, 42);
			label_nivel_eng.Location = location;
			this.Label_nivel_eng.Name = "Label_nivel_eng";
			global::System.Windows.Forms.Control label_nivel_eng2 = this.Label_nivel_eng;
			size = new size(56, 13);
			label_nivel_eng2.Size = size;
			this.Label_nivel_eng.TabIndex = (HorizontalAlignment)3;
			this.Label_nivel_eng.Text = "Nível (%) :";
			this.Tela_nivel.BackColor = global::System.Drawing.Color.Beige;
			global::System.Windows.Forms.Control tela_nivel = this.Tela_nivel;
			location = new location(84, 39);
			tela_nivel.Location = location;
			this.Tela_nivel.Name = "Tela_nivel";
			this.Tela_nivel.ReadOnly = true;
			global::System.Windows.Forms.Control tela_nivel2 = this.Tela_nivel;
			size = new size(66, 20);
			tela_nivel2.Size = size;
			this.Tela_nivel.TabIndex = (HorizontalAlignment)1;
			this.Tela_nivel.TabStop = false;
			this.Tela_nivel.TextAlign = HorizontalAlignment.Center;
			this.Timer_monitoracao.Interval = (HorizontalAlignment)3000;
			this.Grupo_estatistica.Controls.Add(this.Label_Est_retry);
			this.Grupo_estatistica.Controls.Add(this.Est_retry);
			this.Grupo_estatistica.Controls.Add(this.Est_eficiencia);
			this.Grupo_estatistica.Controls.Add(this.Button_limpa_estatistica);
			this.Grupo_estatistica.Controls.Add(this.Label_Est_RX);
			this.Grupo_estatistica.Controls.Add(this.Label_Est_Eficiencia);
			this.Grupo_estatistica.Controls.Add(this.Label_Est_TX);
			this.Grupo_estatistica.Controls.Add(this.Est_Rx);
			this.Grupo_estatistica.Controls.Add(this.Est_TX);
			global::System.Windows.Forms.Control grupo_estatistica = this.Grupo_estatistica;
			location = new location(22, 233);
			grupo_estatistica.Location = location;
			this.Grupo_estatistica.Name = "Grupo_estatistica";
			global::System.Windows.Forms.Control grupo_estatistica2 = this.Grupo_estatistica;
			size = new size(603, 59);
			grupo_estatistica2.Size = size;
			this.Grupo_estatistica.TabIndex = (HorizontalAlignment)5;
			this.Grupo_estatistica.TabStop = false;
			this.Grupo_estatistica.Tag = "v";
			this.Grupo_estatistica.Text = "Estatística";
			this.Label_Est_retry.AutoSize = true;
			global::System.Windows.Forms.Control label_Est_retry = this.Label_Est_retry;
			location = new location(213, 26);
			label_Est_retry.Location = location;
			this.Label_Est_retry.Name = "Label_Est_retry";
			global::System.Windows.Forms.Control label_Est_retry2 = this.Label_Est_retry;
			size = new size(63, 13);
			label_Est_retry2.Size = size;
			this.Label_Est_retry.TabIndex = (HorizontalAlignment)10;
			this.Label_Est_retry.Text = "Tentativas :";
			this.Est_retry.BackColor = global::System.Drawing.Color.Beige;
			global::System.Windows.Forms.Control est_retry = this.Est_retry;
			location = new location(281, 23);
			est_retry.Location = location;
			this.Est_retry.Name = "Est_retry";
			this.Est_retry.ReadOnly = true;
			global::System.Windows.Forms.Control est_retry2 = this.Est_retry;
			size = new size(53, 20);
			est_retry2.Size = size;
			this.Est_retry.TabIndex = (HorizontalAlignment)9;
			this.Est_retry.Tag = "c";
			this.Est_retry.TextAlign = HorizontalAlignment.Center;
			this.Est_eficiencia.BackColor = global::System.Drawing.Color.Beige;
			global::System.Windows.Forms.Control est_eficiencia = this.Est_eficiencia;
			location = new location(432, 23);
			est_eficiencia.Location = location;
			this.Est_eficiencia.Name = "Est_eficiencia";
			this.Est_eficiencia.ReadOnly = true;
			global::System.Windows.Forms.Control est_eficiencia2 = this.Est_eficiencia;
			size = new size(53, 20);
			est_eficiencia2.Size = size;
			this.Est_eficiencia.TabIndex = (HorizontalAlignment)5;
			this.Est_eficiencia.Tag = "c";
			this.Est_eficiencia.TextAlign = HorizontalAlignment.Center;
			global::System.Windows.Forms.Control button_limpa_estatistica = this.Button_limpa_estatistica;
			location = new location(498, 19);
			button_limpa_estatistica.Location = location;
			this.Button_limpa_estatistica.Name = "Button_limpa_estatistica";
			global::System.Windows.Forms.Control button_limpa_estatistica2 = this.Button_limpa_estatistica;
			size = new size(90, 26);
			button_limpa_estatistica2.Size = size;
			this.Button_limpa_estatistica.TabIndex = (HorizontalAlignment)8;
			this.Button_limpa_estatistica.Text = "Reiniciar";
			this.Button_limpa_estatistica.UseVisualStyleBackColor = true;
			this.Label_Est_RX.AutoSize = true;
			global::System.Windows.Forms.Control label_Est_RX = this.Label_Est_RX;
			location = new location(120, 26);
			label_Est_RX.Location = location;
			this.Label_Est_RX.Name = "Label_Est_RX";
			global::System.Windows.Forms.Control label_Est_RX2 = this.Label_Est_RX;
			size = new size(28, 13);
			label_Est_RX2.Size = size;
			this.Label_Est_RX.TabIndex = (HorizontalAlignment)7;
			this.Label_Est_RX.Text = "RX :";
			this.Label_Est_Eficiencia.AutoSize = true;
			global::System.Windows.Forms.Control label_Est_Eficiencia = this.Label_Est_Eficiencia;
			location = new location(353, 26);
			label_Est_Eficiencia.Location = location;
			this.Label_Est_Eficiencia.Name = "Label_Est_Eficiencia";
			global::System.Windows.Forms.Control label_Est_Eficiencia2 = this.Label_Est_Eficiencia;
			size = new size(73, 13);
			label_Est_Eficiencia2.Size = size;
			this.Label_Est_Eficiencia.TabIndex = (HorizontalAlignment)7;
			this.Label_Est_Eficiencia.Text = "Eficiência(%) :";
			this.Label_Est_TX.AutoSize = true;
			global::System.Windows.Forms.Control label_Est_TX = this.Label_Est_TX;
			location = new location(17, 26);
			label_Est_TX.Location = location;
			this.Label_Est_TX.Name = "Label_Est_TX";
			global::System.Windows.Forms.Control label_Est_TX2 = this.Label_Est_TX;
			size = new size(27, 13);
			label_Est_TX2.Size = size;
			this.Label_Est_TX.TabIndex = (HorizontalAlignment)6;
			this.Label_Est_TX.Text = "TX :";
			this.Est_Rx.BackColor = global::System.Drawing.Color.Beige;
			global::System.Windows.Forms.Control est_Rx = this.Est_Rx;
			location = new location(154, 23);
			est_Rx.Location = location;
			this.Est_Rx.Name = "Est_Rx";
			this.Est_Rx.ReadOnly = true;
			global::System.Windows.Forms.Control est_Rx2 = this.Est_Rx;
			size = new size(53, 20);
			est_Rx2.Size = size;
			this.Est_Rx.TabIndex = (HorizontalAlignment)5;
			this.Est_Rx.Tag = "c";
			this.Est_Rx.TextAlign = HorizontalAlignment.Center;
			this.Est_TX.BackColor = global::System.Drawing.Color.Beige;
			global::System.Windows.Forms.Control est_TX = this.Est_TX;
			location = new location(50, 23);
			est_TX.Location = location;
			this.Est_TX.Name = "Est_TX";
			this.Est_TX.ReadOnly = true;
			global::System.Windows.Forms.Control est_TX2 = this.Est_TX;
			size = new size(53, 20);
			est_TX2.Size = size;
			this.Est_TX.TabIndex = (HorizontalAlignment)4;
			this.Est_TX.Tag = "c";
			this.Est_TX.TextAlign = HorizontalAlignment.Center;
			global::System.Drawing.SizeF autoScaleDimensions;
			autoScaleDimensions = new global::System.Drawing.SizeF(6f, 13f);
			this.AutoScaleDimensions = autoScaleDimensions;
			this.AutoScaleMode = AutoScaleMode.Font;
			size = new size(645, 304);
			this.ClientSize = size;
			this.Controls.Add(this.Grupo_estatistica);
			this.Controls.Add(this.Grupo_medidas_eng);
			this.Controls.Add(this.Grupo_ctrl_com);
			this.FormBorderStyle = FormBorderStyle.None;
			location = new location(160, 2);
			this.Location = location;
			this.Name = "Equip_101_mon";
			this.StartPosition = FormStartPosition.Manual;
			this.Text = "Equip_101_mon";
			this.Grupo_ctrl_com.ResumeLayout(false);
			this.Grupo_ctrl_com.PerformLayout();
			this.Tela_end_estacao.EndInit();
			this.Tela_endereco_mestre.EndInit();
			this.Grupo_medidas_eng.ResumeLayout(false);
			this.Grupo_medidas_eng.PerformLayout();
			this.GroupBox1.ResumeLayout(false);
			this.GroupBox1.PerformLayout();
			this.Grupo_estatistica.ResumeLayout(false);
			this.Grupo_estatistica.PerformLayout();
			this.ResumeLayout(false);
		}

		// Token: 0x04001510 RID: 5392
		private global::System.ComponentModel.IContainer components;
	}
}
