namespace iS800
{
	// Token: 0x02000044 RID: 68
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class Equip_820_mon : global::System.Windows.Forms.Form
	{
		// Token: 0x06001032 RID: 4146 RVA: 0x0030D5E8 File Offset: 0x0030B9E8
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				if (disposing && this.components != null)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x06001033 RID: 4147 RVA: 0x0030D628 File Offset: 0x0030BA28
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.components = new global::System.ComponentModel.Container();
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::iS800.Equip_820_mon));
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle4 = new global::System.Windows.Forms.DataGridViewCellStyle();
			this.Grupo_ctrl_com = new global::System.Windows.Forms.GroupBox();
			this.pb_hab_monitoracao = new global::System.Windows.Forms.PictureBox();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.bt_end_default = new global::System.Windows.Forms.Button();
			this.msg_modo_operacaoZ = new global::System.Windows.Forms.TextBox();
			this.Tela_endereco_estacao = new global::System.Windows.Forms.NumericUpDown();
			this.Tela_endereco_mestre = new global::System.Windows.Forms.NumericUpDown();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.msg = new global::System.Windows.Forms.TextBox();
			this.Comando_hab_monitoracao = new global::System.Windows.Forms.Button();
			this.Label_end_estacao = new global::System.Windows.Forms.Label();
			this.Timer_monitoracao = new global::System.Windows.Forms.Timer(this.components);
			this.Grupo_setpoints = new global::System.Windows.Forms.GroupBox();
			this.Valor_Niveldesliga = new global::System.Windows.Forms.TextBox();
			this.Label_NivelDesliga = new global::System.Windows.Forms.Label();
			this.Valor_NivelLiga = new global::System.Windows.Forms.TextBox();
			this.Label_NivelLiga = new global::System.Windows.Forms.Label();
			this.Valor_PressaoSuc = new global::System.Windows.Forms.TextBox();
			this.Label_PressaoSuc = new global::System.Windows.Forms.Label();
			this.Valor_PressaoRec = new global::System.Windows.Forms.TextBox();
			this.Label_PressaoRec = new global::System.Windows.Forms.Label();
			this.Valor_TempoMaisUmaBomba = new global::System.Windows.Forms.TextBox();
			this.Label_TempoMaisUmaBomba = new global::System.Windows.Forms.Label();
			this.Valor_NivelB4 = new global::System.Windows.Forms.TextBox();
			this.Label_NivelB4 = new global::System.Windows.Forms.Label();
			this.Valor_NivelB3 = new global::System.Windows.Forms.TextBox();
			this.Label_NivelB3 = new global::System.Windows.Forms.Label();
			this.Valor_NivelB2 = new global::System.Windows.Forms.TextBox();
			this.Label_NivelB2 = new global::System.Windows.Forms.Label();
			this.Valor_NivelB1 = new global::System.Windows.Forms.TextBox();
			this.Label_NivelB1 = new global::System.Windows.Forms.Label();
			this.Valor_NivelDesejado = new global::System.Windows.Forms.TextBox();
			this.Label_NivelDesejado = new global::System.Windows.Forms.Label();
			this.Comando_escreve_setpoint = new global::System.Windows.Forms.Button();
			this.Comando_le_setpoint = new global::System.Windows.Forms.Button();
			this.Grupo_estatistica = new global::System.Windows.Forms.GroupBox();
			this.Label_Est_retry = new global::System.Windows.Forms.Label();
			this.Est_retry = new global::System.Windows.Forms.TextBox();
			this.Est_eficiencia = new global::System.Windows.Forms.TextBox();
			this.Button_limpa_estatistica = new global::System.Windows.Forms.Button();
			this.Label_Est_RX = new global::System.Windows.Forms.Label();
			this.Label_Est_Eficiencia = new global::System.Windows.Forms.Label();
			this.Label_Est_TX = new global::System.Windows.Forms.Label();
			this.Est_Rx = new global::System.Windows.Forms.TextBox();
			this.Est_TX = new global::System.Windows.Forms.TextBox();
			this.Grupo_status = new global::System.Windows.Forms.GroupBox();
			this.dgv_Controle = new global::System.Windows.Forms.DataGridView();
			this.Estado = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.Quadro = new global::System.Windows.Forms.DataGridViewImageColumn();
			this.Controle = new global::System.Windows.Forms.DataGridViewImageColumn();
			this.LD = new global::System.Windows.Forms.DataGridViewImageColumn();
			this.Grupo_escrita_de_dados = new global::System.Windows.Forms.GroupBox();
			this.Tela_nivel_origem = new global::System.Windows.Forms.NumericUpDown();
			this.Label_nivel_origem = new global::System.Windows.Forms.Label();
			this.Tela_nivel_destino = new global::System.Windows.Forms.NumericUpDown();
			this.Label_nivel_destino = new global::System.Windows.Forms.Label();
			this.Cmd_falha_b2 = new global::System.Windows.Forms.Button();
			this.Grupo_medidas = new global::System.Windows.Forms.GroupBox();
			this.dgv_EA = new global::System.Windows.Forms.DataGridView();
			this.Contagens = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.Conv = new global::System.Windows.Forms.DataGridViewCheckBoxColumn();
			this.Inicio = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.Fim = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.Medida = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.GroupBox1 = new global::System.Windows.Forms.GroupBox();
			this.ck_ativa_ref = new global::System.Windows.Forms.CheckBox();
			this.dgv_Referencias = new global::System.Windows.Forms.DataGridView();
			this.Ref = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.GroupBox_ED = new global::System.Windows.Forms.GroupBox();
			this.cb_ED8 = new global::System.Windows.Forms.CheckBox();
			this.cb_ED7 = new global::System.Windows.Forms.CheckBox();
			this.cb_ED6 = new global::System.Windows.Forms.CheckBox();
			this.cb_ED5 = new global::System.Windows.Forms.CheckBox();
			this.cb_ED4 = new global::System.Windows.Forms.CheckBox();
			this.cb_ED3 = new global::System.Windows.Forms.CheckBox();
			this.cb_ED2 = new global::System.Windows.Forms.CheckBox();
			this.cb_ED1 = new global::System.Windows.Forms.CheckBox();
			this.GroupBox_Alarmes = new global::System.Windows.Forms.GroupBox();
			this.pb_bit0 = new global::System.Windows.Forms.PictureBox();
			this.pb_bit1 = new global::System.Windows.Forms.PictureBox();
			this.pb_bit5 = new global::System.Windows.Forms.PictureBox();
			this.pb_bit2 = new global::System.Windows.Forms.PictureBox();
			this.pb_bit4 = new global::System.Windows.Forms.PictureBox();
			this.pb_bit3 = new global::System.Windows.Forms.PictureBox();
			this.gb_ajuste = new global::System.Windows.Forms.GroupBox();
			this.bt_rel_escrita = new global::System.Windows.Forms.Button();
			this.bt_rel_leitura = new global::System.Windows.Forms.Button();
			this.gb_SA = new global::System.Windows.Forms.GroupBox();
			this.ck_ativa_sa = new global::System.Windows.Forms.CheckBox();
			this.dgv_SA = new global::System.Windows.Forms.DataGridView();
			this.DataGridViewTextBoxColumn1 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.Grupo_ctrl_com.SuspendLayout();
			this.pb_hab_monitoracao.BeginInit();
			this.Tela_endereco_estacao.BeginInit();
			this.Tela_endereco_mestre.BeginInit();
			this.Grupo_setpoints.SuspendLayout();
			this.Grupo_estatistica.SuspendLayout();
			this.Grupo_status.SuspendLayout();
			this.dgv_Controle.BeginInit();
			this.Grupo_escrita_de_dados.SuspendLayout();
			this.Tela_nivel_origem.BeginInit();
			this.Tela_nivel_destino.BeginInit();
			this.Grupo_medidas.SuspendLayout();
			this.dgv_EA.BeginInit();
			this.GroupBox1.SuspendLayout();
			this.dgv_Referencias.BeginInit();
			this.GroupBox_ED.SuspendLayout();
			this.GroupBox_Alarmes.SuspendLayout();
			this.pb_bit0.BeginInit();
			this.pb_bit1.BeginInit();
			this.pb_bit5.BeginInit();
			this.pb_bit2.BeginInit();
			this.pb_bit4.BeginInit();
			this.pb_bit3.BeginInit();
			this.gb_ajuste.SuspendLayout();
			this.gb_SA.SuspendLayout();
			this.dgv_SA.BeginInit();
			this.SuspendLayout();
			this.Grupo_ctrl_com.Controls.Add(this.pb_hab_monitoracao);
			this.Grupo_ctrl_com.Controls.Add(this.Label1);
			this.Grupo_ctrl_com.Controls.Add(this.bt_end_default);
			this.Grupo_ctrl_com.Controls.Add(this.msg_modo_operacaoZ);
			this.Grupo_ctrl_com.Controls.Add(this.Tela_endereco_estacao);
			this.Grupo_ctrl_com.Controls.Add(this.Tela_endereco_mestre);
			this.Grupo_ctrl_com.Controls.Add(this.Label2);
			this.Grupo_ctrl_com.Controls.Add(this.msg);
			this.Grupo_ctrl_com.Controls.Add(this.Comando_hab_monitoracao);
			this.Grupo_ctrl_com.Controls.Add(this.Label_end_estacao);
			global::System.Windows.Forms.Control grupo_ctrl_com = this.Grupo_ctrl_com;
			global::System.Drawing.Point location;
			location = new global::System.Drawing.Point(26, 27);
			grupo_ctrl_com.Location = location;
			this.Grupo_ctrl_com.Name = "Grupo_ctrl_com";
			global::System.Windows.Forms.Control grupo_ctrl_com2 = this.Grupo_ctrl_com;
			global::System.Drawing.Size size;
			size = new global::System.Drawing.Size(551, 176);
			grupo_ctrl_com2.Size = size;
			this.Grupo_ctrl_com.TabIndex = (HorizontalAlignment)1;
			this.Grupo_ctrl_com.TabStop = false;
			this.Grupo_ctrl_com.Text = "Controle de Monitoração";
			this.pb_hab_monitoracao.BackColor = global::System.Drawing.Color.Transparent;
			this.pb_hab_monitoracao.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("pb_hab_monitoracao.Image");
			this.pb_hab_monitoracao.InitialImage = global::iS800.My.Resources.Resources.start_button;
			global::System.Windows.Forms.Control pb_hab_monitoracao = this.pb_hab_monitoracao;
			location = new location(393, 36);
			pb_hab_monitoracao.Location = location;
			this.pb_hab_monitoracao.Name = "pb_hab_monitoracao";
			global::System.Windows.Forms.Control pb_hab_monitoracao2 = this.pb_hab_monitoracao;
			size = new size(140, 118);
			pb_hab_monitoracao2.Size = size;
			this.pb_hab_monitoracao.SizeMode =(System.Windows.Forms.PictureBoxSizeMode)1;
			this.pb_hab_monitoracao.TabIndex = (HorizontalAlignment)11;
			this.pb_hab_monitoracao.TabStop = false;
			this.Label1.AutoSize = true;
			global::System.Windows.Forms.Control label = this.Label1;
			location = new location(14, 76);
			label.Location = location;
			this.Label1.Name = "Label1";
			global::System.Windows.Forms.Control label2 = this.Label1;
			size = new size(62, 13);
			label2.Size = size;
			this.Label1.TabIndex = (HorizontalAlignment)9;
			this.Label1.Text = "Mensagem:";
			global::System.Windows.Forms.Control bt_end_default = this.bt_end_default;
			location = new location(240, 32);
			bt_end_default.Location = location;
			this.bt_end_default.Name = "bt_end_default";
			global::System.Windows.Forms.Control bt_end_default2 = this.bt_end_default;
			size = new size(111, 26);
			bt_end_default2.Size = size;
			this.bt_end_default.TabIndex = (HorizontalAlignment)2;
			this.bt_end_default.Text = "Endereço Default";
			this.bt_end_default.UseVisualStyleBackColor = true;
			this.msg_modo_operacaoZ.BackColor = global::System.Drawing.Color.White;
			this.msg_modo_operacaoZ.ForeColor = global::System.Drawing.SystemColors.WindowText;
			global::System.Windows.Forms.Control msg_modo_operacaoZ = this.msg_modo_operacaoZ;
			location = new location(15, 143);
			msg_modo_operacaoZ.Location = location;
			this.msg_modo_operacaoZ.Multiline = true;
			this.msg_modo_operacaoZ.Name = "msg_modo_operacaoZ";
			this.msg_modo_operacaoZ.ReadOnly = true;
			global::System.Windows.Forms.Control msg_modo_operacaoZ2 = this.msg_modo_operacaoZ;
			size = new size(202, 19);
			msg_modo_operacaoZ2.Size = size;
			this.msg_modo_operacaoZ.TabIndex = (HorizontalAlignment)7;
			this.msg_modo_operacaoZ.TabStop = false;
			this.msg_modo_operacaoZ.TextAlign = HorizontalAlignment.Right;
			global::System.Windows.Forms.Control tela_endereco_estacao = this.Tela_endereco_estacao;
			location = new location(114, 50);
			tela_endereco_estacao.Location = location;
			global::System.Windows.Forms.NumericUpDown tela_endereco_estacao2 = this.Tela_endereco_estacao;
			decimal maximum;
			maximum = new decimal(new int[]
			{
				200,
				0,
				0,
				0
			});
			tela_endereco_estacao2.Maximum = maximum;
			this.Tela_endereco_estacao.Name = "Tela_endereco_estacao";
			global::System.Windows.Forms.Control tela_endereco_estacao3 = this.Tela_endereco_estacao;
			size = new size(93, 20);
			tela_endereco_estacao3.Size = size;
			this.Tela_endereco_estacao.TabIndex = (HorizontalAlignment)1;
			this.Tela_endereco_estacao.TextAlign = HorizontalAlignment.Right;
			global::System.Windows.Forms.Control tela_endereco_mestre = this.Tela_endereco_mestre;
			location = new location(114, 22);
			tela_endereco_mestre.Location = location;
			global::System.Windows.Forms.NumericUpDown tela_endereco_mestre2 = this.Tela_endereco_mestre;
			maximum = new decimal(new int[]
			{
				200,
				0,
				0,
				0
			});
			tela_endereco_mestre2.Maximum = maximum;
			this.Tela_endereco_mestre.Name = "Tela_endereco_mestre";
			global::System.Windows.Forms.Control tela_endereco_mestre3 = this.Tela_endereco_mestre;
			size = new size(93, 20);
			tela_endereco_mestre3.Size = size;
			this.Tela_endereco_mestre.TabIndex = (HorizontalAlignment)0;
			this.Tela_endereco_mestre.TextAlign = HorizontalAlignment.Right;
			this.Label2.AutoSize = true;
			global::System.Windows.Forms.Control label3 = this.Label2;
			location = new location(14, 24);
			label3.Location = location;
			this.Label2.Name = "Label2";
			global::System.Windows.Forms.Control label4 = this.Label2;
			size = new size(91, 13);
			label4.Size = size;
			this.Label2.TabIndex = (HorizontalAlignment)3;
			this.Label2.Text = "Endereço Mestre:";
			this.msg.BackColor = global::System.Drawing.Color.White;
			this.msg.ForeColor = global::System.Drawing.SystemColors.WindowText;
			global::System.Windows.Forms.Control msg = this.msg;
			location = new location(15, 93);
			msg.Location = location;
			this.msg.Multiline = true;
			this.msg.Name = "msg";
			this.msg.ReadOnly = true;
			global::System.Windows.Forms.Control msg2 = this.msg;
			size = new size(336, 30);
			msg2.Size = size;
			this.msg.TabIndex = (HorizontalAlignment)1;
			this.msg.TabStop = false;
			this.msg.TextAlign = HorizontalAlignment.Right;
			global::System.Windows.Forms.Control comando_hab_monitoracao = this.Comando_hab_monitoracao;
			location = new location(269, 136);
			comando_hab_monitoracao.Location = location;
			this.Comando_hab_monitoracao.Name = "Comando_hab_monitoracao";
			global::System.Windows.Forms.Control comando_hab_monitoracao2 = this.Comando_hab_monitoracao;
			size = new size(82, 26);
			comando_hab_monitoracao2.Size = size;
			this.Comando_hab_monitoracao.TabIndex = (HorizontalAlignment)3;
			this.Comando_hab_monitoracao.Text = "Iniciar";
			this.Comando_hab_monitoracao.UseVisualStyleBackColor = true;
			this.Comando_hab_monitoracao.Visible = false;
			this.Label_end_estacao.AutoSize = true;
			global::System.Windows.Forms.Control label_end_estacao = this.Label_end_estacao;
			location = new location(14, 52);
			label_end_estacao.Location = location;
			this.Label_end_estacao.Name = "Label_end_estacao";
			global::System.Windows.Forms.Control label_end_estacao2 = this.Label_end_estacao;
			size = new size(98, 13);
			label_end_estacao2.Size = size;
			this.Label_end_estacao.TabIndex = (HorizontalAlignment)0;
			this.Label_end_estacao.Text = "Endereço Estação:";
			this.Timer_monitoracao.Interval = (HorizontalAlignment)1000;
			this.Grupo_setpoints.Controls.Add(this.Valor_Niveldesliga);
			this.Grupo_setpoints.Controls.Add(this.Label_NivelDesliga);
			this.Grupo_setpoints.Controls.Add(this.Valor_NivelLiga);
			this.Grupo_setpoints.Controls.Add(this.Label_NivelLiga);
			this.Grupo_setpoints.Controls.Add(this.Valor_PressaoSuc);
			this.Grupo_setpoints.Controls.Add(this.Label_PressaoSuc);
			this.Grupo_setpoints.Controls.Add(this.Valor_PressaoRec);
			this.Grupo_setpoints.Controls.Add(this.Label_PressaoRec);
			this.Grupo_setpoints.Controls.Add(this.Valor_TempoMaisUmaBomba);
			this.Grupo_setpoints.Controls.Add(this.Label_TempoMaisUmaBomba);
			this.Grupo_setpoints.Controls.Add(this.Valor_NivelB4);
			this.Grupo_setpoints.Controls.Add(this.Label_NivelB4);
			this.Grupo_setpoints.Controls.Add(this.Valor_NivelB3);
			this.Grupo_setpoints.Controls.Add(this.Label_NivelB3);
			this.Grupo_setpoints.Controls.Add(this.Valor_NivelB2);
			this.Grupo_setpoints.Controls.Add(this.Label_NivelB2);
			this.Grupo_setpoints.Controls.Add(this.Valor_NivelB1);
			this.Grupo_setpoints.Controls.Add(this.Label_NivelB1);
			this.Grupo_setpoints.Controls.Add(this.Valor_NivelDesejado);
			this.Grupo_setpoints.Controls.Add(this.Label_NivelDesejado);
			this.Grupo_setpoints.Controls.Add(this.Comando_escreve_setpoint);
			this.Grupo_setpoints.Controls.Add(this.Comando_le_setpoint);
			this.Grupo_setpoints.Enabled = false;
			global::System.Windows.Forms.Control grupo_setpoints = this.Grupo_setpoints;
			location = new location(189, 365);
			grupo_setpoints.Location = location;
			this.Grupo_setpoints.Name = "Grupo_setpoints";
			global::System.Windows.Forms.Control grupo_setpoints2 = this.Grupo_setpoints;
			size = new size(128, 207);
			grupo_setpoints2.Size = size;
			this.Grupo_setpoints.TabIndex = (HorizontalAlignment)4;
			this.Grupo_setpoints.TabStop = false;
			this.Grupo_setpoints.Text = "Setpoints";
			this.Grupo_setpoints.Visible = false;
			this.Valor_Niveldesliga.BackColor = global::System.Drawing.SystemColors.ButtonHighlight;
			global::System.Windows.Forms.Control valor_Niveldesliga = this.Valor_Niveldesliga;
			location = new location(325, 79);
			valor_Niveldesliga.Location = location;
			this.Valor_Niveldesliga.Name = "Valor_Niveldesliga";
			global::System.Windows.Forms.Control valor_Niveldesliga2 = this.Valor_Niveldesliga;
			size = new size(45, 20);
			valor_Niveldesliga2.Size = size;
			this.Valor_Niveldesliga.TabIndex = (HorizontalAlignment)24;
			this.Valor_Niveldesliga.TextAlign = HorizontalAlignment.Center;
			this.Label_NivelDesliga.AutoSize = true;
			global::System.Windows.Forms.Control label_NivelDesliga = this.Label_NivelDesliga;
			location = new location(170, 82);
			label_NivelDesliga.Location = location;
			this.Label_NivelDesliga.Name = "Label_NivelDesliga";
			global::System.Windows.Forms.Control label_NivelDesliga2 = this.Label_NivelDesliga;
			size = new size(152, 13);
			label_NivelDesliga2.Size = size;
			this.Label_NivelDesliga.TabIndex = (HorizontalAlignment)23;
			this.Label_NivelDesliga.Text = "Proteção - Nível Bloqueio (%) :";
			this.Valor_NivelLiga.BackColor = global::System.Drawing.SystemColors.ButtonHighlight;
			global::System.Windows.Forms.Control valor_NivelLiga = this.Valor_NivelLiga;
			location = new location(325, 107);
			valor_NivelLiga.Location = location;
			this.Valor_NivelLiga.Name = "Valor_NivelLiga";
			global::System.Windows.Forms.Control valor_NivelLiga2 = this.Valor_NivelLiga;
			size = new size(45, 20);
			valor_NivelLiga2.Size = size;
			this.Valor_NivelLiga.TabIndex = (HorizontalAlignment)22;
			this.Valor_NivelLiga.TextAlign = HorizontalAlignment.Center;
			this.Label_NivelLiga.AutoSize = true;
			global::System.Windows.Forms.Control label_NivelLiga = this.Label_NivelLiga;
			location = new location(170, 110);
			label_NivelLiga.Location = location;
			this.Label_NivelLiga.Name = "Label_NivelLiga";
			global::System.Windows.Forms.Control label_NivelLiga2 = this.Label_NivelLiga;
			size = new size(158, 13);
			label_NivelLiga2.Size = size;
			this.Label_NivelLiga.TabIndex = (HorizontalAlignment)21;
			this.Label_NivelLiga.Text = "Proteção - Nível Liberação (%) :";
			this.Valor_PressaoSuc.BackColor = global::System.Drawing.SystemColors.ButtonHighlight;
			global::System.Windows.Forms.Control valor_PressaoSuc = this.Valor_PressaoSuc;
			location = new location(326, 51);
			valor_PressaoSuc.Location = location;
			this.Valor_PressaoSuc.Name = "Valor_PressaoSuc";
			global::System.Windows.Forms.Control valor_PressaoSuc2 = this.Valor_PressaoSuc;
			size = new size(45, 20);
			valor_PressaoSuc2.Size = size;
			this.Valor_PressaoSuc.TabIndex = (HorizontalAlignment)20;
			this.Valor_PressaoSuc.TextAlign = HorizontalAlignment.Center;
			this.Label_PressaoSuc.AutoSize = true;
			global::System.Windows.Forms.Control label_PressaoSuc = this.Label_PressaoSuc;
			location = new location(170, 54);
			label_PressaoSuc.Location = location;
			this.Label_PressaoSuc.Name = "Label_PressaoSuc";
			global::System.Windows.Forms.Control label_PressaoSuc2 = this.Label_PressaoSuc;
			size = new size(108, 13);
			label_PressaoSuc2.Size = size;
			this.Label_PressaoSuc.TabIndex = (HorizontalAlignment)19;
			this.Label_PressaoSuc.Text = "Pressao Sucção (%) :";
			this.Valor_PressaoRec.BackColor = global::System.Drawing.SystemColors.ButtonHighlight;
			global::System.Windows.Forms.Control valor_PressaoRec = this.Valor_PressaoRec;
			location = new location(326, 23);
			valor_PressaoRec.Location = location;
			this.Valor_PressaoRec.Name = "Valor_PressaoRec";
			global::System.Windows.Forms.Control valor_PressaoRec2 = this.Valor_PressaoRec;
			size = new size(45, 20);
			valor_PressaoRec2.Size = size;
			this.Valor_PressaoRec.TabIndex = (HorizontalAlignment)18;
			this.Valor_PressaoRec.TextAlign = HorizontalAlignment.Center;
			this.Label_PressaoRec.AutoSize = true;
			global::System.Windows.Forms.Control label_PressaoRec = this.Label_PressaoRec;
			location = new location(170, 26);
			label_PressaoRec.Location = location;
			this.Label_PressaoRec.Name = "Label_PressaoRec";
			global::System.Windows.Forms.Control label_PressaoRec2 = this.Label_PressaoRec;
			size = new size(117, 13);
			label_PressaoRec2.Size = size;
			this.Label_PressaoRec.TabIndex = (HorizontalAlignment)17;
			this.Label_PressaoRec.Text = "Pressao Recalque (%) :";
			this.Valor_TempoMaisUmaBomba.BackColor = global::System.Drawing.SystemColors.ButtonHighlight;
			global::System.Windows.Forms.Control valor_TempoMaisUmaBomba = this.Valor_TempoMaisUmaBomba;
			location = new location(115, 163);
			valor_TempoMaisUmaBomba.Location = location;
			this.Valor_TempoMaisUmaBomba.Name = "Valor_TempoMaisUmaBomba";
			global::System.Windows.Forms.Control valor_TempoMaisUmaBomba2 = this.Valor_TempoMaisUmaBomba;
			size = new size(45, 20);
			valor_TempoMaisUmaBomba2.Size = size;
			this.Valor_TempoMaisUmaBomba.TabIndex = (HorizontalAlignment)16;
			this.Valor_TempoMaisUmaBomba.TextAlign = HorizontalAlignment.Center;
			this.Label_TempoMaisUmaBomba.AutoSize = true;
			global::System.Windows.Forms.Control label_TempoMaisUmaBomba = this.Label_TempoMaisUmaBomba;
			location = new location(10, 166);
			label_TempoMaisUmaBomba.Location = location;
			this.Label_TempoMaisUmaBomba.Name = "Label_TempoMaisUmaBomba";
			global::System.Windows.Forms.Control label_TempoMaisUmaBomba2 = this.Label_TempoMaisUmaBomba;
			size = new size(99, 13);
			label_TempoMaisUmaBomba2.Size = size;
			this.Label_TempoMaisUmaBomba.TabIndex = (HorizontalAlignment)15;
			this.Label_TempoMaisUmaBomba.Text = "Tempo + 1 B (min) :";
			this.Valor_NivelB4.BackColor = global::System.Drawing.SystemColors.ButtonHighlight;
			global::System.Windows.Forms.Control valor_NivelB = this.Valor_NivelB4;
			location = new location(115, 135);
			valor_NivelB.Location = location;
			this.Valor_NivelB4.Name = "Valor_NivelB4";
			global::System.Windows.Forms.Control valor_NivelB2 = this.Valor_NivelB4;
			size = new size(45, 20);
			valor_NivelB2.Size = size;
			this.Valor_NivelB4.TabIndex = (HorizontalAlignment)14;
			this.Valor_NivelB4.TextAlign = HorizontalAlignment.Center;
			this.Label_NivelB4.AutoSize = true;
			global::System.Windows.Forms.Control label_NivelB = this.Label_NivelB4;
			location = new location(10, 138);
			label_NivelB.Location = location;
			this.Label_NivelB4.Name = "Label_NivelB4";
			global::System.Windows.Forms.Control label_NivelB2 = this.Label_NivelB4;
			size = new size(72, 13);
			label_NivelB2.Size = size;
			this.Label_NivelB4.TabIndex = (HorizontalAlignment)13;
			this.Label_NivelB4.Text = "Nível B4 (%) :";
			this.Valor_NivelB3.BackColor = global::System.Drawing.SystemColors.ButtonHighlight;
			global::System.Windows.Forms.Control valor_NivelB3 = this.Valor_NivelB3;
			location = new location(115, 107);
			valor_NivelB3.Location = location;
			this.Valor_NivelB3.Name = "Valor_NivelB3";
			global::System.Windows.Forms.Control valor_NivelB4 = this.Valor_NivelB3;
			size = new size(45, 20);
			valor_NivelB4.Size = size;
			this.Valor_NivelB3.TabIndex = (HorizontalAlignment)12;
			this.Valor_NivelB3.TextAlign = HorizontalAlignment.Center;
			this.Label_NivelB3.AutoSize = true;
			global::System.Windows.Forms.Control label_NivelB3 = this.Label_NivelB3;
			location = new location(10, 110);
			label_NivelB3.Location = location;
			this.Label_NivelB3.Name = "Label_NivelB3";
			global::System.Windows.Forms.Control label_NivelB4 = this.Label_NivelB3;
			size = new size(72, 13);
			label_NivelB4.Size = size;
			this.Label_NivelB3.TabIndex = (HorizontalAlignment)11;
			this.Label_NivelB3.Text = "Nível B3 (%) :";
			this.Valor_NivelB2.BackColor = global::System.Drawing.SystemColors.ButtonHighlight;
			global::System.Windows.Forms.Control valor_NivelB5 = this.Valor_NivelB2;
			location = new location(115, 79);
			valor_NivelB5.Location = location;
			this.Valor_NivelB2.Name = "Valor_NivelB2";
			global::System.Windows.Forms.Control valor_NivelB6 = this.Valor_NivelB2;
			size = new size(45, 20);
			valor_NivelB6.Size = size;
			this.Valor_NivelB2.TabIndex = (HorizontalAlignment)10;
			this.Valor_NivelB2.TextAlign = HorizontalAlignment.Center;
			this.Label_NivelB2.AutoSize = true;
			global::System.Windows.Forms.Control label_NivelB5 = this.Label_NivelB2;
			location = new location(10, 82);
			label_NivelB5.Location = location;
			this.Label_NivelB2.Name = "Label_NivelB2";
			global::System.Windows.Forms.Control label_NivelB6 = this.Label_NivelB2;
			size = new size(72, 13);
			label_NivelB6.Size = size;
			this.Label_NivelB2.TabIndex = (HorizontalAlignment)9;
			this.Label_NivelB2.Text = "Nível B2 (%) :";
			this.Valor_NivelB1.BackColor = global::System.Drawing.SystemColors.ButtonHighlight;
			global::System.Windows.Forms.Control valor_NivelB7 = this.Valor_NivelB1;
			location = new location(115, 51);
			valor_NivelB7.Location = location;
			this.Valor_NivelB1.Name = "Valor_NivelB1";
			global::System.Windows.Forms.Control valor_NivelB8 = this.Valor_NivelB1;
			size = new size(45, 20);
			valor_NivelB8.Size = size;
			this.Valor_NivelB1.TabIndex = (HorizontalAlignment)8;
			this.Valor_NivelB1.TextAlign = HorizontalAlignment.Center;
			this.Label_NivelB1.AutoSize = true;
			global::System.Windows.Forms.Control label_NivelB7 = this.Label_NivelB1;
			location = new location(10, 54);
			label_NivelB7.Location = location;
			this.Label_NivelB1.Name = "Label_NivelB1";
			global::System.Windows.Forms.Control label_NivelB8 = this.Label_NivelB1;
			size = new size(72, 13);
			label_NivelB8.Size = size;
			this.Label_NivelB1.TabIndex = (HorizontalAlignment)7;
			this.Label_NivelB1.Text = "Nível B1 (%) :";
			this.Valor_NivelDesejado.BackColor = global::System.Drawing.SystemColors.ButtonHighlight;
			global::System.Windows.Forms.Control valor_NivelDesejado = this.Valor_NivelDesejado;
			location = new location(115, 23);
			valor_NivelDesejado.Location = location;
			this.Valor_NivelDesejado.Name = "Valor_NivelDesejado";
			global::System.Windows.Forms.Control valor_NivelDesejado2 = this.Valor_NivelDesejado;
			size = new size(45, 20);
			valor_NivelDesejado2.Size = size;
			this.Valor_NivelDesejado.TabIndex = (HorizontalAlignment)6;
			this.Valor_NivelDesejado.TextAlign = HorizontalAlignment.Center;
			this.Label_NivelDesejado.AutoSize = true;
			global::System.Windows.Forms.Control label_NivelDesejado = this.Label_NivelDesejado;
			location = new location(10, 26);
			label_NivelDesejado.Location = location;
			this.Label_NivelDesejado.Name = "Label_NivelDesejado";
			global::System.Windows.Forms.Control label_NivelDesejado2 = this.Label_NivelDesejado;
			size = new size(104, 13);
			label_NivelDesejado2.Size = size;
			this.Label_NivelDesejado.TabIndex = (HorizontalAlignment)5;
			this.Label_NivelDesejado.Text = "Nível Desejado (%) :";
			global::System.Windows.Forms.Control comando_escreve_setpoint = this.Comando_escreve_setpoint;
			location = new location(297, 151);
			comando_escreve_setpoint.Location = location;
			this.Comando_escreve_setpoint.Name = "Comando_escreve_setpoint";
			global::System.Windows.Forms.Control comando_escreve_setpoint2 = this.Comando_escreve_setpoint;
			size = new size(69, 26);
			comando_escreve_setpoint2.Size = size;
			this.Comando_escreve_setpoint.TabIndex = (HorizontalAlignment)4;
			this.Comando_escreve_setpoint.Text = "Escrever";
			this.Comando_escreve_setpoint.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control comando_le_setpoint = this.Comando_le_setpoint;
			location = new location(179, 151);
			comando_le_setpoint.Location = location;
			this.Comando_le_setpoint.Name = "Comando_le_setpoint";
			global::System.Windows.Forms.Control comando_le_setpoint2 = this.Comando_le_setpoint;
			size = new size(105, 26);
			comando_le_setpoint2.Size = size;
			this.Comando_le_setpoint.TabIndex = (HorizontalAlignment)3;
			this.Comando_le_setpoint.Text = "Ler";
			this.Comando_le_setpoint.UseVisualStyleBackColor = true;
			this.Grupo_estatistica.Controls.Add(this.Label_Est_retry);
			this.Grupo_estatistica.Controls.Add(this.Est_retry);
			this.Grupo_estatistica.Controls.Add(this.Est_eficiencia);
			this.Grupo_estatistica.Controls.Add(this.Button_limpa_estatistica);
			this.Grupo_estatistica.Controls.Add(this.Label_Est_RX);
			this.Grupo_estatistica.Controls.Add(this.Label_Est_Eficiencia);
			this.Grupo_estatistica.Controls.Add(this.Label_Est_TX);
			this.Grupo_estatistica.Controls.Add(this.Est_Rx);
			this.Grupo_estatistica.Controls.Add(this.Est_TX);
			global::System.Windows.Forms.Control grupo_estatistica = this.Grupo_estatistica;
			location = new location(698, 38);
			grupo_estatistica.Location = location;
			this.Grupo_estatistica.Name = "Grupo_estatistica";
			global::System.Windows.Forms.Control grupo_estatistica2 = this.Grupo_estatistica;
			size = new size(328, 112);
			grupo_estatistica2.Size = size;
			this.Grupo_estatistica.TabIndex = (HorizontalAlignment)5;
			this.Grupo_estatistica.TabStop = false;
			this.Grupo_estatistica.Tag = "v";
			this.Grupo_estatistica.Text = "Estatística de comunicação";
			this.Label_Est_retry.AutoSize = true;
			global::System.Windows.Forms.Control label_Est_retry = this.Label_Est_retry;
			location = new location(6, 83);
			label_Est_retry.Location = location;
			this.Label_Est_retry.Name = "Label_Est_retry";
			global::System.Windows.Forms.Control label_Est_retry2 = this.Label_Est_retry;
			size = new size(70, 13);
			label_Est_retry2.Size = size;
			this.Label_Est_retry.TabIndex = (HorizontalAlignment)10;
			this.Label_Est_retry.Text = "Retentativas:";
			this.Est_retry.BackColor = global::System.Drawing.Color.White;
			this.Est_retry.ForeColor = global::System.Drawing.Color.DarkRed;
			global::System.Windows.Forms.Control est_retry = this.Est_retry;
			location = new location(85, 80);
			est_retry.Location = location;
			this.Est_retry.Name = "Est_retry";
			this.Est_retry.ReadOnly = true;
			global::System.Windows.Forms.Control est_retry2 = this.Est_retry;
			size = new size(58, 20);
			est_retry2.Size = size;
			this.Est_retry.TabIndex = (HorizontalAlignment)9;
			this.Est_retry.Tag = "c";
			this.Est_retry.TextAlign = HorizontalAlignment.Center;
			this.Est_eficiencia.BackColor = global::System.Drawing.Color.White;
			this.Est_eficiencia.ForeColor = global::System.Drawing.SystemColors.MenuHighlight;
			global::System.Windows.Forms.Control est_eficiencia = this.Est_eficiencia;
			location = new location(261, 22);
			est_eficiencia.Location = location;
			this.Est_eficiencia.Name = "Est_eficiencia";
			this.Est_eficiencia.ReadOnly = true;
			global::System.Windows.Forms.Control est_eficiencia2 = this.Est_eficiencia;
			size = new size(58, 20);
			est_eficiencia2.Size = size;
			this.Est_eficiencia.TabIndex = (HorizontalAlignment)5;
			this.Est_eficiencia.Tag = "c";
			this.Est_eficiencia.TextAlign = HorizontalAlignment.Center;
			global::System.Windows.Forms.Control button_limpa_estatistica = this.Button_limpa_estatistica;
			location = new location(175, 75);
			button_limpa_estatistica.Location = location;
			this.Button_limpa_estatistica.Name = "Button_limpa_estatistica";
			global::System.Windows.Forms.Control button_limpa_estatistica2 = this.Button_limpa_estatistica;
			size = new size(144, 25);
			button_limpa_estatistica2.Size = size;
			this.Button_limpa_estatistica.TabIndex = (HorizontalAlignment)8;
			this.Button_limpa_estatistica.Text = "Reset Contadores";
			this.Button_limpa_estatistica.UseVisualStyleBackColor = true;
			this.Label_Est_RX.AutoSize = true;
			global::System.Windows.Forms.Control label_Est_RX = this.Label_Est_RX;
			location = new location(6, 55);
			label_Est_RX.Location = location;
			this.Label_Est_RX.Name = "Label_Est_RX";
			global::System.Windows.Forms.Control label_Est_RX2 = this.Label_Est_RX;
			size = new size(60, 13);
			label_Est_RX2.Size = size;
			this.Label_Est_RX.TabIndex = (HorizontalAlignment)7;
			this.Label_Est_RX.Text = "Recepção:";
			this.Label_Est_Eficiencia.AutoSize = true;
			global::System.Windows.Forms.Control label_Est_Eficiencia = this.Label_Est_Eficiencia;
			location = new location(175, 25);
			label_Est_Eficiencia.Location = location;
			this.Label_Est_Eficiencia.Name = "Label_Est_Eficiencia";
			global::System.Windows.Forms.Control label_Est_Eficiencia2 = this.Label_Est_Eficiencia;
			size = new size(80, 13);
			label_Est_Eficiencia2.Size = size;
			this.Label_Est_Eficiencia.TabIndex = (HorizontalAlignment)7;
			this.Label_Est_Eficiencia.Text = "Estatística (%) :";
			this.Label_Est_TX.AutoSize = true;
			global::System.Windows.Forms.Control label_Est_TX = this.Label_Est_TX;
			location = new location(5, 25);
			label_Est_TX.Location = location;
			this.Label_Est_TX.Name = "Label_Est_TX";
			global::System.Windows.Forms.Control label_Est_TX2 = this.Label_Est_TX;
			size = new size(69, 13);
			label_Est_TX2.Size = size;
			this.Label_Est_TX.TabIndex = (HorizontalAlignment)6;
			this.Label_Est_TX.Text = "Transmissão:";
			this.Est_Rx.BackColor = global::System.Drawing.Color.White;
			global::System.Windows.Forms.Control est_Rx = this.Est_Rx;
			location = new location(85, 51);
			est_Rx.Location = location;
			this.Est_Rx.Name = "Est_Rx";
			this.Est_Rx.ReadOnly = true;
			global::System.Windows.Forms.Control est_Rx2 = this.Est_Rx;
			size = new size(58, 20);
			est_Rx2.Size = size;
			this.Est_Rx.TabIndex = (HorizontalAlignment)5;
			this.Est_Rx.Tag = "c";
			this.Est_Rx.TextAlign = HorizontalAlignment.Center;
			this.Est_TX.BackColor = global::System.Drawing.Color.White;
			global::System.Windows.Forms.Control est_TX = this.Est_TX;
			location = new location(85, 22);
			est_TX.Location = location;
			this.Est_TX.Name = "Est_TX";
			this.Est_TX.ReadOnly = true;
			global::System.Windows.Forms.Control est_TX2 = this.Est_TX;
			size = new size(58, 20);
			est_TX2.Size = size;
			this.Est_TX.TabIndex = (HorizontalAlignment)4;
			this.Est_TX.Tag = "c";
			this.Est_TX.TextAlign = HorizontalAlignment.Center;
			this.Grupo_status.Controls.Add(this.dgv_Controle);
			this.Grupo_status.Controls.Add(this.Grupo_escrita_de_dados);
			this.Grupo_status.Controls.Add(this.Grupo_setpoints);
			global::System.Windows.Forms.Control grupo_status = this.Grupo_status;
			location = new location(26, 212);
			grupo_status.Location = location;
			this.Grupo_status.Name = "Grupo_status";
			global::System.Windows.Forms.Control grupo_status2 = this.Grupo_status;
			size = new size(362, 578);
			grupo_status2.Size = size;
			this.Grupo_status.TabIndex = (HorizontalAlignment)6;
			this.Grupo_status.TabStop = false;
			this.Grupo_status.Text = "Controles - Comando e Status";
			dataGridViewCellStyle.BackColor = global::System.Drawing.SystemColors.GradientInactiveCaption;
			this.dgv_Controle.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle;
			this.dgv_Controle.ColumnHeadersHeightSizeMode = (HorizontalAlignment)2;
			this.dgv_Controle.Columns.AddRange(new global::System.Windows.Forms.DataGridViewColumn[]
			{
				this.Estado,
				this.Quadro,
				this.Controle,
				this.LD
			});
			global::System.Windows.Forms.Control dgv_Controle = this.dgv_Controle;
			location = new location(6, 19);
			dgv_Controle.Location = location;
			this.dgv_Controle.Name = "dgv_Controle";
			global::System.Windows.Forms.Control dgv_Controle2 = this.dgv_Controle;
			size = new size(345, 553);
			dgv_Controle2.Size = size;
			this.dgv_Controle.TabIndex = (HorizontalAlignment)2;
			this.Estado.HeaderText = "Estado:";
			this.Estado.Name = "Estado";
			this.Estado.ReadOnly = true;
			this.Quadro.FillWeight = 64f;
			this.Quadro.HeaderText = "Local Remoto";
			this.Quadro.Name = "Quadro";
			this.Quadro.ReadOnly = true;
			this.Quadro.Width = (HorizontalAlignment)64;
			this.Controle.HeaderText = "Modo:";
			this.Controle.Name = "Controle";
			this.Controle.ReadOnly = true;
			this.LD.HeaderText = "Liga Desliga:";
			this.LD.Name = "LD";
			this.LD.ReadOnly = true;
			this.Grupo_escrita_de_dados.Controls.Add(this.Tela_nivel_origem);
			this.Grupo_escrita_de_dados.Controls.Add(this.Label_nivel_origem);
			this.Grupo_escrita_de_dados.Controls.Add(this.Tela_nivel_destino);
			this.Grupo_escrita_de_dados.Controls.Add(this.Label_nivel_destino);
			global::System.Windows.Forms.Control grupo_escrita_de_dados = this.Grupo_escrita_de_dados;
			location = new location(17, 420);
			grupo_escrita_de_dados.Location = location;
			this.Grupo_escrita_de_dados.Name = "Grupo_escrita_de_dados";
			global::System.Windows.Forms.Control grupo_escrita_de_dados2 = this.Grupo_escrita_de_dados;
			size = new size(111, 152);
			grupo_escrita_de_dados2.Size = size;
			this.Grupo_escrita_de_dados.TabIndex = (HorizontalAlignment)7;
			this.Grupo_escrita_de_dados.TabStop = false;
			this.Grupo_escrita_de_dados.Text = "Medidas para simulçação de Nível";
			this.Grupo_escrita_de_dados.Visible = false;
			global::System.Windows.Forms.Control tela_nivel_origem = this.Tela_nivel_origem;
			location = new location(18, 59);
			tela_nivel_origem.Location = location;
			this.Tela_nivel_origem.Name = "Tela_nivel_origem";
			global::System.Windows.Forms.Control tela_nivel_origem2 = this.Tela_nivel_origem;
			size = new size(64, 20);
			tela_nivel_origem2.Size = size;
			this.Tela_nivel_origem.TabIndex = (HorizontalAlignment)9;
			this.Tela_nivel_origem.TextAlign = HorizontalAlignment.Right;
			this.Label_nivel_origem.AutoSize = true;
			global::System.Windows.Forms.Control label_nivel_origem = this.Label_nivel_origem;
			location = new location(18, 45);
			label_nivel_origem.Location = location;
			this.Label_nivel_origem.Name = "Label_nivel_origem";
			global::System.Windows.Forms.Control label_nivel_origem2 = this.Label_nivel_origem;
			size = new size(60, 13);
			label_nivel_origem2.Size = size;
			this.Label_nivel_origem.TabIndex = (HorizontalAlignment)8;
			this.Label_nivel_origem.Text = "Origem(%) :";
			global::System.Windows.Forms.Control tela_nivel_destino = this.Tela_nivel_destino;
			location = new location(18, 116);
			tela_nivel_destino.Location = location;
			this.Tela_nivel_destino.Name = "Tela_nivel_destino";
			global::System.Windows.Forms.Control tela_nivel_destino2 = this.Tela_nivel_destino;
			size = new size(64, 20);
			tela_nivel_destino2.Size = size;
			this.Tela_nivel_destino.TabIndex = (HorizontalAlignment)7;
			this.Tela_nivel_destino.TextAlign = HorizontalAlignment.Right;
			this.Label_nivel_destino.AutoSize = true;
			global::System.Windows.Forms.Control label_nivel_destino = this.Label_nivel_destino;
			location = new location(15, 100);
			label_nivel_destino.Location = location;
			this.Label_nivel_destino.Name = "Label_nivel_destino";
			global::System.Windows.Forms.Control label_nivel_destino2 = this.Label_nivel_destino;
			size = new size(63, 13);
			label_nivel_destino2.Size = size;
			this.Label_nivel_destino.TabIndex = (HorizontalAlignment)2;
			this.Label_nivel_destino.Text = "Destino(%) :";
			this.Cmd_falha_b2.BackColor = global::System.Drawing.Color.FromArgb(255, 255, 128);
			global::System.Windows.Forms.Control cmd_falha_b = this.Cmd_falha_b2;
			location = new location(1018, 725);
			cmd_falha_b.Location = location;
			this.Cmd_falha_b2.Name = "Cmd_falha_b2";
			global::System.Windows.Forms.Control cmd_falha_b2 = this.Cmd_falha_b2;
			size = new size(111, 26);
			cmd_falha_b2.Size = size;
			this.Cmd_falha_b2.TabIndex = (HorizontalAlignment)6;
			this.Cmd_falha_b2.Text = "Falha";
			this.Cmd_falha_b2.UseVisualStyleBackColor = false;
			this.Cmd_falha_b2.Visible = false;
			this.Grupo_medidas.Controls.Add(this.dgv_EA);
			this.Grupo_medidas.Enabled = false;
			global::System.Windows.Forms.Control grupo_medidas = this.Grupo_medidas;
			location = new location(433, 380);
			grupo_medidas.Location = location;
			this.Grupo_medidas.Name = "Grupo_medidas";
			global::System.Windows.Forms.Control grupo_medidas2 = this.Grupo_medidas;
			size = new size(563, 410);
			grupo_medidas2.Size = size;
			this.Grupo_medidas.TabIndex = (HorizontalAlignment)9;
			this.Grupo_medidas.TabStop = false;
			this.Grupo_medidas.Text = "Medidas Analógicas";
			this.dgv_EA.AllowUserToAddRows = false;
			this.dgv_EA.AllowUserToDeleteRows = false;
			this.dgv_EA.AllowUserToResizeColumns = false;
			this.dgv_EA.AllowUserToResizeRows = false;
			dataGridViewCellStyle2.BackColor = global::System.Drawing.SystemColors.GradientInactiveCaption;
			this.dgv_EA.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle2;
			this.dgv_EA.ColumnHeadersHeightSizeMode = (HorizontalAlignment)2;
			this.dgv_EA.Columns.AddRange(new global::System.Windows.Forms.DataGridViewColumn[]
			{
				this.Contagens,
				this.Conv,
				this.Inicio,
				this.Fim,
				this.Medida
			});
			global::System.Windows.Forms.Control dgv_EA = this.dgv_EA;
			location = new location(12, 19);
			dgv_EA.Location = location;
			this.dgv_EA.Name = "dgv_EA";
			global::System.Windows.Forms.Control dgv_EA2 = this.dgv_EA;
			size = new size(537, 376);
			dgv_EA2.Size = size;
			this.dgv_EA.TabIndex = (HorizontalAlignment)11;
			this.Contagens.HeaderText = "Contagens";
			this.Contagens.MaxInputLength = (HorizontalAlignment)4;
			this.Contagens.Name = "Contagens";
			this.Contagens.ReadOnly = true;
			this.Conv.HeaderText = "Converte";
			this.Conv.Name = "Conv";
			this.Conv.Width = (HorizontalAlignment)60;
			this.Inicio.HeaderText = "Início";
			this.Inicio.Name = "Inicio";
			this.Fim.HeaderText = "Fim";
			this.Fim.Name = "Fim";
			this.Medida.HeaderText = "Medida:";
			this.Medida.Name = "Medida";
			this.Medida.ReadOnly = true;
			this.GroupBox1.Controls.Add(this.ck_ativa_ref);
			this.GroupBox1.Controls.Add(this.dgv_Referencias);
			global::System.Windows.Forms.Control groupBox = this.GroupBox1;
			location = new location(433, 212);
			groupBox.Location = location;
			this.GroupBox1.Name = "GroupBox1";
			global::System.Windows.Forms.Control groupBox2 = this.GroupBox1;
			size = new size(206, 162);
			groupBox2.Size = size;
			this.GroupBox1.TabIndex = (HorizontalAlignment)10;
			this.GroupBox1.TabStop = false;
			this.GroupBox1.Text = "Escrita de Referências:";
			this.ck_ativa_ref.AutoSize = true;
			global::System.Windows.Forms.Control ck_ativa_ref = this.ck_ativa_ref;
			location = new location(12, 15);
			ck_ativa_ref.Location = location;
			this.ck_ativa_ref.Name = "ck_ativa_ref";
			global::System.Windows.Forms.Control ck_ativa_ref2 = this.ck_ativa_ref;
			size = new size(50, 17);
			ck_ativa_ref2.Size = size;
			this.ck_ativa_ref.TabIndex = (HorizontalAlignment)1;
			this.ck_ativa_ref.Text = "Ativa";
			this.ck_ativa_ref.UseVisualStyleBackColor = true;
			this.dgv_Referencias.AllowUserToAddRows = false;
			this.dgv_Referencias.AllowUserToDeleteRows = false;
			this.dgv_Referencias.AllowUserToOrderColumns = true;
			this.dgv_Referencias.AllowUserToResizeColumns = false;
			this.dgv_Referencias.AllowUserToResizeRows = false;
			dataGridViewCellStyle3.BackColor = global::System.Drawing.SystemColors.GradientInactiveCaption;
			this.dgv_Referencias.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle3;
			this.dgv_Referencias.ColumnHeadersHeightSizeMode = (HorizontalAlignment)2;
			this.dgv_Referencias.Columns.AddRange(new global::System.Windows.Forms.DataGridViewColumn[]
			{
				this.Ref
			});
			global::System.Windows.Forms.Control dgv_Referencias = this.dgv_Referencias;
			location = new location(12, 37);
			dgv_Referencias.Location = location;
			this.dgv_Referencias.Name = "dgv_Referencias";
			global::System.Windows.Forms.Control dgv_Referencias2 = this.dgv_Referencias;
			size = new size(183, 111);
			dgv_Referencias2.Size = size;
			this.dgv_Referencias.TabIndex = (HorizontalAlignment)0;
			this.Ref.HeaderText = "Referência (0 - 4000)";
			this.Ref.MaxInputLength = (HorizontalAlignment)4;
			this.Ref.Name = "Ref";
			this.Ref.Width = (HorizontalAlignment)130;
			this.Label3.AutoSize = true;
			global::System.Windows.Forms.Control label5 = this.Label3;
			location = new location(29, 807);
			label5.Location = location;
			this.Label3.Name = "Label3";
			global::System.Windows.Forms.Control label6 = this.Label3;
			size = new size(379, 13);
			label6.Size = size;
			this.Label3.TabIndex = (HorizontalAlignment)11;
			this.Label3.Text = "Obs.: Duplo Click, quando permitido, troca os estados de controle nas colunas.";
			this.GroupBox_ED.Controls.Add(this.cb_ED8);
			this.GroupBox_ED.Controls.Add(this.cb_ED7);
			this.GroupBox_ED.Controls.Add(this.cb_ED6);
			this.GroupBox_ED.Controls.Add(this.cb_ED5);
			this.GroupBox_ED.Controls.Add(this.cb_ED4);
			this.GroupBox_ED.Controls.Add(this.cb_ED3);
			this.GroupBox_ED.Controls.Add(this.cb_ED2);
			this.GroupBox_ED.Controls.Add(this.cb_ED1);
			global::System.Windows.Forms.Control groupBox_ED = this.GroupBox_ED;
			location = new location(1030, 514);
			groupBox_ED.Location = location;
			this.GroupBox_ED.Name = "GroupBox_ED";
			global::System.Windows.Forms.Control groupBox_ED2 = this.GroupBox_ED;
			size = new size(90, 162);
			groupBox_ED2.Size = size;
			this.GroupBox_ED.TabIndex = (HorizontalAlignment)22;
			this.GroupBox_ED.TabStop = false;
			this.GroupBox_ED.Text = "Ent. Digitais";
			this.cb_ED8.AutoSize = true;
			global::System.Windows.Forms.Control cb_ED = this.cb_ED8;
			location = new location(20, 126);
			cb_ED.Location = location;
			this.cb_ED8.Name = "cb_ED8";
			global::System.Windows.Forms.Control cb_ED2 = this.cb_ED8;
			size = new size(47, 17);
			cb_ED2.Size = size;
			this.cb_ED8.TabIndex = (HorizontalAlignment)27;
			this.cb_ED8.Text = "ED8";
			this.cb_ED8.UseVisualStyleBackColor = true;
			this.cb_ED7.AutoSize = true;
			global::System.Windows.Forms.Control cb_ED3 = this.cb_ED7;
			location = new location(20, 111);
			cb_ED3.Location = location;
			this.cb_ED7.Name = "cb_ED7";
			global::System.Windows.Forms.Control cb_ED4 = this.cb_ED7;
			size = new size(47, 17);
			cb_ED4.Size = size;
			this.cb_ED7.TabIndex = (HorizontalAlignment)26;
			this.cb_ED7.Text = "ED7";
			this.cb_ED7.UseVisualStyleBackColor = true;
			this.cb_ED6.AutoSize = true;
			global::System.Windows.Forms.Control cb_ED5 = this.cb_ED6;
			location = new location(20, 96);
			cb_ED5.Location = location;
			this.cb_ED6.Name = "cb_ED6";
			global::System.Windows.Forms.Control cb_ED6 = this.cb_ED6;
			size = new size(47, 17);
			cb_ED6.Size = size;
			this.cb_ED6.TabIndex = (HorizontalAlignment)25;
			this.cb_ED6.Text = "ED6";
			this.cb_ED6.UseVisualStyleBackColor = true;
			this.cb_ED5.AutoSize = true;
			global::System.Windows.Forms.Control cb_ED7 = this.cb_ED5;
			location = new location(20, 81);
			cb_ED7.Location = location;
			this.cb_ED5.Name = "cb_ED5";
			global::System.Windows.Forms.Control cb_ED8 = this.cb_ED5;
			size = new size(47, 17);
			cb_ED8.Size = size;
			this.cb_ED5.TabIndex = (HorizontalAlignment)24;
			this.cb_ED5.Text = "ED5";
			this.cb_ED5.UseVisualStyleBackColor = true;
			this.cb_ED4.AutoSize = true;
			global::System.Windows.Forms.Control cb_ED9 = this.cb_ED4;
			location = new location(20, 66);
			cb_ED9.Location = location;
			this.cb_ED4.Name = "cb_ED4";
			global::System.Windows.Forms.Control cb_ED10 = this.cb_ED4;
			size = new size(47, 17);
			cb_ED10.Size = size;
			this.cb_ED4.TabIndex = (HorizontalAlignment)23;
			this.cb_ED4.Text = "ED4";
			this.cb_ED4.UseVisualStyleBackColor = true;
			this.cb_ED3.AutoSize = true;
			global::System.Windows.Forms.Control cb_ED11 = this.cb_ED3;
			location = new location(20, 51);
			cb_ED11.Location = location;
			this.cb_ED3.Name = "cb_ED3";
			global::System.Windows.Forms.Control cb_ED12 = this.cb_ED3;
			size = new size(47, 17);
			cb_ED12.Size = size;
			this.cb_ED3.TabIndex = (HorizontalAlignment)22;
			this.cb_ED3.Text = "ED3";
			this.cb_ED3.UseVisualStyleBackColor = true;
			this.cb_ED2.AutoSize = true;
			global::System.Windows.Forms.Control cb_ED13 = this.cb_ED2;
			location = new location(20, 36);
			cb_ED13.Location = location;
			this.cb_ED2.Name = "cb_ED2";
			global::System.Windows.Forms.Control cb_ED14 = this.cb_ED2;
			size = new size(47, 17);
			cb_ED14.Size = size;
			this.cb_ED2.TabIndex = (HorizontalAlignment)21;
			this.cb_ED2.Text = "ED2";
			this.cb_ED2.UseVisualStyleBackColor = true;
			this.cb_ED1.AutoSize = true;
			global::System.Windows.Forms.Control cb_ED15 = this.cb_ED1;
			location = new location(20, 21);
			cb_ED15.Location = location;
			this.cb_ED1.Name = "cb_ED1";
			global::System.Windows.Forms.Control cb_ED16 = this.cb_ED1;
			size = new size(47, 17);
			cb_ED16.Size = size;
			this.cb_ED1.TabIndex = (HorizontalAlignment)20;
			this.cb_ED1.Text = "ED1";
			this.cb_ED1.UseVisualStyleBackColor = true;
			this.GroupBox_Alarmes.Controls.Add(this.pb_bit0);
			this.GroupBox_Alarmes.Controls.Add(this.pb_bit1);
			this.GroupBox_Alarmes.Controls.Add(this.pb_bit5);
			this.GroupBox_Alarmes.Controls.Add(this.pb_bit2);
			this.GroupBox_Alarmes.Controls.Add(this.pb_bit4);
			this.GroupBox_Alarmes.Controls.Add(this.pb_bit3);
			global::System.Windows.Forms.Control groupBox_Alarmes = this.GroupBox_Alarmes;
			location = new location(911, 212);
			groupBox_Alarmes.Location = location;
			this.GroupBox_Alarmes.Name = "GroupBox_Alarmes";
			global::System.Windows.Forms.Control groupBox_Alarmes2 = this.GroupBox_Alarmes;
			size = new size(218, 162);
			groupBox_Alarmes2.Size = size;
			this.GroupBox_Alarmes.TabIndex = (HorizontalAlignment)23;
			this.GroupBox_Alarmes.TabStop = false;
			this.GroupBox_Alarmes.Text = "Alarmes";
			global::System.Windows.Forms.Control pb_bit = this.pb_bit0;
			location = new location(6, 13);
			pb_bit.Location = location;
			global::System.Windows.Forms.Control pb_bit2 = this.pb_bit0;
			size = new size(64, 64);
			pb_bit2.MaximumSize = size;
			this.pb_bit0.Name = "pb_bit0";
			global::System.Windows.Forms.Control pb_bit3 = this.pb_bit0;
			size = new size(64, 64);
			pb_bit3.Size = size;
			this.pb_bit0.SizeMode =(System.Windows.Forms.PictureBoxSizeMode)1;
			this.pb_bit0.TabIndex = (HorizontalAlignment)12;
			this.pb_bit0.TabStop = false;
			global::System.Windows.Forms.Control pb_bit4 = this.pb_bit1;
			location = new location(76, 13);
			pb_bit4.Location = location;
			global::System.Windows.Forms.Control pb_bit5 = this.pb_bit1;
			size = new size(64, 64);
			pb_bit5.MaximumSize = size;
			this.pb_bit1.Name = "pb_bit1";
			global::System.Windows.Forms.Control pb_bit6 = this.pb_bit1;
			size = new size(64, 64);
			pb_bit6.Size = size;
			this.pb_bit1.SizeMode =(System.Windows.Forms.PictureBoxSizeMode)1;
			this.pb_bit1.TabIndex = (HorizontalAlignment)14;
			this.pb_bit1.TabStop = false;
			global::System.Windows.Forms.Control pb_bit7 = this.pb_bit5;
			location = new location(146, 83);
			pb_bit7.Location = location;
			global::System.Windows.Forms.Control pb_bit8 = this.pb_bit5;
			size = new size(64, 64);
			pb_bit8.MaximumSize = size;
			this.pb_bit5.Name = "pb_bit5";
			global::System.Windows.Forms.Control pb_bit9 = this.pb_bit5;
			size = new size(63, 64);
			pb_bit9.Size = size;
			this.pb_bit5.SizeMode =(System.Windows.Forms.PictureBoxSizeMode)1;
			this.pb_bit5.TabIndex = (HorizontalAlignment)17;
			this.pb_bit5.TabStop = false;
			global::System.Windows.Forms.Control pb_bit10 = this.pb_bit2;
			location = new location(146, 12);
			pb_bit10.Location = location;
			global::System.Windows.Forms.Control pb_bit11 = this.pb_bit2;
			size = new size(64, 64);
			pb_bit11.MaximumSize = size;
			this.pb_bit2.Name = "pb_bit2";
			global::System.Windows.Forms.Control pb_bit12 = this.pb_bit2;
			size = new size(64, 64);
			pb_bit12.Size = size;
			this.pb_bit2.SizeMode =(System.Windows.Forms.PictureBoxSizeMode)1;
			this.pb_bit2.TabIndex = (HorizontalAlignment)15;
			this.pb_bit2.TabStop = false;
			global::System.Windows.Forms.Control pb_bit13 = this.pb_bit4;
			location = new location(76, 83);
			pb_bit13.Location = location;
			global::System.Windows.Forms.Control pb_bit14 = this.pb_bit4;
			size = new size(64, 64);
			pb_bit14.MaximumSize = size;
			this.pb_bit4.Name = "pb_bit4";
			global::System.Windows.Forms.Control pb_bit15 = this.pb_bit4;
			size = new size(64, 64);
			pb_bit15.Size = size;
			this.pb_bit4.SizeMode =(System.Windows.Forms.PictureBoxSizeMode)1;
			this.pb_bit4.TabIndex = (HorizontalAlignment)16;
			this.pb_bit4.TabStop = false;
			global::System.Windows.Forms.Control pb_bit16 = this.pb_bit3;
			location = new location(6, 83);
			pb_bit16.Location = location;
			global::System.Windows.Forms.Control pb_bit17 = this.pb_bit3;
			size = new size(64, 64);
			pb_bit17.MaximumSize = size;
			this.pb_bit3.Name = "pb_bit3";
			global::System.Windows.Forms.Control pb_bit18 = this.pb_bit3;
			size = new size(64, 64);
			pb_bit18.Size = size;
			this.pb_bit3.SizeMode =(System.Windows.Forms.PictureBoxSizeMode)1;
			this.pb_bit3.TabIndex = (HorizontalAlignment)13;
			this.pb_bit3.TabStop = false;
			this.gb_ajuste.Controls.Add(this.bt_rel_escrita);
			this.gb_ajuste.Controls.Add(this.bt_rel_leitura);
			global::System.Windows.Forms.Control gb_ajuste = this.gb_ajuste;
			location = new location(698, 156);
			gb_ajuste.Location = location;
			this.gb_ajuste.Name = "gb_ajuste";
			global::System.Windows.Forms.Control gb_ajuste2 = this.gb_ajuste;
			size = new size(328, 47);
			gb_ajuste2.Size = size;
			this.gb_ajuste.TabIndex = (HorizontalAlignment)24;
			this.gb_ajuste.TabStop = false;
			this.gb_ajuste.Text = "Ajuste Relógio - Somente com a monitoração parada";
			global::System.Windows.Forms.Control bt_rel_escrita = this.bt_rel_escrita;
			location = new location(185, 19);
			bt_rel_escrita.Location = location;
			this.bt_rel_escrita.Name = "bt_rel_escrita";
			global::System.Windows.Forms.Control bt_rel_escrita2 = this.bt_rel_escrita;
			size = new size(134, 23);
			bt_rel_escrita2.Size = size;
			this.bt_rel_escrita.TabIndex = (HorizontalAlignment)1;
			this.bt_rel_escrita.Text = "Escrita";
			this.bt_rel_escrita.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control bt_rel_leitura = this.bt_rel_leitura;
			location = new location(9, 19);
			bt_rel_leitura.Location = location;
			this.bt_rel_leitura.Name = "bt_rel_leitura";
			global::System.Windows.Forms.Control bt_rel_leitura2 = this.bt_rel_leitura;
			size = new size(134, 23);
			bt_rel_leitura2.Size = size;
			this.bt_rel_leitura.TabIndex = (HorizontalAlignment)0;
			this.bt_rel_leitura.Text = "Leitura";
			this.bt_rel_leitura.UseVisualStyleBackColor = true;
			this.gb_SA.Controls.Add(this.ck_ativa_sa);
			this.gb_SA.Controls.Add(this.dgv_SA);
			global::System.Windows.Forms.Control gb_SA = this.gb_SA;
			location = new location(669, 212);
			gb_SA.Location = location;
			this.gb_SA.Name = "gb_SA";
			global::System.Windows.Forms.Control gb_SA2 = this.gb_SA;
			size = new size(206, 162);
			gb_SA2.Size = size;
			this.gb_SA.TabIndex = (HorizontalAlignment)25;
			this.gb_SA.TabStop = false;
			this.gb_SA.Text = "Escrita de Saídas Analógicas";
			this.ck_ativa_sa.AutoSize = true;
			global::System.Windows.Forms.Control ck_ativa_sa = this.ck_ativa_sa;
			location = new location(12, 15);
			ck_ativa_sa.Location = location;
			this.ck_ativa_sa.Name = "ck_ativa_sa";
			global::System.Windows.Forms.Control ck_ativa_sa2 = this.ck_ativa_sa;
			size = new size(50, 17);
			ck_ativa_sa2.Size = size;
			this.ck_ativa_sa.TabIndex = (HorizontalAlignment)3;
			this.ck_ativa_sa.Text = "Ativa";
			this.ck_ativa_sa.UseVisualStyleBackColor = true;
			this.dgv_SA.AllowUserToAddRows = false;
			this.dgv_SA.AllowUserToDeleteRows = false;
			this.dgv_SA.AllowUserToOrderColumns = true;
			this.dgv_SA.AllowUserToResizeColumns = false;
			this.dgv_SA.AllowUserToResizeRows = false;
			dataGridViewCellStyle4.BackColor = global::System.Drawing.SystemColors.GradientInactiveCaption;
			this.dgv_SA.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle4;
			this.dgv_SA.ColumnHeadersHeightSizeMode = (HorizontalAlignment)2;
			this.dgv_SA.Columns.AddRange(new global::System.Windows.Forms.DataGridViewColumn[]
			{
				this.DataGridViewTextBoxColumn1
			});
			global::System.Windows.Forms.Control dgv_SA = this.dgv_SA;
			location = new location(12, 37);
			dgv_SA.Location = location;
			this.dgv_SA.Name = "dgv_SA";
			global::System.Windows.Forms.Control dgv_SA2 = this.dgv_SA;
			size = new size(183, 111);
			dgv_SA2.Size = size;
			this.dgv_SA.TabIndex = (HorizontalAlignment)2;
			this.DataGridViewTextBoxColumn1.HeaderText = "Referência (0 - 4000)";
			this.DataGridViewTextBoxColumn1.MaxInputLength = (HorizontalAlignment)4;
			this.DataGridViewTextBoxColumn1.Name = "DataGridViewTextBoxColumn1";
			this.DataGridViewTextBoxColumn1.Width = (HorizontalAlignment)130;
			global::System.Drawing.SizeF autoScaleDimensions;
			autoScaleDimensions = new global::System.Drawing.SizeF(6f, 13f);
			this.AutoScaleDimensions = autoScaleDimensions;
			this.AutoScaleMode = AutoScaleMode.Font;
			size = new size(1145, 855);
			this.ClientSize = size;
			this.Controls.Add(this.gb_SA);
			this.Controls.Add(this.gb_ajuste);
			this.Controls.Add(this.GroupBox_Alarmes);
			this.Controls.Add(this.GroupBox_ED);
			this.Controls.Add(this.Label3);
			this.Controls.Add(this.Cmd_falha_b2);
			this.Controls.Add(this.GroupBox1);
			this.Controls.Add(this.Grupo_medidas);
			this.Controls.Add(this.Grupo_status);
			this.Controls.Add(this.Grupo_estatistica);
			this.Controls.Add(this.Grupo_ctrl_com);
			this.FormBorderStyle = FormBorderStyle.FixedSingle;
			this.Icon = (global::System.Drawing.Icon)componentResourceManager.GetObject("$this.Icon");
			location = new location(160, 2);
			this.Location = location;
			this.Name = "Equip_820_mon";
			this.StartPosition = FormStartPosition.CenterParent;
			this.Text = "Monitoração";
			this.Grupo_ctrl_com.ResumeLayout(false);
			this.Grupo_ctrl_com.PerformLayout();
			this.pb_hab_monitoracao.EndInit();
			this.Tela_endereco_estacao.EndInit();
			this.Tela_endereco_mestre.EndInit();
			this.Grupo_setpoints.ResumeLayout(false);
			this.Grupo_setpoints.PerformLayout();
			this.Grupo_estatistica.ResumeLayout(false);
			this.Grupo_estatistica.PerformLayout();
			this.Grupo_status.ResumeLayout(false);
			this.dgv_Controle.EndInit();
			this.Grupo_escrita_de_dados.ResumeLayout(false);
			this.Grupo_escrita_de_dados.PerformLayout();
			this.Tela_nivel_origem.EndInit();
			this.Tela_nivel_destino.EndInit();
			this.Grupo_medidas.ResumeLayout(false);
			this.dgv_EA.EndInit();
			this.GroupBox1.ResumeLayout(false);
			this.GroupBox1.PerformLayout();
			this.dgv_Referencias.EndInit();
			this.GroupBox_ED.ResumeLayout(false);
			this.GroupBox_ED.PerformLayout();
			this.GroupBox_Alarmes.ResumeLayout(false);
			this.pb_bit0.EndInit();
			this.pb_bit1.EndInit();
			this.pb_bit5.EndInit();
			this.pb_bit2.EndInit();
			this.pb_bit4.EndInit();
			this.pb_bit3.EndInit();
			this.gb_ajuste.ResumeLayout(false);
			this.gb_SA.ResumeLayout(false);
			this.gb_SA.PerformLayout();
			this.dgv_SA.EndInit();
			this.ResumeLayout(false);
			this.PerformLayout();
		}

		// Token: 0x040008F1 RID: 2289
		private global::System.ComponentModel.IContainer components;
	}
}
