namespace iS800
{
	// Token: 0x0200003A RID: 58
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class GC_82x_conf : global::System.Windows.Forms.Form
	{
		// Token: 0x06000C63 RID: 3171 RVA: 0x002F46F8 File Offset: 0x002F2AF8
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				if (disposing && this.components != null)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x06000C64 RID: 3172 RVA: 0x002F4738 File Offset: 0x002F2B38
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.components = new global::System.ComponentModel.Container();
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::iS800.GC_82x_conf));
			this.ToolStri_RT_810 = new global::System.Windows.Forms.ToolStrip();
			this.ToolStripButton_RT_810_novo = new global::System.Windows.Forms.ToolStripButton();
			this.ToolStripButton_RT_810_Abrir = new global::System.Windows.Forms.ToolStripButton();
			this.ToolStripButton_RT_810_Salvar = new global::System.Windows.Forms.ToolStripButton();
			this.ToolStripSeparator1 = new global::System.Windows.Forms.ToolStripSeparator();
			this.ToolStripButton_RT_810_Download = new global::System.Windows.Forms.ToolStripButton();
			this.ToolStripButton_RT_810_Upload = new global::System.Windows.Forms.ToolStripButton();
			this.ToolStripSeparator2 = new global::System.Windows.Forms.ToolStripSeparator();
			this.ToolStripButton_RT_810_Imprimir = new global::System.Windows.Forms.ToolStripButton();
			this.ToolStripSeparator3 = new global::System.Windows.Forms.ToolStripSeparator();
			this.ToolStripLabel_ID = new global::System.Windows.Forms.ToolStripLabel();
			this.ToolStripSeparator4 = new global::System.Windows.Forms.ToolStripSeparator();
			this.ToolStripTextBox_RT_810_Msg = new global::System.Windows.Forms.ToolStripTextBox();
			this.ToolStripProgressBar_RT_810 = new global::System.Windows.Forms.ToolStripProgressBar();
			this.ToolStripButton1 = new global::System.Windows.Forms.ToolStripButton();
			this.OpenFileDialog_RT_810 = new global::System.Windows.Forms.OpenFileDialog();
			this.SaveFileDialog_RT_810 = new global::System.Windows.Forms.SaveFileDialog();
			this.Timer_limpa_MSG = new global::System.Windows.Forms.Timer(this.components);
			this.PrintDocument1 = new global::System.Drawing.Printing.PrintDocument();
			this.PrintPreviewDialog1 = new global::System.Windows.Forms.PrintPreviewDialog();
			this.RepetidoraBindingSource1 = new global::System.Windows.Forms.BindingSource(this.components);
			this.TabPage_geral = new global::System.Windows.Forms.TabPage();
			this.GroupBox3 = new global::System.Windows.Forms.GroupBox();
			this.GroupBox4 = new global::System.Windows.Forms.GroupBox();
			this.lmt_2_20mA = new global::System.Windows.Forms.NumericUpDown();
			this.Label4 = new global::System.Windows.Forms.Label();
			this.lmt_2_4mA = new global::System.Windows.Forms.NumericUpDown();
			this.Label5 = new global::System.Windows.Forms.Label();
			this.GroupBox1 = new global::System.Windows.Forms.GroupBox();
			this.GroupBox2 = new global::System.Windows.Forms.GroupBox();
			this.lmt_1_20mA = new global::System.Windows.Forms.NumericUpDown();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.lmt_1_4mA = new global::System.Windows.Forms.NumericUpDown();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.GroupBox_informacoes = new global::System.Windows.Forms.GroupBox();
			this.Label26 = new global::System.Windows.Forms.Label();
			this.TextBox_equipamento = new global::System.Windows.Forms.TextBox();
			this.Label_equipamento = new global::System.Windows.Forms.Label();
			this.TextBox_release = new global::System.Windows.Forms.TextBox();
			this.Label_release = new global::System.Windows.Forms.Label();
			this.TextBox_build = new global::System.Windows.Forms.TextBox();
			this.Label_build = new global::System.Windows.Forms.Label();
			this.TextBox_versao = new global::System.Windows.Forms.TextBox();
			this.Label_versao = new global::System.Windows.Forms.Label();
			this.GroupBox_comunicacao = new global::System.Windows.Forms.GroupBox();
			this.NumericUpDown_end_est = new global::System.Windows.Forms.NumericUpDown();
			this.Label_end_est = new global::System.Windows.Forms.Label();
			this.TabControl_810 = new global::System.Windows.Forms.TabControl();
			this.ToolStri_RT_810.SuspendLayout();
			this.RepetidoraBindingSource1.BeginInit();
			this.TabPage_geral.SuspendLayout();
			this.GroupBox3.SuspendLayout();
			this.GroupBox4.SuspendLayout();
			this.lmt_2_20mA.BeginInit();
			this.lmt_2_4mA.BeginInit();
			this.GroupBox1.SuspendLayout();
			this.GroupBox2.SuspendLayout();
			this.lmt_1_20mA.BeginInit();
			this.lmt_1_4mA.BeginInit();
			this.GroupBox_informacoes.SuspendLayout();
			this.GroupBox_comunicacao.SuspendLayout();
			this.NumericUpDown_end_est.BeginInit();
			this.TabControl_810.SuspendLayout();
			this.SuspendLayout();
			this.ToolStri_RT_810.BackColor = global::System.Drawing.Color.Transparent;
			this.ToolStri_RT_810.GripStyle = 0;
			global::System.Windows.Forms.ToolStrip toolStri_RT_ = this.ToolStri_RT_810;
			global::System.Drawing.Size size;
			size = new global::System.Drawing.Size(48, 48);
			toolStri_RT_.ImageScalingSize = size;
			this.ToolStri_RT_810.Items.AddRange(new global::System.Windows.Forms.ToolStripItem[]
			{
				this.ToolStripButton_RT_810_novo,
				this.ToolStripButton_RT_810_Abrir,
				this.ToolStripButton_RT_810_Salvar,
				this.ToolStripSeparator1,
				this.ToolStripButton_RT_810_Download,
				this.ToolStripButton_RT_810_Upload,
				this.ToolStripSeparator2,
				this.ToolStripButton_RT_810_Imprimir,
				this.ToolStripSeparator3,
				this.ToolStripLabel_ID,
				this.ToolStripSeparator4,
				this.ToolStripTextBox_RT_810_Msg,
				this.ToolStripProgressBar_RT_810,
				this.ToolStripButton1
			});
			this.ToolStri_RT_810.LayoutStyle = 3;
			global::System.Windows.Forms.Control toolStri_RT_2 = this.ToolStri_RT_810;
			global::System.Drawing.Point location;
			location = new global::System.Drawing.Point(0, 0);
			toolStri_RT_2.Location = location;
			this.ToolStri_RT_810.Name = "ToolStri_RT_810";
			global::System.Windows.Forms.Control toolStri_RT_3 = this.ToolStri_RT_810;
			size = new size(1147, 55);
			toolStri_RT_3.Size = size;
			this.ToolStri_RT_810.Stretch = true;
			this.ToolStri_RT_810.TabIndex = 0;
			this.ToolStri_RT_810.Text = "ToolStrip1";
			this.ToolStripButton_RT_810_novo.AutoToolTip = false;
			this.ToolStripButton_RT_810_novo.DisplayStyle = 2;
			this.ToolStripButton_RT_810_novo.Image = global::iS800.My.Resources.Resources.folder_add_icon1;
			this.ToolStripButton_RT_810_novo.ImageTransparentColor = global::System.Drawing.Color.Magenta;
			global::System.Windows.Forms.ToolStripItem toolStripButton_RT_810_novo = this.ToolStripButton_RT_810_novo;
			global::System.Windows.Forms.Padding padding;
			padding = new global::System.Windows.Forms.Padding(10, 1, 0, 2);
			toolStripButton_RT_810_novo.Margin = padding;
			this.ToolStripButton_RT_810_novo.Name = "ToolStripButton_RT_810_novo";
			global::System.Windows.Forms.ToolStripItem toolStripButton_RT_810_novo2 = this.ToolStripButton_RT_810_novo;
			size = new size(52, 52);
			toolStripButton_RT_810_novo2.Size = size;
			this.ToolStripButton_RT_810_novo.Text = "Novo";
			this.ToolStripButton_RT_810_novo.ToolTipText = "Novo arquivo";
			this.ToolStripButton_RT_810_Abrir.AutoToolTip = false;
			this.ToolStripButton_RT_810_Abrir.DisplayStyle = 2;
			this.ToolStripButton_RT_810_Abrir.Image = global::iS800.My.Resources.Resources.folder_up_icon;
			this.ToolStripButton_RT_810_Abrir.ImageTransparentColor = global::System.Drawing.Color.Magenta;
			this.ToolStripButton_RT_810_Abrir.Name = "ToolStripButton_RT_810_Abrir";
			global::System.Windows.Forms.ToolStripItem toolStripButton_RT_810_Abrir = this.ToolStripButton_RT_810_Abrir;
			size = new size(52, 52);
			toolStripButton_RT_810_Abrir.Size = size;
			this.ToolStripButton_RT_810_Abrir.Text = "Abrir Arquivo";
			this.ToolStripButton_RT_810_Abrir.ToolTipText = "Abrir arquivo";
			this.ToolStripButton_RT_810_Salvar.AutoToolTip = false;
			this.ToolStripButton_RT_810_Salvar.DisplayStyle = 2;
			this.ToolStripButton_RT_810_Salvar.Image = global::iS800.My.Resources.Resources.folder_down_icon;
			this.ToolStripButton_RT_810_Salvar.ImageTransparentColor = global::System.Drawing.Color.Magenta;
			this.ToolStripButton_RT_810_Salvar.Name = "ToolStripButton_RT_810_Salvar";
			global::System.Windows.Forms.ToolStripItem toolStripButton_RT_810_Salvar = this.ToolStripButton_RT_810_Salvar;
			size = new size(52, 52);
			toolStripButton_RT_810_Salvar.Size = size;
			this.ToolStripButton_RT_810_Salvar.Text = "Salvar Arquivo";
			this.ToolStripButton_RT_810_Salvar.ToolTipText = "Salvar arquivo";
			this.ToolStripSeparator1.AutoSize = false;
			global::System.Windows.Forms.ToolStripItem toolStripSeparator = this.ToolStripSeparator1;
			padding = new padding(10, 0, 0, 0);
			toolStripSeparator.Margin = padding;
			this.ToolStripSeparator1.Name = "ToolStripSeparator1";
			global::System.Windows.Forms.ToolStripItem toolStripSeparator2 = this.ToolStripSeparator1;
			size = new size(6, 52);
			toolStripSeparator2.Size = size;
			this.ToolStripButton_RT_810_Download.DisplayStyle = 2;
			this.ToolStripButton_RT_810_Download.Image = global::iS800.My.Resources.Resources.Upload_icon;
			this.ToolStripButton_RT_810_Download.ImageTransparentColor = global::System.Drawing.Color.Magenta;
			global::System.Windows.Forms.ToolStripItem toolStripButton_RT_810_Download = this.ToolStripButton_RT_810_Download;
			padding = new padding(10, 1, 0, 2);
			toolStripButton_RT_810_Download.Margin = padding;
			this.ToolStripButton_RT_810_Download.Name = "ToolStripButton_RT_810_Download";
			global::System.Windows.Forms.ToolStripItem toolStripButton_RT_810_Download2 = this.ToolStripButton_RT_810_Download;
			size = new size(52, 52);
			toolStripButton_RT_810_Download2.Size = size;
			this.ToolStripButton_RT_810_Download.Text = "Ler Equipamento";
			this.ToolStripButton_RT_810_Upload.DisplayStyle = 2;
			this.ToolStripButton_RT_810_Upload.Image = global::iS800.My.Resources.Resources.Download_icon;
			this.ToolStripButton_RT_810_Upload.ImageTransparentColor = global::System.Drawing.Color.Magenta;
			this.ToolStripButton_RT_810_Upload.Name = "ToolStripButton_RT_810_Upload";
			global::System.Windows.Forms.ToolStripItem toolStripButton_RT_810_Upload = this.ToolStripButton_RT_810_Upload;
			size = new size(52, 52);
			toolStripButton_RT_810_Upload.Size = size;
			this.ToolStripButton_RT_810_Upload.Text = "Gravar no equipamento";
			this.ToolStripSeparator2.AutoSize = false;
			global::System.Windows.Forms.ToolStripItem toolStripSeparator3 = this.ToolStripSeparator2;
			padding = new padding(10, 0, 0, 0);
			toolStripSeparator3.Margin = padding;
			this.ToolStripSeparator2.Name = "ToolStripSeparator2";
			global::System.Windows.Forms.ToolStripItem toolStripSeparator4 = this.ToolStripSeparator2;
			size = new size(6, 52);
			toolStripSeparator4.Size = size;
			this.ToolStripButton_RT_810_Imprimir.DisplayStyle = 2;
			this.ToolStripButton_RT_810_Imprimir.Image = global::iS800.My.Resources.Resources.Hardware_Printer_Text_Icon_128;
			this.ToolStripButton_RT_810_Imprimir.ImageTransparentColor = global::System.Drawing.Color.Magenta;
			this.ToolStripButton_RT_810_Imprimir.Name = "ToolStripButton_RT_810_Imprimir";
			global::System.Windows.Forms.ToolStripItem toolStripButton_RT_810_Imprimir = this.ToolStripButton_RT_810_Imprimir;
			size = new size(52, 52);
			toolStripButton_RT_810_Imprimir.Size = size;
			this.ToolStripButton_RT_810_Imprimir.Text = "Impressão da ficha de configuração";
			this.ToolStripSeparator3.AutoSize = false;
			this.ToolStripSeparator3.Name = "ToolStripSeparator3";
			global::System.Windows.Forms.ToolStripItem toolStripSeparator5 = this.ToolStripSeparator3;
			size = new size(6, 52);
			toolStripSeparator5.Size = size;
			this.ToolStripLabel_ID.Font = new global::System.Drawing.Font("Arial Narrow", 18f, 2, 3, 0);
			this.ToolStripLabel_ID.ForeColor = global::System.Drawing.Color.FromArgb(192, 0, 0);
			global::System.Windows.Forms.ToolStripItem toolStripLabel_ID = this.ToolStripLabel_ID;
			padding = new padding(5, 13, 0, 2);
			toolStripLabel_ID.Margin = padding;
			this.ToolStripLabel_ID.Name = "ToolStripLabel_ID";
			global::System.Windows.Forms.ToolStripItem toolStripLabel_ID2 = this.ToolStripLabel_ID;
			size = new size(112, 29);
			toolStripLabel_ID2.Size = size;
			this.ToolStripLabel_ID.Text = "CG82x/300";
			this.ToolStripSeparator4.AutoSize = false;
			this.ToolStripSeparator4.Name = "ToolStripSeparator4";
			global::System.Windows.Forms.ToolStripItem toolStripSeparator6 = this.ToolStripSeparator4;
			size = new size(6, 52);
			toolStripSeparator6.Size = size;
			this.ToolStripTextBox_RT_810_Msg.BackColor = global::System.Drawing.Color.LightCyan;
			this.ToolStripTextBox_RT_810_Msg.BorderStyle = 1;
			global::System.Windows.Forms.ToolStripItem toolStripTextBox_RT_810_Msg = this.ToolStripTextBox_RT_810_Msg;
			padding = new padding(10, 15, 1, 0);
			toolStripTextBox_RT_810_Msg.Margin = padding;
			this.ToolStripTextBox_RT_810_Msg.Name = "ToolStripTextBox_RT_810_Msg";
			this.ToolStripTextBox_RT_810_Msg.ReadOnly = true;
			global::System.Windows.Forms.ToolStripControlHost toolStripTextBox_RT_810_Msg2 = this.ToolStripTextBox_RT_810_Msg;
			size = new size(250, 23);
			toolStripTextBox_RT_810_Msg2.Size = size;
			this.ToolStripTextBox_RT_810_Msg.TextBoxTextAlign = 2;
			this.ToolStripProgressBar_RT_810.BackColor = global::System.Drawing.SystemColors.Control;
			global::System.Windows.Forms.ToolStripItem toolStripProgressBar_RT_ = this.ToolStripProgressBar_RT_810;
			padding = new padding(20, 15, 1, 1);
			toolStripProgressBar_RT_.Margin = padding;
			this.ToolStripProgressBar_RT_810.Name = "ToolStripProgressBar_RT_810";
			global::System.Windows.Forms.ToolStripControlHost toolStripProgressBar_RT_2 = this.ToolStripProgressBar_RT_810;
			size = new size(180, 20);
			toolStripProgressBar_RT_2.Size = size;
			this.ToolStripProgressBar_RT_810.ToolTipText = "Progresso da operação";
			this.ToolStripButton1.DisplayStyle = 2;
			this.ToolStripButton1.ImageTransparentColor = global::System.Drawing.Color.Magenta;
			this.ToolStripButton1.Name = "ToolStripButton1";
			global::System.Windows.Forms.ToolStripItem toolStripButton = this.ToolStripButton1;
			size = new size(23, 4);
			toolStripButton.Size = size;
			this.ToolStripButton1.Text = "ToolStripButton1";
			this.OpenFileDialog_RT_810.FileName = "OpenFileDialog1";
			this.Timer_limpa_MSG.Interval = 2000;
			global::System.Windows.Forms.PrintPreviewDialog printPreviewDialog = this.PrintPreviewDialog1;
			size = new size(0, 0);
			printPreviewDialog.AutoScrollMargin = size;
			global::System.Windows.Forms.PrintPreviewDialog printPreviewDialog2 = this.PrintPreviewDialog1;
			size = new size(0, 0);
			printPreviewDialog2.AutoScrollMinSize = size;
			global::System.Windows.Forms.Form printPreviewDialog3 = this.PrintPreviewDialog1;
			size = new size(400, 300);
			printPreviewDialog3.ClientSize = size;
			this.PrintPreviewDialog1.Document = this.PrintDocument1;
			this.PrintPreviewDialog1.Enabled = true;
			this.PrintPreviewDialog1.Icon = (global::System.Drawing.Icon)componentResourceManager.GetObject("PrintPreviewDialog1.Icon");
			this.PrintPreviewDialog1.Name = "PrintPreviewDialog1";
			this.PrintPreviewDialog1.Visible = false;
			this.TabPage_geral.BackColor = global::System.Drawing.SystemColors.ControlLight;
			this.TabPage_geral.Controls.Add(this.GroupBox3);
			this.TabPage_geral.Controls.Add(this.GroupBox1);
			this.TabPage_geral.Controls.Add(this.GroupBox_informacoes);
			this.TabPage_geral.Controls.Add(this.GroupBox_comunicacao);
			global::System.Windows.Forms.TabPage tabPage_geral = this.TabPage_geral;
			location = new location(4, 22);
			tabPage_geral.Location = location;
			this.TabPage_geral.Name = "TabPage_geral";
			global::System.Windows.Forms.Control tabPage_geral2 = this.TabPage_geral;
			padding = new padding(3);
			tabPage_geral2.Padding = padding;
			global::System.Windows.Forms.Control tabPage_geral3 = this.TabPage_geral;
			size = new size(963, 505);
			tabPage_geral3.Size = size;
			this.TabPage_geral.TabIndex = 0;
			this.TabPage_geral.Text = "Comunicação e Saídas Analógicas";
			this.TabPage_geral.UseVisualStyleBackColor = true;
			this.GroupBox3.Controls.Add(this.GroupBox4);
			global::System.Windows.Forms.Control groupBox = this.GroupBox3;
			location = new location(395, 129);
			groupBox.Location = location;
			this.GroupBox3.Name = "GroupBox3";
			global::System.Windows.Forms.Control groupBox2 = this.GroupBox3;
			size = new size(338, 96);
			groupBox2.Size = size;
			this.GroupBox3.TabIndex = 4;
			this.GroupBox3.TabStop = false;
			this.GroupBox3.Text = "Saída Analógica 2:";
			this.GroupBox4.Controls.Add(this.lmt_2_20mA);
			this.GroupBox4.Controls.Add(this.Label4);
			this.GroupBox4.Controls.Add(this.lmt_2_4mA);
			this.GroupBox4.Controls.Add(this.Label5);
			global::System.Windows.Forms.Control groupBox3 = this.GroupBox4;
			location = new location(6, 19);
			groupBox3.Location = location;
			this.GroupBox4.Name = "GroupBox4";
			global::System.Windows.Forms.Control groupBox4 = this.GroupBox4;
			size = new size(319, 64);
			groupBox4.Size = size;
			this.GroupBox4.TabIndex = 2;
			this.GroupBox4.TabStop = false;
			this.GroupBox4.Text = "Limites em contagens (0-4000)";
			global::System.Windows.Forms.Control lmt_2_20mA = this.lmt_2_20mA;
			location = new location(256, 30);
			lmt_2_20mA.Location = location;
			this.lmt_2_20mA.Name = "lmt_2_20mA";
			global::System.Windows.Forms.Control lmt_2_20mA2 = this.lmt_2_20mA;
			size = new size(57, 20);
			lmt_2_20mA2.Size = size;
			this.lmt_2_20mA.TabIndex = 3;
			this.Label4.AutoSize = true;
			global::System.Windows.Forms.Control label = this.Label4;
			location = new location(169, 32);
			label.Location = location;
			this.Label4.Name = "Label4";
			global::System.Windows.Forms.Control label2 = this.Label4;
			size = new size(88, 13);
			label2.Size = size;
			this.Label4.TabIndex = 2;
			this.Label4.Text = "Valor para 20mA:";
			global::System.Windows.Forms.Control lmt_2_4mA = this.lmt_2_4mA;
			location = new location(94, 30);
			lmt_2_4mA.Location = location;
			this.lmt_2_4mA.Name = "lmt_2_4mA";
			global::System.Windows.Forms.Control lmt_2_4mA2 = this.lmt_2_4mA;
			size = new size(57, 20);
			lmt_2_4mA2.Size = size;
			this.lmt_2_4mA.TabIndex = 1;
			this.Label5.AutoSize = true;
			global::System.Windows.Forms.Control label3 = this.Label5;
			location = new location(6, 32);
			label3.Location = location;
			this.Label5.Name = "Label5";
			global::System.Windows.Forms.Control label4 = this.Label5;
			size = new size(82, 13);
			label4.Size = size;
			this.Label5.TabIndex = 0;
			this.Label5.Text = "Valor para 4mA:";
			this.GroupBox1.Controls.Add(this.GroupBox2);
			global::System.Windows.Forms.Control groupBox5 = this.GroupBox1;
			location = new location(20, 129);
			groupBox5.Location = location;
			this.GroupBox1.Name = "GroupBox1";
			global::System.Windows.Forms.Control groupBox6 = this.GroupBox1;
			size = new size(338, 96);
			groupBox6.Size = size;
			this.GroupBox1.TabIndex = 3;
			this.GroupBox1.TabStop = false;
			this.GroupBox1.Text = "Saída Analógica 1:";
			this.GroupBox2.Controls.Add(this.lmt_1_20mA);
			this.GroupBox2.Controls.Add(this.Label3);
			this.GroupBox2.Controls.Add(this.lmt_1_4mA);
			this.GroupBox2.Controls.Add(this.Label2);
			global::System.Windows.Forms.Control groupBox7 = this.GroupBox2;
			location = new location(6, 19);
			groupBox7.Location = location;
			this.GroupBox2.Name = "GroupBox2";
			global::System.Windows.Forms.Control groupBox8 = this.GroupBox2;
			size = new size(319, 64);
			groupBox8.Size = size;
			this.GroupBox2.TabIndex = 2;
			this.GroupBox2.TabStop = false;
			this.GroupBox2.Text = "Limites em contagens (0-4000)";
			global::System.Windows.Forms.Control lmt_1_20mA = this.lmt_1_20mA;
			location = new location(256, 30);
			lmt_1_20mA.Location = location;
			this.lmt_1_20mA.Name = "lmt_1_20mA";
			global::System.Windows.Forms.Control lmt_1_20mA2 = this.lmt_1_20mA;
			size = new size(57, 20);
			lmt_1_20mA2.Size = size;
			this.lmt_1_20mA.TabIndex = 3;
			this.Label3.AutoSize = true;
			global::System.Windows.Forms.Control label5 = this.Label3;
			location = new location(169, 32);
			label5.Location = location;
			this.Label3.Name = "Label3";
			global::System.Windows.Forms.Control label6 = this.Label3;
			size = new size(88, 13);
			label6.Size = size;
			this.Label3.TabIndex = 2;
			this.Label3.Text = "Valor para 20mA:";
			global::System.Windows.Forms.Control lmt_1_4mA = this.lmt_1_4mA;
			location = new location(94, 30);
			lmt_1_4mA.Location = location;
			this.lmt_1_4mA.Name = "lmt_1_4mA";
			global::System.Windows.Forms.Control lmt_1_4mA2 = this.lmt_1_4mA;
			size = new size(57, 20);
			lmt_1_4mA2.Size = size;
			this.lmt_1_4mA.TabIndex = 1;
			this.Label2.AutoSize = true;
			global::System.Windows.Forms.Control label7 = this.Label2;
			location = new location(6, 32);
			label7.Location = location;
			this.Label2.Name = "Label2";
			global::System.Windows.Forms.Control label8 = this.Label2;
			size = new size(82, 13);
			label8.Size = size;
			this.Label2.TabIndex = 0;
			this.Label2.Text = "Valor para 4mA:";
			this.GroupBox_informacoes.Controls.Add(this.Label26);
			this.GroupBox_informacoes.Controls.Add(this.TextBox_equipamento);
			this.GroupBox_informacoes.Controls.Add(this.Label_equipamento);
			this.GroupBox_informacoes.Controls.Add(this.TextBox_release);
			this.GroupBox_informacoes.Controls.Add(this.Label_release);
			this.GroupBox_informacoes.Controls.Add(this.TextBox_build);
			this.GroupBox_informacoes.Controls.Add(this.Label_build);
			this.GroupBox_informacoes.Controls.Add(this.TextBox_versao);
			this.GroupBox_informacoes.Controls.Add(this.Label_versao);
			global::System.Windows.Forms.Control groupBox_informacoes = this.GroupBox_informacoes;
			location = new location(373, 10);
			groupBox_informacoes.Location = location;
			this.GroupBox_informacoes.Name = "GroupBox_informacoes";
			global::System.Windows.Forms.Control groupBox_informacoes2 = this.GroupBox_informacoes;
			size = new size(360, 96);
			groupBox_informacoes2.Size = size;
			this.GroupBox_informacoes.TabIndex = 2;
			this.GroupBox_informacoes.TabStop = false;
			this.GroupBox_informacoes.Text = "Versão de Software";
			this.Label26.AutoSize = true;
			this.Label26.Font = new global::System.Drawing.Font("Arial Narrow", 8.25f, 0, 3, 0);
			global::System.Windows.Forms.Control label9 = this.Label26;
			location = new location(51, 50);
			label9.Location = location;
			this.Label26.Name = "Label26";
			global::System.Windows.Forms.Control label10 = this.Label26;
			size = new size(21, 15);
			label10.Size = size;
			this.Label26.TabIndex = 17;
			this.Label26.Text = "GC";
			this.TextBox_equipamento.BackColor = global::System.Drawing.Color.LightCyan;
			this.TextBox_equipamento.Font = new global::System.Drawing.Font("Arial Narrow", 8.25f, 0, 3, 0);
			global::System.Windows.Forms.Control textBox_equipamento = this.TextBox_equipamento;
			location = new location(86, 47);
			textBox_equipamento.Location = location;
			this.TextBox_equipamento.Name = "TextBox_equipamento";
			this.TextBox_equipamento.ReadOnly = true;
			global::System.Windows.Forms.Control textBox_equipamento2 = this.TextBox_equipamento;
			size = new size(47, 20);
			textBox_equipamento2.Size = size;
			this.TextBox_equipamento.TabIndex = 16;
			this.TextBox_equipamento.TabStop = false;
			this.TextBox_equipamento.TextAlign = HorizontalAlignment.Right;
			this.Label_equipamento.AutoSize = true;
			global::System.Windows.Forms.Control label_equipamento = this.Label_equipamento;
			location = new location(51, 29);
			label_equipamento.Location = location;
			this.Label_equipamento.Name = "Label_equipamento";
			global::System.Windows.Forms.Control label_equipamento2 = this.Label_equipamento;
			size = new size(69, 13);
			label_equipamento2.Size = size;
			this.Label_equipamento.TabIndex = 15;
			this.Label_equipamento.Text = "Equipamento";
			this.TextBox_release.BackColor = global::System.Drawing.Color.LightCyan;
			this.TextBox_release.Font = new global::System.Drawing.Font("Arial Narrow", 8.25f, 0, 3, 0);
			global::System.Windows.Forms.Control textBox_release = this.TextBox_release;
			location = new location(242, 47);
			textBox_release.Location = location;
			this.TextBox_release.Name = "TextBox_release";
			this.TextBox_release.ReadOnly = true;
			global::System.Windows.Forms.Control textBox_release2 = this.TextBox_release;
			size = new size(47, 20);
			textBox_release2.Size = size;
			this.TextBox_release.TabIndex = 14;
			this.TextBox_release.TabStop = false;
			this.TextBox_release.TextAlign = HorizontalAlignment.Right;
			this.Label_release.AutoSize = true;
			global::System.Windows.Forms.Control label_release = this.Label_release;
			location = new location(245, 29);
			label_release.Location = location;
			this.Label_release.Name = "Label_release";
			global::System.Windows.Forms.Control label_release2 = this.Label_release;
			size = new size(46, 13);
			label_release2.Size = size;
			this.Label_release.TabIndex = 13;
			this.Label_release.Text = "Release";
			this.TextBox_build.BackColor = global::System.Drawing.Color.LightCyan;
			this.TextBox_build.Font = new global::System.Drawing.Font("Arial Narrow", 8.25f, 0, 3, 0);
			global::System.Windows.Forms.Control textBox_build = this.TextBox_build;
			location = new location(190, 47);
			textBox_build.Location = location;
			this.TextBox_build.Name = "TextBox_build";
			this.TextBox_build.ReadOnly = true;
			global::System.Windows.Forms.Control textBox_build2 = this.TextBox_build;
			size = new size(47, 20);
			textBox_build2.Size = size;
			this.TextBox_build.TabIndex = 12;
			this.TextBox_build.TabStop = false;
			this.TextBox_build.TextAlign = HorizontalAlignment.Right;
			this.Label_build.AutoSize = true;
			global::System.Windows.Forms.Control label_build = this.Label_build;
			location = new location(199, 29);
			label_build.Location = location;
			this.Label_build.Name = "Label_build";
			global::System.Windows.Forms.Control label_build2 = this.Label_build;
			size = new size(30, 13);
			label_build2.Size = size;
			this.Label_build.TabIndex = 11;
			this.Label_build.Text = "Build";
			this.TextBox_versao.BackColor = global::System.Drawing.Color.LightCyan;
			this.TextBox_versao.Font = new global::System.Drawing.Font("Arial Narrow", 8.25f, 0, 3, 0);
			global::System.Windows.Forms.Control textBox_versao = this.TextBox_versao;
			location = new location(138, 47);
			textBox_versao.Location = location;
			this.TextBox_versao.Name = "TextBox_versao";
			this.TextBox_versao.ReadOnly = true;
			global::System.Windows.Forms.Control textBox_versao2 = this.TextBox_versao;
			size = new size(47, 20);
			textBox_versao2.Size = size;
			this.TextBox_versao.TabIndex = 10;
			this.TextBox_versao.TabStop = false;
			this.TextBox_versao.TextAlign = HorizontalAlignment.Right;
			this.Label_versao.AutoSize = true;
			global::System.Windows.Forms.Control label_versao = this.Label_versao;
			location = new location(141, 29);
			label_versao.Location = location;
			this.Label_versao.Name = "Label_versao";
			global::System.Windows.Forms.Control label_versao2 = this.Label_versao;
			size = new size(40, 13);
			label_versao2.Size = size;
			this.Label_versao.TabIndex = 9;
			this.Label_versao.Text = "Versão";
			this.GroupBox_comunicacao.Controls.Add(this.NumericUpDown_end_est);
			this.GroupBox_comunicacao.Controls.Add(this.Label_end_est);
			global::System.Windows.Forms.Control groupBox_comunicacao = this.GroupBox_comunicacao;
			location = new location(20, 13);
			groupBox_comunicacao.Location = location;
			this.GroupBox_comunicacao.Name = "GroupBox_comunicacao";
			global::System.Windows.Forms.Control groupBox_comunicacao2 = this.GroupBox_comunicacao;
			size = new size(291, 92);
			groupBox_comunicacao2.Size = size;
			this.GroupBox_comunicacao.TabIndex = 1;
			this.GroupBox_comunicacao.TabStop = false;
			this.GroupBox_comunicacao.Text = "Parâmetros de Comunicação";
			global::System.Windows.Forms.Control numericUpDown_end_est = this.NumericUpDown_end_est;
			location = new location(204, 41);
			numericUpDown_end_est.Location = location;
			global::System.Windows.Forms.NumericUpDown numericUpDown_end_est2 = this.NumericUpDown_end_est;
			decimal maximum;
			maximum = new maximum(new int[]
			{
				70000,
				0,
				0,
				0
			});
			numericUpDown_end_est2.Maximum = maximum;
			this.NumericUpDown_end_est.Name = "NumericUpDown_end_est";
			global::System.Windows.Forms.Control numericUpDown_end_est3 = this.NumericUpDown_end_est;
			size = new size(72, 20);
			numericUpDown_end_est3.Size = size;
			this.NumericUpDown_end_est.TabIndex = 1;
			this.NumericUpDown_end_est.TextAlign = HorizontalAlignment.Right;
			this.Label_end_est.AutoSize = true;
			global::System.Windows.Forms.Control label_end_est = this.Label_end_est;
			location = new location(21, 42);
			label_end_est.Location = location;
			this.Label_end_est.Name = "Label_end_est";
			global::System.Windows.Forms.Control label_end_est2 = this.Label_end_est;
			size = new size(116, 13);
			label_end_est2.Size = size;
			this.Label_end_est.TabIndex = 4;
			this.Label_end_est.Text = "Endereço da Estação :";
			this.TabControl_810.Controls.Add(this.TabPage_geral);
			this.TabControl_810.HotTrack = true;
			global::System.Windows.Forms.Control tabControl_ = this.TabControl_810;
			location = new location(26, 73);
			tabControl_.Location = location;
			this.TabControl_810.Name = "TabControl_810";
			this.TabControl_810.SelectedIndex = 0;
			global::System.Windows.Forms.Control tabControl_2 = this.TabControl_810;
			size = new size(971, 531);
			tabControl_2.Size = size;
			this.TabControl_810.TabIndex = 1;
			global::System.Drawing.SizeF autoScaleDimensions;
			autoScaleDimensions = new global::System.Drawing.SizeF(6f, 13f);
			this.AutoScaleDimensions = autoScaleDimensions;
			this.AutoScaleMode = AutoScaleMode.Font;
			this.BackColor = global::System.Drawing.SystemColors.ControlLight;
			size = new size(1147, 636);
			this.ClientSize = size;
			this.Controls.Add(this.ToolStri_RT_810);
			this.Controls.Add(this.TabControl_810);
			this.FormBorderStyle = FormBorderStyle.FixedSingle;
			this.Name = "GC_82x_conf";
			this.RightToLeftLayout = true;
			this.ShowIcon = false;
			this.StartPosition = FormStartPosition.Manual;
			this.Text = "Configuração";
			this.ToolStri_RT_810.ResumeLayout(false);
			this.ToolStri_RT_810.PerformLayout();
			this.RepetidoraBindingSource1.EndInit();
			this.TabPage_geral.ResumeLayout(false);
			this.GroupBox3.ResumeLayout(false);
			this.GroupBox4.ResumeLayout(false);
			this.GroupBox4.PerformLayout();
			this.lmt_2_20mA.EndInit();
			this.lmt_2_4mA.EndInit();
			this.GroupBox1.ResumeLayout(false);
			this.GroupBox2.ResumeLayout(false);
			this.GroupBox2.PerformLayout();
			this.lmt_1_20mA.EndInit();
			this.lmt_1_4mA.EndInit();
			this.GroupBox_informacoes.ResumeLayout(false);
			this.GroupBox_informacoes.PerformLayout();
			this.GroupBox_comunicacao.ResumeLayout(false);
			this.GroupBox_comunicacao.PerformLayout();
			this.NumericUpDown_end_est.EndInit();
			this.TabControl_810.ResumeLayout(false);
			this.ResumeLayout(false);
			this.PerformLayout();
		}

		// Token: 0x040007A4 RID: 1956
		private global::System.ComponentModel.IContainer components;
	}
}
